### PR TITLE
Support restricted thumbnails

### LINKED ISSUE #1579: Restricted Thumbnails don't load for any users
(Discovered during the review of #1556, but it's not specific to Withdrawn Item thumbnails)

**Describe the bug**
When a Thumbnail image has any sort of access restrictions, it is unable to display _even to EPersons who have those access rights_.  As a basic example, if you modify a Thumbnail image bitstream to have an Administrator READ policy (without an Anonymous READ policy), then that Thumbnail will no longer be displayed for any users, even Administrators.  Any time it is accessed, a 401 response will be sent back by the REST API.

As [described in 1556](https://github.com/DSpace/dspace-angular/pull/1556#issuecomment-1078898675), the issue appears to be that the thumbnail gets rendered (see `thumbnail.component`) by putting its `/content` link directly in the template and letting the browser retrieve it. So there is no authorisation or short lived token added.
```
    <img *ngIf="src !== null" class="thumbnail-content img-fluid"
         [src]="src | dsSafeUrl" [alt]="alt | translate" (error)="errorHandler()">
```

The solution would be just like for restricted downloads to retrieve a short-lived token first, and add it to the contents url. However this is an image shown/resolved by the browser on item page/search grid view/..., so can't go through a 'download page' like done for (restricted) downloads...

**To Reproduce**
One basic example:
1. Find an Item which has an existing Thumbnail
2. Edit the Item, find the Thumbnail bitstream and Edit its policies
3. Remove any Anonymous READ policy.  Add an Admin READ policy
4. Now, go back to the Item.  Verify the Thumbnail doesn't load (your browser's devtools will show a 401 response code)
5. Login as an Admin, verify the Thumbnail still doesn't load.

**Expected behavior**
Ideally, restricted thumbnails should still be displayed to users who have permissions to view them.

** Workaround **
Currently, the workaround is to ensure all Thumbnails are publicly available.  If you encounter this issue, you can modify the policies of the Thumbnail bitstream to ensure it has an Anonymous READ policy. 

**Related work**
* Discovered during review of #1556. 
* Likely needs to be solved in a way similar to how we managed restricted bitstream downloads in #716 and #1004 (which fixed 924)

### PR DESCRIPTION
**Pull request by ybnd**
## References

_Add references/links to any related issues or PRs. These may include:_
* Fixes #1579

## Description
Show restricted Bitstream thumbnails for logged in users that have the permissions to view them.

* Try to show the thumbnail's `/content` first (this is same behavior as before)

  By assuming that _most_ thumbnails would not be restricted we can avoid having to check permissions when it's not necessary.

* If a thumbnail was resolved from a Bitstream but couldn't be shown

  * Check if the user is logged in (if not, fall back to default)
  * Check if the user is authorized to view the thumbnail (if not, fall back to default)
  * Retry with a short-lived token

Some changes in order to make transitions between failed & successful images more smooth:

- Hide the `` with `d-none` instead of `*ngIf` so it can fetch the image while it's hidden
- Start out with the loading animation playing by default
- Stop it once an image is successfuly loaded or when falling back to the HTML placeholder (for non-restricted thumbnails this is quite quick)

## Instructions for Reviewers
1. Find (or create) a DSO with a restricted thumbnail
2. Open a page where that thumbnail would be displayed (e.g. a DSO page, a search page in grid mode, ...)
3. Log out 
   * The thumbnail should not appear
4. Log in as an EPerson that has no access to the thumbnail
   * The thumbnail should not appear
5. Log in as an EPerson that has access to the thumbnail
   * The thumbnail should appear
  

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
@ybnd : I came across this older draft PR from July.  Any chance of this moving forward for 7.4 possibly?  Bug #1579 was just mentioned on Slack by a user, so I'd be OK with bumping up the priority to `high` if you or @artlowel had time to help tackle this for 7.4.

**Comment by ybnd** [comment]
I wasn't super sure about the approach here, but this should work at least.
IIRC there was a slight graphical issue with the animation wrapping when the thumbnail is very small, could be pretty noticeable on slow machines/networks

**Comment by tdonohue** [comment]
@ybnd : I've pulled this over onto the 7.4 board in the hopes we can move this along for 7.4.  That said, it looks like this is failing tests right now (I've tried restarting the tests & the same failure persists, so it does not appear to be a random failure).

**Comment by ybnd** [comment]
Note to self: as written right now, this tries to redo failed thumbnail GETs with a token each time, even if we already know that there is no thumbnail.

Restricted Bitstreams should come back with 403 instead of 404, we can be more selective here and prevent extra effort for thumbnails that are just missing
→ if we narrow the type of `thumbnail` to `RemoteData<Bitstream>` we can rely on the status code always

**Review by artlowel — APPROVED** [review]
Thanks @ybnd!

The code looks good, and it works the way it should

>Restricted Bitstreams should come back with 403 instead of 404, we can be more selective here and prevent extra effort for thumbnails that are just missing
→ if we narrow the type of thumbnail to RemoteData<Bitstream> we can rely on the status code always

At first sight it doesn't look like the regular 'Bitstream' case is still used anywhere, so I'd be in favor of this change.

**Comment by ybnd** [comment]
Changed the loading animation to fit better with narrow thumbnail. Especially helpful in mobile/tablet view when combined with https://github.com/DSpace/dspace-angular/pull/1780

**Comment by tdonohue** [comment]
@ybnd : It looks like your latest change resulted in some spec failures.  They look like they may be very minor, but they also don't look random.

**Comment by ybnd** [comment]
@tdonohue thanks, seems like I was rushing this morning → updated

**Review by tdonohue — APPROVED** [review]
👍 Thanks @ybnd !  I tested this today and it works well.  Restricted thumbnails now load when you have access to them.

**Pull request merged**
