### PR TITLE
Update fi.json5

### PR DESCRIPTION
**Pull request by reetagithub**
Added two new translation keys and their translation to Finnish,  "home.search-form.placeholder" and  "search.search-form.placeholder"

## Description
Added two new translation keys and their translation to Finnish,  "home.search-form.placeholder" and  "search.search-form.placeholder"

## Instructions for Reviewers
These tralstation keys were missing from the Finnish file fi.json5.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.

The following ones are not tsue, no testing done.

- [ ] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [ ] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@reetagithub : This is currently failing `yarn lint` checks (which verify no extra spaces exist, etc.).  You might be able to fix all this issues automatically via `yarn lint --fix` (which tries to automatically fix the issues).  If you run into problems, I might be able to help later this week or next.

**Comment by reetagithub** [comment]
Thanks, Tim! I am not familiar with yarn, I've just edited json files until now. A colleague of mine promised to help me, but we will have  common time next week. Perhaps it is better if you take care of this one and I will try and learn to use yarn so that the future PRs will not fail because of this.

**Comment by alanorth** [comment]
Hi @reetagithub, in the interest of time, since DSpace 7.6 will be released in the next week or so and it would be good to have these in there, I fixed the whitespace errors and ported your changes to a new pull request that we can use instead of this one if you agree.

See: #2305

**Comment by reetagithub** [comment]
Certainly I agree - thank you so much!

**Pull request closed without merging**
