### PR TITLE
Withdrawn item tombstone

### LINKED ISSUE #346: Withdrawn item tombstone page
A page needs to be added to serve as a tombstone when the item is withdrawn. 

Currently the REST API returns a 401 Unauthorized when a withdrawn item is accessed by an anonymous user.  
So, this depends on a fix to https://github.com/DSpace/DSpace/issues/3245

Once this issue is fixed, a component should be added to render the tombstone page for a withdrawn item

### PR DESCRIPTION
**Pull request by YanaDePauw**
## References
* Fixes #346
* Requires DSpace/DSpace#3264

## Description
This PR cleans up the withdrawn tombstone page. An alert will be shown at the top of a withdrawn item with a go back to the home page button without showing 401 errors.

When an admin accesses the page, the same alert will be shown, but the item itself will still be displayed. 

This is changed for both simple view and full view. 

## Instructions for Reviewers
As a non-admin user: 
1. Go to a withdrawn untyped item page (both simple and full display page) 
2. Verify that an alert is shown, saying that the item is withdrawn with a go back to the home page button
3. Verify that no 401 errors are showing and no other information is shown on the page
4.  Go to a withdrawn entity page (both simple and full display page) 
5. Verify that an alert is shown, saying that the item is withdrawn with a go back to the home page button
6. Verify that no 401 errors are showing and no other information is shown on the page 

As an admin user:
1. Go to a withdrawn untyped item page (both simple and full display page) 
2. Verify that an alert is shown, saying that the item is withdrawn with a go back to the home page button
3. Verify that the item itself is still displayed underneath the alert
4.  Go to a withdrawn entity page (both simple and full display page) 
5. Verify that an alert is shown, saying that the item is withdrawn with a go back to the home page button
6. Verify that the item itself is still displayed underneath the alert

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@YanaDePauw : I gave this a test today. Overall, it works as described & looks good.

I only noticed one minor issue (though we could simply leave it as-is, if it's too difficult to resolve easily).

If a withdrawn Item has a *thumbnail* associated with it, then when you access the Item's page as an Administratory, then you'll still get a 401 response for the Thumbnail image (and the thumbnail will not be displayed).   This only occurs for Administrators though, and it's not a major bug.... but, if there's an easy fix to avoid the 401 and still display the thumbnail to the Adminsitrators, that might be the best solution here.

Beyond that, I'm +1 this PR. Just wanted to note that small bug.

**Comment by MarieVerdonck** [comment]
Looked into this, and I'm not seeing a failed 401 request for the `/bitstreams/{thumbnailBitstreamUUID/content` in the network tab, nor notification shown. 

However the thumbnail of a withdrawn item for the admin indeed is not being rendered. (added one to ex item `/items/e55aa032-8d92-4e0f-874f-87a59c23cc77` => `/bitstreams/1a463ca7-12ff-45cb-b664-0bd7681d4850`)

This is because the thumbnail gets rendered (see `thumbnail.component`) by putting its `/content` link directly in the template and letting the browser retrieve it. So there is no authorisation or short lived token added.

```
    <img *ngIf="src !== null" class="thumbnail-content img-fluid"
         [src]="src | dsSafeUrl" [alt]="alt | translate" (error)="errorHandler()">
```

The same issue would occur on for example the admin search page in grid view, for any non publically accessible item.

The solution would be just like for restricted downloads to retrieve a short-lived token first, and add it to the contents url. However this is an image shown/resolved by the browser, so can't go through a 'download page' like done for (restricted) downloads...

I would suggest turning this into a separate ticket since this affects more than just the withdrawn item (tombstone) page.

**Comment by tdonohue** [comment]
@MarieVerdonck : thanks for digging into this issue!  

To verify, I was definitely getting a 401 from `/bitstreams/{thumbnailBitstreamUUID}/content`... it could have been that this only occurs when running in production mode (I was using `yarn run build:prod; yarn run serve:ssr`).  In any case, I agree that this can be split out into a separate ticket, as it sounds like a separate issue with thumbnails.  I'll create a ticket for it, and then get this PR merged.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @YanaDePauw and @MarieVerdonck !   I've moved the issue with restricted thumbnails to a separate ticket #1579.  So, this PR looks good to me now.

**Pull request merged**
