### PR TITLE
Restored highlighting of title in search results

### LINKED ISSUE #1968: Missing highlights in title in search results
**Describe the bug**
When a search is performed, discovery search response brings information about terms to be highlighted in title. 

`https://api7.dspace.org/server/api/discover/search/objects?sort=score,DESC&page=0&size=10&configuration=default&query=dengue&embed=thumbnail&embed=item%2Fthumbnail&embed=accessStatus` 

returns
image

but "dengue" term is not highlighted in title

image

**Expected behavior**
Searched terms highlighted in title as well

### PR DESCRIPTION
**Pull request by corrad82-4s**
## References
* Fixes #1968

## Description
Short summary of changes (1-2 sentences).
Title metadata value in search results list is filled using `firstMetadataValue` function, taking into account parts to be highlighted, if any.

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

List of changes in this PR:
* `item-search-result-list-element-component` updated to use `firstMetadataValue` 

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@corrad82-4s & @nikunj59: Finally tested this today.  This *works*, **but only for Items and Publication Entities**.  If the search result is any other type of Entity (e.g. Journal, Project, OrgUnit or Person) *or* is a Community or Collection, then the title highlighting still does not occur.  For example, try searching for a person's last name and the Person Entity won't have its title highlighted.  Or, try searching for a term in a Journal title, and again highlighting will not occur for a matching Journal Entity.  Or search on a Collection title, and you'll see the Collection's title will not be highlighted in the results.

So, this appears to only be a partial fix.  I think the issue may be in the `dsoTitle` (which seems to be used as the title of all objects in search results).  By default that `dsoTitle` just get the name of the object, but in this scenario maybe there's a way we can dynamically update it to use the `firstMetadataValue('dc.title')`??   I admit though that I'm not sure how plausible that would be... I'm just pointing out that if you can fix `dsoTitle` directly, then it may fix this issue for all objects.

**Comment by Nik5992** [comment]
@tdonohue 
As per your suggestion, I applied changes and updated PR: https://bitbucket.org/4Science/dspace-angular/pull-requests/388

**Comment by nikunj59** [comment]
@tdonohue as Per your suggestion, updated PR: https://bitbucket.org/4Science/dspace-angular/pull-requests/388

**Comment by corrad82-4s** [comment]
This PR has been updated with latest requested changes

**Review by tdonohue — COMMENTED** [review]
@corrad82-4s and @nikunj59 :  Re-tested this today.  The behavior is *better*, but it's still not working for OrgUnits & Person Entities.  I did notice those are the only two Entity Types where you switched *away from* using `dsoTitle`.  Could that be the reason these don't work?

I have verified though that Community/Collection/Project/Journal/Journal Issue/Journal Volume/Publication/Item **all work**.  It's just down to the last two entities.

**Comment by nikunj59** [comment]
@tdonohue 
can you please check if those orgUnits and person entities have **hitHighlights** from BE response?
I tested in local and its working fine with my person data.
Screenshot 2022-12-16 at 6 57 26 PM

In orgUnit dont have **hitHighlights**:
Screenshot 2022-12-16 at 7 01 14 PM

**Comment by tdonohue** [comment]
@nikunj59 :  When searching Person Entities, I see the behavior in your first screenshot.  If you look closely, the *first person* in your screenshot above **should have hit highlighting**.  You searched on "test" and somehow it didn't highlight "Test, Test" (the first person in your list).   If I similarly search on a Person's last name or first name, I cannot get hit highlighting to appear.
no-name-highlight
no-firstname-highlight

I **can verify** that in the REST API response, the `hitHighlights` are always `null` in these scenarios.  So, it appears this PR may be all the fixes that are needed on the *frontend*, but we obviously still have bugs on the backend for `Person` and `OrgUnit` entities.

So, I can move this PR forward as-is.  However, do you or @corrad82-4s plan to fix these backend bugs?  Or should we create a new ticket to clarify that know issues with hit highlighting still occur for `Person` and `OrgUnit` entities?

**Review by tdonohue — APPROVED** [review]
👍 Changing my vote to a +1.  This PR *appears* to have fixed the issues on the frontend.  

However, `Person` and `OrgUnit` entities **still do not show hit highlighting** in the Name/Title field.  This appears to be a backend issue though as the `hitHighlights` in the REST response is always `null`. 

So, this fixes the frontend bug, but some known issues still remain.

**Comment by nikunj59** [comment]
@corrad82-4s @tdonohue 
As per My investigation 
For Person it comes in highlights as **person.familyName, person.givenName** with html tags.
For OrgUnit it comes in highlights as **organization.legalName** with html tags.
But we are using to highlight title **this.firstMetadataValue('dc.title')**


Screenshot 2023-01-05 at 7 55 20 PM
Screenshot 2023-01-05 at 7 49 46 PM

**Comment by tdonohue** [comment]
@nikunj59 and @corrad82-4s :  As the hit highlights are coming through on a different metadata field, that implies that this PR may need to not *assume* that the highlighted field is always `dc.title`.   The fields that are receiving hit highlights for Person and OrgUnit are the same fields which the `DSONameService` uses to display Person & OrgUnit names: https://github.com/DSpace/dspace-angular/blob/main/src/app/core/breadcrumbs/dso-name.service.ts#L28-L42

Maybe this PR should be refactored to somehow use `DSONameService` instead of only using the `dc.title` field??  Otherwise, it seems like hit highlighting will never work for objects which do not use `dc.title`.

I'm going to leave this PR open until you have a chance to reanalyze whether there's a way to refactor to use `DSONameService`.  I suspect there should be, but I do realize it may take some closer analysis.

**Comment by nikunj59** [comment]
@tdonohue 
Thanks for clarification.
I'll try to cover responded field for Person and OrgUnit and refactor pull request.

**Comment by nikunj59** [comment]
@tdonohue 
in DSONameService  [factory](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/breadcrumbs/dso-name.service.ts#L28-L42) you mentioned will return plain title because on the dso object which its processing is indexableObject.
https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/object-list/search-result-list-element/search-result-list-element.component.ts#L35-L36

**Comment by corrad82-4s** [comment]
Hi @tdonohue , 
we have pushed latest required changes. A further REST PR (https://github.com/DSpace/DSpace/pull/8626) has been  created to enable hightlighting for Person and OrgUnits.

**Comment by nikunj59** [comment]
@tdonohue 
I Refactored PR.
Screenshot 2023-01-10 at 7 20 45 PM
Screenshot 2023-01-10 at 7 20 58 PM
Screenshot 2023-01-10 at 7 22 52 PM
Screenshot 2023-01-10 at 7 22 59 PM

**Review by tdonohue — APPROVED** [review]
👍 Thanks @nikunj59 and @corrad82-4s !  This works well now, and I appreciate that the logic has all moved into `dso-name.service.ts` alongside the `getName()` method there.

I was able to verify that all object types & all entity types now show hit highlighting in the displayed title/name.

**Pull request merged**
