### PR TITLE
Added Arabic Translation

### PR DESCRIPTION
**Pull request by mohamedali654321**
Added Arabic Translation

Added ar.json5 translation and modified config files to include this translation

List of changes in this PR:

Added Arabic translation
Updated config.example.yml

### CODE REVIEW

**Comment by tdonohue** [comment]
@mohamedali654321 : It looks like this PR is currently failing "lint" (formatting) checks.  You can see these locally by running `yarn lint`.  You also may be able to automatically clean them up by running `yarn lint --fix` (this will fix many things automatically, but may not be able to fix everything)

**Comment by alexandrevryghem** [comment]
@mohamedali654321: Could you also restore the comments in the json5 file, these are used to detect outdated translations. So your translation file should look like this:
```json5
{
  // "401.help": "You're not authorized to access this page. You can use the button below to get back to the home page.",
  "401.help": "غير مصرح لك بالوصول إلى هذه الصفحة. يمكنك استخدام الزر أدناه للعودة إلى الصفحة الرئيسية.",

  // "401.link.home-page": "Take me to the home page",
  "401.link.home-page": "اذهب إلى الصفحة الرئيسية",
  
  ...
}
```

**Comment by mohamedali654321** [comment]
> @mohamedali654321 : It looks like this PR is currently failing "lint" (formatting) checks. You can see these locally by running `yarn lint`. You also may be able to automatically clean them up by running `yarn lint --fix` (this will fix many things automatically, but may not be able to fix everything)

**Comment by alexandrevryghem** [comment]
Hey @mohamedali654321 because I realise that adding all those comments manually back in would have taken quite a while I created a script to fix your translation file. If you enable this option on your PR I think I can push the fix on your branch:
image

The new translation file also doesn't contain the translation for `cookies.consent.app.description.google-analytics` since it has two different values in your file and I wasn't sure which one was the correct one
- `"cookies.consent.app.description.google-analytics": "يسمح لنا بتتبع البيانات الإحصائية",`
- `"cookies.consent.app.description.google-analytics": "تسمح لنا بتتبع بياناتك الإحصائية",`

And these translations are now also no included anymore because they don't exist in the english file:
- `"collection.page.browse.recent.head": "أحدث التقديمات"`, -> I removed this key in `en.json5` since it has been replaced with a search page so this is normal
- `"collection.page.browse.recent.empty": "لا توجد مواد للعرض"`, -> I removed this key in `en.json5` since it has been replaced with a search page so this is normal
- `"menu.section.notifications_reciter": "مطالبة المنشورات",`
- `"quality-assurance.button.detail": "عرض التفاصيل",`
- `"person.page.givenName": "الاسم الأول",`
- `"submission.sections.submit.progressbar.detect-duplicate": "التكرارات المحتملة",`

**Comment by mohamedali654321** [comment]
@alexandrevryghem Can you send the script because commenting on a translation line will take a lot of time? Also, the commands sent by you return with an error PS F:\ar-fix\dspace-angular-main> git push -fu origin alexandrevryghem/fixed-ar-i18n-file: main
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by alexandrevryghem** [comment]
@mohamedali654321 Try running the command `git remote add origin https://github.com/knowledgeWare-Tech/dspace-angular.git`. I can give you the script but I don't think it will be very useful for you since using it is not simply executing the command there is still some manual work that needs to be done because this was a one off script so I didn't make it super fancy 😅

**Review by tdonohue — APPROVED** [review]
👍 Thank you @mohamedali654321  for your contribution!  My apologies it has taken a while to get back to this PR.  But, today I tested it out and found that the translation is working.  Using Google Translate, I verified a few pages and they all look good.  Thanks again.

**Pull request merged**
