### PR TITLE
src/app: fix path to deny-request-copy component

### PR DESCRIPTION
**Pull request by alanorth**
## References
* Fixes https://github.com/DSpace/dspace-angular/issues/2351

## Description
The themed-deny-request-copy.component erroneously includes the custom theme's deny-request-copy component instead of its own. This _appears_ to work, but breaks when the custom theme is missing (and of course the application should not be relying on the custom theme at all).

## Instructions for Reviewers
Build the application and see if the deny request copy functionality is working as expected (including the themed component in the custom theme).

List of changes in this PR:
* Fix path to `deny-request-copy.component`

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
I don't use the request a copy feature so I can't test this other than building and seeing if anything is broken. @Leano1998 could also take a look since he found the issue and might be using request a copy?

**Comment by tdonohue** [comment]
@mwoodiupui : This might be a quick test for you, as it appears this bug was accidentally in #2245 .

**Comment by Leano1998** [comment]
I tested the change and it works good for me.

**Comment by tdonohue** [comment]
@alanorth :  We talked about how to sync "dspace-7_x" and "main" in today's dev meeting: https://wiki.lyrasis.org/display/DSPACE/2023-07-06+DSpace+Developers+Meeting#id-20230706DSpaceDevelopersMeeting-Notes

We decided that the rule should be to have two PRs (one for each branch).  But, for small fixes, it's OK to make an exception and just apply the fix to either branch...and I (or another Committer) can sync it to the other one.

So, to answer your question, yes you can merge into "dspace-7_x", but I'd appreciate it if you could then `port to main` (I just added that flag as a reminder).  Once done, it can be merged immediately to `main` and the `port to main` flag removed.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@alanorth : Before you merge, this must be fixed.  It's tiny, but you shouldn't change our version on this branch.

**Pull request merged**
