### PR TITLE
Setup the Docker GH Action for Matrix Building

### PR DESCRIPTION
**Pull request by misilot**
This PR enables building of the amd64 and arm64 images simultaneously.

## References

Logic borrowed from https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners

## Description
Once both images finish, the manifest is sent to Docker Hub, allowing for a single image that has both the amd64/arm64 images.

This will allow for faster building of the amd64 image, and being sent to Docker Hub, while the arm64 image is still being built.

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

List of changes in this PR:
* Creates a matrix for the target arch (amd64, arc64).
* Merges the two docker images and pushes the manifest to Docker Hub at completion

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
Thanks @misilot !  I found this looks to be borrowed from https://github.com/docker/docs/blob/main/content/build/ci/github-actions/multi-platform.md#distribute-build-across-multiple-runners .  I went searching around as I was finding the logic of the "merge" step a bit difficult to follow.  But I see that's the recommended approach from Docker themselves.

It's a shame this is so complex to achieve, but I agree that the benefits are wonderful.  I'll see if I can get this merged soon so that we can test it out.  We'll also need to create a version of this for `DSpace/DSpace`.  I might be able to help with that if I find time (and you don't beat me to it).

**Comment by misilot** [comment]
@tdonohue yup, I think that is where I borrowed from! It was a while go.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @misilot ! Looks good and makes sense now that I look at the Docker recommendations (see links above).  The only way to fully test it is to merge it.  So, I'm going to merge it now.  (I was already planning on doing some minor GitHub Actions cleanup tomorrow to prep for 8.0, so this is good timing!)

**Comment by tdonohue** [comment]
Ported to `dspace-7_x` in #2655

**Pull request merged**
