### PR TITLE
Label is not persistent

### LINKED ISSUE #1184: [Deque Analysis] Login module's "serious" accessibility issues
> Serious: This issue results in serious barriers for people with disabilities, and will partially prevent them from accessing fundamental features or content. People relying on assistive technologies will experience significant frustration as a result. Issues falling under this category are major problems, and remediation should be a priority. 

## Deque Analysis Summary

A total of 3 serious issues exist (not including color contrast which are handled in other tickets) in our login module (available in the upper right on each page).

1. ~~(ID: 469328) "Label is not persistent" on the email/password fields. "placeholder is being used as the only visual label for a text field. The placeholder label is not visually available after data is entered in the text field."~~
    * ~~Recommended Fix: "Labels MUST be visible. Ensure that the label is programmatically associated with the form fields via the label/for technique or ARIA attributes."~~
    * FIXED ALREADY VIA Aria attributes (verified as of 7.5, though uncertain when it was actually fixed)
2. (ID 469335) "Identify Input Purpose Not Accurate." on the email/password fields. "Autocomplete attribute to identify the purpose of this form element is not accurate." (Currently both have `autocomplete="off"`)
    * Recommended fix: Fix this issue by using the autocomplete attribute with the appropriate value from HTML5.2 on the text input element. The list of 53 defined input purposes for UI components can be found here -
https://www.w3.org/TR/WCAG21/#input-purposes  (For our purposes, they likely should be set to "username" and "current-password")
3. (ID 469343) ~~"Text spacing content cut off." on the "Have you forgotten your password?" link.~~
    * ~~Recommended fix: Fix this issue by allowing users to override text spacing styles by providing flexibility in the height and width of content containers. Some common techniques include:~~
        * ~~Size containers to a have a value greater than the default width of the text. Small areas of text (such as navigation bars) need to have sufficient space within each box so that words and characters do not expand out of their containers.~~
        * ~~Use the inline-block value of the CSS display property and do not set negative margins to help allow for spacing overrides.~~
        * ~~Do not set the CSS height property, it can help ensure paragraphs are able to expand.~~
        * ~~See also https://www.w3.org/WAI/WCAG21/Understanding/text-spacing~~
        * NO LONGER REPRODUCIBLE IN 7.6.1.  Unsure when fixed.
4. (ID 469229) ~~"id attribute value must be unique". Document has multiple static elements with the same id attribute: `loginDropdownMenu`~~
    * ~~NOTE: Rated a "minor" issue, not "serious", but it may be simple to fix. If it's not simple, it should be delayed & moved to a different ticket.~~
    * FIXED BY #2683

Full list of issues is viewable at (requires login): https://axeauditor.dequecloud.com/test-run/0856438a-a19a-11eb-bc31-b7d5be387c86/issues?sortField=ordinal&sortDir=asc&filter%5Bseverity%5D=3&filter%5Btype%5D=issue&filter%5Bpage_number%5D=8

### PR DESCRIPTION
**Pull request by CrisGuzmanS**
Hello @tdonohue i've done the activity with **ID 469328**.

## References
* Fixes part of #1184 (ID 469328)

## Description
The placeholder for email and password is consistent and not removed when user is typing.

## Instructions for Reviewers

List of changes in this PR:
* from `placeholder` to `[attr.placehoder]` in file: `log-in-password.component.html`.

1. click on login credentials.
2. type email or password.
3. see console.log that placeholder is persistent.

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@CrisGuzmanS : Maybe I'm overlooking it, but I'm not seeing how this small change makes the login form have different behavior.  

To me, it looks like the behavior with this PR applied is identical to the behavior *on current `main`*.  Could you describe how this change has fixed things?  Maybe I'm overlooking something in your change.

It also looks (to me) like this issue may already be fixed on `main` because I'm seeing `aria-label` values on these fields already.  So, I'm not sure whether this PR is necessary or not.

**Comment by CrisGuzmanS** [comment]
Hello @tdonohue 🤚. Before making this change, I noticed that the "placeholder" attribute disappears when we start typing. I realized that it is because the attribute is bound to an angular variable, but without the brackets "[...]", I understand that those brackets make the placeholder attribute reactive, so at all times the angular variable is bound to the attribute.

**Comment by tdonohue** [comment]
@CrisGuzmanS : Thanks for the explanation.  I'll give this one last test on my end to see if I notice the difference in behavior as you noticed.

**Comment by tdonohue** [comment]
@CrisGuzmanS :  I looks into this a bit more today.  In this scenario, I believe `placeholder="..."` and  `[attr.placeholder]="..."` are **identical**.   Those syntaxes work the same way when the value is a **string**.   However, you MUST use `[attr.placeholder]` (square bracket) syntax when the value is an **object** (as that lets you pass the object back into the `*.component.ts`. 

There's some more discussion about the differences in this StackOverflow answer: https://stackoverflow.com/a/35944965/3750035 (Especially look at the comments under that answer, where someone asks directly about the difference between `prop="{{value}}"` and `[attr.prop]="value"`)

So, overall, I think this PR should be closed as it's essentially not changing any behavior.  I've also tested again manually and found no behavior change.  

That said, I think the original issue with ID 469328 looks **fixed already**.  I'm not sure where/when we fixed it, but I believe it is already resolved.  Thanks for your work here though!

**Pull request closed without merging**
