### PR TITLE
COAR Notify impossible to send/receive message from another DSpace

### PR DESCRIPTION
**Pull request by atarix83**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes https://github.com/DSpace/DSpace/issues/9644
* Requires DSpace/DSpace#9645

## Description
This PR introduce important fixes in order to address https://github.com/DSpace/DSpace/issues/9644.
It also contains a porting of fixes for the suggestions page from DSpace-CRIS.

## Instructions for Reviewers

List of changes in this PR:
* Added 'announce-relationship' as supported pattern when configuring a LDN service
* When configuring a LDN service the pattern is no longer mandatory
* Improved LDN form by adjusting form button color following application guidelines
* Renamed and reorganized suggestion data services
* Fixed an issue in the suggestion page with pagination of the suggestion entries 

**Include guidance for how to test or review your PR.** 
Please refer to instructions present in the REST PR here https://github.com/DSpace/DSpace/pull/9645#issuecomment-2162953741.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 Thanks @atarix83 !  I was able to successfully test this process of sending LDN messages from one DSpace 8 instance to another DSpace 8 instance in order to link together two items.  

The process itself went smoothly, but I found one **odd** / minor issue that I wish to report.

On the target repository, after you accept the COAR notify change, it adds a `datacite.relation.isSupplementedBy` field which links back to the source Item (in the source repository).  This works well, but it shows the label "Dataset" for this field:

DataSet-label

These relationships may not always be to a "Dataset", so I'd propose we update the code with new i18n keys.  This improper label exists also for `datacite.relation.isReferencedBy` and exists in two places (which were not added by this PR, but **were added in earlier COAR Notify PRs**). 

* https://github.com/DSpace/dspace-angular/blob/main/src/app/item-page/simple/item-types/untyped-item/untyped-item.component.html#L81-L88
* https://github.com/DSpace/dspace-angular/blob/main/src/app/item-page/simple/item-types/publication/publication.component.html#L95-L102

I'd propose we remove the `item.page.dataset` i18n key, and replace it with two keys:
```
"item.page.supplemented": "Supplemented By",
"item.page.referenced": "Referenced By",
```

Then, obviously the `datacite.relation.isSupplementedBy` field should use `item.page.supplemented` and `datacite.relation.isReferencedBy` should use `item.page.referenced`. 

This is a minor change, but I feel it's important to properly label these fields.  If you have any objections, let me know, but I suspect this will take only a few minutes to fix.  

Once fixed, I'll quickly review this and merge it.  Thanks!

**Comment by atarix83** [comment]
thanks @tdonohue 

changes applied

**Review by tdonohue — APPROVED** [review]
👍 Thanks @atarix83 !  Looks good to me now

**Comment by tdonohue** [comment]
Merging, however this is flagged as `needs documentation` because we need to document how to send messages between DSpace instances using COAR Notify, perhaps in a new page under https://wiki.lyrasis.org/display/DSDOC8x/COAR+Notify

**Comment by tdonohue** [comment]
This has now been documented at https://wiki.lyrasis.org/display/DSDOC8x/Use+Cases+-+Getting+two+DSpace+application+to+communicate+with+each+other

**Pull request merged**
