### PR TITLE
Changing the bitstream title in the submission form to use the view c…

### LINKED ISSUE #3291: Author lookup modal causes bitstream titles to disappear in submission form
## Describe the bug
In DSpace there is a bug when you are in the submission process. The filename of an uploaded bitstream disappears when you use the lookup (modal) to search for an author to create a relationship.

_My test was made locally with DSpace in version 8, the same error occurs in the sandbox (sandbox.dspace.org) with Version 9._

## To reproduce
1. Login (using a account/role which is allowed to create any new item)
2. Create a new item in any collection that contains an author lookup (e.g. "Publications > Publications 2").
3. Upload an arbitrary file (see screenshot 1 with its red marker - all is well after uploading)
4. Open the author lookup modal by clicking on the search icon
5. Click any checkbox next to a person
6. Now the bitstream title has disappeared (see screenshot 2 with the red marker at same place - the title next to the file size is gone)

If more than one file was uploaded, the title/filename of all bitstreams will disappear.

## Expected behavior
The process of creating a relationship (using the lookup modal) should not cause the filename(s) of any previously uploaded bitstreams to disappear.

### 1
dspace-upload-bug-1

### 2
dspace-upload-bug-2

### PR DESCRIPTION
**Pull request by DanGastardelli**
…omponent title, avoiding disappearance with changes to the form

## References
* Fixes #3291 

## Description
The "fileName" variable was removed from the upload "step" and the bitstream visualization component was used to display the title and thus prevent it from disappearing when the form is changed.

## Instructions for Reviewers

Install this frontend connected to the demo backend or a clean backend and test the submission in a publishing entity that has a form that links metadata to another entity with the search modal active (different from the "suggest" mode). In this submission, you must initially upload the file, check if the file title appears correctly and then open the modal and select the entity to be linked (whether author, advisor, journal...). Note that after this the bistream title remains intact, correcting the problem reported where the title disappeared.

List of changes in this PR:

* Removing original line 21 from the file "src/app/submission/sections/upload/file/section-upload-file.component.html" and replacing it with the import of the "ds-submission-section-upload-file-view" view component; removing this same call from line 46 of the same file.

* In the "src/app/submission/sections/upload/file/view/section-upload-file-view.component.html" view component, the title size was changed from "h5" to "h3" as it was in the previous title and the "span" was included, taking into account the size of the file being processed.

* Inserting the "FileSizePipe" call in the "src/app/submission/sections/upload/file/view/section-upload-file-view.component.ts" component so that it is possible to process the viewing of the submitted file.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You do not need to complete this checklist prior creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [ ] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [ ] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [ ] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [ ] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by jlipka** [comment]
(Not an official reviewer here, still new to DSpace - but I give it a try to test these changes)

The behavior described in the Github issue seems to be fixed. After uploading a new file, the filenames of existing uploads are not removed.

- Expected behavior is present
- Frontend tests (by running "yarn test") are successful

*lgtm*

**Review by jlipka — APPROVED** [review]
lgtm

**Review by tdonohue — APPROVED** [review]
👍 Thanks @DanGastardelli !  Gave this a quick test as well and it fixes the bug.  Code looks good.  I'll port this also to 8.x.

**Comment by DanGastardelli** [comment]
Ok @tdonohue, glad to help!

**Pull request merged**
