### PR TITLE
Upload files - Edit bitstream (improvements and bug fixes)

### LINKED ISSUE #1337: Can't change embargo resource policy on bitstream to open access during submission
**Describe the bug**
When you add an embargo resource policy to a bitstream during submission and save, but during the same submission later change the embargo selected to open access and save then that patch/action fails because the start date previously set for the embargo is also passed along in the patch despite the start date being grayed out when you change the option to open access. (From Log: `Caused by: java.lang.IllegalStateException: The access condition openaccess cannot contain a start date.`)

**To Reproduce**
1. Go to an item in submission (or submit new item), add a bitstream
2. Edit the bitstream and add an embargo on the bitstream with a start date, save it ([example workspace item](https://demo7.dspace.org/workspaceitems/4242/edit))
3. Edit the same bitstream again and change the embargo resource policy to open access and save it
4. This patch fails (`{"op":"add","path":"/sections/upload/files/0/accessConditions","value":[{"name":"openaccess","startDate":"2024-06-01T02:00:00Z"}]}]' \`) => Contains startDate and openaccess, not allowed combination

**Expected behavior**
Should be able to change the embargo resource policy on a bitstream to open access. When the option is changed and the start/end dates are greyed out depending on the option, then those start/end date parameters should not be sent along with the RP replace patch.

### LINKED ISSUE #1359: Enable/Disable start/end date picker in submission broken when no access condition which has start/end date = true config
**Describe the bug**
If you change the [`access-conditions.xml`](https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/access-conditions.xml) config so that your `UploadConfiguration.metadata.options` no longer contains an option which has true for `hasEndDate` (or `hasStartDate`) then the enable/disable of the date picker of that field in submission doesn't work (is always enabled).

If for example you remove the 'lease' option then there is no option that and hasEndDate=true resulting in the endDate option always being enabled in the submission.

This config gets assigned to the form data config [here](https://github.com/DSpace/dspace-angular/blob/main/src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts#L187-L206), resulting in:

- confStart: 

  ```
  [
      {
          "match": "ENABLED",
          "operator": "OR",
          "when": [
              {
                  "id": "name",
                  "value": "embargo"
              }
          ]
      }
  ]
  ```

- confEnd:

  ```
  [
      {
          "match": "ENABLED",
          "operator": "OR",
          "when": []
      }
  ]
  ```

  => This empty when makes it so this condition doesn't work for enabling/disabling the date picker

**To Reproduce**
Steps to reproduce the behaviour:
1. Remove `lease` upload config option [here](https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/access-conditions.xml#L14)
2. Go to submission, add a bitstream, edit the bitstream 
3. On all options the endDate date picker will be enabled, despite all having config `hasEndDate=false`

**Expected behaviour**
The end date picker should be disabled for all options

**Possible solution**
Before checking all accessConditionsConfig [here](https://github.com/DSpace/dspace-angular/blob/main/src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts#L188), add an empty `name=''` so the when is never empty:

```
      const hasStart = [];
      hasStart.push({ id: 'name', value: '' });
      const hasEnd = [];
      hasEnd.push({ id: 'name', value: '' });
      const hasGroups = [];
      hasGroups.push({ id: 'name', value: '' });
```

### LINKED ISSUE #1399: Usability issue when editing uploaded bitstream within the submission
**Is your feature request related to a problem? Please describe.**
We found out that editing the bitstream information during the submission has an usability issue. Indeed when the bitstream form is open the user frequently click the save button in the footer instead of the green save icon, believing in this way to have saved the bitstream form, while it doesn't happen. 
Schermata da 2021-11-10 14-57-24

**Describe the solution you'd like**
To avoid this issue we suggest to change the functionality in order to open the bitstream form in a modal so that it is clear how to save the changed information

### LINKED ISSUE #1415: Can't delete description on bitstream
**Describe the bug**
While working on issue #1337 I found another bug in bitstream edit form.
If the bitstream have a description it is not possible to delete it.
When saving the bitstream the submission is not removed (`remove` is not present in the patch).
The patch is successful and the user does not receive any error notification.

**To Reproduce**
1. Go to an item in submission (or submit new item)
2. Add a bitstream with a non empty description and save it
3. Edit the same bitstream again and delete the content of the description field

### PR DESCRIPTION
**Pull request by davidenegretti-4science**
## References
* Fixes #1337 
* Fixes #1359 
* Fixes #1399 
* Fixes #1415 
* Fixes DSpace/DSpace#7977 (this was actually a **dspace-angular** issue)

## Description
The **Edit bitstream** form has been moved in a modal. Several bugs in the form, mostly related to the **Access condition type**, have been fixed.

## Instructions for Reviewers

List of changes in this PR:

1. The **Edit bitstream** form (`section-upload-file-edit.component`) is now displayed inside a modal. Saving process is managed within the modal component.
2. When  **Access condition type** is changed the PATCH does not fail anymore.
  * Bug reason: when the previous access condition type had a start date or an end date and the new condition type did not have it the previously saved date was still included in the patch, although the corresponding form field was deactivated
3. **Grant access from/until** fields are now correctly deactivated
  * Bug reason: if no access condition type had a start date or an end date the corresponding field was not deactivated for all the access condition types
  * With this fix, when no access condition requires start date or end date the corresponding field is not present at all
4. The description can now be deleted 

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@davidenegretti-4science : Overall, this works GREAT.  However, I found a few minor issues (which is why I'm submitting this as "Request changes").  I tested this today using `yarn start`, and found these results:

1. FIXED #1337
2. FIXED #1359 ... however, I now get a TypeError from the `section-upload-file-edit.component.ts`
    ````
   TypeError: Cannot read properties of null (reading 'markAsUntouched')
    at e.setOptions (section-upload-file-edit.component.ts:247)
    at e.onChange (section-upload-file-edit.component.ts:214)
    at section-upload-file-edit.component.html:16
    ````
    * It appears that the "endDateControl" is now `null` (if you disable the "lease" option), and the code hasn't been updated to handle that.
3. FIXED #1399
4. FIXED #1415 
    * HOWEVER, the Delete (trash can) button next to the "Description" field doesn't work (never enables).  You can remove the old description though by simply deleting all the text and clicking Save.
5. FIXED [#7977](https://github.com/DSpace/DSpace/issues/7977) - Grant Access from/until are only displayed when configured. However, see TypeError above (in bullet 2)


So, overall, every bug is fixed.  However, I think we should minimally fix the TypeError that now occurs (see bullet 2).  If possible, we could also look into fixing the Delete button issues (bullet 4), but that could be moved to a different ticket if it's complex.

**Comment by davidenegretti-4science** [comment]
@tdonohue
I'll check bullet #2 ASAP.
As for bullet #4, the trashcan button (which was already present) removes the whole Description fields, not its content. Assuming that at least one description field is required, this behaviour should be correct. If you add a second field, both buttons are enabled and allow to remove one of the two fields:
image

**Comment by tdonohue** [comment]
@davidenegretti-4science : Thanks for the reminder regarding bullet 4.  If we can simply get the `TypeError` resolved, then this can move forward as-is.

**Comment by davidenegretti-4science** [comment]
@tdonohue I fixed the TypeError

**Review by tdonohue — APPROVED** [review]
👍 Thanks @davidenegretti-4science ! I've retested this today and the TypeError is removed. So, this is ready to merge.

**Pull request merged**
