### PR TITLE
Simple Search tests

### PR DESCRIPTION
**Pull request by LotteHofstede**
This PR connects #134 and is dependent on #162 
As requested in the discussion at PR #151, I added new tests (both unit and e2e tests) for the simple search page.

### CODE REVIEW

**Comment by wwelling** [comment]
The test coverage reduced considerably. And not because of the lack of coverage on this pull requests feature. The nature of the karma test build is how the low coverage was immediately unnoticed. Karma brings in the spec.bundle.js which it includes all the spec files by globbing. The test build and coverage is only aware of code imported into spec files.

**Comment by tdonohue** [comment]
@wwelling : I'm not sure if I fully understand your explanation (though I'm less familiar with how Karma works, as of yet).  Are you saying that this newly calculated coverage percentage (51.5%) is more accurate than the one currently noted on `master` (~70%)?

**Comment by LotteHofstede** [comment]
@tdonohue I understood from @wwelling that the coverage tool only looks at files that are used by (karma) spec files. 
The existing tests only used a few components (because they probably were pretty low level and not dependent on existing components), which it also tested for the most part (70%).

The tests I added test components that are more high-level and use other components (i.e. the object-list component) that already existed, but for which no tests were written yet. So the coverage tool is now all of a sudden also aware of all those other components (as they weren't mentioned/used before in any spec file). 
There may be more tests, but the tool is also aware of more code that exists.

So we probably need a way of making all code "visible" to the coverage test plugin. I think @wwelling was looking for a solution for this. At the moment the percentage has little to do with actual coverage - if you'd test a single low-level component for 100% in 1 spec file and would not add any other spec files, according to this tool, our test coverage would be 100%.

**Comment by wwelling** [comment]
@tdonohue yes, they are more accurate. The spec tests written so far are not importing the entire code base. Therefore, there is no way for karma to create coverage against files not imported into a spec. The primary culprit is that the core module, which imports all the service singletons, is not imported into any spec.

**Comment by wwelling** [comment]
@artlowel suggested simply importing app.module.ts into app.component.spec.ts. This should include everything app.module.ts imports. This may not include lazily loaded modules though.

**Comment by tdonohue** [comment]
Approved in today's meeting. Merging

**Pull request merged**
