### PR TITLE
Angular 8 update

### PR DESCRIPTION
**Pull request by LotteHofstede**
This PR upgrades the code base to Angular 8.2

Angular 8 adds an opt-in for Ivy compilation, which should make compilation faster and might give us the possibility to switch themes at runtime.
Unfortunately, [Ivy is unable to compile Universal (AoT) projects for Angular 8](https://github.com/angular/angular/issues/31522).
This issue has been solved for Angular 9.

Due to this upgrade, the minimal Node.js version is now 10. I updated the Travis configuration to make sure Node 10 and 12 are now used for testing.

The most important code changes after the upgrade include:

 - De CSS selector `/deep/`was replaced by `::ng-deep`
 - The `options` argument for `@ViewChild`/`@ContentChild` is no longer optional and includes a mandatory `static: boolean` field, other fields are still optional
	 - From the angular documentation:
	     > static: True to resolve query results before change detection runs, false to resolve after change detection. 
 - Unnecessary fakeAsyncs in tests result in failed tests, caused by a time out

### CODE REVIEW

**Comment by LotteHofstede** [comment]
@tdonohue Thanks for your review. I haven't been able to reproduce the problems you've reported with the Admin menu. However, I did not use Docker for my build.

I tested this with both node 10 and 12 and in watch and prod mode.

I will update the node version for the Dockerfile as requested.

**Comment by tdonohue** [comment]
@LotteHofstede : Thanks for the minor Dockerfile update & feedback.

I've re-tested this PR today *both* inside of and outside of Docker and the Admin menu issues do not exist.  I'm not sure what the problem was last Friday, but I no longer can reproduce them (maybe it was a temporary hiccup with the REST API). 

That said, in both scenarios (running `yarn run watch` in each case), I'm having difficulty loading the Submissions page. It seems to just hang forever, whether I start a new submission from a Collection or from the MyDSpace page. I've been able to reproduce this both inside & outside of Docker, so, I think there may be an issue here. But, I'd appreciate more eyes.

**Comment by LotteHofstede** [comment]
@tdonohue Thanks for retesting the PR.

I suspect the issue with submission you're experiencing has to do with a recently merged REST PR that limits the amount of embeds in a lot of responses. 

Unfortunately, submission currently heavily relies on these embeds, which is why the page does not load anymore.

Could you test if you're experiencing the same issue with submission using the current dspace-angular master branch?

**Comment by tdonohue** [comment]
@LotteHofstede : You are correct. The same issue (`/submit` just hangs with no response) occurs on the latest `master` codebase, so it's unrelated to this PR.

**Comment by tdonohue** [comment]
Merging as this is at +2.  Thanks again @LotteHofstede !

**Pull request merged**
