### PR TITLE
Added Serbian Cyrillic translation and corrected Serbian Latin translаtion

### PR DESCRIPTION
**Pull request by imilos**
## Description
Added Serbian Cyrillic translation and corrected Serbian Latin translаtion

## Instructions for Reviewers
Added `sr-cyr.json5` translation and modified config files to include this translation. Also slightly corrected Serbian Latin.

List of changes in this PR:
* Added Serbian Cyrillic
* Modified Serbian Latin
* Updated `config.example.yml` and `default-app-config.ts`.

### CODE REVIEW

**Comment by imilos** [comment]
Corrected linter errors.

**Comment by imilos** [comment]
I am not sure what exactly is failing in 18.x. Anyone help with this?

**Comment by tdonohue** [comment]
@imilos : The failure in Node 18.x looks to be a random failure, not caused by this PR.  We occasionally have a few tests that fail semi-randomly (which is unfortunate), but we know that they will usually succeed if we rerun the test.  I just triggered a re-run of the 18.x tests on this PR.

So, this looks good.  I'll pull this over to our 7.6.x maintenance board to find a tester so that we can try to include this in 7.6.1.  Thanks!

**Comment by alanorth** [comment]
Thanks @imilos. I tested this on DSpace 7.6 and it looks good. It's also good you caught the minor errors in the Serbian Latin strings. Хвала!

**Review by alanorth — APPROVED** [review]

**Pull request merged**
