### PR TITLE
Complete tag translations in french for ORCID and Researcher Profile

### PR DESCRIPTION
**Pull request by pilasou**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes partially  #3578 

## Description
Those french translations focus only on the ORCID module and Researcher Profile feature.

### CODE REVIEW

**Review by nimabehforouz — APPROVED** [review]
All the added French translations for ORCID and Researcher Profile reviewed and checked.

**Comment by tdonohue** [comment]
@pilasou : This looks good overall, but it cannot be merged because of linting errors. You should be able to see them by running `npm run lint` locally...and it may be possible to auto-fix them by running `npm run lint --fix`.   They all appear to be small alignment errors in the json5 files.

Once those errors are fixed, the automated tests should pass & we can merge this.  Thanks!

**Comment by pilasou** [comment]
@tdonohue I just changed all the indent problems. I hope all tests will pass! I unsure how to use the npm run lint command, but fortunatly the indent problems were easy to spot.

**Comment by tdonohue** [comment]
@pilasou : It's closer now !  Just two lint errors remain.  You can fix them manually, or you could try running `npm run lint --fix` on the commandline to see if it will fix them automatically.

**Comment by pilasou** [comment]
Hi @tdonohue I corrected the 2 remaining errors. Should be ok now. I know how to better read test results for Lint errors! I will also run the test before committing changes!

**Pull request merged**
