### PR TITLE
Add more themed components

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## Description
Added multiple new themed components

## Instructions for Reviewers

List of changes in this PR:
* Created new themed components for:
  * `AuthNavMenuComponent`
  * `ExpandableNavbarSectionComponent`
  * `ItemMetadataComponent`
  * `EditItemTemplatePageComponent`
  * `LoadingComponent`
  * `ConfigurationSearchPageComponent`
  * `SearchResultsComponent`
* Added themable `MenuSection` decorator

**Include guidance for how to test or review your PR.** 
- Set the theme to custom theme in `config.yml`
- Uncomment the `CustomEagerThemeModule` in `src/themes/eager-themes.module.ts`
- Test if the new components in the custom theme folder can be themed

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by alexandrevryghem** [comment]
Hey @hpwBLN normally those issues have already been fixed here 5682c81217c5da5090ad6cbb4cb561cbca5cd84c

**Review by tdonohue — CHANGES_REQUESTED** [review]
@alexandrevryghem : Overall this works well. I tested it with both the `custom` theme and the `dspace` theme.  

However, I found a bug with the `dspace` theme in that that "All of DSpace" dropdown menu (in the header) sometimes becomes misaligned (just by browsing around).
browse-menu-alignment

When it occurs on the `dspace` theme, it remains misaligned until you reload the page.
This doesn't occur when using the `custom` theme (likely because it has a different style header).

Beyond that, the rest of this PR looks good.  I'm not seeing any other issues in either the code or via testing.

**Comment by alexandrevryghem** [comment]
> @alexandrevryghem : Overall this works well. I tested it with both the `custom` theme and the `dspace` theme.
> 
> However, I found a bug with the `dspace` theme in that that "All of DSpace" dropdown menu (in the header) sometimes becomes misaligned (just by browsing around). I was able to reproduce this by just clicking on "Communities & Collections" in the header: browse-menu-alignment
> 
> Once it occurs on the `dspace` theme, it remains misaligned until you reload the page. This bug doesn't occur when using the `custom` theme (likely because it has a different style header).
> 
> Beyond that, the rest of this PR looks good. I'm not seeing any other issues in either the code or via testing.



> @alexandrevryghem : Overall this works well. I tested it with both the `custom` theme and the `dspace` theme.
> 
> However, I found a bug with the `dspace` theme in that that "All of DSpace" dropdown menu (in the header) sometimes becomes misaligned (just by browsing around). I was able to reproduce this by just clicking on "Communities & Collections" in the header: browse-menu-alignment
> 
> Once it occurs on the `dspace` theme, it remains misaligned until you reload the page. This bug doesn't occur when using the `custom` theme (likely because it has a different style header).
> 
> Beyond that, the rest of this PR looks good. I'm not seeing any other issues in either the code or via testing.

I centered all the elements in the navbar navigation (of the DSpace theme) so it should be fixed now

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem ! This looks good to me now.  I've retested both the `dspace` and `custom` themes and didn't find any other issues.  The code also looks good.

**Pull request merged**
