### PR TITLE
Fix whitespace in links due to newlines

### LINKED ISSUE #2492: Community-List page has extra spaces after links
**Describe the bug**
On DSpace 7.6.1 Angular adds spaces around links, which creates a visual glitch that underlines beyond the text content on hover. The bug can be seen on the [community list page of sandbox.dspace.org](https://sandbox.dspace.org/community-list):

https://github.com/DSpace/dspace-angular/assets/191754/8698fd70-7135-492c-9a9e-fa9170966ace

I have also noticed it on browse links on the item page, but can't find an example on the DSpace demo right now.

**Expected behavior**
We should be using literal metadata values without adding whitespace.

### PR DESCRIPTION
**Pull request by alanorth**
## References
* Fixes #2492

## Description
Fix erroneous whitespace inside link text in community-list cdk tree and browse definition links.

## Instructions for Reviewers
Build the frontend and make sure the links on `/community-list` look and work as expected.

List of changes in this PR:
* Remove newlines in link text

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
Added another fix for browse links. Before:

before-fs8

After:

after-fs8

**Comment by alanorth** [comment]
Assuming this is uncontroversial so adding `1 APPROVAL` tag.

**Review by nwoodward — APPROVED** [review]
👍 It's odd to me that these spaces get created in the first place, but this PR gets rid of them.

**Comment by alanorth** [comment]
Thanks @nwoodward. It's due to whitespace being inside the anchor tag.

**Pull request merged**
