### PR TITLE
Encode all `RequestParam` values

### LINKED ISSUE #2724: Vocabulary `displayed-value`s aren't retrieved using the encoded `stored-value` in submission form
**Describe the bug**
When a field that uses a vocabulary already contains a value (on page refresh or using item template), the `displayed-value` is retrieved by sending the `stored-value` to the backend. The problem is that this value isn't encoded, which means that it sometimes can't retrieve the correct `displayed-value`. This happens for example if your `stored-value` ends with a trailing slash.

**To Reproduce**
1. Add this `value-pairs` to your `submission-forms.xml`:
   ```xml
   <value-pairs value-pairs-name="custom_rights" dc-term="type">
       <pair>
           <displayed-value>N/A</displayed-value>
           <stored-value></stored-value>
       </pair>
       <pair>
           <displayed-value>CC-BY-SA</displayed-value>
           <stored-value>https://creativecommons.org/licenses/by-sa/4.0/</stored-value>
       </pair>
       <pair>
           <displayed-value>CC-BY-NC</displayed-value>
           <stored-value>https://creativecommons.org/licenses/by-nc/4.0</stored-value>
       </pair>
   </value-pairs>
   ```
2. Add this field to your submission form:
   ```xml
   <field>
       <dc-schema>dc</dc-schema>
       <dc-element>rights</dc-element>
       <repeatable>false</repeatable>
       <label>Rights</label>
       <input-type value-pairs-name="custom_rights">dropdown</input-type>
       <hint>Select the rights.</hint>
       <required></required>
   </field>
   ```
3. Select `CC-BY-SA` and click save
4. Refresh the page

**Expected behavior**
After refreshing the page you should still see `CC-BY-SA` in the `dc.rights` field, but now `https://creativecommons.org/licenses/by-sa/4.0/` is being displayed instead

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #2724

## Description
This PR encodes all the `RequestParam`s values. I added an optional parameter to still make it possible to provide already encoded values if needed. This has also an added advantage that it will throw errors for all values that are not created by using the `new RequestParam` constructor, since the third parameter will be missing.

## Instructions for Reviewers
List of changes in this PR:
* Encode the value received in `RequestParam` by default
* Removed the `encodeURIComponent()` of values that were given as parameters to `RequestParam` to prevent values from being encoded twice

**See #2724 ~~& #2727~~ for how to test this PR ~~(#2727 is only reproducible in production mode)~~**

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@alexandrevryghem : Tried to test this today (just cause it looked small & simple).    Unfortunately, it's not working for me.  I was able to reproduce the bug. 

But, with this PR installed, all of the `<value-pairs>` fields no longer show any values.  Here's a screenshot showing the "Type" field.  All fields that use `<value-pairs>` act like this.  Maybe this requires a backend fix as well?
empty-type

There's *no rush* in fixing this issue (as the currently priority for 8.0 is on cleaning up **feature** PRs).  I'm simply reporting what I found, so that you can revisit this after you've finished up with any feature PRs you are working with.

**Comment by alexandrevryghem** [comment]
@tdonohue: Like discussed in #2727 I refactored this PR to encode all `RequestParam`s,  since this fixes both issues at the same time

**Review by tdonohue — CHANGES_REQUESTED** [review]
@alexandrevryghem : I retested this today, and it doesn't seem to have solved both of the issues that it claims to fix:

* First, I can verify that this fixes #2724   That is no longer reproducible with this PR
* However, it does NOT seem to fix #2727.   I no longer get the 500 error that used to occur, but now you are given a 403 error (even after logging in as an Admin) when downloading bitstreams with accented characters. 

Here's how to reproduce the issues with #2727.
1. First, create an item with two files with **no access restrictions**.  Make sure one has **zero** accented characters and one has **at least one**.  Here's an example:
    * One bitstream named `test.doc`
    * One bitstream named `test_ć.pdf`
2. Determine the Item's handle (e.g. `123456789/10`).  Make sure that a basic redirect works properly like this:
    * Visit http://localhost:4000/handle/123456789/10 and make sure you are redirected to the Item
    * Or run `curl --head http://localhost:4000/handle/123456789/10` and make sure it returns a 301 redirect.
3. Now, try the "handle" style redirect for the first bitstream (`test.doc`).  **It should work.**
    * Visit  http://localhost:4000/bitstream/handle/123456789/10/test.doc and verify the file is downloaded.
    * Or, run `curl --head http://localhost:4000/bitstream/handle/123456789/10/test.doc` and make sure it returns a 302 redirect.  (The 302 redirect is slightly wrong, but that's a different bug ticket #2963 )
4. Finally, try the same redirect for the accented bitstream (`test_ć.pdf`) **It will NOT work**
    * Visit  http://localhost:4000/bitstream/handle/123456789/10/test_ć.pdf   You will be prompted to login.  If you login as an Admin, you'll still get a 403 exception
    * Or, run `curl --head http://localhost:4000/bitstream/handle/123456789/10/test_ć.pdf` and you'll see it returns a 200 OK **instead of** a 302 redirect.

If you'd rather split this into two PRs, that's another option.  We could merge this as a proper fix for #2724, if we want to treat that other bug separately.

**Comment by tdonohue** [comment]
@alexandrevryghem : Any chance of still moving this forward for 8.0?  It appears the [feedback in my review](https://github.com/DSpace/dspace-angular/pull/2725#pullrequestreview-2012253773) wasn't addressed yet.  If this is turning out to be too difficult, we can reschedule or separate out the fix for #2727.  Just wanted to remind you that this is waiting on attention.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  Re-tested today and this fixes #2724.   However, since it does NOT fix #2727, I've removed the link to that issue.  We'll need to fix that issue separately.  Code looks good to me & I like that this forces all RequestParams to be encoded by default.

**Comment by tdonohue** [comment]
@alexandrevryghem : I've realized this PR appears to have had a side effect of increasing these statements in the UI logs:
```
The response for 'http://localhost:8080/server/api/authz/authorizations/search/object?uri=http%3A%2F%2Flocalhost%3A8080%2Fserver%2Fapi%2Fcore%2Fsites%2F6d65c6a2-3fe7-44dd-bacb-79271257c35d&feature=canSubmit' has the self link 'http://localhost:8080/server/api/authz/authorizations/search/object?uri=http://localhost:8080/server/api/core/sites/6d65c6a2-3fe7-44dd-bacb-79271257c35d&feature=canSubmit'. These don't match. This could mean there's an issue with the REST endpoint
```

The reason is that the UI is comparing one URL that has the `RequestParam` values all encoded, to one which does NOT have those params encoded.  If you look closely, in the statement above, the URLs are identical except for the encoded params.

Any thoughts on how we might solve this?   In the meantime, I'll pull this into a new ticket

**Pull request merged**
