### PR TITLE
Refactored community & collection pages

### LINKED ISSUE #2425: Community/collection title remains when navigating from local to global browse
# Describe bug

When in a community or collection and using the "browse by" function, if you navigate to the global browse feature under "all of dspace" when moving from local "browse by" category (title) to global nav's "all of dspace" browse, same category (title), the community or collection you were in remains. This only happens if you choose the same category. You will be given the all of dspace browse list for the specific category but it displays under the community or collection you were previously viewing. 

reproduce: 
1. Go to DSpace Demo
2. https://demo.dspace.org/community-list 
3. Choose a community that has a couple items like [2023 BIBLIO TIC Villalba](https://demo.dspace.org/communities/1c10270e-49fe-4b16-88aa-2322585896b8)
4. Choose "Browse by Title" and note the number of search results
5. From here, navigate to the global "All of DSpace" menu and choose "By Title"
6. The community/collection title and breadcrumb trail remains, but the search results change

# Expected behavior

if going along with numbers above, in step 5, after clicking a category to browse by, you would be taken to a page that looks like this https://demo.dspace.org/browse/title and does not indicate that you are within a collection or community but rather browsing the entire system.

### LINKED ISSUE #2700: [Accessibility] Browse By Tabs on Community/Collection Homepages are missing ARIA labels.
Originally reported in #1178 as part of the Deque Analysis in 2021.  This was rated as "serious" by Deque (one level down from "critical") which means:
> Serious: This issue results in serious barriers for people with disabilities, and will partially prevent them from accessing fundamental features or content. People relying on assistive technologies will experience significant frustration as a result. Issues falling under this category are major problems, and remediation should be a priority.

**Describe the bug**

This issue impacts **both** the Community and Collection homepages: 
* (ID 469552, 469655) "Selected state of the element is missing or incorrect." on the currently selected browse by option (e.g. "Subcommunities and Collections" on Community homepage, "Recent Submission" on Collection homepage). In both cases, the selected option is displayed visually, but not noted in ARIA tags.
    * Fix: Use the `aria-current` attribute to indicate the element that represents the current item within a container or set of related elements, such as the currently selected page, step, location, date, or time. https://www.w3.org/TR/wai-aria-1.1/#aria-current

**To Reproduce**
1. Can be reproduced on the demo site with these sample communities/collections:
    * https://demo.dspace.org/communities/0958c910-2037-42a9-81c7-dca80e3892b4
    * https://demo.dspace.org/collections/282164f5-d325-4740-8dd1-fa4d6d3e7200
2. When on either of those pages, verify that the Browse By tabs (under Collection/Community page title) do not have `aria-current` attributes.

**Related work**
Originally reported in #1178

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #2425
* Fixes #2700
* Requires #2339

## Description
The reason why the community/collection title remained was because the global browse by page and the community & collection browse pages used the same component (`BrowseByMetadataPageComponent`). When you went to a community/collection browse page the comcol header & footer that were hardcoded on the global browse page were shown, otherwise they were hidden. Because changing from scope didn't change the component that should be rendered (because both wit or without scope the global browse page was displayed), the page didn't refresh completely. This isn't really a clean way of creating tabs because the community & collection header & footer were duplicate. The cleanest way was to completely refactor the global browse pages and to extract the code that needed to be displayed on both the comcol pages and the global browse pages and move them into browse sections. These sections can then be displayed on the newly created `BrowseByPageComponent` or as a tab on the community/collection pages.

## Instructions for Reviewers
List of changes in this PR:
* Created the `SubComColSectionComponent` containing the community's `Subcommunities and Collections` tab content
* Created the `CollectionRecentlyAddedComponent` containing collection's the `Recent Submissions` tab content
* Removed the comcol header & footer from the `BrowseByMetadataPageComponent` because now this is not needed anymore
* Updated the community & collection routing modules in order to be able to work with the `app-routlet`
* Created a new tab `ComcolBrowseByComponent` that will display the browse sections for both community & collection pages
* Created a new page `BrowseByMetadataPageComponent` that will be used to render the global browse by pages by using the browse sections

During this PR I also found & fixed additional bugs:
- The browse by `dateissued` has an infinite load animation when there are 0 items to display
  -  Fixed this by creating a separate `loading$` variable to that is automatically upated when the backend sends a response back
- The hierarchical browse pages didn't support scoped searches
  - Fixed this by adding the scope to the search query when clicking on the `browse` link
- When you switch between 2 tabs who used the `ComcolBrowseByComponent` the rendered browse section weren't automatically updated. This was because the parameters (in this case `browseByType`) who are used to retrieve the component in `getComponent()` changed without calling the `getComponent` method again. Because the component wasn't reinitialised switching between 2 browse tabs didn't have any effect and it looked like you were still on the same page.
  - Because this is a general component loader bug I moved the fix to #2339 (instead of fixing it in all the loaders individually). This is also the reason why this PR is dependant from that PR
- Themed versions of the browse pages were created, but these are dynamically loaded components using custom decorators, so the correct way to theme those is using the theme parameter in `@rendersBrowseBy(BrowseByDataType, theme)`
  - Also moved this fix to #2339

**Guidance for how to test or review this PR:**
- Verify that the community & collection tabs work
- Verify that the browse sections on the community & collection pages don't display items from different collections
- Verify that the community & collection browse by `dateissued` tab correctly displays the message `No items to show.` instead of the infinite load animation
- Verify that the accessibility issues on the browse page are fixed
- Verify that the hierarchal browse tabs on the community & collection pages now also display their respective header & footer and that the browse button only displays results inside that scope
- Verify that the global hierarchal browse doesn't set a scope

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@alexandrevryghem : Thanks for this work!  I've verified all the accessibility bugs linked in the description are fixed. I've tested all the Community/Collection features that I could think of (including everything related to browse options & all editing options too).  Everything seems to work well overall, but I've found what looks to be a very minor bug with the "Browse by Issue Date" year field.

Here's what I'm doing:
* First, browse to a Community or Collection
* Click on Browse "By Issue Date" tab.
* Immediately click on the "Choose year" dropdown. It will be empty. (This is the bug)
empty-year-browse-date

If you browse to a different Browse option on that same Community or Collection and return to the "By Issue Date" tab, then the year field will show all it's options.  So, the bug appears to be that the menu isn't loaded the first time you access the page.

NOTE: This bug also appears in the global Browse by Issue Date.  It is not reproducible on https://sandbox.dspace.org, so I'm guessing it may be caused by this PR.

Beyond that, this PR looks great.  I've also done a code review and I don't notice anything concerning.

**Comment by alexandrevryghem** [comment]
@tdonohue: Thnx for the review! I fixed the issue, it was caused because [these values in the injector](https://github.com/DSpace/dspace-angular/blob/dspace-7.6/src/app/shared/browse-by/browse-by.component.ts#L187-L188) were only initialised during the `ngOnInit` instead of updating them each time they changed (it's weird that it never came up until now 😅). Moving that code to the `ngOnChanges` method fixed the issue. Afterwards I also refactored the injector logic into the new `StartsWithLoaderComponent`. This way that component doesn't need to be regenerated every time the `ngOnChanges` is triggered.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  I can confirm this works perfectly now.  The code looks good too. 

This PR is waiting on #2722 (which it depends on) to be merged.  @artlowel : if you can find a moment in the next few days, it'd be good to add your feedback to #2722...as this PR further builds in that same direction.

Once these two PRs are ready, I'm currently planning to try to port these to 7.6.x unless anyone has objections.  I figured it'd be nice to ensure the accessibility fixes and general code cleanup get ported back.

**Comment by alexandrevryghem** [comment]
@tdonohue: If PR #2339 is going to get back ported I can also add [these changes](https://github.com/DSpace/dspace-angular/compare/main...alexandrevryghem:dspace-angular:memory-leak-fixes_contribute-7.6) to that PR. On that branch I added improvements that I thought should be back ported to 7.6.2:
- I replaced all the remaining usages of the deprecated `ComponentFactoryResolver`
- I ensured that every dynamically generated componentRef is destroyed in `ngOnDestroy()` by calling the `destroy()` on the `componentRef`
- I also added an `if` statement around the `instantiateComponent()` call in `ngOnInit` in order to prevent the component from being recreated a second time (first it is created by `ngOnChanges` and then it is recreated a second time when the `ngOnInit` is triggered).

**Comment by tdonohue** [comment]
Removed `port to dspace-7_x` label as this will need to be ported manually.  Discussed this with @alexandrevryghem and he noted that the only fix in this PR which should be ported is https://github.com/DSpace/dspace-angular/pull/2722/commits/6adac109682295e6d0624372e2878c7b9f9e14d2

**Comment by tdonohue** [comment]
@alexandrevryghem : If you can get this updated (all merge conflicts are caused by the merger of #2339), I'd love to get this re-reviewed quickly as other work depends on it.

**Review by tdonohue — APPROVED** [review]
👍 Thank you @alexandrevryghem !  I retested this today, and it's working well.  Verified it fixes the two linked issues and that no new issues have appeared in this refactor.

I'll next test that the (partial) port of this to `dspace-7_x` in #2800 is working for that branch.

**Pull request merged**
