### PR TITLE
Export/Import metadata CSV

### PR DESCRIPTION
**Pull request by MarieVerdonck**
## References
Depends on: https://github.com/DSpace/dspace-angular/pull/717
Related issues:
https://github.com/DSpace/dspace-angular/issues/635
https://github.com/DSpace/dspace-angular/issues/756

## Export
The export metadata option on the sidebar is now available for administrator. It opens a modal where you can select all dso, selecting items will result in an error notification however (a way to limit search to communities and collections is being implemented, expect a rest PR next week). While selecting a community and collection will trigger the export and redirect you to the resulting process page where the export csv can be downloaded. This functionality uses the scripts&processes endpoint, specifically the metadata-export script (with params: -i {dso-handle} -f {dso-uui}.csv )

## Import
In the sidebar the import metadata function is now activated and will redirect you to the {dspace-ui}/admin/import-metadata page where there is a dropzone for a single file which will activate the metadata-import script (with params: -e {currentUserEmail} -f {selectedFileName}). If the script request fails (for example if the script does not exist in the backend) an error notification will be shown, otherwise the user is redirected to the corresponding processes’ page where you can check the status of the import process.

## Issues

**Disabling import/export options**
If script is not available in the backend we would like to not show the export/import metadata options, but this is not possible for now and the filter for it has been disabled (see TODO) until Issue #635 is fixed.
If uncommented now: in production mode: button only available after refresh after login; in dev mode: button not available in any way because authorisation request header is not added to script request.
Authentication is not happening before first requests (among which to check if script exists) of page have already been sent; Issue: https://github.com/DSpace/dspace-angular/issues/756

**Scripts failing**
On collection/communities metadata export/import that have complex metadata the script sometimes fails, this is likely a backend issue that will need to be investigated (Failing export example: https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/core/communities/d9c483ca-89d2-437f-aedc-9da0935fd533).

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs for any bug fixes, improvements or new features. A few reminders about what constitutes good tests:
    * Include tests for different user types (if behavior differs), including: (1) Anonymous user, (2) Logged in user (non-admin), and (3) Administrator.
    * Include tests for error scenarios, e.g. when errors/warnings should appear (or buttons should be disabled).
    * For bug fixes, include a test that reproduces the bug and proves it is fixed. For clarity, it may be useful to provide the test in a separate commit from the bug fix.
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
@MarieVerdonck : Just a quick note.  This has some minor merge conflicts after I merged https://github.com/DSpace/dspace-angular/pull/717.  So, it needs a quick rebase.

**Comment by artlowel** [comment]
>1. First, I built this PR with AOT compilation (`yarn start`).  Now, anytime I click reload in my browser, in my commandline (where I ran `yarn start`), I see two errors appear:
>    * `Http failure response for http://localhost:8080/server/api/system/scripts/metadata-import: 401 Unauthorized`
>    * `Http failure response for http://localhost:8080/server/api/system/scripts/metadata-export: 401 Unauthorized`
>    * It seems like something is immediately calling these endpoints when the app loads?  That seems very odd as I haven't even tried to visit this feature.  Those errors appear anytime I click the browser reload button, even if I'm just on the homepage.  Maybe this is a server-side rendering issue?

Marie added a check to verify that the scripts exist on the rest api. If they don't, there's no point in showing the menu options, even if you'd have the rights to show them. As mentioned in the PR description, she commented out the code to actually hide them, because they'll always seem unauthorized until #756 is fixed

>2. While the export feature "works", it's very quick to kick off.  I'd really prefer some sort of prompt that says "Are you sure you want to export [object]"?  The first time, I searched for a Collection and clicked the "Enter" key...it ended up immediately exporting the first result of my search (which was a Community that also matched) which was *not* what I was trying to export.  So, the usability here could be improved since there's no way to cancel an existing export, it'd be nice to prompt the user to confirm the Collection/Community they want to export *before* starting the process.

That's a good point. We'll see what we can do.

**Comment by tdonohue** [comment]
As we decided in today's meeting, my feedback about the AOT compilation could likely be resolved by simply commenting out the check on whether those scripts exist, until we find a resolution for https://github.com/DSpace/dspace-angular/issues/756.  That way the errors do not appear.

**Comment by MarieVerdonck** [comment]
@tdonohue 
- Requests that are launched to backend to check whether or not import/export metadata script exists also commented out for now (until #756 resolves); so no error occurs
- Added a confirmation modal after you press a dso to export; on which you can confirm (proceed as before), cancel (return to export selection modal with previous dso in search) or close (close all modals)

**Comment by tdonohue** [comment]
@paulo-graca : It sounds like this feature mostly worked for you in your testing (other than your stumbling on a backend bug: https://github.com/DSpace/DSpace/issues/2900).  Did you want to give this a second quick review, or should I just merge?

**Comment by tdonohue** [comment]
Merging, as this is at +2 and works as described/scoped.

@paulo-graca : Just a quick FYI regarding the "screen that existed in JSPUI that enabled you to see what it would be changed/added/deleted".  That will be coming in later work. We specifically delayed that task for 7.1, see #782 which describes that task.

**Pull request merged**
