### PR TITLE
DS-2175: send "forgot password" email when user registration fails

### LINKED ISSUE #2175: Fix problem with registration of new user for same email than existing user in 7.5
**Describe the bug**
In DSpace 7.5 you can start the registration process for a new user with an email address that is the address of an already existing user. You receive the email to complete the registration, and only when you try to finish the registration you get an unspecific error message.

**To Reproduce**
1. Create a new user with an email address
2. Finish the registration process
3. Create another user with the same email address
4. You receive an email to finish the registration process, only when you complete the registration process, you get an unspecific error message, saying "Registration failed An exception has occurred"

**Expected behavior**
When you try to register a new user with an email address for which a user exists already, the UI should tell you so, and perhaps offer to reset the password, in case you forgot the password. In no case should it start a new registration process.

**Screenshot**
That's the error message you get, when you try to complete a registration for an email address for which a user exists already:

Screenshot 2023-03-30 at 11 18 03

### PR DESCRIPTION
**Pull request by nwoodward**
## References
* Fixes #2175 

## Description
This PR removes the error message after a failed user registration and attempts to send a "forgot password" email instead.

## Instructions for Reviewers

1. Create a user with an email address
2. Finish the registration process
3. Create another user with the same email address
4. You should receive a "forgot password" alert in the browser and an email instead of an error message

### Notes
- This PR uses the given translation for the "forgot password" alert. A separate one could be created for this specific case if necessary.
- All of the potential failures when creating an EPerson send the same DSpaceBadRequestException, including when an EPerson with the same email address already exists – https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/EPersonRestRepository.java#L159-L185. I could create a separate PR in the REST API that throws a different exception and HTTP Status Code for duplicate entity if that's warranted.

## Checklist
- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [X] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [X] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [X] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [X] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@nwoodward : Apologies for the delay in testing.  Unfortunately, though, this isn't working for me.  Here's the behavior I see:

1. First, I set `mail.server.disabled=true` and watched the backend logs...This allows me to see the full email text in the logs
2. I registered for a new account in my local instance for test@example.com
3. In my logs, I see the "Account Registration" email.  Copied link from that email and finished registration
4. Logged out from that account.
5. Went back to the registration page and entered "test@example.com" again.
6. In my logs, I see the "Account Registration" email AGAIN (wrong behavior).

Am I misunderstanding how this should work?  I was assuming the second time I should see the Forgot Password email?  Currently, it forces me to register again... so I have to fill out an email address & password a *second time*.

**Comment by nwoodward** [comment]
@tdonohue No worries. I recall being a little uncertain as to _when_ the "forgot password" email should be sent. If you added to your testing a seventh step where you copy the link from the second email and fill out the registration form again **then** you would receive the "forgot password" email instead of an error. I see now that you want it to happen at the initial step when the user only enters their email.

**Comment by tdonohue** [comment]
@nwoodward : Yes, I think it makes sense to send the "forgot password" email *instead of* sending them back through the registration form.  I did find that is how this PR currently works, but the workflow is really really odd to me...

1. Register via email.
2. Get "new registration" email response.
3. Click link in email, Fill out name and password for new account
4. Attempt to register same email again.
5. Get "new registration" email response.
6. Click link in email. Fill out name and password *again* (this time they are not saved, so it doesn't matter what you enter... but you must enter something to submit the form)
7. Get "forgot password" email.

I was hoping for simply:
1. Register via email.
2. Get "new registration" email response.
3. Click link in email, Fill out name and password for new account
4. Attempt to register same email again.
5. Get "forgot password" email.

If that's not possible, we can look at other options.

**Comment by nwoodward** [comment]
I remember now why I ended up on the workflow with the few extra steps. It's a less intrusive approach that piggybacks on the response coming back from the REST API when it tries to create an eperson by token after the user fills out the second form. I couldn't find a way for the frontend to query the backend for epersons with a given email address, unless I created a corresponding PR in the backend repo to open it up.

I know the current approach adds a few steps for the user, but presumably this won't happen very often and there will be some time between their registrations, so it may not be too onerous. But I'll look again to see if there's some way to do it that I'm missing.

**Comment by tdonohue** [comment]
@nwoodward : Hmmm... that makes me wonder if there's a better way to do this entirely the backend?  If someone fills out the registration form with an email that already exists...maybe the backend can detect it, and send the "forgot password" email _instead of_ the "new user registration" email?  I.e. Maybe there's a way to handle this in the logic of `RegistrationRestRepository`? https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RegistrationRestRepository.java#L92

I think you are correct, that the UI cannot determine if a user has an account. That's on purpose. See the docs for how both registration & forgot password work in the REST API: https://github.com/DSpace/RestContract/blob/main/epersonregistrations.md#forgot-password

**Comment by tdonohue** [comment]
Closing, replaced by https://github.com/DSpace/DSpace/pull/8816

**Pull request closed without merging**
