### PR TITLE
Fix i18n labels and alignment in vocabulary-treeview

### PR DESCRIPTION
**Pull request by davide-negretti**
### i18n labels

The `vocabulary-treeview` uses the `description` variable to show an i18n label:

    this.translate.get(`search.filters.filter.${this.vocabularyOptions.name}.head`).pipe(
      map((type) => lowerCase(type)),
    ).subscribe(
      (type) => this.description = this.translate.get('vocabulary-treeview.info', { type })
    );

The label used to contain a `type` parameter, but it doesn't contain it anymore.
Therefore this code can be safely removed and the label can be used directly in the HTML template.

### Alignment

The tree view uses `fa-angle-right` and `fa-angle-down` FA icons, which have different widths. When an item is expanded it is no longer aligned with other items:
Schermata del 2023-10-13 10-53-01

I added the `fa-fw` class to give the icons a fixed width:
Schermata del 2023-10-13 10-59-36

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
Hi @davide-negretti. What is `vocabulary-treeview`? I want to test this patch but I'm not sure what that is. Related to hierarchical vocabularies in the submission form or browse interface?

**Comment by davide-negretti** [comment]
Hi @alanorth 
It is in the browse interface, you can find it here: https://demo.dspace.org/browse/srsc

**Comment by davide-negretti** [comment]
@tdonohue I added a very very small commit to this PR to fix the treeview alignment

**Review by artlowel — APPROVED** [review]
Thanks @davide-negretti!

**Pull request merged**
