### PR TITLE
Truncation

### PR DESCRIPTION
**Pull request by LotteHofstede**
I implemented a truncation component that can contain one or more "truncatable" parts.
The truncation component itself can have one of the following 2 state: collapsed or expanded.
When the component is expanded, all its child "truncatable" parts are either totally expanded or capped at a specified amount of lines (@Input() max-lines).
When the component is collapsed, all its child "truncatable' parts are capped at a specified amount of lines  (@Input() min-lines).

I tried a lot of different approaches to implement the multiline clamping, including libraries like shave, ellipsis, clamp...
The issue with all these libraries is that heights can only be calculated when the content is already displayed. At the moment, there's no way of knowing when a component is totally loaded, the default Angular Lifecycle Hooks can't provide us with a solution.

This is why @artlowel and I chose to implement this with CSS instead. We took some inspiration for this from popular websites with a comparable layout. The text is now fading out at the end of a clamped line. 

You might expect an ellipsis at the end of a clamped line instead, but with CSS this is only possible outside of a text block. This did not give us the expected results, especially in list views. 

For now, the truncation has been applied to the search result items (both list and grid view). Clicking a truncated component, will expand it, clicking it again will collapse it again.

### CODE REVIEW

**Comment by Coder206** [comment]
Works visually very well on Fedora 27 in Firefox 58.0.1. 
I noticed that in Chrome (64.0.3282.140), when trying to select the truncated text, the behaviour of the selection differs from what a user normally expects. After you start to select the text, when you reach the point of truncation, your selection jumps back and starts over at the beginning.

**Comment by PTrottier** [comment]
Works visually very well on Fedora 27 in Firefox 58.0.1.
I noticed that in Chrome (64.0.3282.140), when trying to select the truncated text, the behaviour of the selection differs from what a user normally expects. After you start to select the text, when you reach the point of truncation, your selection jumps back and starts over at the beginning.

**Comment by atarix83** [comment]
It looks good to me too

**Comment by tdonohue** [comment]
I've retested this today, and I do see the same behavior as @PTrottier around selecting text in Chrome.  However, I noticed this only occurs if the text is faded/truncated. If you click on the text, it appears fully and you can easily select it.  But, if the fade is in place, selecting the faded text is harder to achieve.

That said, I think this is a relatively minor UX issue (and, as I said, if you click to expand the text first, it can be easily selected).  So, I think this PR should still be merged as-is, and we can always open up a new ticket to describe this minor UX issue, as necessary.

**Comment by PTrottier** [comment]
Agreed, this behaviour also does not occur in Firefox.

**Comment by tdonohue** [comment]
Merged, and logged the minor UX bug here: #234

**Pull request merged**
