### PR TITLE
Search features

### LINKED ISSUE #173: Active filter labels
Create a component to show the active filters as labels on the search page, underneath the search box [as shown in the mockups on the wiki](https://wiki.duraspace.org/display/DSPACE/Search+Mockup#SearchMockup-Selectingfilters)

Add a method to the SearchService that will return the list of active filters based on the URL. The `paramName`s you get back from `SearchService.getConfig()` (e.g. `f.author`, `f.scope`, `f.date`, …) are the request params in the url.

e.g. it the url is `https://dspace7-demo.atmire.com/search?query=influenza%20hospital&f.author=Doe%2C%20John&f.author=Smith%2C%20Donald%20Jr.&f.scope=94c6458d-277c-4b04-b328-4e88a5ceec76&view=grid&f.date=2009` this new method should return 
``` typescript
[
    {
        value: 'Doe, John',
        removeLink: 'https://dspace7-demo.atmire.com/search?query=influenza%20hospital&f.author=Smith%2C%20Donald%20Jr.&f.scope=94c6458d-277c-4b04-b328-4e88a5ceec76&view=grid&f.date=2009'
    },
    {
        value: 'Smith, Donald Jr.',
        removeLink: 'https://dspace7-demo.atmire.com/search?query=influenza%20hospital&f.author=Doe%2C%20John&f.scope=94c6458d-277c-4b04-b328-4e88a5ceec76&view=grid&f.date=2009'
    },
    {
        value: '94c6458d-277c-4b04-b328-4e88a5ceec76',
        removeLink: 'https://dspace7-demo.atmire.com/search?query=influenza%20hospital&f.author=Doe%2C%20John&f.author=Smith%2C%20Donald%20Jr.&view=grid&f.date=2009'
    },
    {
        value: '2009',
        removeLink: 'https://dspace7-demo.atmire.com/search?query=influenza%20hospital&f.author=Doe%2C%20John&f.author=Smith%2C%20Donald%20Jr.&f.scope=94c6458d-277c-4b04-b328-4e88a5ceec76&view=grid'
    },
]
```

Use the data from this new SearchService method to render the filter labels.

Each label should have a "close"-link (the `x`) with the `removeLink` property as their href

### PR DESCRIPTION
**Pull request by LotteHofstede**
This PR depends on #271 and closes #173

* These REST PRs need to be merged before we can merge this one:
  * https://github.com/DSpace/DSpace/pull/2109
  * https://github.com/DSpace/DSpace/pull/2041
  * https://github.com/DSpace/DSpace/pull/2125

Features that were added to the search page:
* Facet suggestions
  * Find possible values for a facet by using the input field at the bottom of the facet component
  * Entering characters shows a dropdown with suggestions for this facet field
  * Uses debounce to limit server traffic
* Date widget
  * Widget used for date facets to easily select a date range
  * Widget: https://github.com/tb/ng2-nouislider
* Filter labels
  * Current active filters shown below the search input field
* Dynamic scope
  * The contents of the scope dropdown are now determined by the currently selected scope
  * When a scope is selected, this scope and it's direct children (if it's a community) are shown
* Multiple sort options
  * Extended the sort options so you can sort by scope, title descending and title ascending
  * Can now easily be updated to contain other fields

Other changes and fixes: 
* Moved some functions in SearchFilterService to a new service: SearchConfigurationService
* PIDService for parsing data from the PID endpoint
* Refactored observables that were explicitly reassigned new values to BehaviorSubjects that emit the new value instead
* Added documentation to all search related typescript files
* Made sure search configuration defaults are defined in one place
* Changing the scope now immediately updates the search results

### CODE REVIEW

**Comment by LotteHofstede** [comment]
Currently the end-2-end tests fail, because the code was written using an updated version of the REST API.
I will rerun the travis build when the PR's mentioned in the description are merged and deployed on 4Science's server.

**Comment by tdonohue** [comment]
The code here looks good.  Thanks for ensuring it has TypeDoc comments, @LotteHofstede! Much appreciated.

However, I'm stuck with how to test / merge this, as there are too many dependencies on other PRs:

* This PR depends on #271, However, #271 is waiting for TypeDocs.  So, it seems like we cannot move this PR forward without #271 getting finalized / merged?
* This PR also needs the three REST API PRs mentioned in the description. However, one of those DSpace/DSpace#2041 is in an uncertain state -- it's failing tests & has merge conflicts.  See latest comments on that PR.

Overall, I'd love to be able to test this more fully in order to approve & merge, but I'm waiting on updates to #271 and DSpace/DSpace#2041 -- as both seem to be blockers for this PR.

**Comment by LotteHofstede** [comment]
Thanks for you feedback.
I fixed #271 and asked @Raf-atmire to take a look at DSpace/DSpace#2041 
He has created a new PR after rebasing, including fixes for the tests that were failing:  DSpace/DSpace#2163

I have merged #271 into this PR to make sure everything is up to date and added some other small fixes.

If you have any other issues testing this PR, please let me know.

**Comment by tdonohue** [comment]
@LotteHofstede : Thanks for the updates. I'll get these PRs reviewed again today or tomorrow.

Just a quick note though...this PR seems to now be failing a few tests.  I suspect it's something minor that occurred during the latest merger.

**Comment by LotteHofstede** [comment]
@tdonohue The failing e2e tests are related to what I mentioned here: https://github.com/DSpace/dspace-angular/pull/280#issuecomment-410162326

Two of the REST PR's I mentioned were merged, but https://github.com/DSpace/DSpace/pull/2125 is still open. This endpoint is used by this PR to lookup the scope list on the search page - therefore the e2e tests that use the scope will fail. 
I tested the current REST master +  https://github.com/DSpace/DSpace/pull/2125 locally, and all tests succeeded.

I will rerun the tests when this last REST PR has also been merged and 4Science has deployed the latest changes to master on their server.

**Comment by tdonohue** [comment]
The final REST dependent PR was merged: https://github.com/DSpace/DSpace/pull/2179
The REST demo site has now been updated with the new `/api/dso/find?uuid=[uuid]` endpoint: https://dspace7.4science.it/dspace-spring-rest/#/dspace-spring-rest/api

I've restarted the latest Travis CI build, so now we can see if the tests all succeed.

**Pull request merged**
