### PR TITLE
Miscellaneous fixes

### PR DESCRIPTION
**Pull request by LotteHofstede**
This PR solves some small remaining issues for the preview release.

It takes care of:

- Making sure clicking the search icon in the header actually directs the user to the search page
- Admin menu links that do not direct to a useful page yet, are greyed out
- The admin menu link to New --> Item now links the user to `/submit`
- Going to item/collection/community pages that don't exist, will now show you a 404 page instead of crashing

#### Update
The tests failed due to the [dspaceObject -> indexableObject issue](https://github.com/DSpace/dspace-angular/issues/391#issuecomment-490005103). So we merged in the [MyDSpace PR](https://github.com/DSpace/dspace-angular/pull/384) to get them to pass. 

[Here](https://github.com/4Science/dspace-angular/compare/mydspace...atmire:Miscellaneous-fixes) you can see only the changes for this PR

### CODE REVIEW

**Comment by LotteHofstede** [comment]
@tdonohue After trying out the examples you gave, I realised you are actually testing something else than what I was referring to when I mentioned "item/collection/community pages that don't exist".
What I implemented was a 404 page for when - for example - an item has been deleted. This implicates that the URL you go to, still contains a valid UUID. The rest service will return a 404 error when this happens.

However, when you simply type any string as an identifier, like you did in your example, the REST service will detect that this is not a UUID and return a 401 status. 
After consulting with @artlowel, I do think the "Error fetching ..." page seems to be appropriate, when the server doesn’t return a 404. I made sure the collection page now behaves similarly to the community and item pages.

**Comment by tdonohue** [comment]
@LotteHofstede : this now has merge conflicts with the latest `master` after I merged the Configurable Entities PR: https://github.com/DSpace/dspace-angular/pull/372

Could you get these cleaned up?  If possible, this is also a good opportunity to simply rebase the PR against `master` -- that should decrease the size of this PR (easing the final review), since the MyDSpace and Configurable Entities PRs are now both merged.

**Comment by LotteHofstede** [comment]
@tdonohue I rebased my branch onto master. Could you verify everything now works as expected? Thanks!

**Comment by Atmire-Kristof** [comment]
I've added an entities related fix to this PR:

There was a bug on certain entity pages (for example Journal), where the filtered search component wouldn't show up at the bottom of the page. This was due to the recent change to how SearchConfigurationService is used. It is expected to be using an Inject annotation.
The bug is fixed after adding an inject annotation (as well as a provider) to SearchConfigurationService in FilteredSearchPageComponent.

**Pull request merged**
