### PR TITLE
Fix #2124 : added default selected option to dropdowns

### LINKED ISSUE #2124: Some dropdowns show a preselected option in Safari, where there is an empty preselection in other browsers. The selection will be shown, but not sent.
**Describe the bug**
In DSpace 7.5 (and before) some dropdowns show a preselected option in Safari, where there is an empty preselection in other browsers. The selection will be displayed, but not sent, which is cause for bugs and confusion.

**To Reproduce**
1. If you have entities enabled, add a new Collection in Safari. The "Entity Type" field shows a preselection, that is not actually saved, when you submit the form.
2. If you have entities enabled, add a new Collection in Firefox. The "Entity Type" field shows no preselection.
3. Create a new Resource Policy in Safari. The fields "Select the policy type *" and "Select the action type *" show a preselection that is not actually selected. As those fields are mandatory, you cannot submit the form, even if they appear to have values selected. You have to select a different value, or select a different value and then reselect the first value to be able to submit the form.
4. Create a new Resource Policy in Firefox. The fields "Select the policy type *" and "Select the action type *" show no preselection.

Screenshot 2023-02-28 at 15 57 54
Screenshot 2023-02-28 at 16 00 51
Screenshot 2023-02-28 at 15 58 33
Screenshot 2023-02-28 at 16 01 53

**Expected behavior**
Dropdowns should work identical to other browsers in Safari. No preselection should be shown, that is not actually selected and sent!

**Related work**
The problem led to some confusion where it appears as if collections have a certain entity type, that is not present in the database:
https://github.com/DSpace/dspace-angular/issues/2123
https://github.com/DSpace/dspace-angular/issues/1661

### PR DESCRIPTION
**Pull request by nishchay7pixels**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #2124
* 
## Description
Short summary of changes (1-2 sentences).
if we set a default value for the dropdown: This ensures that the dropdown always has a preselected option irrespective of the browser

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.
Added default option value for drop downs so that always a preselected option is displayed. This will make sure that across all browsers behaviour stays same.

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

1. If you have entities enabled, add a new Collection in Safari. The "Entity Type" field shows a preselection, that is not actually saved, when you submit the form.
2. If you have entities enabled, add a new Collection in Firefox. The "Entity Type" field shows no preselection.
3. Create a new Resource Policy in Safari. The fields "Select the policy type *" and "Select the action type *" show a preselection that is not actually selected. As those fields are mandatory, you cannot submit the form, even if they appear to have values selected. You have to select a different value, or select a different value and then reselect the first value to be able to submit the form.
4. Create a new Resource Policy in Firefox. The fields "Select the policy type *" and "Select the action type *" show no preselection.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [X] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [X] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [X] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [X] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@nishchay7pixels : Just a quick FYI, it appears this PR currently has build failures if you attempt to build in production mode (`yarn build:prod`).  That's why the automated tests are all failing.

**Comment by tdonohue** [comment]
@nishchay7pixels : I'll restart the tests & see if it succeeds when run again.  There are sometimes "flakey" tests which randomly fail....and it's possible this is one. We'll see if it succeeds on the next run.

**Comment by nishchay7pixels** [comment]
> @nishchay7pixels : I'll restart the tests & see if it succeeds when run again. There are sometimes "flakey" tests which randomly fail....and it's possible this is one. We'll see if it succeeds on the next run.

Looks like we should restart em. It completed with no error however when merged changes from main the test again are failing.

**Review by tdonohue — COMMENTED** [review]
@nishchay7pixels:  While this PR looks good overall, it doesn't appear to solve the bug detailed in #2124 .  The originally reported bug had to do with the "Entity Type" dropdown when you create a new Collection.  This dropdown is unmodified in this PR, because it appears to be using a third-party library. 

So, I'm not against the changes you've made here...but they don't appear to fix the bug ticket #2124 as far as I can tell.  If you have time to investigate #2124 further, it'd be great to add the fix to this PR.  If not, I'll need to find a new volunteer for that ticket.

One other small comment inline below.. I believe there's unnecessary/unused code in this PR that needs to be fixed.

**Comment by tdonohue** [comment]
@nishchay7pixels : Are you still planning to work on this PR?  If not, please close it out or let us know to reassign it.  In the meantime, I've been looking for a volunteer to help with #2124 , as the changes in this PR don't appear to fix the bug.

**Pull request closed without merging**
