### PR TITLE
Added scope @Input() to the SearchComponent & fixed related bugs

### LINKED ISSUE #2792: Switching scopes on the search page with different facets throws 400 errors
**Describe the bug**
Switching between scopes that have different facets throws 400 Bad Request errors in the network tab.

**To Reproduce**
1. Add a new community/collection mapping to your `discovery.xml` like this:
   ```xml
   <entry key="123456789/2" value-ref="person"/>
   ```
2. Go to the search page and select the community/collection scope for which you defined the new `DiscoveryConfiguration` mapping
3. In the network tab you will see 400 Bad Request errors, because the facets of the previous scope will be retrieved with the new selected scope's id first before retrieving the correct ones:
    image

### LINKED ISSUE #2793: Sort options on search page ignore the scope
**Describe the bug**
Currently the sort options displayed on the search page don't take the scope into account.

**To Reproduce**
1. Add a new community/collection mapping to your `discovery.xml` like this:
   ```xml
   <entry key="123456789/2" value-ref="person"/>
   ```
2. Go to the search page and select the community/collection scope for which you defined the new `DiscoveryConfiguration` mapping
3. The displayed sort options should now be the ones from the `person` `DiscoveryConfiguration`

**Expected behavior**
The sort options displayed on the search page should also use the scope like the search facets.

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #2792
* Fixes #2793

## Description
I added an `@Input()` scope to the `SearchComponent` in order to easily be able to defined change the default scope without having to defined it in the url as a query parameter. This PR also fixes a bug caused by a timing issue with the `currentScope$` causing invalid request to be sent to the backend when you changed scope that use a different `DiscoveryConfiguration`. This PR also fixes an issue where the scope was ignored when retrieving the sort options.

## Instructions for Reviewers
List of changes in this PR:
* Added the `@Input() scope: string` to the `SearchComponent` and passed it down to the `SearchFilterComponent` & `SearchFacetFilterComponent` in order to retrieve the facets with the correct scope.
* Refactored the way the the `currentScope$` is used in order to prevent invalid request to be send when you switch between 2 scopes who have different `DiscoveryConfiguration` `searchFilters`.
* Passed the scope to the `searchConfigService#getConfigurationSearchConfig` in order to retrieve the correct sort options

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alexandrevryghem** [comment]
@alanorth: Yes this will fix that issue I will also add the `ds-themed-search-form` on the community & collection pages in PR #2732. If you still see results from the whole repository it probably means that you forgot to add `[scope]="collection.id"` to the `ds-themed-search-form` tag on your collection page.

**Comment by alanorth** [comment]
@alexandrevryghem thanks, apologies as I don't want to derail the conversation.

I had tried the custom `ds-themed-search-form` some weeks ago before this PR. Now I tried again with `[scope]="collection.id"` but it doesn't seem to work: the `scope` is added as a query parameter but the results return immediately and contain all items in the collection. URL with query becomes:

http://localhost:4000/collections/5990226f-7268-4097-a39b-eb2da4d2f367?spc.page=1&query=energy&scope=5990226f-7268-4097-a39b-eb2da4d2f367

**Comment by alexandrevryghem** [comment]
@alanorth: Sry I just realised that you said `ds-themed-search-form` and not `ds-themed-search` 😅, this fix is for the `ds-themed-search` component. I made an example on how this fix works for collection pages: https://github.com/alexandrevryghem/dspace-angular/commit/683c279ec85e0550541ff9100add942914deec47

**Comment by alanorth** [comment]
Thanks @alexandrevryghem. I verified your example. It is indeed working with `ds-themed-search` on collection pages. I was hoping there would be a similar fix for the scope with `ds-themed-search-form` too.

**Comment by alexandrevryghem** [comment]
@alanorth: That's because the recent submission section on collection pages ignores those url parameters, but this component will be replaced with the search component, so I don't think it's worth it to add that functionality for dspace-7.6.2 only. But if you want to hide the search facets & settings on your community/collection pages you should be able to achieve this by adding `[showSidebar]="false"` on the `ds-themed-search-form` tag.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  I tested this today and verified that both bugs are fixed.  The community/collection scope is now taken into account in the facets & sort options.  I couldn't find any side effects to this change, so I'm merging it immediately & auto-porting to 7.x

**Pull request merged**
