### PR TITLE
Fixed ItemSearchResultListElementComponent not fully themable

### LINKED ISSUE #2511: ItemSearchResultListElementComponent not fully themable
**Describe the bug**
Version: 7.6, browser: any
I encountered this while attempting to customize ItemSearchResultListElementComponent so that advisor names (they are `dc.contributor`s in our metadata) wouldn't be displayed in search results (we just want author/creator). We have a theme based off the custom theme, and that component is in custom, so I copied it from the custom theme and made the relevant changes. Advisors indeed no longer show up in the search results, but they continue to show up in browse results (which uses the same component). What seems to be happening is that in browse, the component is wrapped in an [ItemListElementComponent](https://github.com/DSpace/dspace-angular/tree/main/src/app/shared/object-list/item-list-element/item-types/item) which backdoors the core version of ItemSearchResultListElementComponent instead of our customized version.

**To Reproduce**
1. Make a custom version of [ItemSearchResultListElementComponent](https://github.com/DSpace/dspace-angular/tree/main/src/themes/custom/app/shared/object-list/search-result-list-element/item-search-result/item-types/item) or just use the custom theme. and enable the component.
2. Make a visible change to the HTML.
3. Do a search. Your change should be visible.
4. Browse to where the item is visible in a result list. Notice that your change is not visible.

**Expected behavior**
The item displays the same in both search results and browse.

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #2511

## Description
The `ItemListElementComponent` previously used the `ItemSearchResultListElementComponent` selector directly in its HTML, instead of using the `ListableObjectComponentLoaderComponent`. Because of this the `base` theme is always used instead of the correct one.

## Instructions for Reviewers
List of changes in this PR:
* Updated `ItemListElementComponent` to use the `ListableObjectComponentLoaderComponent`.
* Created `ItemListElementComponent#transformItemToItemSearchResult` to convert an `Item` to an `ItemSearchResult`.

**Guidance for how to test or review this PR:**
- Theme the `ItemSearchResultListElementComponent` in your theme (or use the `custom` theme, but don't forget to uncomment the theme in `src/themes/eager-themes.module.ts`)
- Verify that with this PR the `ItemSearchResultListElementComponent` in the browse by pages is now also correctly themed

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@alexandrevryghem :  For some reason, with this PR installed, SSR hangs indefinitely.  It's possible this has conflicts with recent changes like #2865 

To reproduce:
1. Build this PR in production mode by pulling this code on top of latest `main` and running: `yarn install; yarn build:prod`
2. Run via `yarn serve:ssr`
3. Attempt to access the homepage.  The page will never load.

The e2e tests that are run by this PR show a similar behavior.

**Comment by alexandrevryghem** [comment]
@tdonohue: I merged the latest `main` branch and the error was automatically fixed, so this was probably because of a recent change on `main`

**Comment by tdonohue** [comment]
@alexandrevryghem : This appears to be failing specs at this time.  Once that's resolved, I can retest.  Here's the error:
```
FAILED TESTS:
  ItemListElementComponent
    when the publication is rendered
      ✖ should contain a PublicationListElementComponent
        Chrome Headless 124.0.6367.60 (Linux x86_64)
      TypeError: Cannot read properties of undefined (reading 'getRenderTypes')
          at ListableObjectComponentLoaderComponent.getComponent (src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts:131:51)
          at ListableObjectComponentLoaderComponent.instantiateComponent (src/app/shared/abstract-component-loader/abstract-component-loader.component.ts:112:51)
          at ListableObjectComponentLoaderComponent.instantiateComponent (src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts:114:11)
          at ListableObjectComponentLoaderComponent.call [as ngOnInit] (src/app/shared/abstract-component-loader/abstract-component-loader.component.ts:83:10)
          at callHookInternal (node_modules/@angular/core/fesm2022/core.mjs:5136:14)
          at callHook (node_modules/@angular/core/fesm2022/core.mjs:5163:13)
          at callHooks (node_modules/@angular/core/fesm2022/core.mjs:5118:17)
          at executeInitAndCheckHooks (node_modules/@angular/core/fesm2022/core.mjs:5068:9)
          at refreshView (node_modules/@angular/core/fesm2022/core.mjs:12806:21)
          at detectChangesInView$1 (node_modules/@angular/core/fesm2022/core.mjs:13015:9)
```

**Comment by tdonohue** [comment]
It looks like the port to 7.x failed.  If we want to port this to 7.x, that'd need to be in a separate PR.  That said, I'm OK with this also just being an 8.0 change.

**Pull request merged**
