### PR TITLE
miscellaneous fixes for import from external source page

### PR DESCRIPTION
**Pull request by atarix83**
## Description
This PR fixes small bugs present in the import from external source page : 
* Fix issues with route changing from and to the `/import-external`
* Fix issue with dropdown of the extenal providers that showed only the first 5 entries

## Instructions for Reviewers
to reproduce the test : 

- go to https://dspace7-demo.atmire.com/import-external page
- try to go back to mydspace page, the page should show an hanging loading icon. if redirecting to mydspace page works, you should have the same problem if you try to go again to `/import-external` page
Schermata da 2020-10-15 12-24-55
Schermata da 2020-10-15 12-33-16
- if open the dropdown menu you have only 5 entries even if the total entries are more than 5 
Schermata da 2020-10-15 12-34-27

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by atarix83** [comment]
@tdonohue @artlowel 
PR is ready to be reviewed

**Comment by tdonohue** [comment]
NOTE: For some reason the results from `codecov` didn't get synced back into this PR.  Codecov approved this PR & noted that it results in a slight increase (of .01%) in overall coverage. https://codecov.io/gh/DSpace/dspace-angular/pull/894

**Review by tdonohue — APPROVED** [review]
@atarix83 : I tested this today.  I can confirm both issues on our demo site.  I also can confirm that this PR *fixes* the dropdown issue (now all providers are listed).  

It also seems to have better behavior when switching between `/import-external` and `/mydspace`...Usually going back and forth works well for a bit.  But, eventually it always (again) hits a "Loading..." message which causes the page to hang.  In the Chrome DevTools though, it seems like it eventually hits the same error as #897 ... as soon as that error occurs, the "Loading" message never goes away.

So, overall, I think this PR is much better than what is in `main`.  But, it's still not entirely fixing the "Loading" bug.  Nonetheless, I'll approve it as I think that's a separate bug.

**Review by artlowel — APPROVED** [review]
Thanks @atarix83!

I can reproduce the issues, this PR fixes them, and the code looks good

**Comment by artlowel** [comment]
Just saw @tdonohue's comment now, and I can reproduce his issue as well: clicking back and forth between this page and mydspace repeatedly will eventually end up breaking things. So it would be good if you could investigate that still, but as Tim said: it's already an improvement so I'm fine with this being fixed later as well

**Comment by tdonohue** [comment]
I'm going to merge this as-is since it's at +2.  As noted above, it fixes the main bug (it's much better behavior), and the error I was able to still reproduce appears (to me) to be described by #897 .   So, I still think #897 is still necessary to resolve, but as it's already a separate ticket, this one can be merged as-is.

**Pull request merged**
