### PR TITLE
Fix recent submissions list thumbnails

### LINKED ISSUE #1855: Thumbnail placeholders in recent Item list rendered incorrectly
**Describe the bug**
Currently, `ds-recent-item-list` has the same issues with font scaling & tthumbnails/placeholder images not being loaded as we saw with e.g. Relationships on Item pages. 
Here's a screenshot from my phone; the font scaling problem may not be as apparent in "desktop view"

Screenshot_20220923-214901

I should have caught this when reviewing #1780, and since it's right on the front page I think we should try to fit it into 7.4 if at all possible.

**To Reproduce**
Open the front page with list thumbnails enabled

**Expected behavior**
Front page thumbnail placeholders should be rendered correctly

**Related work**
#1780

### PR DESCRIPTION
**Pull request by ybnd**
## References
* Fixes #1855

## Description
This PR fixes list thumbnails in the "Recent Items" section on the homepage. The cause ended up being a combination of the following three bugs:
* `ds-recent-item-list` was not updated to match the changes in #1780 (`followLink('thumbnail')` and CSS class to determine thumbnail placeholder font)
* `HomePageModule` was not set up with all entity classes; it would render results as plain Items, skipping the custom SVG images for e.g. Projects
* `ds-thumbnail` would sometimes fall back to the placeholder even when the default image was valid (faulty logic from #1694)

**TODO:**
* [x] Update specs
* [x] Check SSR

## Instructions for Reviewers
Make sure `browseBy.showThumbnails` is set to true and confirm that #1855 can no longer be replicated.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [ ] My PR doesn't introduce circular dependencies
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by alanorth** [comment]
Hi @ybnd I was just testing the new thumbnail stuff and noticed that items on the "recent submissions" section of the home page didn't have thumbnails, but on search/browse/item pages they did. Your PR fixes it for me on 7.4-SNAPSHOT. I didn't notice any of the other font issues you mentioned, though.

**Before:**
Screenshot 2022-09-27 at 14-27-41 DSpace Angular Home-fs8

**After:**

Screenshot 2022-09-27 at 14-28-09 DSpace Angular Home-fs8

**Comment by ybnd** [comment]
@alanorth the font issues are limited to specific screen widths, in your screenshots the page seems wide enough for everything to work properly without the scaling logic that was missing.

The original issue did include the thumbnails not being loaded at all (I focused on the placeholders & font because that was the first thing I saw)
→ thanks for confirming that this works for you!

**Review by tdonohue — APPROVED** [review]
👍 Thanks @ybnd !  Code looks good.  I tested this and verified it fixes the thumbnail issue in recent submission lists.  Also see that the placeholder images are displaying properly there and in all search/browse pages.  So, this looks good!

**Comment by tdonohue** [comment]
Merging as this is at +1 (alongside a test from @alanorth !)

**Pull request merged**
