### PR TITLE
DS-4283: (Google Scholar) Provide Entity Type Label/Name as part of URL path

### LINKED ISSUE #745: DS-4283: (Google Scholar) Provide Entity Type Label/Name as part of URL path
This is a duplicate of [DS-4283](https://jira.lyrasis.org/browse/DS-4283)

Estimate from release plan: TBD

This is a request from the Google Scholar team.  I talked with them briefly today about the upcoming DSpace 7 release.

They've requested the ability to differentiate Entity Types via the URL path/pattern (e.g. a Person might have a URL of `/person/[uuid]`, while a Publication may have a path of `/publication/[uuid]`. 

The reason they want this feature is so that their crawlers can be "trained" to concentrate on objects of specific types.  Not all Entities may be of interest to Google Scholar (e.g. Persons would likely not be indexed).  Ideally they'd like to be able to make a decision based on the URL, if possible.

They are aware that Entities are entirely configurable, so that this will not be a complete solution for all DSpace installations.  However, for any out-of-the-box Entities, they can train their crawlers to be selective regarding which ones to concentrate on.

### PR DESCRIPTION
**Pull request by Atmire-Kristof**
## References
* Fixes #745
* Depends on #975
* Affected by REST issue https://github.com/DSpace/DSpace/issues/3113

## Description
An additional routing option has been added to support retrieving entities through their entity type and ID.
Visiting an item page will automatically redirect the user to this new entity route (when the item contains a value for `relationship.type`).
The new entity route is now also used instead of the item route wherever possible (e.g. item links, buttons...), the same goes for child-routes like `/edit`.
Furthermore, this new routing option will be used when redirecting handles.

## Instructions for Reviewers
This PR seems a lot bigger than it is, because it depends on #975 You can see only the changes in this PR [here](https://github.com/atmire/dspace-angular/compare/cache-redesign-part-2...atmire:Item-page-redirects)

### To test the route

* Navigate to an entity by going to an url with the following structure: `/entities/:entitytype/:uuid`
* Verify that this displays the corresponding entity.
Note: The `:entitytype` parameter is currently not used for the actual resolved of the entity, only the `:uuid`.

### To test the handle redirection

To test this, some mocks will need to be enabled in the code since the REST handle endpoint current does not work for retrieving items based on the handle, see https://github.com/DSpace/DSpace/issues/3113
To test an entity:

* Enable the `mockPublicationResponse` by uncommenting it in `src/app/shared/mocks/dspace-rest/mocks/response-map.mock.ts`
* Navigate to a handle url like `/handle/123456789/5`, the exact handle does not matter since the response will be overwritten by the mock response.
* Verify that you get redirected to `/entities/publication/0136fe00-43ca-439e-ae6c-b2b08c2b8f5e`.
To test a non-entity item: 
* Enable the `mockUntypedItemResponse` by uncommenting it in `src/app/shared/mocks/dspace-rest/mocks/response-map.mock.ts`
* Navigate to a handle url like `/handle/123456789/5`, the exact handle does not matter since the response will be overwritten by the mock response.
* Verify that you get redirected to `/items/0136fe00-43ca-439e-ae6c-b2b08c2b8f5e`.

### To test the item route redirect

* Visit the `/items/:uuid` route for an item containing a metadata value for `relationship.type`. Verify you're redirected to `/entities/:entitytype/:uuid` (also verify the entity type is lowercased)
* Visit the `/items/:uuid` route for an item containing **no** metadata value for `relationship.type`. Verify you still end up on the item page without entity route.

### To test entity route links

Any location containing a clickable link to an item page, should now contain a link to the entity route where available.

* Visit discovery and filter on items containing a relationship type. Hover over their links and verify they contain the entity route instead of the item route.
* Log in as administrator and visit the item page for an item containing a metadata value for `relationship.type`. Hover over the "edit item" button (top-right of the page) and  verify they contain the entity route instead of the item route. Clicking the button should redirect you to the edit page of the item on the entities route.
* Try to find other locations with item links and verify they translate to entity routes for items containing a metadata value for `relationship.type`.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by artlowel** [comment]
**note**: added label e/39, not e/61, because those 61 hours also contain rest estimates. 39h was the angular total

**Review by tdonohue — APPROVED** [review]
👍 @Atmire-Kristof : I gave this a review and test today.  I reviewed the diff with #975, and the code changes look good.  I also tested this thoroughly with about 4-5 entity types & some normal items.  It all works exactly as I'd expect it would (and to me it looks like it aligns perfectly with what Google Scholar has asked for).  

I was also able to test Handle redirects and they seem to work great too.  NOTE FOR OTHER REVIEWERS:  While I have verified https://github.com/DSpace/DSpace/issues/3113 is a bug, you can work around it by changing your `handle.prefix` setting in local.cfg.  Handle redirects for Items work as long as the `handle.prefix` matches the Item handle prefix (see [this comment](https://github.com/DSpace/DSpace/issues/3113#issuecomment-769379728))

All in all, I'm +1 this, but obviously I cannot merge this until #975 gets merged (and then I'd prefer we do a quick rebase here just so the changes in this PR can be more clearly seen).

**Comment by tdonohue** [comment]
@Atmire-Kristof : Now that #975 was just merged, please rebase this so that I can give it a final check & approval.  Thanks!

**Review by tdonohue — APPROVED** [review]
👍 Retested this today (alongside https://github.com/DSpace/DSpace/pull/3150) and this is working as described and looks good to me.  Thanks @Atmire-Kristof !

**Comment by tdonohue** [comment]
@Atmire-Kristof or @artlowel  : Could you rebase this on the latest `main`?  It looks to have a number of new code conflicts.  This is ready to be merged as soon as it can be rebased.  Thanks!

**Review by tdonohue — APPROVED** [review]

**Pull request merged**
