### PR TITLE
Collection mapper

### LINKED ISSUE #974: The Edit Collection - Item Mapper page has disappeared
**Describe the bug**
In https://github.com/DSpace/dspace-angular/pull/348, a page was added to edit the mapped items in a collection. Now I can no longer see any links to it in the UI, and if you go to the route directly you get a 404.

**To Reproduce**
1. Authenticate as an admin
2. Go to the edit/mapper route of a collection
3. Verify that you get a 404

**Expected behavior**
The page should be linked from the edit collection page, and work if you go to the url directly

**Related work**
The page was added by https://github.com/DSpace/dspace-angular/pull/348

### PR DESCRIPTION
**Pull request by MarieVerdonck**
## References
* Fixes #974
* Depends on #975

## Description
This PR fixes the item and collection mapper pages created in #348 and adds links to them as tabs on the respective edit collection and edit item pages as tabs. 

This PR seems a lot bigger than it is, because it depends on #975 You can see only the changes in this PR [here](https://github.com/atmire/dspace-angular/compare/cache-redesign-part-2...atmire:collection-mapper)

## Instructions for Reviewers
Go to a collection edit page > Item Mapper tab:
Try to map new items to the collection and remove some of them.
Go to one of the mapped items > edit page > Collection Mapper tab:
Your previous collection should be present in mapped collections.
Try to add/remove mapped collections of item on collection mapper tab.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
@MarieVerdonck : Please rebase on latest `main`.  Keep in mind we just updated to Angular 10, which changed some lint rules. So, you may also want to ensure `yarn lint` doesn't throw errors (as its possible the PR may need minor formatting updates to pass).

**Review by tdonohue — COMMENTED** [review]
@MarieVerdonck : Thanks for this. The code changes here are small (it's <200 lines of new code, once #975 is merged, so I'm adding the `1 Approval` label) and they look good.  I've also tested this and the Item & Collection Mappers are working well for me.

One thing I *did notice* (which doesn't seem to be the fault of this PR) is that **after I map an item into a Collection, surprisingly it does NOT appear in the Collection homepage** (in any of the browse by options).  My guess is this may be an issue with the backend...but, I wonder if you could confirm whether you see the same thing?  If so, I'll simply log that as a backend bug and we can move this PR forward as-is (once #975 is merged though).

**Comment by MarieVerdonck** [comment]
@tdonohue I had only tested that it appeared in the corresponding mapper tab (so when you map an item on a collection edit page that that collection is present in the corresponding item’s mapper page). But I tested your scenario and indeed it doesn’t appear in the Collection browse after you map an item on the edit collection page. I’m guessing the discover search or browses which is used there doesn’t include mappedItems.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @MarieVerdonck .  This PR looks good & works as described.  I've logged a separate bug for the issue with mapped Items not appearing in the Collection Browse (https://github.com/DSpace/DSpace/issues/3141). 

This PR is ready to merge **AFTER** the #975 PR (which it depends on) gets merged....this also should be quickly rebased after 975 is merged, just so it's clearer which changes are unique to this PR.

**Comment by tdonohue** [comment]
@MarieVerdonck : Now that #975 is merged, could you please rebase this PR so that it only shows the new, unique changes?  Then I'll give it a final look over before merging. Thanks!

**Comment by artlowel** [comment]
@tdonohue Ben pointed out you don't need to rebase for the PR to update. Simply switch the base away from main, and back to it, and the list of commits in the PR updates. I've done that here and I'll do the same with the others

**Review by tdonohue — APPROVED** [review]
Re-reviewed after merger of #975, and this looks good!  Merging with `1 approval`!  Thanks again @MarieVerdonck!

**Pull request merged**
