### PR TITLE
Update Arabic Translation

### PR DESCRIPTION
**Pull request by mohamedali654321**
Update Arabic Translation by KnowledgeWare Technologies Est.

Update  ar.json5 translation

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #`issue-number` (if this fixes an issue ticket)
* Requires DSpace/DSpace#`pr-number` (if a REST API PR is required to test this)

## Description
Short summary of changes (1-2 sentences).

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

List of changes in this PR:
* First, ...
* Second, ...

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [ ] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by Massoud-Alshareef** [comment]
This PR provides the Arabic Translation of DSpace 8.0 strings as found in DSpace 8 repository at the time of its official release announcement. It has been loaded in our DSpace 8 demo instance (https://dspace8.kwaretech.com/) currently under testing. 

We will wait until DSpace 8.1 strings freeze to add the translation of those additional strings that will come with 8.1. 

Thanks, Massoud.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @mohamedali654321 for this translation update.  This looks good to me. (Apologies for the delay in getting to this one)

**Comment by Massoud-Alshareef** [comment]
Thank you Tim.The current translation is intended for DSpace 8.0. It needs to be updated for the next release, 8.1 and 9.0. We need to be informed by the freezing date for the upcoming release.Massoud.On 15 Oct 2024, at 12:48 AM, Tim Donohue ***@***.***> wrote:﻿
@tdonohue approved this pull request.

👍 Thanks @mohamedali654321 for this translation update.  This looks good to me. (Apologies for the delay in getting to this one)

**Comment by tdonohue** [comment]
@mohamedali654321 and @Massoud-Alshareef :  At this time, unfortunately, we don't have anyone who is able to notify all translators when a new translation is ready to create.  So, you must be proactive if you want to keep the Arabic translation up to date at all times.

However, I can state that minor release (e.g. 8.1) tend to have _few or no_ new i18n keys, because they are bug-fix only releases.  So, it's likely that 8.1 will be very little effort (when that release is ready).

For 9.0, the best approach would likely be to work on an updated translation as soon as the 9.0 Community Testathon is announced. Tentatively that would be in the Feb/Mar timeframe next year (2025).  The 9.0 release is tentatively due in April 2025 (date to be determined), so I'd recommend considering doing an updated translation in Feb or Mar.

The final 9.0 release schedule will be posted to our Developer Meeting agendas as soon as it is ready (it is still being worked out).  So, you can also follow along with that release schedule in Developer Meeting agendas/notes here: https://wiki.lyrasis.org/display/DSPACE/Developer+Meetings

**Pull request merged**
