### PR TITLE
Fix for "No option appears for Bundle when the user is loading a bitstream of an item"

### LINKED ISSUE #2101: No option appears for Bundle when the user is loading a bitstream of an item
Hello @tdonohue i found an issue

**Describe the bug**
When the user tries to upload a bitstream when he is editing an item bundle options does not appear.

**To Reproduce**
1. Login as Administrator
2. Edit any item
3. Go to bitstreams section
4. click on upload button
5. try to select a bundle

image

**Expected behavior**
The user should be able to see the option texts.

### PR DESCRIPTION
**Pull request by CrisGuzmanS**
Hello @tdonohue i alredy worked on this task and i hope this can be worth for this issue. I will be attentive 👍 
## References
* Fixes #2101 

## Description
I added a the suggestion option text to display them in bistream upload.

## Instructions for Reviewers
i just added the suggestionOption.name in the bitstream upload section.

List of changes in this PR:
* suggestionOption.name in _dso-input-suggestions.component.html_

1. login as Admin
2. edit any input
3. go to bitstreams section
4. click on upload bitstream section
5. select a Bundle.
6. You will see that the bundle names is displayed.

image

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
Thank you so much @CrisGuzmanS !  I'll get this reviewed/tested immediately.  If it works for me, I'll ensure it is merged into 7.5 prior to that release.

**Comment by tdonohue** [comment]
@CrisGuzmanS : Thanks for this work.  Overall, this **fixes the bug**, but I'm seeing errors occurring behind the scenes... which makes me suspect there's something else broken in the code.

Here's the error I see behind the scenes in my Chrome DevTools Console:
```
core.mjs:7739 ERROR TypeError: Cannot read properties of null (reading 'ɵcmp')
    at getComponentDef (core.mjs:1128:1)
    at ViewContainerRef.createComponent (core.mjs:22959:1)
    at ListableObjectComponentLoaderComponent.instantiateComponent (listable-object-component-loader.component.ts:171:37)
    at ListableObjectComponentLoaderComponent.ngOnInit (listable-object-component-loader.component.ts:144:10)
    at callHook (core.mjs:2551:1)
    at callHooks (core.mjs:2520:1)
    at executeInitAndCheckHooks (core.mjs:2471:1)
    at refreshView (core.mjs:9595:1)
    at refreshEmbeddedViews (core.mjs:10731:1)
    at refreshView (core.mjs:9604:1)
```

It appears to be referencing our `ListableObjectComponentLoader`, which I know had some recent changes in behavior... e.g. in #1912.

So, while I **think** your fix is at least part of the solution, I'm going to ask @artlowel to look at this tomorrow as well (since his team worked on #1912) to see if there are additional fixes need (I'm not familiar enough with this code to be certain).  He's based in Belgium though, so he surely won't be online at this time of night.

So, overall, I'd like to leave this PR open until tomorrow, waiting on @artlowel 's feedback.  I'll make sure some sort of fix gets into 7.5 so that this bug no longer exists.  Thank you so much for your quick solution here!

@artlowel , if you could help test/review this I'd appreciate it (or delegate to someone on your staff).  I suspect there may be additional changes necessary, but it's very possible that this PR should be merged first & then followed up with additional fixes.

**Comment by CrisGuzmanS** [comment]
@tdonohue thank you for the answer.

I found the same error too, but i am not pretty sure how to fix it, that error appears in the main branch:
image

i will be attentive to @artlowel comments, if I can help in any way, I will 👍

**Comment by tdonohue** [comment]
@CrisGuzmanS : Yes, I'm seeing the same thing as you.  The console error appears on both `main` and in this PR.  I **suspect** @artlowel will have a better idea of the cause of this error... and, if so, I want to give him the chance to comment on this PR.  It may be that this PR is a "good enough" fix for 7.5, and we could always fix the underlying errors in 7.6 (if they will take longer to solve). But, I'll wait for @artlowel  to also look at this first before making a decision.

**Review by artlowel — DISMISSED** [review]
Thank @CrisGuzmanS, but I don't think this is the way to solve it

This component is used for more than just bundles. The `ds-listable-object-component-loader` below your change is supposed to render the content dynamically based on its type, so the solution shouldn't be to put a fixed string in front of that, rather we should fix the dynamic loading in this case.

The reason for both https://github.com/DSpace/dspace-angular/issues/2101 and the console error is that the listableObjectComponents for rendering bundles can't be found. Looks like it was accidentally removed from the ENTRY_COMPONENTS array in SharedModule in https://github.com/DSpace/dspace-angular/commit/1c7108e9286edf3ef54157454a99dca4123ebb79#diff-71ee557103ff1e53a7c4f46a8d510ceb4134b7e22caa6c531c2255b76317100aL454

Putting it back should fix both issues

**Comment by CrisGuzmanS** [comment]
Thank you for the feedback @artlowel i am attending your request

**Comment by CrisGuzmanS** [comment]
Hello @tdonohue according to the feedback by @artlowel was able to solve both problems. Thank you so much 👍 
image

**Comment by tdonohue** [comment]
Thanks @CrisGuzmanS !  I'll give this a test again today so that we can get this fixed in 7.5

**Review by tdonohue — APPROVED** [review]
👍 Thanks @CrisGuzmanS and @artlowel !  I've verified this updated PR fixes both issues.  Merging immediately so we can get this into 7.5

**Pull request merged**
