### PR TITLE
Add HTML support on system-wide alert (Fixes #3019)

### LINKED ISSUE #3019: HTML support on system-wide-alert
**Is your feature request related to a problem? Please describe.**
When using the system-wide alert feature I've wanted several times to put a specific link for our users. Normally it's to give them a direct link to a specific page describing an update or an email address to contact for a specific reason. Being able to highlight some information would also be really useful.

**Describe the solution you'd like**
To be able to use HTML for the system-wide alert messages.

**Describe alternatives or workarounds you've considered**
I don't think full HTML support is necessary, only the ability to put links and maybe bold text.

### PR DESCRIPTION
**Pull request by abelgomez**
## References

* Fixes #3019.

## Description

Adds HTML support to the system-wide alert banner.

## Instructions for Reviewers

The commit only includes two simple changes, as explained in https://github.com/DSpace/dspace-angular/issues/3019#issuecomment-2103135271.

In a second commit (I did it in a separate commit to ease the PR review), I also reformatted the code of the HTML templates, since the indenting was a bit mangled.

To test, log in as an admin, and set a system-wide alert message with HTML code in it.

Some examples of the result:

imagen

imagen

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by AgustinAlfieri** [comment]
Just tested this, I can add HTML to the system-wide alert banner but It **gave me problems trying to set up a timer:**
image

------------------------------------------------------------------
**The issue persists even if I don't use HTML on the form:**

image

------------------------------------------------------------------
**If I roll back the changes, the timer works just fine:**

image

**Comment by abelgomez** [comment]
Can anybody else try this PR?

I cannot reproduce the misbehavior with the timer... 😞

imagen

**Comment by AgustinAlfieri** [comment]
Just in case this is why, I tested using yarn start:dev not by doing the yarn build.

**Comment by abelgomez** [comment]
I also tested this PR in the dev environment with `yarn start:dev` using the main branch of DSpace 8.

But I deployed this patch in a stable server running DSpace 7.6/7.6.1 months ago without issues: https://biblioteca.sistedes.es

**Comment by AgustinAlfieri** [comment]
Just re-tested, it works perfectly. Sorry I had something else generating the problem.

**Comment by abelgomez** [comment]
No worries! Great! ☺🤗

**Review by tdonohue — APPROVED** [review]
👍 Thanks @abelgomez !  Tested this today and it works well.  It's a very simple change (basically a "one-liner" style bug fix), so I'm going to also port this back to 7.x

**Pull request merged**
