### PR TITLE
Comcol resource policies

### PR DESCRIPTION
**Pull request by atarix83**
## References
https://github.com/DSpace/dspace-angular/issues/848

## Description
This PR adds implementation for collections/communities resource policy management.
Implementation is similar to the existing Item-level feature.

## Instructions for Reviewers
- login as admin to the application
- open a community edit item page
- go to new `authorizations` tab and try to add/edit a new resource policy
- do the same for a collection

## List of changes in this PR:
* added a new `authorizations` tab in the community edit page
Schermata da 2020-11-10 09-58-16

* added a new `authorizations` tab in the community edit page
Schermata da 2020-11-10 09-58-41

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by artlowel — APPROVED** [review]
Thanks @atarix83!

There's a small merge conflict at the moment, but apart from that: it works, and the code looks good

**Comment by tdonohue** [comment]
@atarix83 : Just a reminder, this PR has a merge conflict... it also should be rebased so that the GitHub CI tests run against this branch.  Thanks!

**Comment by atarix83** [comment]
@tdonohue this should be ok now

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me now, @atarix83 !  I also tested it and everything is working as expected.

Therefore, I'm going to merge this as it's at +2.

NOTE for @artlowel  : As I know you'll likely need to update #739 anyway after this merger, keep in mind there's a TODO in this PR in `resource-policy-create.component.ts`  -- it might be unnecessary code once #739 is applied.

**Comment by artlowel** [comment]
>NOTE for @artlowel : As I know you'll likely need to update #739 anyway after this merger, keep in mind there's a TODO in this PR in resource-policy-create.component.ts -- it might be unnecessary code once #739 is applied.

You're right, it was no longer necessary. Updated in #961

**Pull request merged**
