### PR TITLE
verify whether file uploads are mandatory

### PR DESCRIPTION
**Pull request by benbosman**
This PR will ensure the Angular UI will take the "upload required" value from REST into account.
For testing this, make sure to explicitly set `webui.submit.upload.required` in REST, the default value is not implemented correctly in REST yet

### CODE REVIEW

**Comment by benbosman** [comment]
@atarix83 We discovered and solved a bug in REST that caused the default behavior to be incorrect: https://github.com/DSpace/DSpace/pull/2650
Until that's merged, the webui.submit.upload.required has to be set explicitly in REST to ensure it works

**Comment by benbosman** [comment]
Thanks for the reviews, I was able to reproduce this as well now.
It seems the master merge has caused a timing issue, the `getSectionStatus()` is sometimes called before the `this.required` is set.
I will check this out in more detail

**Comment by benbosman** [comment]
The `this.required` has been migrated to a BehaviorSubject
This has resolved the problem

**Comment by tdonohue** [comment]
Merging, as this required one review and I've verified that the previous bugs have all been resolved.

**Pull request merged**
