### PR TITLE
Fix issue with submission sections visibility

### LINKED ISSUE #3274: Submission step can't be hidden for only one submission scope
**Describe the bug**
By submission form documentation it's possible to configure a step with visibility hidden

immagine

Nevertheless currently it works only if the step is hidden for both scopes, e.g.
```
<step-definition id="traditionalpageone" mandatory="true">
    <heading>submit.progressbar.describe.stepone</heading>
    <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
    <type>submission-form</type>
    <scope visibility="hidden" visibilityOutside="hidden">submission</scope>
</step-definition>
```

But if i want to hide the step for only one scope it doesn't work. For example the following configuration should say the step is visible during submission scope but hidden during the workflow scope
```
<step-definition id="traditionalpageone" mandatory="true">
    <heading>submit.progressbar.describe.stepone</heading>
    <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
    <type>submission-form</type>
    <scope visibilityOutside="hidden">submission</scope>
</step-definition>
```

**To Reproduce**
1. Change the submission configuration in order to set the visibility of a step like the following 
```
<step-definition id="traditionalpageone" mandatory="true">
    <heading>submit.progressbar.describe.stepone</heading>
    <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
    <type>submission-form</type>
    <scope visibilityOutside="hidden">submission</scope>
</step-definition>
```
2. Create a new submission in a collection where workflow is enabled and that it's using the submission configuration set in the previous step
3. The step is visible during submission
4. deposit the item
5. as admin claim the workflow item created and edit it
6. the same step which should be hidden is visible anyway

**Expected behavior**
It should be possible hide a submission step just for one specified scope

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by atarix83**
## References
* Fixes #3274
* Requires DSpace/DSpace#9783

## Description
This PR fixes a bug with submission section visibility described by #3274

## Instructions for Reviewers
To test this PR follow those steps:
- Change the submission configuration in order to set the visibility of a step like the following
```
<step-definition id="traditionalpageone" mandatory="true">
    <heading>submit.progressbar.describe.stepone</heading>
    <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
    <type>submission-form</type>
    <scope visibilityOutside="hidden">submission</scope>
</step-definition>
```
- Create a new submission in a collection where workflow is enabled and that it's using the submission configuration set in the previous step
- Check the step is visible during submission
- Deposit the item
- As admin claim the workflow item created and edit it
- Check the same step is hidden

You can also test the case where the step should be visible during workflow only, by using the following configuration
```
<step-definition id="traditionalpageone" mandatory="true">
    <heading>submit.progressbar.describe.stepone</heading>
    <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
    <type>submission-form</type>
    <scope visibilityOutside="hidden">workflow</scope>
</step-definition>
```
More test could be done by following the documentation **https://wiki.lyrasis.org/display/DSDOC8x/Submission+User+Interface**

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `yarn lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `yarn check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [x] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@atarix83 : Just a quick note, this PR seems to include a large number of unrelated commits (45 commits in total), when only the last few seem related to this bug fix.  Could you try to rebase or cleanup this PR so that is shows the proper commits?  It might be that you just need to rebase on latest `main`.

**Comment by atarix83** [comment]
@tdonohue done

**Review by nwoodward — APPROVED** [review]
👍 I tested and confirmed this PR and https://github.com/DSpace/DSpace/pull/9783 work. With both PRs deployed locally I was able to limit the scope of the `traditionalpageone` step so that it only appeared in the submission form but not when editing a Workflow item.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @atarix83 !  Code looks good to me.  I gave it a light test & trust the tests from @nwoodward

**Comment by tdonohue** [comment]
@atarix83 : This was unable to be ported to 7.6.x automatically.  Would you be able to make a `dspace-7_x` version of this PR, so that we could port this fix back to 7.x?

(NOTE: It was ported to 8.x automatically.  So, at the very least we'll have this fixed in 8.1)

**Pull request merged**
