### PR TITLE
Cookie consent preferences

### PR DESCRIPTION
**Pull request by LotteHofstede**
## References
* Fixes [#734](https://github.com/DSpace/dspace-angular/issues/734)
* Fixes [#735](https://github.com/DSpace/dspace-angular/issues/735)
* Dependent on [#856](https://github.com/DSpace/dspace-angular/pull/856)

## Description
This PR adds a cookie preference pop-up using [Klaro](https://kiprotect.com/klaro) and saves them per account.

## Instructions for Reviewers

To test this feature, make sure the metadata field `dspace.agreements.cookies` exist on the REST server you're testing with. I already created this field on https://dspace7.4science.it/server/api.

On opening the application, a small dialog in the bottom right corner (or just at the bottom on mobile) shows, where the user can choose to accept/decline/customise their cookie consent preferences.
Clicking 'customise' should open a more detailed pop-up where you can see what cookies are used for DSpace and disable them. Some of the cookies are required for DSpace to work and can not be disabled. 

When a user logs in, the preferences selected are copied to a cookie specifically used for this user and stored in the metadata field `dspace.agreements.cookies` of the user.

When the user already has preferences defined in the`dspace.agreements.cookies` field, these settings are used when the user logs in and copied to a cookie specifically used for the authenticated user.

When the authenticated user changes their consent preferences later, the metadata field value for the user is updated.

The cookie consent preferences can be changed by the user at any time clicking the 'Cookie settings' link in the footer.

I have already added a link for the "End user agreement" and "Privacy policy" in the footer, however these pages will be added by different PRs.

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by LucaGiamminonni — COMMENTED** [review]
@LotteHofstede I noticed that even if the user does not accept cookies clicking on deny, after he login the dspace.agreements.cookies metadata is still set as if he had accepted only the mandatory ones. How should the application behave if the user does not accept the cookie conditions?

**Comment by artlowel** [comment]
The user can't refuse the mandatory cookies, they're required for the site to function. So even if you click deny all, you can't help but accept the mandatory cookies. Their toggles are also disabled in the UI. That approach is GDPR compliant as long as our mandatory cookies are _actually_ required for the site to function.

**Comment by LucaGiamminonni** [comment]
@artlowel Ok, thanks. So I think it can be integrated:
- I have analyzed the changes made to the code and they seem ok to me
- I have verified that when the application is opened the cookie box is shown at the bottom right
- I have verified that clicking on 'customise' opens a detail in which the collected information is listed, divided between the mandatory (functional) and optional (statistical) ones
- I verified that at the user's login the choice made by the user regarding cookies is correctly saved in the metadata dspace.agreements.cookies
- I verified that the cookie consent preferences can be changed by the user clicking the 'Cookie settings' link in the footer. in this case the dspace.agreements.cookies metadata is also updated correctly.

**Review by LucaGiamminonni — APPROVED** [review]

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me.  The code changes in this PR are less than they seem (as it looks to include all of the changes from #856).  So, I reviewed the code via a [diff of the branches](https://github.com/atmire/dspace-angular/compare/Hard-redirect-after-log-in...Cookie-preferences).

I also tested it, and it works as described.  Also made sure to test the scenario where you accept cookies prior to login, and I verified that the accepted cookies are then copied to your user account after you authenticate.

Overall, looks good to me.  Thanks @LotteHofstede !

**Pull request merged**
