### PR TITLE
Admin Registry pages and service

### PR DESCRIPTION
**Pull request by Atmire-Kristof**
This PR is dependent on #235 

Created admin registry pages for metadata-registry, metadata-schema and bitstream-formats. 

The pages are accessible through the routes "/admin/registries/metadata", "/admin/registries/metadata/:schemaName" and "admin/registries/bitstream-formats" respectively.
:schemaName refers to the schema's prefix (e.g. "dc")

These pages use a service called RegistryService, which fetches data from the rest api.

Currently, there's no edit functionality and no pagination because the rest api doesn't support editing data and fetching fields per schema yet.

### CODE REVIEW

**Comment by tdonohue** [comment]
FYI, this PR currently has conflicts with latest `master`.  It likely needs a rebase.

**Comment by Atmire-Kristof** [comment]
@tdonohue resolved conflicts with master. Thanks for the heads-up!

**Comment by tdonohue** [comment]
@Atmire-Kristof and @artlowel : I gave this a quick test today. It looks good! 

However, I did notice one bug.  While the `/admin/registries/metadata` endpoint seems to work fine, the `admin/registries/bitstream-formats` only returns the first *page* of results. So, only the first 20 file formats are returned, even though the [demo REST API claims to have "totalElements=80"](https://dspace7.4science.it/dspace-spring-rest/#https://dspace7.4science.it/dspace-spring-rest/api/core/bitstreamformats).  Even though you mentioned that pagination isn't working, I had expected this to return 80 results instead of 20.

If this is an expected bug (caused by lack of pagination), we can merge this PR as-is and simply create a new ticket to fix it (when pagination support is added).  Otherwise, I'm OK with merging this as soon as the bug is resolved.

**Comment by Atmire-Kristof** [comment]
@tdonohue It's an expected bug due to the lack of filtering support in the rest (which made us remove pagination for now, because of some weird results).
Increased the page size for bitstream formats and metadata-registry so it always shows all results on one page.

**Comment by tdonohue** [comment]
Looks good to me. Thanks @Atmire-Kristof! Sorry for the delay in getting back.

**Pull request merged**
