### PR TITLE
edit item metadata fix

### LINKED ISSUE #1317: edit item metadata not working when changing metadata field name
**Describe the bug**
This is a bug shown Edit Item page.
It is related with edition of the metadata of an item, concretely, with the edition of the field of the metadata related with an item.
When the user tries to edit the field of one of the metadatas, with which it is related, an error is shown with popup in the edit item page. 

**To Reproduce**
1. The first step is going into Menu → Edit → Item → Selecting an item from popup list of items. 

image-20210824-095956
image-20210824-100124

2. In the Edit Item page, select the third option “Metadata“ to work with.

image-20210824-100336

3. Click button edit (the first button) in the section Edit of the table (the last column) for one of the rows. 

image-20210824-100531

4. Try to edit the first column → named “Field“ (representing the metadata field) and replace it with another metadata field, for example replace dc.description with person.identifier.orcid. After that click check button (the first button in the last column with check sign). 

image-20210824-100736

5. After check button, click Save button shown above, in blue color. Change won't be saved and a popup error will appear

image-20210824-101128

In the console is shown this request  sending a replace operation with the new metadata field set by the user, as it is shown in images below (the request and the error thrown  by the server):

image-20210824-101417
image-20210824-101330

**Expected behavior**
Is expected that after edition of the metadata field,  the metadata related with this item should be changed successfully  and must be related with the new field replaced by the user.  

A popup of confirmation should be shown in the edit item page as it is shown below, as an example. Also in the table (in the row edited) must be shown the row of the metadata edited,  containing in the first column,  the new field replaced by the user. 

We (4Science) can take in charge the fix of this bug, with two different approaches: 

1. block the possibility of editing metadata field name by disabling it (and removing angular code triggered when metadata field name is changed) 
OR
2. Handle the metadata field name change. When metadata field name changes:  i) a  remove is performed for the metadata which field is being changed, in case of repeated metadata only metadata in position (place) related to field being changed should be removed, and then an add in append (“/new-metadata/-”) for the new metadata  is performed.

First approach would roughly require 6 to 8 hours, including tests, while the second 12 to 16 hours.

### PR DESCRIPTION
**Pull request by corrad82-4s**
## References
* Fixes #1317

## Description
When editing an item metadata, it is not possible change metadata field name since its input field is disabled. 
This to prevent errors reported in issue #1317. 
Despite of what estimated, this update took us 2 hours.

## Instructions for Reviewers

List of changes in this PR:
* added disable input to ValidationSuggestionComponent
* edit-in-place-field-component html changed so that its ds-validation-suggestion is disabled, using above input field, during metadata update and deletion operations, this change 

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 
* Log in into dspace7
* from left menu select edit -> item and choose an item to edit
* go to "metadata" tab
* Click the right column toggle to edit an existing metadata
* Verify that input field for metadata name is blocked 
* Click on Add button
* Verify that it is possible to define a name for metadata to be added, and suggestion works.

## Checklist

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [X] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [X] My PR doesn't introduce circular dependencies
- [X] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [X] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@corrad82-4s : The code here looks good & it works (just tested it).  Could we add some specs though to the `edit-in-place-field.component.spec.ts` or maybe at least the `validation-suggestions.component.spec.ts`.   Tests will help us ensure that future code changes don't accidentally break this fix.

**Comment by corrad82-4s** [comment]
hi @tdonohue , thank you for your feedback. We have pushed some changes on specs in order to provide test coverage on this feature.

**Comment by tdonohue** [comment]
@corrad82-4s : It looks like the tests you pushed have lint errors.  You should be able to see those errors locally by running `yarn lint`.  Once those are fixed, I'll gladly re-review.  Thanks!

**Comment by corrad82-4s** [comment]
hi @tdonohue , apologies for missing lint issues. I have done another push that should fix this issue.

**Review by tdonohue — APPROVED** [review]
👍 Reviewed the new specs and they look good.  I also re-tested and this works as described.  Thanks @corrad82-4s!

**Pull request merged**
