### PR TITLE
Preview release theme

### PR DESCRIPTION
**Pull request by LotteHofstede**
This PR adds a custom theme to the DSpace 7 Angular frontend, made especially for the preview release.
This new theme isn’t meant to replace the default bootstrap foundation we have, but rather to make a first attempt at what a theme on top of that could look like.

The green from the DSpace logo was used to add some contrast to the theme and make it look more vibrant.
A photo banner was added behind the home page news and search bar to add more color.
The search bar also got a more prominent place on the home page.
We changed the repository's font to [Source Sans Pro](https://fonts.google.com/specimen/Source+Sans+Pro)

All changes to the theme have been saved in separate files.
We looked in to ways to be able to switch between themes on the fly or using config, but because DSpace 6 has quite elaborate theming functionalities (the ability to have different themes for different scopes, the ability to  include not only CSS but HTML in the theme, etc) we decided not to implement a quick and inadequate solution for this right now, but instead keep it as simple as possible until we have a well thought-out solution that’s at least as versatile as DSpace 6.

This PR also includes the home news text from PR #321 taking Tim’s comments into account.

Screenshot of the new home page:
localhost_3000_home (2)

Screenshot of the new search page:
localhost_3000_home (3)

### CODE REVIEW

**Comment by tdonohue** [comment]
@LotteHofstede and @artlowel :  I really like this theme overall!  After reviewing it though, I have a number of questions (which might be easier to discuss in great detail in next week's meeting -- already added to the agenda).  Here's just a few:

1. Because there's no easy configurability of themes yet, merging this PR would apply this theme as the default one on `master`.  Is that what we want to do for the Preview Release? Or should we consider applying this to a different branch initially?
2. I don't really like calling this theme "preview-release".  Even if it's for the Preview Release, I'm assuming we'd want this theme maintained after that, so we likely should have a better name :)
3. Do we have an idea of a long term theming strategy for DSpace 7? Should themes be allowed to customize/override the component templates (like this one is doing), or do we aim for themes that are more like Bootstrap themes (CSS/SASS themes)?  This PR points out that overriding templates in components is a bit awkward at best (I'm not sure about the file naming strategy that results in files like `home-news.component.preview-release.html`, but I admit I don't have a better idea right now).

I don't expect the two of you to answer all these questions -- some of these likely require more discussion.  But, if you've thought about a longer term theming strategy (or have links to examples of what we might consider), it could be worth bringing brainstorms to our next meeting.

Overall though, I do like this theme. I only have questions about how best to move it forward.

**Comment by artlowel** [comment]
>1. Because there's no easy configurability of themes yet, merging this PR would apply this theme as the default one on `master`.  Is that what we want to do for the Preview Release? Or should we consider applying this to a different branch initially?

Because there's no easy configurability, I'd prefer to keep it out of master until there is. I want to prevent that new components are only styled for this theme. I want the plain bootstrap version to be the default for new development so that future themes have a clean slate to start from.

>2. I don't really like calling this theme "preview-release".  Even if it's for the Preview Release, I'm assuming we'd want this theme maintained after that, so we likely should have a better name :)

I asked Lotte not to spend time thinking up a clever name. But we'll try to come up with something snazzier.

>3. Do we have an idea of a long term theming strategy for DSpace 7? Should themes be allowed to customize/override the component templates (like this one is doing), or do we aim for themes that are more like Bootstrap themes (CSS/SASS themes)?  This PR points out that overriding templates in components is a bit awkward at best (I'm not sure about the file naming strategy that results in files like `home-news.component.preview-release.html`, but I admit I don't have a better idea right now).

If we want to be support all of DSpace 6's features we'd need to support template overrides in themes, as that is supported in at least XMLUI (I'm not sure about JSPUI). However, that isn't common in the angular world, I haven't found another example yet (though I'd like to look some more before proclaiming it doesn't exist). CSS-only themes are the norm, and I can find multiple examples on how to create them, swap them on the fly, etc. 

Even to support CSS-only themes, we'd still need to tweak our webpack config though, to build separate CSS bundles for the different themes, instead of chucking everything in style tags in the HTML as we do now. Because we want to be able to set different values for our SASS variables for each theme, we can't load all themes at once (that wouldn't be good for the performance anyway). I spent some time trying to change the webpack config for this PR, but I wasn't able to get it working well enough just yet.

The naming strategy can definitely still be changed. I'd also like to support themes as separate npm packages, that you can just add as a dependency without having to touch the dspace source code. That would mean that the theme files would have their own, separate directory structure and wouldn't necessarily need a name that was different from the original files. But for now, we figured putting the theme name in the files was a clear way of indicating they belonged to the theme.

I'll work on a theming strategy that supports all our requirements, and present in the discussion section of one of our meetings. I can't promise it will be ready by this week's meeting though.

**Comment by artlowel** [comment]
>>I don't really like calling this theme "preview-release". Even if it's for the Preview Release, I'm assuming we'd want this theme maintained after that, so we likely should have a better name :)
>
>I asked Lotte not to spend time thinking up a clever name. But we'll try to come up with something snazzier.

We renamed it to "Mantis" which refers to "mantis green" the shade of green used in the dspace logo, and the theme

**Comment by artlowel** [comment]
Closing in favour of #389. Since entities has been merged there is no more need for this PR

**Pull request closed without merging**
