### PR TITLE
Added support for change list sizes on bundle edit

### LINKED ISSUE #2779: Re-ordering bitstreams on the item edit page not possible when pagination is triggered
**Describe the bug**
On the item edit page, all bundles are shown with their related bitstreams.
If more than 10 bitstreams are attached to a given bundle, those bitstreams are paginated.
That in and of itself is a good thing, but it has a negative effect on the possibility to reorder these bitstreams.
It's only possible to reorder bitstreams on the page that they currently are on 

**To Reproduce**
* Take any random item and add more than 10 different bitstreams to a given bundle.
* Test that the reordering works on any given page by dragging and dropping
* Screenshot 2024-01-29 at 14 15 32
* If you want to move a bitstreams from the second page to the first page, you'll notice that is not possible, you can only drag and drop on the same page
Screenshot 2024-01-29 at 14 15 37

**Expected behavior**
With or without pagination triggered for bitstreams in a certain bundle, it should be possible to reorder the relevant files.

Simply increasing the number of bitstreams being shown before pagination is triggered is not an option, as some dataset repositories could have an even larger number of bitstreams.

### PR DESCRIPTION
**Pull request by oscar-escire**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #2779 

## Description
Added a button for change element list size

## Instructions for Reviewers
- Generate an item with 11 or more bitstreams in a bundle
- Click on the gear icon on the bundle name row and change size of list

List of changes in this PR:
* Added a custom gear button that enables change size  of bundle paginator drag and drop list

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You do not need to complete this checklist prior creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `yarn lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `yarn check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [x] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by artlowel — CHANGES_REQUESTED** [review]
Thanks @oscar-escire!

As [I commented on the ticket](https://github.com/DSpace/dspace-angular/issues/2779#issuecomment-2318073329), there is already a way to move a bitstream to a different page, though at the moment it seems it's a bit buggy, and clearly people don't know about it, so it needs to be made more apparent

However, that doesn't mean it's a bad idea to add the ability to set a page-size to this page. Your PR works, so I don't see why we couldn't include this as well

A few comments though: 
- The tests are currently failing, it seems likely these changes have broken some pre-existing tests
- It would be a good idea to refactor the gear and all the logic involved into a separate, dedicated component

**Comment by mwoodiupui** [comment]
I don't oppose changing the list size, but in yesterday's meeting I thought of an alternate approach which should work (if it is workable!) for lists of *any* size:  cut/paste.  Many tools do this by simply remembering that the user requested to cut a list element and then moving the element to the target position when "paste" is done.

**Comment by oscar-escire** [comment]
Thanks @tdonohue, @artlowel, @mwoodiupui!

I have updated the PR attending your comments. 

- I improved the function to drag and drop on a specific page, the function was based on hovering the mouse to select when and to which page the item should be moved, which caused that if the user quickly moved the mouse to another place after releasing the element, the element will only move to the end of the list instead of the selected page, it now relies on the point where the item is dropped to make this calculation.
- I updated the unit tests based on the changes of the components
- Also added a tooltip to "make more visible" the drag and drop function to a item page (maybe the position of the tooltip need to be improved)

By now I prefer no to move the logic of the page size to a separated component because the PaginationComponent include the necessary to change the page size in the lists, but it doesn't fit very wheel in the bundle's drag and drop list' case so, that configuration options its hidden

**Review by artlowel — APPROVED** [review]
Thanks @oscar-escire!

The latest changes make it more clear how moving an item to a different page works. 

The issue where the loading component for the next page sometimes doesn't disappear until something _else_ moves isn't solved yet. But we're already working on https://github.com/DSpace/dspace-angular/issues/3154, so we'll fix that in the context of that PR

**Comment by tdonohue** [comment]
@oscar-escire and @artlowel :  I noticed this was already at +1, so I was trying it out myself.  While the Page Size option **works well**, I cannot seem to get the drag & drop to a different page to work.  Is it supposed to work?

I've tried this:
* Create an Item with 6 bitstreams in the `ORIGINAL` Bundle
* Edit that Item & go to the Bitstreams tab
* Change the page size of the `ORIGINAL` Bundle to 5.  This creates two pages.
* Now, drag the 3rd item in the list to Page 2.  The page reloads but no reordering occurs.

In the backend logs, I see this error:
```
2024-10-08 19:19:06,072 ERROR ec49885b-3617-4441-a022-20dcf8505f51 1f1d6765-f820-46d9-a084-bb1097082f7c org.dspace.app.rest.RestResourceController @ Failed moving bitstreams of bundle with id 2c08572e-b393-4c8d-886f-ee5a8671d768 from location 2 to 10: "to" location out of bounds. Latest available position: 5
 org.dspace.app.rest.exception.DSpaceBadRequestException: Failed moving bitstreams of bundle with id 2c08572e-b393-4c8d-886f-ee5a8671d768 from location 2 to 10: "to" location out of bounds. Latest available position: 5
   at org.dspace.app.rest.repository.patch.operation.BundleMoveOperation.perform(BundleMoveOperation.java:73) ~[dspace-server-webapp-9.0-SNAPSHOT.jar!/:9.0-SNAPSHOT]
   at org.dspace.app.rest.repository.patch.operation.BundleMoveOperation.perform(BundleMoveOperation.java:32) ~[dspace-server-webapp-9.0-SNAPSHOT.jar!/:9.0-SNAPSHOT]
   at org.dspace.app.rest.repository.patch.ResourcePatch.performPatchOperation(ResourcePatch.java:58) ~[dspace-server-webapp-9.0-SNAPSHOT.jar!/:9.0-SNAPSHOT]
   at org.dspace.app.rest.repository.patch.ResourcePatch.patch(ResourcePatch.java:42) ~[dspace-server-webapp-9.0-SNAPSHOT.jar!/:9.0-SNAPSHOT]
   at org.dspace.app.rest.repository.DSpaceObjectRestRepository.patchDSpaceObject(DSpaceObjectRestRepository.java:64) ~[dspace-server-webapp-9.0-SNAPSHOT.jar!/:9.0-SNAPSHOT]
   at org.dspace.app.rest.repository.BundleRestRepository.patch(BundleRestRepository.java:111) ~[dspace-server-webapp-9.0-SNAPSHOT.jar!/:9.0-SNAPSHOT]
```

It looks like it's trying to add the moved bitstream to position 10 (the last position on page two?), when it should be likely moving it to the *first position* on page two?

I've also tried moving the one Bitstream on page 2 onto page 1.  But, that also fails with a similar error:
```
org.dspace.app.rest.exception.DSpaceBadRequestException: Failed moving bitstreams of bundle with id 2c08572e-b393-4c8d-886f-ee5a8671d768 from location 10 to 0: "from" location out of bounds. Latest available position: 5
```
Maybe it doesn't work as soon as you change the page size from the default of 10?

**Comment by tdonohue** [comment]
Closing, as this doesn't fully work & now appears to have been fixed in #3464 (and the port PRs).  I've just verified that PR fixes the same issue, along with several accessibility fixes.  At that PR is nearly completed / approved, I'm closing this one as a duplicate. 

Nonetheless, thanks @oscar-escire for your work on this.  It's a shame we were not able to get this merged prior to another PR fixing the same problem.

**Pull request closed without merging**
