### PR TITLE
Czech DSpace 7 UI translation by NTK

### PR DESCRIPTION
**Pull request by dewi-g**
## Description
Added full translation of DSpace 7.6 frontend into Czech language 

## Instructions for Reviewers
Please notify us of any translation you disagree with on specified email, alongside  opening a new pull request.

### CODE REVIEW

**Comment by dewi-g** [comment]
I have fixed the formatting issues and it went through most of the tests, but it failed on 20.x accessibility test (in single case). How can I fix that please? I couldn't understand anything on the ARIA rules link it linked.

**Comment by tdonohue** [comment]
@dewi-g : I'll restart the test.  It's likely a *random failure* if it only fails in either 18.x or 20.x.  We have a few tests which are randomly failing for some PRs & haven't yet figured out why.  It's likely it will succeed for 20.x once the next run completes.

**Comment by alexandrevryghem** [comment]
@dewi-g: Your `cs.json5` file currently doesn't contain the comments above the translations, these are used to track when translations might be outdated & this also prevents those values from being overridden the next time someone runs the `yarn run sync-i18n` script (an example of a key that will be reset the next time the script is run is: `admin.registries.bitstream-formats.edit.head`). [This is the branch](https://github.com/alexandrevryghem/dspace-angular/commits/fix-cs-json5/) with the fixed json file, could you follow these steps in order to update this PR:
```
git remote add origin https://github.com/techlib/dspace-angular.git
git remote add alexandrevryghem https://github.com/alexandrevryghem/dspace-angular.git
git fetch alexandrevryghem fix-cs-json5
git push -fu origin alexandrevryghem/fix-cs-json5:main
```
In addition to restoring the comments, I also mapped some translations for keys that were renamed to the new keys, removed keys that were no longer used & did a sync with the latest `en.json5` file

**Comment by dewi-g** [comment]
@tdonohue one of the tests has failed again, can you please restart it?

**Review by tdonohue — APPROVED** [review]
👍 Thank you @dewi-g !  I tested this today and verified that the new translations load correctly.  I also verified via Google Translate that they look accurate.

**Comment by tdonohue** [comment]
Port to 7.x in #3043

**Pull request merged**
