### PR TITLE
Collection dropdown on MyDSpace & support enable/disable in Submission UI

### LINKED ISSUE #671: MyDSpace page should include a way to select a Collection for starting a new submission
As in DSpace 6, it was possible to start a new submission & select a Collection via a user's the MyDSpace page.  This feature is necessary for individuals who only have SUBMIT level rights, as they will not be able to access this Admin side menu to start a new submission.

For DSpace 7, we must implement a way to start a new submission from the MyDSpace page while also selecting the Collection to start in.  

Ideally, this should use the same Angular component as the Collection dropdown in the Submission UI and the Collection selector in the Admin Sidebar menu (as there is no need to maintain multiple components that do the same thing).  This may require code refactoring.

This could be implemented as a simple dropdown next to the drag & drop box in the MyDSpace area.  Or it could be a popup window/component that occurs after initiating a drag & drop (which is similar to how this occurred in DSpace 6).

This is dependent on first fixing the performance issues with this Collection dropdown component. See #487.

### LINKED ISSUE #673: Collection dropdown in Submission UI should not appear if disabled in backend configuration
As discussed in this week's DSpace 7 meeting and in https://wiki.lyrasis.org/display/DSPACE/Collection+dropdown+in+submission, we need to support the ability to **disable the Collection dropdown** in the Submission UI.  This change is necessary as not all institutions may be willing to accept the side effects of changing a Collection after already starting a submission (see wiki page for details on those side effects)

As proposed in the above wiki page, the idea is to not display this dropdown if the "collection" step is _not included_ in the submission configuration.  This would, in effect, revert to DSpace 6-like behavior, where the Collection must be specified *prior to starting the submission* and cannot be changed after the fact. 

This change is dependent on #671, as that separate ticket defines how we will specify the Collection (on the MyDSpace page) prior to starting the submission.

### PR DESCRIPTION
**Pull request by ddinuzzo**
## References

Fixes #671
Fixes #673

## Description

In this PR has been added:
- a new shared component used to display list of collections. This component is used as the collection dropdown in the Submission UI, as the collection selector in the Admin Sidebar menu and to start a new submission from the MyDSpace page
- support to enable/disable the collection dropdown in the Submission UI

## Instructions for Reviewers

- This PR must have to testing with REST API presents in another PR (https://github.com/DSpace/DSpace/pull/2771)
- to test the status (enabled/disabled) of the collection dropdown in the Submission UI comment/uncomment the collection step in the submission configuration.

## Checklist

_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

 - [x]  My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
 - [x]  My PR passes Checkstyle validation based on the  [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide)
 - [x]  My PR includes Javadoc for  _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
 - [x]  My PR passes all tests and includes new/updated Unit or Integration Tests for any bug fixes, improvements or new features. A few reminders about what constitutes good tests:
    -   Include tests for different user types, including: (1) Anonymous user, (2) Logged in user (non-admin), and (3) Administrator.
    -   Include tests for known error scenarios and error codes (e.g.  `400 Bad Request`,  `401 Unauthorized`,  `403 Forbidden`,  `404 Not Found`, etc)
    -   For bug fixes, include a test that reproduces the bug and proves it is fixed. For clarity, it may be useful to provide the test in a separate commit from the bug fix.
 - [ ]  N/A If my PR includes new, third-party dependencies (in any  `pom.xml`), I've made sure their licenses align with the  [DSpace BSD License](https://github.com/DSpace/DSpace/blob/master/LICENSE)  based on the  [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions)  documentation.
 - [ ]  N/A If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by tdonohue** [comment]
Just wanted to add a quick note here to say that I've reviewed the code and it all looks good/reasonable. I haven't had a chance to test this yet though, but will do so tomorrow.

**Comment by atarix83** [comment]
thanks @artlowel for review 
> On mydspace, when I click the new submission button, I get the collection select, as was discussed. However if you drop a file on the dropzone, I get a notification that the workspace item was created: click HERE to edit it. If I click HERE I go straight to the submission. I would expect to also get the collection select first in this case.

This will be fixed in a follow-up PR regarding [this issue](https://jira.lyrasis.org/browse/DS-4514)

> Not new in this PR, but the word HERE in that notification is positioned strangely, it is lower than the rest of the text. There's also no need to put in in all caps.

we will fix it

**Comment by ddinuzzo** [comment]
Hi @artlowel !
I have fixed the position of the word "here" in the notification

**Comment by atarix83** [comment]
@tdonohue since the [related REST PR](https://github.com/DSpace/DSpace/pull/2771) was merged I realized is urgent to merge this PR in the master, otherwise Angular app doesn't work properly
could you give a test as soon as you can? thanks

**Pull request merged**
