### PR TITLE
Port OIDC (OpenID Connect) auth plugin from DSpace-CRIS

### PR DESCRIPTION
**Pull request by hardyoyo**
## References
* Fixes DSpace/DSpace#8087
* Requires DSpace/DSpace#8088 be applied to backend

## Description
Adds UI elements to support OIDC (OpenID Connect) logins in DSpace-Angular. This code is a direct port of the OIDC code from DSpace-CRIS 7.

## Instructions for Reviewers
You must have the changes in DSpace/DSpace#8088 applied to the REST-API you're using to test, and you must have an OIDC provider of some sort available and configured to work with your REST-API server (see docs on DSpace/DSpace#8088). 

List of changes in this PR:
* src/app/core/auth/models/auth.method-type.ts
* src/app/core/auth/models/auth.method.ts
* src/app/shared/log-in/methods/oidc/log-in-oidc.component.html
* src/app/shared/log-in/methods/oidc/log-in-oidc.component.spec.ts
* src/app/shared/log-in/methods/oidc/log-in-oidc.component.ts
* src/app/shared/shared.module.ts
* src/assets/i18n/en.json5

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@hardyoyo : This works once I got the backend working.  Code looks good to me overall, and looks very similar to our existing Shibboleth implementation.

So, I'm basically a +1 on this, but I have feedback on the backend PR (see that separate review) which I think should be addressed...and this should be retested with the backend after that feedback is addressed.

**Review by tdonohue — APPROVED** [review]
👍 This is working for me now, once I figured out how to configure it to just use PhantAuth  (https://www.phantauth.net/). See my review on the backend which also has the required PhantAuth configs: https://github.com/DSpace/DSpace/pull/8088#pullrequestreview-866432513

**Review by LucaGiamminonni — APPROVED** [review]
Hi @hardyoyo, I tried this feature using google as provider and was able to log into the system. So for me the changes are ok and can be merged. Thank you

**Comment by tdonohue** [comment]
Merging, as this is at +2. Thanks again @hardyoyo and @LucaGiamminonni !

**Pull request merged**
