### PR TITLE
Dedupe patch operations by op and path

### PR DESCRIPTION
**Pull request by wwelling**
## Description
It was discovered that when many modifications of the submission form are done within a section, the PATCH request to update the section processes unnecessary patches on the back end. i.e. Change name, then title, then date multiple times, then name and title again. Only the last changes per input are necessary for the patch and the preceding by op and path are unnecessary to process on the backend.

## Instructions for Reviewers

Determine the use case for providing the backend with all the UI form manipulations. If there is no valid use case, there is excessive processing done for each patch operation included that will nullify a previous patch.

List of changes in this PR:
- for each new patch operation dispatched, dedupe any existing patch operations that where stored previously

To test concern:
Open inspector tools in the browser and watch the network traffic. During submission form change inputs repeatedly as if you either have a typo or inputted value in incorrect field or selected month and day of the date picker or changed your mind on an input. Then click save or click away from the submission section. There will be a PATCH request in the network traffic. Open the request body of the PATCH and there will be patch operations that are not the last changes and will not affect the JSON entity after PATCH.

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
@wwelling I don't fully understand the issue this solves. Is it just an optimization or is there a bug? I am seeing values getting cleared when the autosave is triggered when moving between submission steps (#2781) though I don't know if it's related.

**Comment by wwelling** [comment]
@alanorth it is technically not a bug. It more like an optimization but rather just preventing inefficient spurious processing on the backend and additional request bytes.

**Comment by alanorth** [comment]
@wwelling thanks. This is +1 by testing from me.

I managed to reproduce this (with network tab of developer tools open):

1. Enter a title like "Title"
2. Click outside the text field, then enter it again and change the title to "Title2"
3. Click outside the text field, then enter it again and change the title to "Title3"
4. Click outside the text field, then enter it again and change the title to "Title4"
5. Move to another submission step to trigger the autosave

Inspect the request body of the PATCH and you see all four titles as separate `replace` operations:

```json
[
   {
      "op":"replace",
      "path":"/sections/traditionalpageone/dc.title/0",
      "value":{
         "value":"Title",
         "language":null,
         "authority":null,
         "display":"Title",
         "confidence":-1,
         "place":0,
         "otherInformation":null
      }
   },
   {
      "op":"replace",
      "path":"/sections/traditionalpageone/dc.title/0",
      "value":{
         "value":"Title2",
         "language":null,
         "authority":null,
         "display":"Title2",
         "confidence":-1,
         "place":0,
         "otherInformation":null
      }
   },
   {
      "op":"replace",
      "path":"/sections/traditionalpageone/dc.title/0",
      "value":{
         "value":"Title3",
         "language":null,
         "authority":null,
         "display":"Title3",
         "confidence":-1,
         "place":0,
         "otherInformation":null
      }
   },
   {
      "op":"replace",
      "path":"/sections/traditionalpageone/dc.title/0",
      "value":{
         "value":"Title4",
         "language":null,
         "authority":null,
         "display":"Title4",
         "confidence":-1,
         "place":0,
         "otherInformation":null
      }
   }
]
```

With this PR the PATCH after the test sequence is:

```json
[
   {
      "op":"replace",
      "path":"/sections/traditionalpageone/dc.title/0",
      "value":{
         "value":"Title4",
         "language":null,
         "authority":null,
         "display":"Title4",
         "confidence":-1,
         "place":0,
         "otherInformation":null
      }
   }
]
```

**Comment by wwelling** [comment]
@alanorth thanks for the testing.

**Review by alanorth — APPROVED** [review]

**Pull request merged**
