### PR TITLE
Add configuration option to disable inlined CSS in SSR HTML

### PR DESCRIPTION
**Pull request by ybnd**
## References
* #1954 
* #2042 

## Description
The `inlineCriticalCss` setting in Angular Universal can pose performance issues.

With this enabled (as it is by default since Angular 13), the server needs to determine which styles are "critical" to a given page. This can take up a good chunk of CPU time.
Turning it off would free up that time, at the expense of loading "smoothness" in the browser.

Previously I thought the decreased "smoothness" outweighed the performance impact, but especially when stacked with the "keepalive fix" the effect is pretty substantial after all.

I've also noticed that while the "flash of unstyled content" is pretty severe in Firefox, it's minimal in Chrome.
Leaving this PR as a draft for now until I can figure out how to mitigate this.

## Instructions for Reviewers
Compare this PR's branch with `preboot.inlineCriticalCss` on/off and see if you notice a significant difference in performance

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
@ybnd I've recently stumbled upon this as well and it seems to be a common observation that `inlineCriticalCss` isn't optimized for cases where there are many selectors:

- https://github.com/angular/angular/issues/42098
- https://github.com/angular/universal/issues/2106
- https://github.com/GoogleChromeLabs/critters/issues/78

After migrating to DSpace 7 recently I have seen very high load from the Node.js `main.js` processes and I have currently disabled `inlineCriticalCss` in production. The server is much more stable now, though we also had incredible load coming from bots so it's hard to tell how much was due to this change versus applying strict rate limiting to Amazon, etc network blocks in the nginx reverse proxy.

**Comment by tdonohue** [comment]
@ybnd and @artlowel : Per today's DevMtg discussion about improvements to SSR performance, it'd be good to revisit this PR and/or officially mark it "ready for review".  It sounds like at least one institution (@alanorth 's) has found this useful/beneficial.  So, as long as any side effects are minimal, it seems worth considering adding this to 8.0 and (likely also) 7.6.x.

**Comment by ybnd** [comment]
Resolved some minor merge conflicts (due to the lint PR).

> I've also noticed that while the "flash of unstyled content" is pretty severe in Firefox, it's minimal in Chrome.

Looking back at it now, it doesn't seem that much of a problem honestly. Not sure what changed, but it looks pretty ok now.

**Comment by misilot** [comment]
Even without this change we were seeing flashing of content

**Comment by alanorth** [comment]
> Even without this change we were seeing flashing of content

Yes, us too. I use Firefox as my main browser as well.

**Comment by pnbecker** [comment]
We started to use this in production as well and it is very helpful. This must be included in DSpace 8.0 please.

**Review by pnbecker — APPROVED** [review]

**Comment by mwoodiupui** [comment]
Should this not be added to `config/config.example.yml` as well?

**Comment by pnbecker** [comment]
@mwoodiupui if I see it correctly, this must be est in environment.ts at compile time.

**Comment by mwoodiupui** [comment]
Then would someone please point me to the place in the code that prevents overriding this at startup, server-side.

**Comment by ybnd** [comment]
@pnbecker @mwoodiupui this should work fine from the YAML config, so probably best to include it in `config/config.example.yml` indeed

**Comment by ybnd** [comment]
@tdonohue @pnbecker @alanorth should we flip the default setting to `false`, since the overall feedback above?

**Comment by tdonohue** [comment]
@ybnd : based on feedback, if setting this to `false` works better then I'd recommend we make that the default value.   That said, we won't merge this until the upgrade to Angular 16 is completed (see #2871 )...so, there's still time for others to test this out as necessary.

**Comment by tdonohue** [comment]
@ybnd : If you are able to quickly update this, I'd **love to get this merged by tomorrow** (Friday, April 5).  That will let me deploy this on our sandbox.dspace.org site **during Testathon** which starts next week.  Thanks!

**Comment by ybnd** [comment]
@tdonohue ready.

**Review by tdonohue — APPROVED** [review]

**Pull request merged**
