### PR TITLE
add Hungarian translation file

### PR DESCRIPTION
**Pull request by akoscomp**
Create file for Hungarian translation

### CODE REVIEW

**Comment by bram-atmire** [comment]
Hi @akoscomp !!!

Thank you for your first contribution to DSpace!
I noticed that right now, only a few keys have been translated. By when do you think you can complete this?

One hint, and I did this for you to illustrate: each time you put in a translation, please manually remove the "TODO New Key - Add a translation" statement. this way, by counting the TODO's, it's easy to track how much work remains in the translation.

Also feel free to join us on #translation in the DSpace Slack channel:
https://wiki.lyrasis.org/display/DSPACE/Slack

If you give share your email address, I can send you an invite!

with kindest regards,

Bram

**Comment by akoscomp** [comment]
I sent the files for translation to an organization who use DSpace but I don't know, when they send me back the full translation.

**Comment by bram-atmire** [comment]
Hi @akoscomp 

the location of the catalogs has changed from /resources/i18n to /src/assets/i18n. Could you update or close your pull request & start a new one, to propose changes in this new location?

thank you !!!

Bram

**Comment by bram-atmire** [comment]
Closing this pull request because a newer PR with Hungarian message keys from the same contributors has been merged in #705

**Pull request closed without merging**
