### PR TITLE
Ask current password to user when setting a new password

### LINKED ISSUE #1737: Ask current password to user when he / she sets a new password
This is the counterpart of the REST ticket https://github.com/DSpace/DSpace/issues/8255

### PR DESCRIPTION
**Pull request by atarix83**
## References
* Fixes #1737
* Requires DSpace/DSpace#8477

## Description
Added changes to pass current password as challenge value to BE to update password.

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

List of changes in this PR:
- Added DynamicInputModel for current-password field to profile-page-security-form, if its profile security form.(profile-page-security-form.component.ts)
- Added @Output param to profile-page-security-form to emit current-password value to parent component.(profile-page-security-form.component.ts)
- Receive current password to profile-page which set in profile-page-security-form.(profile-page.component.ts)
- changed operation signature to call /password endpoint of BE with challenge value.(profile-page.component.ts)
- Added translation strings with key (en.json5)
- Added test case to handle currentPasswordValue emit.
- Added test case to handle when password is filled in, and is valid but return 403

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes.

Note: To test this feature use webui.user.assumelogin = true property in dspace/config/local.cfg file of Back End.

1. Go to Profile page, current password field should exist.

2. Type current password, enter new password and retype new password. Then try to save. 3. send the current password correctly.

4. send current password wrong:

5. send no current password:

6. create a new user from the sidebar menu.

7. Once created try to impersonate him.

8. In the profile section the “Security box should not be available anymore.
 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by mwoodiupui** [comment]
I am surprised that we are not using the method of emailing a link to a confirmation page, which DSpace has had for years.  The `change_password` email body is still present in `config/emails/` and code to use it is still in `org.dspace.eperson.AccountServiceImpl`.  I would consider that *at least* as secure as requiring the old password, and it also works in the case of having *forgotten* the old password.

**Comment by tdonohue** [comment]
Noted in today's meeting to verify that an Admin can still add/reset another user's password

**Review by tdonohue — CHANGES_REQUESTED** [review]
@atarix83 : Overall, the basics of this PR work.  I also tested the new user registration page (which allows you to set an initial password) and it works fine.

However, I've found a few issues in my testing today...
1. The "Forgot Password" page no longer works (always throws a 422 error)
    * From the UI, Click on "Have you forgotten your password?"
    * Reset the password -- sends you an email
    * In the email, click the link to go to the "Forgot Password" page.
    * Enter in a new password.  Result will always be a 422 error.
2. When attempting to change your password, if you enter an invalid "Current password", the error message displayed is confusing.  It says "The provided challenge is invalid".  This message makes no sense in the User Interface because there's no field called "challenge".  Maybe the UI needs to catch the error and change the message to something that makes more sense (e.g. "The provided current password is invalid")
provided-challenge
3. If I login as an Admin & Impersonate a user, then I still see the "Security" box under that user's Profile page.  According to the description of this PR, that box should no longer be available when impersonating a user.

Per @mwoodiupui 's points above, I've verified that the `change_password` email is still used even with this PR in place. That email is triggered when a user clicks on "Have you forgotten your password?", so it's name is confusing (it probably should be named `reset_password`).  I've also verified that it's still possible for an Administrator to reset a different person's password (this also triggers the `change_password` email to be sent).

Overall, I think this feature looks good and works decently well.  I haven't finished reviewing the code though on the frontend or backend.

**Comment by mwoodiupui** [comment]
I'm going to be very picky here and point out that "challenge" is not just the wrong word; it's the wrong concept.  The challenge is "current password:".  The user has provided an invalid *response*.  But that is a security term of art, and probably unclear to a lot of users.  The least jargonic expression of the failure would be something like "that is not your current password."

While I'm picking nits:  "Password:" would be unambiguous if it were "New password:" and "Retype to confirm:" would be unambiguous if it were "Retype new password to confirm:".

**Comment by atarix83** [comment]
@tdonohue 

your feedback should be addressed. Please mind for the third point you should update also the REST branch to properly check it

**Review by tdonohue — CHANGES_REQUESTED** [review]
@atarix83 : I retested this today, and it no longer works.

The issue appears to be that, on the backend (https://github.com/DSpace/DSpace/pull/8477), the `challenge` field has been renamed to `current_password` (on my and @mwoodiupui 's request).  This PR still is trying to use `challenge`, which causes it to fail.  Once you update that, I *suspect* this should succeed now.

**Comment by atarix83** [comment]
@tdonohue 

fixed

**Review by tdonohue — APPROVED** [review]
👍 Thanks @atarix83 and @nikunj59  !  This is working perfectly now, and the code looks good.

Today, I manually tested all the following scenarios:
* Register a new user & click on registration email & set their password.  WORKS
* Change the new user's password from their profile page.
    * Entering invalid current password, which correctly shows an error. WORKS
    * Entering a valid current password, which changes password. WORKS
* Clicking "Forgot password" & click on link in email & change their password. WORKS
* Login as an Admin, and Impersonate another user. Verified I cannot change that impersonated user's password from the Profile page. WORKS
* Login as an Admin & Edit an EPerson & click "Reset Password".  Verified that Admin *can* send a forgot password email to a different EPerson. WORKS

So, I think this is working correctly and it hasn't accidentally introduced any new errors in the existing processes for "forgot password" or "register new user".

**Comment by atarix83** [comment]
@tdonohue  merge conflicts resolved

**Comment by tdonohue** [comment]
Merging with 1 approval.

**Pull request merged**
