### PR TITLE
add import of missing Angular interfaces (squashed version)

### PR DESCRIPTION
**Pull request by saschaszott**
## Description

This PR is a replacement of https://github.com/DSpace/dspace-angular/pull/2870 where all commits were squashed into one commit as suggested by @alanorth .

It is synced with the latest changes in `main` branch.

### CODE REVIEW

**Comment by saschaszott** [comment]
Should I open an issue for the adoption of an additional lint rule as suggested by @ybnd in https://github.com/DSpace/dspace-angular/pull/2870#issuecomment-2009750013 ?

**Comment by saschaszott** [comment]
One test is failing, but it is not related to the proposed changes:

```
1) Edit Item > Edit Metadata tab
       should pass accessibility tests:
     AssertionError: 1 accessibility violation was detected: expected 1 to equal 0
      at Context.eval (webpack://dspace-angular/./node_modules/cypress-axe/dist/index.js:100:0)
```

**Comment by tdonohue** [comment]
@saschaszott : We've had random failures from that "Edit Item" e2e test.  It's not specific to this PR.  I've restarted the tests, as usually it passes after rerunning the tests.

**Comment by saschaszott** [comment]
> I'm curious what the issue is here, though? If these interfaces were missing and everything was already working, what problem is this solving? 😄

https://www.reddit.com/r/Angular2/comments/ge3evp/comment/fpmzpah/

**Comment by ybnd** [comment]
@alanorth everything will still work if we don't implement those interfaces, but this way the intent is a lot more clear and it can serve as a sort of spell-check too

https://v17.angular.io/guide/styleguide#implement-lifecycle-hook-interfaces

**Comment by saschaszott** [comment]
@alanorth , to enforce the import of Angular lifecycle interfaces a lint rule should be added as suggested by @ybnd in https://github.com/DSpace/dspace-angular/pull/2870#issuecomment-2009750013

**Comment by alanorth** [comment]
Awesome, thanks for the explanations.

**Review by ybnd — CHANGES_REQUESTED** [review]
The changes that you've made so far are all good, but it looks that there's a few more files that should be updated.

Can you add `"@angular-eslint/use-lifecycle-interface": "error"` to `.eslintrc.json` and run `yarn lint --fix`?

This should fix the remaining problems and cover any upcoming ones as well.

**Comment by saschaszott** [comment]
@ybnd , @tdonohue : `yarn lint` is now reporting 21 new problems due to missing imports of Angular lifecycle interfaces. I will create **one** new commit that fixes these problems.

**Comment by saschaszott** [comment]
@ybnd , this PR is ready for review.

**Review by ybnd — APPROVED** [review]

**Comment by tdonohue** [comment]
Merging with one approval.  Looks good to me too.  Thanks again @saschaszott !

**Pull request merged**
