### PR TITLE
Use the DSONameService to display DSpaceObjects names

### LINKED ISSUE #343: Communities created without a title cannot be accessed
Currently the REST API demo has two communities with no name/title: https://dspace7.4science.it/dspace-spring-rest/#https://dspace7.4science.it/dspace-spring-rest/api/core/communities

These communities are listed on the Angular UI homepage with a blank name.  Since the name provides the link to that Community, there's no way to visit that Community (to either edit it or delete it).

The Angular UI should handle unnamed Communities/Collections/Items/Bitstreams by replacing the empty text with a standard (translatable) word like "Unnamed".

### LINKED ISSUE #2153: Submitter: undefined undefined
**Describe the bug**
When there is not any submitter, an "undefined undefined" message appears.
image

**To Reproduce**
I am not pretty sure how to reproduce this error, but when i login as admin and i go to: 
https://demo7.dspace.org/mydspace?configuration=workflow

**Expected behavior**
The submitter should not appear if not exists or a message with "N/A". Maybe ussing the translation pipe

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #343
* Fixes #2153

## Description
Used the `DSONameService` on all the places where the name of a `DSpaceObject` is rendered

## Instructions for Reviewers

List of changes in this PR:
* I replaced all the places who used `dso.name` (found using the regex `\.name[^a-zA-Z0-9]` & by browsing the through the UI)
* Also fixed CSS of `ItemCollectionMapperComponent`
  * The title at the top needed some extra margin top
  * There was a lot of whitespace in the table (at first I thought it was an empty column)
     image
* Also fixed issue in `SearchFormComponent` where a page refresh after selecting a scope would set the text value of the button by default to "All of DSpace" instead of the name of the Community/Collection.

**Include guidance for how to test or review your PR.**
1. Edit the `DSONameService.getName()` & `DSONameService.getHitHighlights()` to return hardcoded easy to find strings like `__EPERSON__`
2. Browse through all the pages on the repo and check that all the names of the Collections, Communities, Items or (E)Persons are being displayed with `__{type}__`
3. Check that everything is still being displayed correctly without the `__{type}__` overrides and with some Collections, Communities, ... without a `dc.title`, `person.familyName`, `dc.lastname`, ...

## Checklist
- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  I've reviewed the code and it looks good. It's basically the same change over and over.  I've also tested as many of the components as I could from the UI and noticed no change in behavior.  I've verified #343 is fixed.  

This all looks good to me & I think it can be merged as soon as @mwoodiupui has a chance to give it a secondary test.

**Comment by alexandrevryghem** [comment]
Hey @tdonohue, I'm just curious but does this mean that you were not able to test the fix for #2153?

**Comment by tdonohue** [comment]
@alexandrevryghem : I'm not yet certain that this PR fixes #2153 to be honest... I *do believe* this PR improves the behavior because it properly handles a Submitter / EPerson which has no name.  

However, I believe #2153 is describing a slightly different issue where the submitter is *null* (i.e. doesn't exist at all). In that scenario, I don't believe this DSONameService fixes the problem, because the DSO itself is `null` / undefined.

While I haven't had a chance to fully verify things, I believe this PR provides a _partial fix_ to #2153 (for the scenario where the submitter exists but is missing a name).... and I think #2155 (also linked to #2153) may provide the rest of the fix (for the scenario where the submitter is null).  That said, I haven't had a chance yet to test #2155 along with this PR...and it appears that #2155 needs more work based on recent reviews.

**Comment by alexandrevryghem** [comment]
@tdonohue: You're right this solution only fixes the problem when the firstname and/or lastname of the submitter is not defined and it does not handle the case when the user is not defined. Because that PR currently also doesn't fix the issue when the submitter is `null` yet I created [this commit](https://github.com/alexandrevryghem/dspace-angular/commit/c45c648d7c240126121ddaec3f4e81f67a7c41e3) based on this branch. I created it because these 2 PRs will have a merge conflict and solving that merge conflict would basically result into a complete replacement from all the changes made in that PR with the usage of the `DSONameService` used in this PR. Because my solution also handles the cases where the name would correctly be displayed when only the firstname or only the lastname is used I think using this solution would be best. Maybe this PR can be merged first and then Cris could replace that PR with the changes I made in [this commit](https://github.com/alexandrevryghem/dspace-angular/commit/c45c648d7c240126121ddaec3f4e81f67a7c41e3) (or I could just add that commit to this PR)

**Comment by tdonohue** [comment]
@alexandrevryghem : If you want to simply push your new fix to this PR, I'm OK with that.  Currently, it appears the commit you linked it isn't in this PR (it's on a different branch).

Based on my reading of that new code, I think you are correct that it would make this PR a complete fix to #2153 (and the other PR could simply be closed).  I'm OK with that approach.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem .  I retested this today and verified it fixes both #343 and also #2153.  Here's a screenshot which proves submitter bug is now fixed... I have two WorkflowItems, one with an existing Submitter...and one where the submitter (EPerson object) is deleted.

submitter-test

So, I think this can be merged as soon as @mwoodiupui gives it a quick glance (even just a quick code review is fine).

**Comment by tdonohue** [comment]
@mwoodiupui : Would you have an chance to give this a quick test on your end so that we can merge this?  

One very quick way to test this is to create a Community and then remove it's `dc.title` (at the database level).  You can then just verify that it shows up as "Untitled" instead of as an empty entry like in the screenshot of the original ticket: https://github.com/DSpace/dspace-angular/issues/343#issuecomment-1447237425

**Review by mwoodiupui — APPROVED** [review]
Tested as @tdonohue suggests:  it works as advertised.  I have not read all of the code, but it looks sensible, builds and runs without error.

**Pull request merged**
