### PR TITLE
Convert i18n files to JSON5 format

### PR DESCRIPTION
**Pull request by artlowel**
This PR aims to make it easier to work with the i18n json files.

~It removes the nested keys. That way you can search for a key you encounter in a template and find it in the translation file~ 👉 this has been moved to its own PR: #457 

It also adds [json5](https://json5.org/) support. It allows us to have trailing commas or add comments to the translation files without issues.

### CODE REVIEW

**Comment by tdonohue** [comment]
@artlowel : I'm a bit curious about the idea to switch to JSON5.  While it's nice that it makes JSON easier to manage, I'm wondering if it could make the translation job a bit more difficult.  To clarify, I was hoping we'd still find a way (eventually) for translators to **not have to touch JSON** directly.  Ideally, it'd be nice if they had a specialized editor (like those you can find for gettext format, etc).  While I'm not sure there are such specialized editors for JSON, there do seem to be tools to transform gettext to JSON (e.g. po2json).

So, I guess I'm wondering out loud if moving to JSON5 makes it more difficult to use third-party specialized editors and/or tools to transform from common i18n formats (like gettext, etc)?

I think our overarching goal here should be to try to allow translators to work in tools that are comfortable to them.  So, if JSON5 is not well adopted/supported in other tools/editors, then those extra benefits over JSON may not actually be beneficial to those translators.

**Comment by artlowel** [comment]
@tdonohue I added json5 support because as I was flattening and sorting the i18n files, I was annoyed by the fact that in json the last line can't have a trailing comma. So to add a new message at the bottom, you need to modify the last line (add the comma) and add your new line. If this happens in multiple parallel branches it has a higher chance to lead to merge conflicts that need to be solved manually. 

A way to prevent this issue is to put the commas at the start of the line instead of the end, but that's up to the discipline of the devs and reviewers (although it's conceivable that jshint could check for it)

But I remembered reading [an ngx-translate issue where the main developer suggested adding json5 as an official format](https://github.com/ngx-translate/core/issues/339#issuecomment-264114586), and that it was very easy to do so already. Since json5 would also solve the issue of not being able to add commas, [which @cjuergen had noted as a problem](https://github.com/DSpace/dspace-angular/issues/306#issuecomment-428948764), I thought I'd add it.

This being said, I'm perfectly fine leaving it out just to ensure better compatibility with other tools.

**Comment by tdonohue** [comment]
@artlowel : Understood, and thanks for the summary of your thoughts here. 

I have to admit, I'm still torn here.  I can see how JSON5 makes our (developers) lives easier here, and it very well might help translators too (if they plan to touch JSON directly).  But, maybe this is also an opportunity to get more opinions before we move down the JSON5 route?  

@cjuergen, @pnbecker , @bram-atmire ... as you all have expressed interest in this topic, do you have opinions/thoughts on basic JSON vs JSON5?  For more context, this ticket now replaces #366 (migration to PO format), as we've [hit issues with the PO translation loader](https://github.com/DSpace/dspace-angular/pull/366#issuecomment-515093623).  Ideally I'd still like to find a way to move towards letting translators use PO or XLIFF (or some format that has nicer third-party editing tools), but we've not yet found a way to easily achieve that.

**Comment by cjuergen** [comment]
It will definitely make the direct translation of json files easier and the developers lives too.

So far I have not found an editor (could not check Babeledit, my trial expired, but tried Translation Manager, Po-Editor), which supports json5. But this may just be a question of time.

I have one question though,  does json5 work with [ngx-translate-messageformat-compiler](https://www.npmjs.com/package/ngx-translate-messageformat-compiler)? This would help us a lot with pluralization and gender.

**Comment by artlowel** [comment]
@cjuergen I gave it a quick test, and indeed ngx-translate-messageformat-compiler works with json5 as well. I think the reason is that it sits after the loader, so the source format doesn't matter anymore at that point, it has already been converted to a JS object.

**Comment by artlowel** [comment]
@tdonohue to make things simpler I created a separate PR with just the commit that flattens the file: #457 .  Since there's no discussion about that point, we can merge that, and make this PR just about json5

**Comment by bram-atmire** [comment]
The ability to provide comments is a key ability that would enable us to convert from translator friendly formats like .PO into the JSON5 format.

It's indeed true that tools don't support JSON5 translation directly, but at the same time, we couldn't find a solution that has full support for all the capabilities of native .po.

So I'm personally also definitely ok settling for a solution where json5 is the format, in the code. And that we build a suite of assistive convertors around this, to help translators, if they don't want to work with the json5 files directly.

**Comment by bram-atmire** [comment]
@helix84 could you also add your 2cents here?

**Comment by helix84** [comment]
Thank you for the improvement. While I'm not happy that the format is something easier for the developers than for the translators to work with, I'm still hopeful will help us integrate with some tool that will make it effortless for the translator to work with, perhaps Pootle, Transifex or Weblate.

**Pull request merged**
