### PR TITLE
Added bootstrap with ng-bootstrap: this connects to #4

### PR DESCRIPTION
**Pull request by wwelling**
1. Added bootstrap and ng-bootstrap as dependencies
2. Setup app level main.scss that includes custom variables.scss, bootstrap.scss, and font-awesome.scss
3. Setup a collapsable navbar with AppComponent

With sass currently not being compatible with AoT we must compile scss files before the build. Also, we would like to combine global level styling as well as component level styling. A main.scss compiled to main.css and brought in from index.html head tag will provide for global styling. All the other scss files are component level. With the custom variables.scss file overriding styles for custom look and feel should be relatively easy.

If you would like to have a component's styling inherited by child components, change the encapsulation from ViewEncapsulated.Emulated to ViewEncapsulated.None. FYI, ViewEncapsulated.Emulated is default.

There does not seem to be a way to style the body tag from within the Angular app.

### CODE REVIEW

**Comment by wwelling** [comment]
I will resolve the merge conflicts with this pull request this morning. I would also like to update a few things. Such as add an logo image that is customizable in the main.scss. Also, webpack needs some tweaks as with some unused dependencies should be removed. And last, css files should be ignored.

This will probably need multiple reviewers and discussion.

**Comment by artlowel** [comment]
- [Mirage 2 contains an SVG version of the dspace logo](https://github.com/DSpace/DSpace/blob/master/dspace-xmlui-mirage2/src/main/webapp/images/DSpace-logo.svg), albeit not in the exact same configuration. But I'd prefer to use a scalable version rather than a png. @tdonohue do you know if there is a scalable version of [the logo William used](https://github.com/wwelling/dspace-angular/blob/657d5c35f389a26b3f3b25ca68b39cc409cd7d25/resources/images/dspace_logo.png) out there?
- ngc is the tool with the problem with sass right? Does that mean we can't use webpack to build the style? I'd like to include [postcss](https://github.com/postcss/postcss) with [autoprefixer](https://github.com/postcss/autoprefixer). That'd be easy to do with [a webpack loader](https://github.com/postcss/postcss-loader)...

**Comment by wwelling** [comment]
Pros: 
1. has bootstrap globally
2. supports global custom scss
3. supports component level scss

Cons
1. *requires sass compilation before build
2. **sass variables are not automatically interpreted in component scss
3. ng-bootstap does not seem to have animations yet

* AoT is not compatible yet with a scss or sass loaders. It will only work with precompiled css.

** in order to use variables within component level scss you must import the variables.scss

Art, I agree we do need a scalable logo. That is what I found with a quick search. And yes ngc is the tool that does not like the sass, yet. It pretty much compiles and encapsulates all code into manageable parts to hands it off to the client. This provides quicker page load and less data transfer to the client. The client no longer needs the full compiler. I imagine this AoT compile phase does not support sass or scss loaders yet. I have not found anywhere online of a use with autoprefixer and I could not get it to work.

**Comment by tdonohue** [comment]
@artlowel : We have DSpace logos of various sizes up at https://wiki.duraspace.org/display/DSP/Logos and http://www.dspace.org/marcom .  I'm not seeing any official SVG ones, but there are TIFFs which could be used to create an SVG.  I'm not sure who created that Mirage2 logo, it's possible it was created via one of the TIFFs.

**Comment by artlowel** [comment]
Thanks Tim. It is entirely possible that I created the SVG logo in Mirage 2 by tracing the official one in illustrator.

>**in order to use variables within component level scss you must import the variables.scss

I don't really see that as a 'con'. It makes it easier to grasp where variables used in a component style are coming from if all dependencies need to be explicitly imported.

Am I supposed to run `npm run sass` followed by `npm run build:prod:ngc`? Because that fails during the final `npm run build:prod` part (which runs `webpack --config webpack.prod.config.ts`). 
ngc replaces the generated `app.component.css` with `app.component.shim.ts` but the webpack prod build still searches for the css file.

PostCSS works on plain css, not scss, and I see it can also be used from the command-line, so this way of working doesn't prevent us from using it. It would need to be executed after node-sass but before ngc. I'll look into that after this PR gets merged.

**Comment by wwelling** [comment]
I seem to have forgot to setup for production. Let me update and commit. Give me 30-35 minutes please.

**Comment by wwelling** [comment]
1. Updated npm scripts, details below.
2. Added concurrently for cross platform watch capabilities.

```npm start``` - builds and starts production
```npm run start:dev``` - builds and starts development

```npm run watch:prod``` - *builds and watches production
```npm run watch:dev``` - builds and watches development

```npm run clean``` - cleans everything including node_modules
```npm run clean:prod``` - cleans production generated files
```npm run clean:dist``` - cleans distribution directory

I made ```npm start``` the production script by default as it normally would be.
Use ```npm run start:dev``` or ```npm run watch:dev``` for development.

**Comment by wwelling** [comment]
I am having some trouble with all scripts working correctly. Please give me a bit. Thanks.

**Comment by wwelling** [comment]
I found the problem I was having. Universal starter project uses an advanced compression technique for production. It saves very little. I think it was like 1-2% more efficient than the compression package. But it breaks things such as bringing in custom fonts. I will have a commit in a few.

**Comment by wwelling** [comment]
Ok, this is ready to go. Build, start, watch, and clean are working for both development and production. The npm scripts above will get us started. I am not apposed to tweaking this to better serve our purpose.

**Comment by artlowel** [comment]
LGTM

**Comment by wwelling** [comment]
I am good with it. @artlowel when you are comfortable with the level of review, we should proceed with merge. Any concerns can be addressed in future requests. I was hoping others would of reviewed by now.

**Pull request merged**
