### PR TITLE
rename +dir to dir

### PR DESCRIPTION
**Pull request by vitorsilverio**
Solve this #327

### CODE REVIEW

**Comment by tdonohue** [comment]
Thanks @vitorsilverio , I like this direction. But, the DSpace 7 team may need to talk about when best to apply this change (as this PR has a high probability of creating a lot of merge conflicts with other currently open PRs).

@artlowel : adding you as a reviewer to this.

**Comment by vitorsilverio** [comment]
@tdonohue if you prefer i can close this one and open small PRs for each dir for easy conflict management

**Comment by tdonohue** [comment]
@vitorsilverio : I'd like to look for advice from @artlowel on this.  Doing this directory by directory would definitely cause less conflicts (but it'd be more PRs to manage).  

So, I'd like advice from @artlowel on whether we can quickly fix this "all at once" in the near future, or if we may want to split this up.  (I think the answer depends on upcoming work from Art's team)

**Comment by artlowel** [comment]
I think doing it quickly all at once is the way to go, but right now is indeed not ideal. Due to the big PRs that are open at the moment, and all the work that we'd still like to finish before the end of the year, I think we're better off doing it in Januari.

**Comment by tdonohue** [comment]
Closing, as this was (finally) just fixed by #1278

**Pull request closed without merging**
