### PR TITLE
Made it possible to reorder the login methods

### LINKED ISSUE #2365: Log in popup should respect order of enabled login methods in the back end
**Describe the bug**
In back-end config, it is possible to change the order of login methods.
As a result, it is expected that the login popup on the homepage would respect the configured order.

Screenshot 2023-07-12 at 14 40 36

There are two issues at present:

1. Password login, when configured as active, is hard coded to always go first
2. The links at the bottom to reset your password or to register a new account, only apply to the password authentication method. They should be grouped together with the password login option to make it clear to the user that these have nothing to do with the other authentication methods.

**To Reproduce**
1. Change the order of login options in back end config
2. Look at the rendering of the login pop up. The rendering is garbled.

**Expected behavior**
The login methods should appear in the order that they have been enabled. Any related links or other info about a login method, should be grouped together.

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #2365
* Maintenance PR #2488

## Description
Made it possible to reorder the login methods based on the order provided in the config
image

## Instructions for Reviewers
List of changes in this PR:
* Save the display position in the `AuthMethod`
* Moved the user registration & password reset link to the `LogInPasswordComponent`
* Refactored the way `authMethods` are retrieved, now the subscription is automatically taken care of by the `async` pipe

**Guidance for how to test/review this PR:**
- Set the following config in the backend:
   ```cfg
   plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.OrcidAuthentication, org.dspace.authenticate.ShibAuthentication, org.dspace.authenticate.PasswordAuthentication, org.dspace.authenticate.OidcAuthentication
   ```
- Check that the authentication methods are displayed in the correct order

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@alexandrevryghem : I can verify that this code works & looks good overall.

However, I'm hitting a few bugs in my testing which are caused by this PR.

1. When testing with this PR in production mode (`yarn install;  yarn build:prod; yarn serve:ssr`), I'm seeing this error appear during SSR. This occurs every time I reload the homepage (/home).
```
GET /home 200 1670.319 ms - -
ERROR TypeError: Cannot read properties of undefined (reading 'trim')
    at LogInComponent_div_3_ng_container_1_Template (C:\dspace-angular\dist\server\main.js:1:1827496)
    at executeTemplate (C:\dspace-angular\dist\server\main.js:1:5495958)
    at refreshView (C:\dspace-angular\dist\server\main.js:1:5494195)
    at refreshEmbeddedViews (C:\dspace-angular\dist\server\main.js:1:5511109)
    at refreshView (C:\dspace-angular\dist\server\main.js:1:5494637)
    at refreshEmbeddedViews (C:\dspace-angular\dist\server\main.js:1:5511109)
    at refreshView (C:\dspace-angular\dist\server\main.js:1:5494637)
    at refreshComponent (C:\dspace-angular\dist\server\main.js:1:5511881)
    at refreshChildComponents (C:\dspace-angular\dist\server\main.js:1:5491057)
    at refreshView (C:\dspace-angular\dist\server\main.js:1:5495107)
```
2. At the same time, the initial SSR content flashes briefly in my browser & shows the search icon in the header along the left side of the page.  This is quickly replaced by CSR, but it's a bug specific to this PR (and it might be caused by the error above, not sure).  Here's a brief video that shows the behavior as I click reload in my browser window (watch the left side of the screen).
strange-reload


Beyond those issues, I can verify this works overall.  The login menu is now appearing in the same order as the `plugin.sequence.org.dspace.authenticate.AuthenticationMethod` configurations on my backend.

**Comment by alexandrevryghem** [comment]
@tdonohue: Thanks for the feedback. I was able to successfully replicate this error message in a production environment. I just added a check to ensure that the `contentRef.innerText` was always defined, and this fixed the error message and the header content displacement issue.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  This is now working as expected and I'm no longer seeing any of the prior errors.  Looks good!

**Comment by tdonohue** [comment]
Fixed on `dspace-7_x` in #2488

**Pull request merged**
