### PR TITLE
[Port dspace-7_x] Fixed creation & deletion of relationships not working correctly & added same entity type relationship support

### LINKED ISSUE #1511: Relationships between same entity types are not supported
**Describe the bug**

DSpace angular is currently missing support for relationships between the same type. 
Example: Linked publications, or parent and child projects. 

In the edit item -> relationships tab, you will only get one of those relationships and won't be able to add more items. 

**To Reproduce**
1. Set up a stock Dspace 7.2 to serve as the backend
2. Configure a relationship that uses the same entity type on both ends. 
```    <type>
        <leftType>Publication</leftType>
        <rightType>Publication</rightType>
        <leftwardType>isPublicationLinkedTo</leftwardType>
        <rightwardType>isPublicationLinkingTo</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToRight>true</copyToRight>
    </type>
```
3. Go to the front end and ensure a couple of publications are present in the repository. 
4. Go to the edit Item page of one of the publications and to the relationships tab
5. Look through the present relationships 
6. Verify that there is a relationship present without a header, but just an add button
7. Verify that clicking that add button opens an empty modal instead of the normal lookup window

**Expected behavior**
1. The publication to publication relationship should be shown with proper title for both sides of the relationship. 
2. Users should be able to add new relationships through the add buttons
3. The added relationships should be displayed under the correct side of the relationship (isPublicationLinkedTo vs isPublicationLinkingTo)

### LINKED ISSUE #2978: Cannot add new relationships between Entities
**Describe the bug**
When adding a new relationship between entities, it's not possible to save the results.  The page hangs and the new relationship is never saved.

**To Reproduce**
1. Edit a publication, going to the "Relationships" tab
2. Click "+Add" next to Authors and attempt to add a new Author
3. Select a local author who is already in the system.
4. Click "Save".
5. Behind the popup, you'll see the author has appeared.  But the popup never closes.  It hangs.
6. Click away from the popup and it will finally close.  It looks like the Author may be added.
7. Now reload the page in your browser. The new Author disappears. It was not added.

NOTE: If you try the same process but attempt to import a new Author from an external source, the **imported Person Entity** will be created. **However, it will not be linked to your Publication.**

**Expected behavior**
Obviously this should work like in 7.x.

### LINKED ISSUE #2998: When deleting an author to publication relation, the author is completely remove from the item.
**Describe the bug**
When removing a author from a publication using the Relation tab of the item, the relation is removed but also the author metadata. 

**To Reproduce**
1. Select a publication item with Person item associated to it (ex from the Sandbox: https://sandbox.dspace.org/entities/publication/ad15c7fa-2da6-42f0-87d5-0e5c396c0644)
3. Got ot the Relation Tab, delete the Author
4. In the "_Select the items for which you want to save the virtual metadata as real metadata_" window check the publication entity and Save
5. Person is removed from the Relation tab, but the name also disappears from the metadata.

**Expected behavior**
The auther name remain as a real metadata in the publication item.

**Related work**
May be related to the entity addition problem : https://github.com/DSpace/dspace-angular/issues/2978

### PR DESCRIPTION
**Pull request by alexandrevryghem**
Port of #3060 to `dspace-7_x`.

### CODE REVIEW

**Comment by paulo-graca** [comment]
Does this PR also fixes - https://github.com/DSpace/dspace-angular/issues/1387 ?

**Comment by alexandrevryghem** [comment]
@paulo-graca: No this doesn't fix that issue

**Comment by tdonohue** [comment]
I've verified the changes in this PR look the same as the `main` version in #3060.  So, generally, I'm +1.  But, I want to find time to briefly test this on the `dspace-7_x` branch (to ensure no differences of behavior since 7.x and `main` are quite different now).

**Comment by tdonohue** [comment]
@alexandrevryghem : This port needs to be updated to revert the last few changes.  This PR seems like it may be out of sync with the `main` version in #3060 (if I'm not mistaken)

**Comment by alexandrevryghem** [comment]
@tdonohue: I synced both branches so now they contain the same fixes

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  I gave this a quick test with the demo.dspace.org site as the backend.  Appears to work the same as #3060 , so it looks like an accurate backport.

**Pull request merged**
