### PR TITLE
Fixed creation & deletion of relationships not working correctly & added same entity type relationship support

### LINKED ISSUE #1511: Relationships between same entity types are not supported
**Describe the bug**

DSpace angular is currently missing support for relationships between the same type. 
Example: Linked publications, or parent and child projects. 

In the edit item -> relationships tab, you will only get one of those relationships and won't be able to add more items. 

**To Reproduce**
1. Set up a stock Dspace 7.2 to serve as the backend
2. Configure a relationship that uses the same entity type on both ends. 
```    <type>
        <leftType>Publication</leftType>
        <rightType>Publication</rightType>
        <leftwardType>isPublicationLinkedTo</leftwardType>
        <rightwardType>isPublicationLinkingTo</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToRight>true</copyToRight>
    </type>
```
3. Go to the front end and ensure a couple of publications are present in the repository. 
4. Go to the edit Item page of one of the publications and to the relationships tab
5. Look through the present relationships 
6. Verify that there is a relationship present without a header, but just an add button
7. Verify that clicking that add button opens an empty modal instead of the normal lookup window

**Expected behavior**
1. The publication to publication relationship should be shown with proper title for both sides of the relationship. 
2. Users should be able to add new relationships through the add buttons
3. The added relationships should be displayed under the correct side of the relationship (isPublicationLinkedTo vs isPublicationLinkingTo)

### LINKED ISSUE #2978: Cannot add new relationships between Entities
**Describe the bug**
When adding a new relationship between entities, it's not possible to save the results.  The page hangs and the new relationship is never saved.

**To Reproduce**
1. Edit a publication, going to the "Relationships" tab
2. Click "+Add" next to Authors and attempt to add a new Author
3. Select a local author who is already in the system.
4. Click "Save".
5. Behind the popup, you'll see the author has appeared.  But the popup never closes.  It hangs.
6. Click away from the popup and it will finally close.  It looks like the Author may be added.
7. Now reload the page in your browser. The new Author disappears. It was not added.

NOTE: If you try the same process but attempt to import a new Author from an external source, the **imported Person Entity** will be created. **However, it will not be linked to your Publication.**

**Expected behavior**
Obviously this should work like in 7.x.

### LINKED ISSUE #2998: When deleting an author to publication relation, the author is completely remove from the item.
**Describe the bug**
When removing a author from a publication using the Relation tab of the item, the relation is removed but also the author metadata. 

**To Reproduce**
1. Select a publication item with Person item associated to it (ex from the Sandbox: https://sandbox.dspace.org/entities/publication/ad15c7fa-2da6-42f0-87d5-0e5c396c0644)
3. Got ot the Relation Tab, delete the Author
4. In the "_Select the items for which you want to save the virtual metadata as real metadata_" window check the publication entity and Save
5. Person is removed from the Relation tab, but the name also disappears from the metadata.

**Expected behavior**
The auther name remain as a real metadata in the publication item.

**Related work**
May be related to the entity addition problem : https://github.com/DSpace/dspace-angular/issues/2978

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #2978
* Fixes #1511
* Fixes #2998
* PR for 7.x: #3059

## Description
This component fixes various bugs related to the `Edit Item > Relationships` tab. This PR fixes the bugs preventing  relationships to be created, adds support for adding relationships between the same type of entities and it also fixes the bug where removing a relationship while explicitly saying that you want to keep the virtual metadata as plaintext metadata fields.

## Instructions for Reviewers
List of changes in this PR:
* Moved all the logic to create the relationships and display the success/ error notifications to `EditItemRelationshipsService`
* Fixed multiple bugs in `EditRelationshipListComponent` that prevented the `submitModal` to emit (which caused the modal never to close after clicking save)
* Added support for same entity type relationships
* Refactored the way relationships are added/removed by doing them sequentially one at a time in order to ensure that all relationships operations were executed before closing the modal

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alexandrevryghem** [comment]
These changes fix a bug where the selected status in the popup modal would stay cached even after adding and then removing a relationship without refreshing the page. And also fix a very small bug where the incorrect `nameVariant` was retrieved when creating the delete relationship object in the store. This issue was never seen before because type `any` was used.

**Comment by tdonohue** [comment]
@alexandrevryghem : I'm retesting this today, and adding/removing relationships is now very buggy again. 

Here's what I'm doing:
* Find/create a Publication with no relationships
* Edit it, go to the Relationships Tab
* Add 3 (local) Persons as authors. Click Save 
* Back on the Relationships Tab, I now see *6* persons linked.  Each Person appears to be listed twice?  Some are highlighted in green (meaning they are not yet saved) but some are saved immediately (and I have an immediate option to delete).

This seemed to all work well before your last two changes.  If necessary, I can retest tomorrow the older version of the code, to see if that's still working for me.

**Comment by alexandrevryghem** [comment]
@tdonohue: I removed the commit that caused this issue. But that commit fixed the bug where the selected status of items in the popup modal were cached & also an issue where the save button wouldn't be disabled when it should be. If you want we can already merge this PR as is, and I can open an additional PR later to fix this (but that will probably only be next week).

To reproduce the issue where the disabled button is still shown:
- Add an item as a relationship
- Remove the relationship
- The save button will still be clickable

**Comment by tdonohue** [comment]
Thanks @alexandrevryghem .  I think rolling back that change makes sense for now.  It can be treated as a separate bug, as it seems less significant then the bugs this PR fixes.  That said, please do send an additional PR if you find a way to solve that separate bug...as I'd definitely like to find a way to solve it in 8.0 if possible.

I'll retest this later today and verify it's still working for me.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  I can verify this is working again with your recent changes removed.

As for the new bug you are seeing, I'm not sure that I can reproduce it.  But, perhaps I'm not understanding the steps involved.  Here's what I tried:
* Go to a Publication with no Relationships.  Edit it and go to "Relationships" tab
* Add 3 Person relationships.  After saving in the popup window, all three appear on the Relationships tab & an green success notice appears.
* Now, on Relationships tab, click delete (trash icon) next to any of the new Person relationships.  The Save button enables (as it should).  Clicking "Save" will confirm the deletion.  The page reloads and the relationship is removed.

In my opinion this is ready to be merged as-is.  Any additional bugs can be addressed separately.

**Comment by tdonohue** [comment]
Merging immediately as this works well and fixes the major bugs.  Follow-up work is welcome in a separate PR.   @atarix83 : if you have feedback on this after OR2024, we can address that in follow-up work.

**Comment by jschultze** [comment]
@tdonohue I'm trying to get relationships between two items of the same entity to work, and found this fix. Just a quick question: does this fix only work for the "standard" entity types (Person, OrgUnit, ...) or should it also work custom entities? There some behaviour with custom types that still does not seem to work (display of selected items in the submission form and display of the related items in edit mode on both items, ...).

**Pull request merged**
