### PR TITLE
Collection home page

### PR DESCRIPTION
**Pull request by rivaldi8**
This PR connects to #63.

An example item can be viewed at [base-url]/collections/5179

### CODE REVIEW

**Comment by artlowel** [comment]
LGTM

**Comment by tdonohue** [comment]
@rivaldi8 : this now has minor conflicts.

However, I also tested this, and it looks good to me. It can be merged once the conflicts are resolved.

**Comment by rivaldi8** [comment]
@tdonohue I've fixed the conflicts.

**Comment by artlowel** [comment]
I found one more issue: if there's no logo, as in the mock collection with id 6547, an exception is thrown, and the page stops loading.

This can likely be solved by adding an `*ngIf="logoData"` to `<ds-collection-page-logo>` in collection-page.component.html

**Comment by rivaldi8** [comment]
Fixed as suggested.

**Comment by artlowel** [comment]
Can confirm that it works.
Merging

**Pull request merged**
