### PR TITLE
EPerson creation page changed

### LINKED ISSUE #2026: When creating a new EPerson "Reset password" button is not needed
**Describe the bug**
This isn't properly a bug, but a behavior that might confuse administrators when creating a new EPerson. 
Current EPerson form does not make distinctions between the creation of a new EPerson and the edit of an existing one. In particular the set of buttons is the same. 

**To Reproduce**
1. login as administrator
2. Go to "Access Control / People"
3. Click "Add Person"
4. The form will propose "Reset password" button

**Expected behavior**
In our opinion, it could be a good improvement if, when a new person is created: 
- "Reset password" button is not displayed
- Instead of "Save" the "Create" label is displayed on the button that creates the EPerson
- (Nice to have) when "Save / Create" button is clicked (only in case of new EPerson) the user registration mail is automatically sent

We, at 4Science, are interested in working on this improvement for which we roughly estimate from 1 to 2 days of work

### PR DESCRIPTION
**Pull request by amanbudgujar**
## References
* Fixes #2026 

## Description
While creating a new EPerson -
* Reset password button is not displayed.
* Submit button label changed from 'Save' to 'Create'.

### Steps to test
* Open page to add new eperson.
* Check that submit button label is changed from 'Save' to 'Create' and Reset Password button is not displayed.

List of changes in this PR:
* New variable added in `en.json5` file.
* _if_ statement added to display 'Reset Password' button in `eperson-form.component.html` file
*  if eperson is non-null (i.e edit eperson mode), submit button label set to 'Save' and Reset Password button to be displayed in `eperson-form.component.ts` file.
## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [ ] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@amanbudgujar : Just wanted to let you know this PR is failing a "lint" check cause of trailing spaces.  You can find the details of the error by running `yarn lint` locally.

**Comment by amanbudgujar** [comment]
@tdonohue 
Sorry about that.
I have pushed the updated code after testing it.
Please check if this can be reviewed now.

**Comment by amanbudgujar** [comment]
@tdonohue 
Any update on this.

**Comment by tdonohue** [comment]
@amanbudgujar : This PR is on our 7.6 board and is waiting on reviewers to be assigned.  As all reviewers are volunteers, we unfortunately cannot promise a timeline for when the review will occur. But, we can promise this fix will be reviewed in time for 7.6. Since it's a small PR though, hopefully we can find someone sooner rather than later (or maybe I'll find time to review it myself).

If you'd like to help our review process along, we accept PR feedback from anyone.  So, you are welcome to help by volunteering to review or simply test (if you don't feel comfortable with code reviews yet) the PRs of others.  That can help us keep our backlog smaller and allow us to get to your PRs more quickly as well.  Thanks and hopefully I or someone else will get back to this PR soon.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @amanbudgujar !  I finally got around to reviewing/testing this today.  It works well, and I like that the creation page now has a "Create" button instead of a "Save" button.

**Pull request merged**
