### PR TITLE
Fix support for adding and removing relationships in relationship-only fields in the submission

### LINKED ISSUE #1094: Most relation fields (except Author) do not display their relations in the Submission form.
## Describe the bug

The majority of relation fields (except the Author field on the Publication form) do not display their selected relations in the submission form.

Known Relation fields that work:
* The "Author" field on the Publication form (this is a repeatable field which allows free text entry)

Know Relation fields that **do not work:**
* The "Publication" field on the Person form (this is a non-repeatable field which doesn't allow free text entry)
* The "Journal" field on the Journal Volume form (this is a non-repeatable field which doesn't allow free text entry)
* The "Volume" field on the Journal Issue form (this is a non-repeatable field which doesn't allow free text entry)

Fields that do not work all exhibit the same behavior.  You can select a relation & it appears to be created. However, after closing the popup, the relation does not appear on the form.

While all the fields that do not work have the same configuration, changing their configuration (e.g. to repeatable or to allow free-text entry) doesn't seem to allow them to work.  They continue to behave in the same manner, regardless of configuration.

## To Reproduce

My testing environment:
* Using current `main` branch of `dspace-angular` (as of April 12, 2021)
* On the REST API backend, I'm using the [sample Entities data set](https://github.com/DSpace-Labs/AIP-Files/releases/tag/demo-entities-data)
* I'm using the latest version of `main` (again from April 12) including having https://github.com/DSpace/DSpace/pull/3224 applied/merged.
* I've enabled all the Entity related collection mappings: https://github.com/DSpace/DSpace/blob/main/dspace/config/item-submission.xml#L36-L49 (to more easily test various Entity submission forms)
* **UPDATE:** As of today, this same environment exists on https://api7.dspace.org  It has Entity-related Collection mappings uncommented & all of the above applied.

One example which **doesn't work** (Linking a new Issue to an existing Volume)
1. Start a new Submission in the "Journal Issues" collection. This will use the "Journal Issue" Entity form
2. The first field gives the ability to select a "Journal Volume" associated with this Issue. This is a non-repeatable field.
3. Click the lookup &  select from existing Journal Volumes. 
4. Selecting a Journal Volume will work, but the Volume name is not displayed after closing the popup.
5. If you open the popup again, the linked Volume will be shown. (Relationship was created)

Another example which **doesn't work** (Linking a new Person to an existing Publication)
1. Start a new Submission in the "People" collection. This will use the "Person" Entity form
2. The first field gives the ability to link the Person to a single Publication. This is a non-repeatable field.
3. Click the lookup & select a Publication
4. Selecting the Publication will work, but the Publication is not displayed after closing the popup.
5. If you open the popup again, the linked Publication will be shown. (Relationship was created)

An example which **works** (Linking a new Publication to an existing Person)
1. Now start a new Submission in the "Articles" collection. This will use the "Publication" Entity form.
2. This has an "Author" field as the first field. It's a repeatable field.
3. Using the Lookup button, select one or more existing Persons as authors
4. They immediately appear back in the Submission form. (Everything works!)

_I've also attempted changing fields from non-repeatable to repeatable (no effect on results) and other minor configuration changes. It's currently unclear to me why the Author field works while others do not._

## Further testing
Because of the discussion in #1092, I attempted to **rollback** `dspace-angular` to before #1025 was applied. **This had seemingly no effect on the results above.** I still cannot get relationships to work.

Here's how I rolled back my UI to before #1025:
```
# Checkout the commit before #1025
git checkout 3815bdbd8c1e458ea88d906459b823eaa33dbe25
# Reapply #1055 only, as this is needed to run a current REST API backend (as entity types are in a different metadata field now)
git cherry-pick -m 1 0f7a32d0dfcee30f0436ba0b762e87c812b8b48a
yarn clean
yarn install
yarn start:dev
```
Again, after those steps, I retested the above examples & got the same results. The Author field works while others do not.

## Expected behavior
All relation fields (regardless of backend configuration) should show display their selected value(s) in the Submission Form.  Obviously some are only allowed one value, while others can have multiple values (depending on the `repeatable` setting).

## Related work
Related to discussions in #1092 , but this bug seems **unrelated to repeatable fields in my opinion**.

### PR DESCRIPTION
**Pull request by artlowel**
## References
* Fixes #1094
* ~Depends on #1092~
* ~Requires DSpace/DSpace#3224~

## Description
This PR will auto update the item input in the submission form when the item changes. That way, when a relationship is added the form will update.

It will also fix an issue where the lookup button wasn't shown for repeatable relationship only fields, when they already had a value

## Instructions for Reviewers
You can test this PR by verifying that relationships can be added and removed regardless of whether they're for a mixed field.

~This PR seems bigger than it is, because it depends on #1092 You can see only the changes in this PR [here](https://github.com/atmire/dspace-angular/compare/4Science:CST-3782-final-adjustments...atmire:fix-1094)~

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by benbosman — APPROVED** [review]
I've tested this PR, and it seems to solve the remaining issues which were not yet handled in https://github.com/DSpace/dspace-angular/pull/1092

Using the PR, our standard test configs are functional again

**Review by tdonohue — CHANGES_REQUESTED** [review]
@artlowel : Overall this works & fixes #1094 for me as well.

That said, a few bugs I'm noticing:
1. The field "hint" appears seems to be duplicated under any relation. See below screenshot.
small-bug
2. Clicking the delete/trash button next to a current selection doesn't appear to fully work. Sometimes the item in the form remains (e.g. on the Journal Issue form, I cannot seem to delete a selected volume). However, sometimes it appears to work (e.g. on the Person form. I can delete the Publication) but if I click the Lookup button again, I see it's still selected in the popup.  (I haven't dug into this deeply, it might be a backend issue or an issue with the deletion request to the backend.)
3. For single-valued fields, if you change the selected entity in the Lookup modal, it keeps adding new values to the list on the form.  See this screenshot where it appears I have 3 Volumes linked to this new Issue.  All I did was open the Lookup modal, select one volume. Close the modal. Open it again, change the selection. Close it. Open it a third time, change the selection and close it.  The Submission Form thinks I now have 3 values, but it's just one relationship that has been changed 3 times. If I open the Lookup modal though, I see it only has one current selection. 
another-bug

Overall, the behavior here is much improved! The basics work.  So, if one of these is difficult to solve quickly, we could leave it as a "known issue" for now.  I just wanted to make sure these bugs were documented somewhere.

**Comment by artlowel** [comment]
@tdonohue 

The first issue should be fixed now. 

Issues 2 and 3 are symptoms of the same problem as far as I can tell: the DELETE request for those relationships fails. Rest returns a 400 with the message "Request is invalid or incorrect". It's a fairly straightforward request, the authorization and CSRF headers look to be correct. The relationship to be deleted also definitely still exists, you can still GET it afterwards. So this looks to be a problem on the REST side.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @artlowel .  I re-tested today and it looks good now.

Somewhat strangely, today the delete button appears to be working correctly for me.  I also had Chrome DevTools open and I see the DELETE request succeeds.  I'm not sure why it wasn't working yesterday.

I will note though that after clicking the DELETE button, I see the value disappear from the Submission Form, but it's still "cached" in the Lookup window (if I click Lookup it still appears selected there even though the DELETE command to REST succeeded, returning a 204).  This is not a significant bug to block this PR, but it's something we may wish to look into further during Testathon.  I can log it separately.

In any case, this looks good to me now.

**Pull request merged**
