### PR TITLE
Fix "Browse by Author" remaining serious accessibility issues

### LINKED ISSUE #1176: [Deque Analysis] Browse by Author "serious" issues
> Serious: This issue results in serious barriers for people with disabilities, and will partially prevent them from accessing fundamental features or content. People relying on assistive technologies will experience significant frustration as a result. Issues falling under this category are major problems, and remediation should be a priority. 

## Deque Analysis Summary

Browse by Author pages have a total of 4 serious issues (not including color contrast which are handled in other tickets):

1. ~~(ID 469380) "Selected/Active state of the element is missing" (in the gear dropdown where "Results per page" and "Sort options" are visible).  In the dropdown, the selected RPP and Sort by options _are shown with a visible checkmark_, but that is NOT displayed to screen readers.~~
    * ~~HOW TO FIX: Use the `aria-current` attribute to indicate the element that represents the currently selected item within a container or set of related elements, such as the currently selected page, step, location, date, or time. https://www.w3.org/TR/wai-aria-1.1/#aria-current~~
    * ~~_ALSO occurs on Community Homepage, so this should be fixed in a general location._ See also ID 469634~~
    * FIXED BY #2717
2. (IDs 469483, 469487, 469491) Issues with placeholder text "Type the first few letters and click on the Browse button"
      * First, it is cut off when text spacing is adjusted
      * ~~Second, it is also cut off when you zoom 200%~~ (No longer reproducible in 7.6.1)
      * Third, it is also cut off when you set the screen at 320px width.
      * In all three scenarios that placeholder text is too long to display.  I wonder if we should simply move it to a *label* or *hint* (below the textbox) so that it can more easily wrap...instead of using placeholder text.
      
Full list of issues is viewable at (requires login): https://axeauditor.dequecloud.com/test-run/0856438a-a19a-11eb-bc31-b7d5be387c86/issues?activeTab=dt-issue&page=0&pageSize=50&sortField=ordinal&sortDir=asc&row=9&filter%5Bseverity%5D=3&filter%5Btype%5D=issue&filter%5Bpage_number%5D=2

## More Information / Tools

* Consider using [Deque's free Chrome plugin](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US) to check your work

### PR DESCRIPTION
**Pull request by Andrea-Guevara**
Browse by Author "serious" issues #1176

## References
Fixes #1176
This change was addressed in issue #1176, which now allows the correction of the placeholder text problem "Type the first few letters and click the Search button" in the search bar of the author, title, and subject navigation pages.

## Description
In the "starts-with-text" component I modified and added some standard bootstrap classes and HTML tags. The search bar of the "starts-with-text" component was too small for smaller screen sizes, so I removed the "col-8" class and added the "col-auto" class from bootstrap. Another change was to insert a smaller placeholder text; the original text was added in a "small" tag under the search bar so that in smaller dimensions it could appear in full without being cut off.

## Instructions for reviewers
List of changes in this PR:

* Change of bootstrap class col-8 to col-auto in the div containing the navigation bar; 
* Modification of the placeholder text by adding a new translation key "browse.search-form.placeholder"; 
* Addition of the "small" tag, containing the explanatory text "Filter results by entering the first letters"; 
* Addition of a new div that will contain the navigation bar, the explanatory text and a bottom margin with the mb-3 bootstrap class; 
* Changing the bottom margin of the form-group class from 1rem to 0; 
* Finally, the : at the end of the text has been removed from the translation key "browse.startsWith.type_text".

**Include guidance on how to test or review your PR.**

Go to the navigation page by author, title or subject and reduce the page width to 320px resolution and test the responsiveness of the navigation bar.

### CODE REVIEW

**Comment by tdonohue** [comment]
@Andrea-Guevara : Thanks for the PR!  Please note this PR is failing automated tests because it has lint formatting errors.  You can run `yarn lint` locally to see those errors, or see inline notes on the "Files changed" tab of this PR.  These errors might be automatically fixed if your run `yarn lint --fix` or you can manually resolve them.

**Comment by Andrea-Guevara** [comment]
@tdonohue: Thanks for your guidance, the formatting error has now been corrected!

**Review by tdonohue — APPROVED** [review]
👍 Thanks @Andrea-Guevara !  This looks like a good solution to me.  I've verified the remaining issues in #1176 have been fixed by the changes you've made.

**Comment by tdonohue** [comment]
Manually ported to 7.x in #3119

**Pull request merged**
