### PR TITLE
#3288 - Enabled 'admin-div' only for Site Administrator

### LINKED ISSUE #3288: Community admins wrongly see the button to create top-level communities
## Describe the bug
Community admins see the button to create top-level communities, although they shouldn't.
Since they administer one or more communities, they should be able to create sub-communities but not top-level ones.
image

If they click on the top-level community creation button, they see the form, but an error prevents them from saving it.
image

## To Reproduce
1. Log in as Community admin on https://demo.dspace.org/home
2. On the admin bar, click on New -> Community
3. Select Create a new top-level community
4. Fill the form
5. Save
An error will correctly block the creation

## Expected behavior
The Community admins don't see the button for creating top-level communities in the admin bar.
image

### PR DESCRIPTION
**Pull request by Simone-Ramundi**
## References
* Fixes #3288 

## Description
This PR introduces a change to the CreateCommunityParentSelectorComponent to display the admin-div section only to users with Site Administrator privileges.

## Instructions for Reviewers
The key changes include:

- **New** `isAdmin$` **Observable:** Added an isAdmin$ observable to the CreateCommunityParentSelectorComponent to track admin status.

- **Conditional Rendering**: Added a `<div>` with `data-test="admin-div"` in the component's template, which is displayed only if `isAdmin$ `emits `true`.

- **Updated Tests**: Adjusted the unit tests to check for the presence of the `admin-div` based on the admin status.

**How to test:**

1. Log in as Community admin on https://demo.dspace.org/home
2. On the admin bar, click on New -> Community
3. Verify that the admin-div is not visible.

Screenshot from 2024-09-06 18-05-31

This will confirm that the `admin-div` is correctly shown or hidden based on the user's admin status.
## Checklist
- [X] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [X] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [X] My PR **passes [ESLint](https://eslint.org/)** validation using `yarn lint`
- [X] My PR **doesn't introduce circular dependencies** (verified via `yarn check-circ-deps`)
- [X] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [X] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [X] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [X] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [X] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by nwoodward — APPROVED** [review]
Thanks @Simone-Ramundi! I tested these changes, and they work well.

**Comment by alanorth** [comment]
Thanks @Simone-Ramundi. I also tested this and found it works as expected. Since this is https://github.com/DSpace/dspace-angular/labels/1%20APPROVAL and it passes all tests in CI I think we can merge this now.

**Review by alanorth — APPROVED** [review]

**Comment by alanorth** [comment]
Dear @Simone-Ramundi, the automatic backport to `dspace-7_x` failed. If you have time would you be able to create a manual port? Thank you!

**Comment by Simone-Ramundi** [comment]
Thank you for bringing this up, @alanorth. There you go: #3696. Let me know if there’s anything else to address.

**Pull request merged**
