### PR TITLE
Added support for caching embedded objects without a self link & null responses

### LINKED ISSUE #2833: Null objects aren't cached
**Describe the bug**
Objects aren't cached when they return `null`. This is visible for example on the search page, where thumbnails are requested again even tough they were embedded.

**To Reproduce**
1. Go to the search page and open the network tab (ensure there are items without thumbnails)
2. You will see that even tough the results contain `thumbnail: null` an additional request is sent to retrieve who returns a 204

**Expected behavior**
No additional thumbnail requests should be sent

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes DSpace/DSpace#9316
* Partially solves #3163
* Fixes #2833

## Description
Reduced the number of requests sent to the backend by caching embedded null objects (this will prevent unnecessary thumbnail requests). Also added support for caching embedded objects without a self-link. (Credit for this PR goes to @Atmire-Kristof)

## Instructions for Reviewers
List of changes in this PR:
* Added support to cache `null` responses.
* Added support to cache embedded objects without `self` links.
* Embedded the `accessStatus` in places where a separate request was made.

**Guidance for how to test/review this PR:**
- On [demo](https://demo.dspace.org/), go to your network tab and select Item Type Publication. Verify that a lot of `thumbnail` and `accessStatus` requests are made.
- Perform the same action with this fix and verify that both the `thumbnail` and `accessStatus` requests are now cached.
- These changes also apply to the browse page, the item page's related items section, the delete item tab, and the recent submissions section on the home page.

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [x] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by ybnd** [comment]
Note: https://github.com/DSpace/dspace-angular/issues/3163 should probably remain open since this PR doesn't cover everything mentioned there (search facets)

**Review by kshepherd — APPROVED** [review]
+1 I tested search, browse, item status / edit item, My DSpace, related entities / items and can verify fewer requests (many fewer requests in the case of item lists with no thumbnails) as both an unauthenticated and authenticated user. No errors or issues encountered.
The code changes look good to me too, nothing big stood out (though this +1 is more of a practical test and feedback than a thorough code review.)
Thanks @alexandrevryghem ! Looks like great progress towards improving performance and efficiency

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  This looks great and works well.  I can verify this has many fewer requests on all browse/search pages.   I **did notice** however that we still have several `/items/[uuid]/accessStatus` calls occurring on the MyDSpace (but those `/accessStatus` calls no longer occur for the search/browse pages).

Nonetheless, this is a huge improvement, so I'll go ahead and merge it and see if it can be ported automatically to 7.x and 8.

**Comment by tdonohue** [comment]
@alexandrevryghem : Would you be able to (manually) port this to both `dspace-8_x` and `dspace-7_x`?  Both of the automated ports have failed.

**Pull request merged**
