### PR TITLE
Parameter box, shown or not

### LINKED ISSUE #2188: Parameter box is shown but the script takes none
**Describe the bug**
In the processes tab, for the solr-database-resync, a parameter box appears, even if the script takes none.
image
**To Reproduce**
1. Open processes
2. Select the solr-database-resync
3. You are now able to see the parameter box
**Expected behavior**
There should be no parameter box if the script takes no parameter

### PR DESCRIPTION
**Pull request by Sondissimo**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #2188

## Description
Check the parameters if available, if not, hides selector box

## Instructions for Reviewers
Added a single line in the process-parameters.component.html, we now check if the parameters selector for the process contains at least 1 value, if not, the selector box is not shown.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [ ] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@Sondissimo : Thanks for the fix!  While this fix *does work*, it results in a large number of errors being displayed in my browser's DevTools console. They all look like this:
```
ERROR TypeError: Cannot read properties of undefined (reading 'parameters')
```

The issue appears to be that this new code runs even *before* I select a script.  Here's how to reproduce this error (I'm running it in production mode: `yarn build:prod; yarn serve:ssr`):
1. First visit the User Interface
2. Open your browser's DevTools and keep an eye on the "Console"
3. Login as an Admin and go to the the Processes page (http://localhost:4000/processes)
4. Click "+ New" on that page.   Now, look back at your Console, and you'll see at least 3 errors have appeared.

**Comment by Sondissimo** [comment]
Im actually fixing it and writing the tests for it in the spec file, will provide code for tomorrow!

**Comment by Sondissimo** [comment]
I improved the checks in the existing ngIf statement by declaring that values could be optional. 
This prevents any further console errors. 

Additionally, I revisited the spec file and added a describe that was missing.

I would appreciate feedback on the changes made, particularly on the use of ${ParameterSelectComponent.name}. 
This ensures that developers do not have to manually change the component's name in the strings if it ever changes. 
Similarly, I added the data-TestID attribute to avoid basing the test on the HTML, this is because, i think, we are actually testing the logic functionality and not how it relates to the HTML itself.

Please let me know if these changes are welcome. We can always rollback to the previous spec file, with only my test added.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @Sondissimo !  I've verified your fixes work.  The new tests look reasonable to me as well (no objections to the approach).

**Pull request merged**
