### PR TITLE
Bump Angular to 17.3.11 and Angular-CLI to 17.3.8

### PR DESCRIPTION
**Pull request by tdonohue**
Bump Angular from 17.3.4 to 17.3.11 and Angular-CLI from 17.3.0 to 17.3.8

## Description
This PR is a minor update to Angular 17 to ensure we are on the latest version of our major dependencies.  Includes:
* Bump Angular from 17.3.4 to 17.3.11
* Bump Angular-CLI from 17.3.0 to 17.3.8
* Bump webpack from 5.76.1 to 5.90.3 to align with webpack version in `@angular-devkit/build-angular`

## Instructions for Reviewers
* Verify all tests pass
* Verify everything builds.  I tested it locally & found no issues
* Verify UI works as normal.  I tested it locally and found no issues.  (I tested Search, Browse, Login/Logout, external import, complete submission process, and SSR.)

### CODE REVIEW

**Comment by tdonohue** [comment]
@atarix83 and @artlowel :  Any objections to this minor update of Angular & Angular CLI?  I noticed we are quite outdated on both..and it might be nice to get up-to-date prior to 8.0.

**Comment by tdonohue** [comment]
@atarix83 and @artlowel :  Nevermind! It appears this isn't as simple as it seemed.  Unit tests are not running.  So, we'll reschedule for post 8.0

**Comment by atarix83** [comment]
@tdonohue 

i'd try to exclude webpack update, for all the rest I'd not expect any issues

**Comment by tdonohue** [comment]
@atarix83 : I just pushed up the webpack update (a moment ago) as it seems to be **required**.   We were hitting [this issue](https://stackoverflow.com/questions/67727180/the-compilation-argument-must-be-an-instance-of-compilation), and the problem seemed to be that we had two versions of webpack being brought in.  One by `@angular-devkit/build-angular` and one that we listed in `package.json`.  

So, I synced those two versions and updated `package.json` to have the same webpack version as in the (updated) version of `@angular-devkit/build-angular`.    

I tested it locally and found `yarn test` now succeeds.  I also did a full `yarn build:prod; yarn serve:ssr` and verified everything seems to work fine & SSR works, etc.

So, I think this is ready for review now by you and @artlowel if one of you finds time.

**Review by atarix83 — COMMENTED** [review]
@tdonohue 

i'm testing it and everything seems to work fine.

However while testing i found the following error in console 
Schermata del 2024-06-18 19-37-35

is not related to this PR but [here](https://github.com/DSpace/dspace-angular/commit/472fa1c47348514de4006817d74ccd847d468c13) there is a commit to fix it, could you include in this small PR? thanks

**Comment by tdonohue** [comment]
@atarix83 : I was able to pull your small commit into this PR.  See 472fa1c47348514de4006817d74ccd847d468c13 which is now part of this PR.

**Review by kshepherd — APPROVED** [review]
+1 all tests passed, I tested various UI tasks in dev mode and all looks good, including the fix for the user suggestion refresh

**Pull request merged**
