### PR TITLE
Fix to Metadata Registry create new metadata schema doesn't appear without reload #1081

### LINKED ISSUE #1081: Metadata Registry create new metadata schema doesn't appear without reload
**Describe the bug**
On Metadata Registry page, when creating a new schema, the new schema is not listed after successful submit.
Name-field keeps old value.

**To Reproduce**
Create a new schema.

**Expected behavior**
New schema should list as last entry, both Namespace- and Name-fields should be empty.

**Temporary solution**
Reload.

### PR DESCRIPTION
**Pull request by hugo-escire**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #1081

## Description
On Metadata Registry page, when creating a new schema, the new schema is not listed after successful submit.
Name-field keeps old value.

## Instructions for Reviewers
Create a new schema, but the doesn't show at least you edit, delete or reload the page.

List of changes in this PR:
* First, I made a refactor to avoid async issues onSubmit function of the metadata-schema-form.component.ts
* Second, I change the "clearMetadataSchemaRequests", because it has a little async issue in the old code. It was a cache problem, like @tdonohue mentioned.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
Thank you @hugo-escire. I tested the patch and confirmed it fixes the issue. I was able to see the new metadata schema in the registry immediately after saving, without refreshing.

So this looks good to me on functionality, but don't understand the TypeScript code so I will let someone else review and approve.

**Comment by alanorth** [comment]
@hugo-escire looking at this again, I notice that there are many changes to the code that are unrelated to the fix. This makes patches more "noisy" than they need to be, which means reviewing changes is more difficult and merging/rebasing more likely to conflict due to unnecessary changes.

Would it be possible for you to rework this patch without the formatting changes? Thank you.

**Comment by hugo-escire** [comment]
Hi @alanorth, I reverted the format changes. Sorry for the delay.

**Comment by alanorth** [comment]
@hugo-escire no problem. Thanks for the fix. I will merge this now.

I personally try to avoid changes to the code that are not related to the fix, but I think we (the DSpace open source project) are partly to blame because we don't have Angular lint rules to catch these type of changes to whitespace or imports.

**Review by alanorth — APPROVED** [review]

**Pull request merged**
