### PR TITLE
Correctly load choice ui form.other-information translation keys

### LINKED ISSUE #2219: i18n for other-information not loaded
**Describe the bug**
Translations starting with `form.other-information` are not resolved correctly. 

These informations are for example shown in the typeahead/otherinformation of the onebox form element. https://github.com/DSpace/dspace-angular/blob/5e277414832f8241e8b5dc2a81399cb68507c6bf/src/app/shared/form/builder/ds-dynamic-form-ui/models/onebox/dynamic-onebox.component.html#L12

_Our Investigation/reason of the bug:_
The english translation file https://github.com/DSpace/dspace-angular/blob/5e277414832f8241e8b5dc2a81399cb68507c6bf/src/assets/i18n/en.json5#L1740 and as well (most/all) other translations use some json object `{}` , which block all subsidiary translation keys.

**To Reproduce**
1. We discovered this issue in DSpace-Cris (cris-authority-metadatagenerator.xml) which of course does not exist in DSpace. 
2.a Analyzing DSpace and the rare usage of Choice extra-information (e.g.) https://github.com/DSpace/DSpace/blob/80cb84433b16feab17bb06b0808ed2790551397f/dspace-api/src/main/java/org/dspace/content/authority/DSpaceControlledVocabulary.java#L294 it could be reproducable if you configure some onebox field with some vocabulary like srsc (I'm not sure if this works)
2b. Or: the behaviour should be reproducable if some other translation is changed, e.g. introduce
` "form": {}` in en.json5 to see the impact on all subsidiary keys

**Expected behavior**
We expect all translation keys to be resolved.

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by floriangantner**
fixes https://github.com/DSpace/dspace-angular/issues/2219 by removing the json object for key form.other-information which avoids to load subordinated translation keys

## References
* Fixes #2219 

## Description
- removed json object in translation files which blocks loading subordinated translation files used by some components

## Instructions for Reviewers
- it's certainly easier and faster to proof that behaviour of json objects in the translation files on other keys
- e.g. use `"form": {},` or `"submission": {},` to check if the translation messages in the submission forms are not loaded.

List of changes in this PR:
* removed json object in translation files
* added missing `form.other-information` keys which are displayed in AuthorityValues on the Choice UI

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [ ] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@floriangantner and @atarix83 :  While this PR seems like a necessary change, I see several references to `form.other-information` in our codebase, and there are no new keys added to i18n to support those fields:

* https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/models/lookup/dynamic-lookup.component.html#L120
* https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/models/onebox/dynamic-onebox.component.html#L12
* https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/chips/chips.component.ts#L101

So, it looks odd to me that we are not adding replacement keys of some sort?

It looks, to me, like @atarix83 originally added these i18n keys in the initial Submission implementation PR (#279).  But, it's unclear to me if we ever display "other-information"?

It looks, to me, like these fields are related to Controlled Vocabularies in the REST API (e.g. https://github.com/DSpace/RestContract/blob/main/vocabularies.md?plain=1#L214)

Are we certain these keys don't need to be replaced in i18n with something else?  It's unclear to me how to test this however, as I'm not sure I understand the original purpose of this code.  I'm just pointing out that removing these i18n keys seems odd since they **are referenced** in our codebase.  But, I don't know how to replace them.

**Comment by tdonohue** [comment]
I've finally figured out where the `form.other-information` i18n keys are used.  They are used in authority control, e.g. if you enable ORCID Authority on the `Authors` field: https://wiki.lyrasis.org/display/DSDOC7x/ORCID+Authority

Here's a screenshot using `main` and searching for an author name in ORCID.  It appears they do not have translations in our `i18n` files, so they just appear as keys:
authority

So, I don't believe this PR is "harmful".  But, it might be made better by adding the proper `form.other-information` keys that are missing to `en.json5`.  It looks like, at a minimum we need:

```
form.other-information.insolr = "In Solr Index"
form.other-information.orcid = "ORCID"
form.other-information.first-name = "First Name"
form.other-information.last-name = "Last Name"
```

**Comment by floriangantner** [comment]
I've updated the PR with the suggested keys.
And I've also added email and institution as well, as they might appear on the choice ui being generated here
( https://github.com/DSpace/DSpace/blob/6fd31622aefc16e5d6190828e2550db5bc7a6fa0/dspace-api/src/main/java/org/dspace/authority/PersonAuthorityValue.java#L186 )

**Review by tdonohue — APPROVED** [review]
👍 Thanks @floriangantner !  This looks good to me now.  I've also verified the new i18n keys are now displaying properly when using ORCID Authority.

**Pull request merged**
