### PR TITLE
Let the production server "serve for direct CSR" if SSR is disabled or fails

### PR DESCRIPTION
**Pull request by ybnd**
## References
* Fixes https://github.com/DSpace/dspace-angular/issues/2034

## Description
`server.ts` used to just send `index.html` if SSR was disabled or failed. A while back this was changed, and **now it always tries to render on the server**.  Just restoring the previous behaviour didn't work however, because of the changes to configuration handling.

This PR resolves this problem and enables "direct CSR" again.
* In `main.browser.ts`, check if the document contains a transfer state to determine whether SSR was performed. In this context `environment.universal.preboot` does not follow the server configuration, so it used to always follow the SSR branch when running in production.
* When SSR is disabled or fails, just send `index.html`

Other minor changes
* Removed "support" for missing `index.html`; this wasn't functional as far as I can tell
* Removed `index.csr.html`, it was unused.

## Reviewing

Run the app and confirm it works as before
* in development mode
* in production mode with SSR enabled
* with a base path (`yarn base-href` to update `angular.json`)

Turn off SSR via the configuration (no rebuild necessary)
* `index.html` should be served as-is
* the app should work as usual
* base path changes should still be supported

Simulate an SSR error (e.g. by commenting out [this](https://github.com/DSpace/dspace-angular/blob/430b43581a5b8dfe29d8d8a5f0d94b0a62006c81/server.ts#L229-L237))
* `index.html` should be served as-is
* the app should work as usual
* base path changes should still be supported

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by artlowel — APPROVED** [review]
Thanks @ybnd!
This has bugged me for a while

**Comment by tdonohue** [comment]
@ybnd : I like this idea as well..  I just merged #2033 though, which caused some code conflicts with this PR.  Could you rebase this on the latest `main`?  I'll then give it a quick test and get this merged for 7.5

**Comment by ybnd** [comment]
@tdonohue resolved the conflicts.

Please note that it's not possible to selectively toggle CSR for bots/anonymous users as of yet -- I didn't see an quick & good way to do this with how the bot/anonymous split is implemented right now.
This is something we should look into for upcoming releases; IMO this PR is useful enough as-is.

**Comment by tdonohue** [comment]
@ybnd : That's perfectly OK. To be honest, I don't think we should make this configurable per bots/anonymous users anyways.  While I *want* direct CSR to work, I would not recommend most sites to only use direct CSR because it can have a major impact on SEO.  There are still some web crawlers/bots which cannot do as well with a Javascript-only site... so one of the main reasons SSR is highly recommended it because it's really required for accurate SEO.

All in all, thanks for getting this working!  I will test this and move it forward, but (in general) I don't think we should be recommending sites only use CSR unless they really don't care about SEO.  (That said, as I said, I fully agree that this should be an option.. as there may be some sites behind a firewall where SEO really doesn't matter, making direct CSR is a perfectly reasonable approach)

**Comment by ybnd** [comment]
@tdonohue my idea was to make it configurable separately so we can choose to do CSR for anonymous and SSR for bots (fore SEO reasons).

Right now we can only turn off SSR altogether, which I agree is problematic

**Comment by tdonohue** [comment]
@ybnd : Ah, now that makes sense.  Yes, that might be an option... although, I have to admit I'm still worried about CSR-only for anonymous users.  We'd have to look at how that would also impact things like screen readers (for accessibility), etc.   It's a path we could go down, but I still have too many concerns/questions about CSR-only that we'd need to dig into first.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @ybnd !  Tested this and verified it works perfectly & that the site now falls back to direct CSR if SSR throws an error.

**Pull request merged**
