### PR TITLE
Add more automated accessibility scanning to e2e tests & fix a few minor accessibility bugs

### PR DESCRIPTION
**Pull request by tdonohue**
## Description
This PR is **primarily** impacting e2e tests (via Cypress), with a few minor changes to DSpace itself.  

It does the following:
* Refactors some of the Cypress code in `commands.ts` and `e2e.ts` to simplify duplicative code & make it easier to perform tasks that require a CSRF token.  Also cleanup code to use `Cypress.env` instead of our own custom variables.
* Add new accessibility scanning to `e2e` testing for the following pages (NOTE: Some pages, like submission form, have specific accessibility checks turned off for them to fully pass. I linked to associated tickets):
    * Admin Sidebar
    * Item Edit page (all tabs on this page)
    * Collection Edit page (all tabs on this page)
    * Community Edit page (all tabs on this page)
    * New User Registration page
    * User Menu (available after authentication)
    * Submission Form (for normal Item and Person entity)

A few minor fixes were applied to DSpace UI itself:
* Added some `data-test` attributes for usage in some tests.  These are harmless and only used in tests.
* Corrected some `<h4>` tags to be `<h3>` in Collection Edit tabs. This fixes an accessibility issue related to header ordering
* Replaced some `id` attributes with `data-test` on Item Edit Metadata page.  These `id` attributes resulted in duplicative IDs on the page (which fails accessibility) and were only used by tests.
* Added/corrected ARIA labels on several fields in Submission form.  Also fixed a `tabindex` issue in `date-picker.component.html`. Both of these were accessibility issues caught by the accessibility scanner.  The `tabindex` fix has been tested and doesn't seem to affect tab ordering.

## Instructions for Reviewers
* Most of the code here is e2e tests and only requires a quick code review (if desired).  It is tested automatically by GitHub CI.
* The Submission form can be retested as minor changes were made there, primarily to `tabindex`.  Verify that tab ordering is still correct when tabbing between month/day/year of date fields.

### CODE REVIEW

**Comment by tdonohue** [comment]
@alexandrevryghem : Would you be interested in giving this a quick review either in December or January?  I know you've helped with a ton of accessibility fixes recently.. this PR adds a few more tiny ones, but also adds *automatic accessibility scanning* to many pages in our e2e tests (to avoid us breaking accessibility in any future changes).   Most of the PR is e2e tests (which are all succeeding in GitHub CI), with only very minor changes to the actual DSpace UI.  So, it may be very quick to review.

**Review by alexandrevryghem — CHANGES_REQUESTED** [review]
@tdonohue thanks for these new tests. I ran all the tests locally with my own backend and after updating the `cypress.config.ts` variables, they all succeeded, except for a test in `submission.cy.ts`. This is because this test requires you to also create a collection with the entity type `Person`. Perhaps we could create a variable for this as well, for example `DSPACE_TEST_PERSON_COLLECTION`, to make it clearer that such a collection is also required.
I also added two inline comments for two minor changes and two translations that should ideally be moved to the `en.json5` file. It would probably then also be best to translate the `name` & `placeholder` `@Input()`s in `src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.html` as well. However if you think this is out of scope, this can be fixed in a separate PR.

**Comment by tdonohue** [comment]
@alexandrevryghem : Thanks for your prior review.  I've addressed your [prior feedback](https://github.com/DSpace/dspace-angular/pull/2711#pullrequestreview-1799153726) in the most recent two commits (0aaf313 and a5a89a4) and rebased it on latest `main` to ensure no recent changes have broken these tests (they have not as everything is still passing).

I will note I did *not* translate the `name` and `placeholder` inputs as you recommended as I feel that's out of the scope of this PR.  I agree it'd be nice to do, but it's not part of the code that this PR touches & this PR concentrates on accessibility fixes not i18n fixes.

If you have a chance to re-review this, I believe it will be quick to verify as the changes you requested are minor & covered by tests.

**Review by alexandrevryghem — APPROVED** [review]
Thanks @tdonohue! I've verified that my feedback was indeed addressed, so it looks good to me!

**Pull request merged**
