### PR TITLE
More meaningful regex error messages

### PR DESCRIPTION
**Pull request by hutattedonmyarm**
## References
* Fixes DSpace/DSpace#9178
* Backported to 7.x in #2641

## Description
Adds field-specific error messages for regex validation in the form of `error.validation.pattern.schema_element_qualifier`.
If no error message for a specific field has been added to the i18n files, the old error message will be used.

## Instructions for Reviewers
- Add a regex validation for a field, e.g. `dc.title` in the submission configuration
- Enter a value which does not pass the regex validation
- No change should be visible now compared to before
- Then add the corresponding message key to the i18n files, e.g. `error.validation.pattern.dc_title` with custom error message
- Restart your frontend
- Now the custom error message should be visible

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by kanasznagyzoltan** [comment]
I have tested this improvement and it has worked for me.

I have modified the dc.title field in the default form (traditionalpageone) of the submission.xml:
```
            <row>
                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>title</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>Title Regex</label>
                    <input-type>onebox</input-type>
                    <hint>Enter the main title of the item.</hint>
                    <required>You must enter a main title for this item.</required>
                    **<regex>/[a-z]+/i</regex>**
                </field>
            </row>
```

I have added an extra translation key to the English translation file of the dspace-angular frontend:
"error.validation.pattern.dc_title": "The title for the given pattern is not valid... this error message comes from translation file and related to the dc.title field!"

If I put an invalid input to the field I have got my custom translation back:


If I remove my custom translation key I have got the default translation corresponding to the acceptance regular expression:

**Review by tdonohue — APPROVED** [review]
👍 Thanks @hutattedonmyarm !  I also had a chance to give this a test (based on @kanasznagyzoltan 's example) and it's working well.  So, I'll merge this into 8.0 and 7.x immediately.

That said, I'm going to add the `needs documentation` as I think we should mention in the documentation that these regex messages are now translatable.  If you have the chance to add a note to the [Submission Docs](https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface) (next to the docs for regex), that may be the best place.  If you don't have access you can also add basic notes here & I'll get them copied over.

**Comment by hutattedonmyarm** [comment]
@tdonohue I don't have an account for the wiki. I'd suggest to add a note to the "regex" section. I've left the beginning as is and added instructions 

**regex**: When specified, this field will be validated against the Regular Expression, and only successfully validating values will be saved.  An example is commented out in the default "Author" field. If the validation fails, the following error message will be shown by default: _"This input is restricted by the current pattern: {{ pattern }}."_. This can be customized, by adding an entry to the internalization files with the key `error.validation.pattern.schema_element_qualifier` and the schema, element and qualifier of the field. For example: _"error.validation.pattern.dc_identifier": "The identifier can only consist of numbers"_. For instructions on how to add custom entries see: [Customize UI labels using Internationalization (i18n) files](https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Customization#UserInterfaceCustomization-CustomizeUIlabelsusingInternationalization(i18n)files)

**Comment by tdonohue** [comment]
Thanks @hutattedonmyarm !  I've copied those docs into the 7.x and 8.x documentation for the Submission User Interface.  I'll remove the `needs documentation` flag now.

**Pull request merged**
