### PR TITLE
Swedish language file for DSpace 7

### PR DESCRIPTION
**Pull request by jokermanse**
## Description
Swedish language file. 

## Instructions for Reviewers
Added new Swedish language file for DSpace 7. Includes some basic translations, but more work is needed.

List of changes in this PR:
* Swedish language file (sv.json5)

### CODE REVIEW

**Comment by tdonohue** [comment]
@jokermanse : Thanks!  I took a quick look at this today, and while it looks like it's a good start, I see that much of the text hasn't been translated yet.  Did you want to work on this more before we merge it?  Or do you feel it'd be beneficial to add this "as-is" in order to allow others to help complete the Swedish translation?

**Comment by tdonohue** [comment]
@jokermanse : I took another look at this today, and I see you've added many more translations. Thanks!  Do you want me to assign reviewers to this PR, or are you still working on it?  Once we assign reviewers, we can test and merge this PR (once approved)... so, just let me know when you feel this is completed enough to review.

**Comment by jokermanse** [comment]
> @jokermanse : I took another look at this today, and I see you've added many more translations. Thanks! Do you want me to assign reviewers to this PR, or are you still working on it? Once we assign reviewers, we can test and merge this PR (once approved)... so, just let me know when you feel this is completed enough to review.

@tdonohue : The translation file should be complete enough to be merged into the main branch now. Thanks!

**Comment by tdonohue** [comment]
@jokermanse : It looks like this PR somehow accidently modifies the `tr.json5` unintentionally.  Could you revert the changes to that other file by running something like: 

`git checkout upstream/main -- src/assets/tr.json5`  

That should revert your local copy of `src/assets/tr.json5` to the version in `DSpace/dspace-angular` (which likely is called "upstream" in your local repository).

If that doesn't work and you cannot figure out a fix, let me know and I can see if this is something I can resolve on my end on your behalf.  Ideally though this PR should only modify the single `sv.json5` file that you've added.  Thanks!

**Comment by jokermanse** [comment]
> 

I had some problems with this and ended up updating the local branch (pull upstream main) before I could checkout/restore the tr.json5 file. But everything should be fine now.
Should I create a new PR or would it work as is?

**Comment by tdonohue** [comment]
@jokermanse : The PR looks good to me now! It no longer shows changes to the `tr.json5` file, which is good.  I'll give it a quick test on my end today... assuming the Swedish language pack works, I'll get it merged.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @jokermanse !  I've tested this locally and verified that the translation file works when enabled.  I'll merge this immediately so that it will be in 7.4.  I'll also follow it up with a small PR to enable Swedish in the language dropdown menu by default, so that it appears there as well.

**Pull request merged**
