### PR TITLE
Update dependencies for Node v20

### LINKED ISSUE #2290: dspace-angular 7.6 won't build with Node v20
**Describe the bug**
```
./server.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: Transform failed with 1 error:
/home/mwood/NetBeansProjects/dspace-angular/src/app/health-page/health-page.component.scss:64:84: ERROR: Unterminated string token
```
The stylesheet varies; the location is always "64:84", which likely doesn't exist in the named file.  Some component of the toolchain has very poor error recovery.  There's a Stack post somewhere about this, and it seems that everyone who comes there says none of the previous answers worked but he found a new one that does.

Even when I install `nvm` and set it to Node v18, I get the same error.

After much trial and error and Googling all over the place:  for some reason, `webpack` was evading `nvm` and using the system `node` v20.  The `css-loader` version it wanted was unable to cope, threw up its hands, and some bletcherous piece of code with rotten error recovery somehow turned that into "unterminated string token" at a nonexistent location.

To find this, I had to disable optimization (twice) in `angular.json`.  I then had to raise the "initial" budgets to 13mb/15mb to get to the server build and see the real problem that should have been reported all along.  After that I raised the `@angular/cli` version to 16.0.4 -- the latest.  That got me a `css-loader` that was, not the latest, but late enough not to wig out when running on Node v20.

So, it appears that the minimum we'll need to support building with Node v20 in some future release is:
- "@angular/cli": "^16.0.4"
- "eslint-plugin-jsdoc": "^45.0.0" (which I had previously discovered by running `yarn install`)

(`ng version` says:  "Node: 20.2.0 (Unsupported)" but built it anyway.)

**To Reproduce**
1. Install Node v20
2. `yarn build:prod`

**Expected behavior**
A clean build as on Node v18.

### PR DESCRIPTION
**Pull request by mwoodiupui**
## References
* Fixes #2290

## Description
Updated dependencies to make the project build with Node v20.

## Instructions for Reviewers
List of changes in this PR:
* Updated `@angular/cli` and `eslint-plugin-jsdoc` enough to fix build failures.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
Just a sidenote:  We should test these changes using Node 18 & 16 as well.  If these updates work for v16, 18 and 20, we may want to consider backporting this to `dspace-7_x`.   If not, then this must be only applied to `main`.

**Comment by mwoodiupui** [comment]
The automated tests build with Node 16 and 18.  Do we need additional testing with those versions?

**Comment by tdonohue** [comment]
@mwoodiupui : I'd recommend a quick manual test as well. Since the automated tests work, that's an _excellent sign_.  But, for safety sake, I'd really like to spin up the UI in Node 16 & 18 to ensure nothing strange occurs, especially since our e2e (integration) tests are still very minimal.

**Comment by alanorth** [comment]
I did some basic tests on `dspace-7_x` using Node.js v18:

- Build dev app
- Browse, search
- Submit item, edit item

No errors in the console or logs. Here are the versions resolved at the time I built and tested @mwoodiupui's patch:

```console
$ npx ng version
...
Angular CLI: 16.1.4
Node: 18.16.0
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 15.2.8
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.5
@angular-devkit/build-angular   15.2.6
@angular-devkit/core            12.2.18
@angular-devkit/schematics      12.2.18
@angular/cli                    16.1.4
@ngtools/webpack                15.2.6
@nguniversal/builders           15.2.1
@nguniversal/express-engine     15.2.1
@schematics/angular             16.1.4
rxjs                            7.8.0
typescript                      4.8.4
webpack                         5.76.1
```

**Comment by mwoodiupui** [comment]
Built and run on Gallium (v16 LTS).  Browse, search, submit seem to work.

```
Angular CLI: 16.1.4
Node: 16.20.1
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 15.2.8
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.5
@angular-devkit/build-angular   15.2.6
@angular-devkit/core            12.2.18
@angular-devkit/schematics      12.2.18
@angular/cli                    16.1.4
@ngtools/webpack                15.2.6
@nguniversal/builders           15.2.1
@nguniversal/express-engine     15.2.1
@schematics/angular             16.1.4
rxjs                            7.8.0
typescript                      4.8.4
webpack                         5.76.1
```

**Comment by mwoodiupui** [comment]
Locally tested this day with `yarn test` on Node 16.20.2, 18.19.1, 20.11.0.  All passed.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @mwoodiupui !  I figured this be good to apply before other dependency updates.  Tested this locally using Node 18 and I found no adverse effects.   Merging immediately.  

NOTE: I've setup the automatic backporting on this PR...but I'm uncertain how well that will work with the `yarn.lock` file.  So, if it doesn't work, we'll need to manually port this to 7.6.x for 7.6.2

**Comment by tdonohue** [comment]
@mwoodiupui : As I feared, this couldn't be ported automatically.  If you can find time to create a corresponding PR for the `dspace-7_x` branch, I can get it quickly tested/merged once it is ready.  Thanks!

**Pull request merged**
