### PR TITLE
Fix issue where a colon in a uuid would get misinterpreted as a route param

### PR DESCRIPTION
**Pull request by artlowel**
## References
* Replaces https://github.com/DSpace/dspace-angular/pull/2283

## Description
Some logic meant to copy route params to menu link params didn't work properly if the menu link contained a param, but the route didn't have a matching one

## Instructions for Reviewers
- Verify that the DSO routes containing a colon work properly now (they should redirect to the login page if you're logged out, or to 404 if you're logged in). e.g.
    - `/collections/sample:path`
    - `/communities/ab:cd`
- Verify what happens if you use the name of the route param in the route. e.g.
    - `/items/:id:foo`
- Verify that regular DSO routes still work
- Verify that context sensitive statistics links in the header menu still work (which is the reason the method causing the issue was written in the first place)

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by artlowel** [comment]
Moving this to draft again: this doesn't deal with the case where you put the name of the route param in the route: e.g. `/items/:id:something` (where `:id` is the name of the param)

**Comment by alanorth** [comment]
I tested basic browsing of communities, collections, and items. Everything working as expected.

**Comment by MW3000** [comment]
I tested the functionality. It fixes the problems for the problematic URLs we were in encountering in production.

**Comment by tdonohue** [comment]
@MW3000 : That issue with `http://localhost:4000/browse/foo:bar` seems unrelated to this issue... I can verify that `/browse/foo:bar` never responds, but neither will any other invalid browse (e.g. `/browse/nothing`).  It appears we need better error handling for that path, but it doesn't result in the same behavior as this colon-in-uuid issue.

That said, if @artlowel sees a quick fix to `/browse` to handle invalid browse-by options, I do agree it'd be nice to fix as well.  It's just a different issue from what I can see.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @artlowel !  Verified this fixes the issues with a colon passed in as an object UUID.  Code looks correct and the tests verify the fix is correct.

**Pull request merged**
