### PR TITLE
Login menu refactoring

### LINKED ISSUE #1943: Refactoring of login components
DSpace currently uses a component for each login method. Currently we have`log-in-oidc` `log-in-orcid` and `log-in-shibboleth` which are basically the same, and they could be replaced with a single `log-in-external-provider` component.

### PR DESCRIPTION
**Pull request by davide-negretti**
## References
* Fixes #1943 

## Description
All `log-in-***` components have been replaced with a single `log-in-external-provider` component.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by jtimal** [comment]
Hi @davide-negretti 

The operation for me is correct, but I got an error screen, this happens when I am logged in and enter the page /login this is loading.

image

Greetings!

**Comment by davide-negretti** [comment]
Hi @jtimal 
This is the current behaviour of the main branch. However, if you are already logged in you should not be able to reach the `/login` page (unless you manually type the url in the address bar).

**Review by artlowel — APPROVED** [review]
Thanks @davide-negretti!

The code looks good and it works

Note that I've only verified using orcid and shibboleth, as I don't have a server with OIDC configured.

**Comment by tdonohue** [comment]
@davide-negretti : Could you fix the code conflicts in this PR?  That'd allow me to do a quick test myself and then get it merged.  Thanks!

**Comment by tdonohue** [comment]
@davide-negretti : Just a reminder that we cannot merge this (even though it has +1 approval) until it is rebased on the latest code.  If you can find a chance to rebase it, I'd appreciate it. Thanks!

**Comment by davide-negretti** [comment]
Hello @tdonohue,I fixed the merge conflicts

**Review by tdonohue — APPROVED** [review]
👍 Thanks @davide-negretti !  I tested this with OIDC using https://www.phantauth.net/ and it appears to be working for that as well.  So, I'll merge this immediately since we've verified it works for all current external  auth providers (Shib, OIDC, Orcid).

**Pull request merged**
