### PR TITLE
Enhanced community/collection logo edit

### PR DESCRIPTION
**Pull request by Sondissimo**
**Description**
When editing an existing Community/Collection the Dspace standard behaviour is redirecting the user back to the Community/Collection page, after it uploads/remove the selected logo.
With this PR it's possible to handle the logo remaining in the same edit page.
When creating a new Community/Collection the current behaviour for the logo upload is kept.

**List of changes in this PR:**
* Logo editing is now handled inside the edit itself
* Updated tests to reflect new behaviour

**Instructions for reviewers**:
Please try removing/uploading the logo in community/collection edit
Please try creating a new community/collection with and without logo

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.

### CODE REVIEW

**Comment by tdonohue** [comment]
@Sondissimo : This has code conflicts.  If you wish to have it still considered for 8.0, please get this PR cleaned up and updated to latest `main`.  Otherwise, we'll have to reschedule for 9.0

**Comment by Sondissimo** [comment]
Taking care of it 😀

**Review by tdonohue — CHANGES_REQUESTED** [review]
@Sondissimo :  I tested & reviewed this today.  Overall, this looks *great*!  However, I did find a minor bug that we should try to fix.  If you upload a logo in the creation step, you go back to the creation form.

Here's how to reproduce the bug.  I'm testing in prod mode (`yarn build:prod; yarn serve:ssr`)
1. Login as an Admin
2. Go to "New" -> "Community" and create a new Community
3. Upload a logo immediately.  Add a Name for the community.
4. Click "Save"
5. You'll see a notification that it worked, but you **remain on the Create Community Page** `/communities/create`.   In the past, you'd go directly to that new Community's homepage.
6. This same behavior also occurs when creating a new Collection.

Beyond that, I think everything else is working well.  If I upload a logo when editing a Community or Collection, then I remain on the edit form and the logo appears immediately.

**Comment by kanasznagyzoltan** [comment]
We have tested this PR.
Checked out the PR branch, after uploading a logo, it appears and can be deleted, without being redirected from the edit page. Works as described.

image

**Comment by Sondissimo** [comment]
The bug reported  was present on Dspace8 already, we provided a fix for it in the last commits  😊

**Pull request merged**
