### PR TITLE
Communities & Collections tree browser updates

### PR DESCRIPTION
**Pull request by wwtamu**
## Description
This PR fixes two issues with the community collection list page:

- The show more button not rendering after selection and more pages available.
- When multiple show more nodes without unique id, the nodes are not being placed or expanding correctly.

## Instructions for Reviewers

Set `communityList.pageSize` to a small number (less than half the number of top-level communities and less then subcommunities under a community).

```
communityList:
  # No. of communities to list per expansion (show more)
  pageSize: 4
```

Navigate to [Communities & Collections](http://localhost:4000/community-list) page. Click show more pages and expand communities/subcommunities which multiple pages at the same level. The described issues above should no longer occur.

List of changes in this PR:

* The condition to render the show more button has been updated to render when more pages are available after selection. Previously it was not rendering after a selection and more pages are available.
* The id of the show more node added to the tree must be unique otherwise it is placed at the wrong level and clicking pages the wrong page (level). To make the node id unique, it was appended with hyphen and a newly generated UUID. The condition during `getNextPage` was updated to match `node.id` `startsWith` `collection` or `community`.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by artlowel — APPROVED** [review]
Thanks @wwtamu 

The fixes work, and the code looks good.

One more bug in a similar vein I noticed while testing this: if you have multiple nodes in the tree with the same name (e.g. currently the "biochemistry" top level communities on demo.dspace.org) and you open more than one, then close one, they all close at once. And the chevron for the ones you didn't click won't be updated.

I'm willing to bet the fix is as simple as changing the names [here](https://github.com/DSpace/dspace-angular/blob/e2425696a501d2407bd8ecbce93d9d042d18ff77/src/app/community-list-page/community-list/community-list.component.ts#L87) to ids

This PR doesn't cause that bug, but it seems a suitable one to fix as well, if you still have the time

**Comment by wwtamu** [comment]
Here is the successor PR, https://github.com/DSpace/dspace-angular/pull/2611. Let's see if we get those green check marks.

**Comment by wwtamu** [comment]
@artlowel would you like the above comment pulled out into an issue? I will look for a solution in the meantime.

**Comment by wwtamu** [comment]
Closed as commits split during CI build resolution.

**Comment by tdonohue** [comment]
@wwtamu : Please be aware we are finishing the 7.6.1 release this week (and early next week).  So, I'll likely move the PR #2611 forward "as-is" unless you find a very quick solution.  (I'll wait to merge that PR though until tomorrow to give you a chance to look into it)

If the solution @artlowel suggests above is the correct fix, it may not need a separate ticket or PR (as it sounds like a tiny fix).  But, if we find the issue is bigger than that, then we should move it to a separate ticket and find a volunteer to look into it (likely after 7.6.1)

**Comment by wwtamu** [comment]
No objections here.

**Pull request closed without merging**
