### PR TITLE
Feature: Entity / relationship versioning

### LINKED ISSUE #1312: Create a new Version of Entities
In #776, Versioning was implemented for Items.

However, this feature does not fully support Configurable Entities (which are special types of Items). Ideally, this feature should allow for Versioning to work more seamlessly for Configurable Entities. The Item versioning in #2844 would work at a basic level for Entities (as they are Items), but it ignores existing Relationships. This behavior would be problematic when versioning an Entity that has many Relationships.

Based on the final design in DSpace/DSpace#7937 , the Versioning User interface may require updates to support versioning of Entities. The scope of those updates is not yet certain.  This ticket is for defining & estimating those UI specific updates.

Depends on REST Ticket DSpace/DSpace#7937

### PR DESCRIPTION
**Pull request by benbosman**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #1312
* Related to https://github.com/DSpace/DSpace/issues/7937
* Related to https://github.com/DSpace/DSpace/pull/8265

## Description
This introduces support for versioning of entities with relationships. The solution displays the buttons to create a new version when the backend states versioning is supported for the given item.

## Instructions for Reviewers
When testing this functionality, it's best to use the REST PR: https://github.com/DSpace/DSpace/pull/8265

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by benbosman** [comment]
I've now also merged the solution to ensure the older versions can be returned in the discovery relations on item pages

**Review by tdonohue — COMMENTED** [review]
👍 Thanks @benbosman .  Code here looks good and it works.  I don't have any comments as it looks designed just to act the same as Item Versioning.  (I admit didn't do a deep test of several versions across relationships, but the basics all work fine.  I do want to try and do a deeper test still...but overall this looks great.)

**Review by atarix83 — CHANGES_REQUESTED** [review]
thanks @benbosman for this PR

code looks good to me, but during test I've encountered in a strange behaviour.
Basically when i create a version for an entity the worksapceitem created has the dc.title repeated two times : 
Schermata da 2022-05-20 11-44-03

this strange behaviour occurs only when creating a version of an entities, for a normal item it doesn't happen.

Could you check this problem on rest side?

**Comment by benbosman** [comment]
@atarix83 this took me a while to identify the problem because it was very hard to reproduce

What's going wrong here is:
* In the default database, this was present twice with the same place (bad metadata to start from). I've included that below
* If two dc.title values have the same place, REST will only return one (because it uses a Map on the place). So you only see one
* When you create a new version, places are re-calculated, and the receive places 0 and 1
* As of now, you see two titles

Extract from the original database:
```
select * from metadatavalue where dspace_object_id = 'f4dcd8a6-4cc4-4806-8bb9-a7e8202e05b0' and metadata_field_id= 70; 
 metadata_value_id | metadata_field_id |    text_value     | text_lang | place | authority | confidence |           dspace_object_id           | parentmetadatavalue 
-------------------+-------------------+-------------------+-----------+-------+-----------+------------+--------------------------------------+---------------------
              5584 |                70 | Volume 7, Issue 2 | en_US     |     0 |           |         -1 | f4dcd8a6-4cc4-4806-8bb9-a7e8202e05b0 |                    
              5585 |                70 | Volume 7, Issue 2 |           |     0 |           |         -1 | f4dcd8a6-4cc4-4806-8bb9-a7e8202e05b0 |                    
(2 rows)
```

**Review by tdonohue — COMMENTED** [review]
Thanks @benbosman !  Re-tested today and everything is working well overall. I tried the following:
* Version an Author (Person Entity) linked to a Publication. Verify both point at same Publication.
* Version the Publication related to that Author. Verify new and old Publication both point at latest version of Author
* Version Author again. Verify it now is only referenced to by the *latest* version of Publication. Older version of Publication still points at prior version of Author.

I've also verified locally that the issue that @atarix83 reported was a "bad data" issue.  It seems in the tests entities data set, Entity `f4dcd8a6-4cc4-
4806-8bb9-a7e8202e05b0` does accidentally have _two_ duplicated `dc.title` fields.  With an Entity with a single `dc.title`, I found versioning did not change or duplicate any metadata fields.

**Performance Issue:** I did run into a performance issue when attempting to version an Entity having a large number of relationships  (e.g. versioning an Author with many related Publications).  The easiest way to reproduce this is to version the Person "Simmons, Cameron" (from the test entities data set): http://localhost:4000/entities/person/b1b2c768-bda1-448a-a073-fc541e8b24d9 as that Person is linked to 190 Publications

Here's what I saw when versioning "Simmons, Cameron":
1. Click version, enter a Summary comment & click "Create"
2. At this point, the UI appears to do nothing... but if you are watching DevTools, you'll see it's waiting on a response from the backend.  After **~30 seconds** the backend responds and UI will redirect you to the newly created Submission Form.
    * I think we could improve this usability, a few minor suggestions below
3. Now the Submission Form starts loading. This takes **forever** (approximately 3 minutes). For a very long time, you'll just see a screen like this (until all the linked Publications can be loaded): 
Slow-new-version-loading

I feel (3) above is a separate bug.  It likely needs to be dealt with separately as it's a performance issue in the current submission form.

With (2), I feel we may want to improve the usability to make it clear to the user that a version is being created & it could take some time.  A few suggestions:
* We could display a yellow notification here that says something like "Creating a new version. This may take some time if the entity has many relationships..." (Or something similar)
* Or, we could keep the "New version" window open (don't close it immediately), disable the buttons & display a message saying "Creating a new version... this may take some time".  Then the window would close once the version creation _is completed_.

Overall, I'm basically a +1 as this functionality works.  I just wanted to point out the performance issue and provide a few suggestions on making the usability better when these performance issues are encountered.

**Comment by benbosman** [comment]
@tdonohue We will check the performance (at least the versioning part of it), and you've suggested good ways to display it.

The submission part is indeed not versioning related. And with this setup, it's probably best the person doesn't get a publication lookup, and the tilted configuration is used.

We will fix the merge conflict, and adjust the wording (and if we would see an easy performance improvement when creating the new version, we'll also update on that)

**Review by tdonohue — APPROVED** [review]
👍 Thanks @benbosman and @bruno-atmire !  I retested this today, and I really like the new behavior ... when versioning I now see the modal stays open until versioning is completed and has a message saying "The new version is being created. This may take some time if the item has a lot of relationships."

With this improvement, I think this is a good initial implementation of Entities/Relationship versioning. Future improvements can come in future PRs.

As a small sidenote, I'd appreciate it if you would fix the (very minor) [LGTM warnings on this PR](https://github.com/DSpace/dspace-angular/pull/1624#issuecomment-1154936023) before it is merged.

**Comment by tdonohue** [comment]
@atarix83 : This PR is waiting on a re-review from you.  As noted above, the earlier issue you reported was found to be [an issue of duplicative data in our demo data set](https://github.com/DSpace/dspace-angular/pull/1624#issuecomment-1142024502) (I also verified the duplicative data exists in that data set).  If you try any other Entity the versioning should work as expected.

**Comment by benbosman** [comment]
Thanks @tdonohue , the imports are actually present for the type docs. As you can see, the comments contain `@link` tags, which would otherwise not be interpreted correctly in the IDE.

**Comment by tdonohue** [comment]
@benbosman : Apologies but after merging the ORCID auth PR, this PR (and the REST PR) has new merge conflicts.  This should be the next major feature to be merged if you can get it updated tomorrow.

**Comment by benbosman** [comment]
The merge conflicts are solved, this was agreed to be merged

**Pull request merged**
