### PR TITLE
Update to latest Angular 13 & Remove unused dependencies

### PR DESCRIPTION
**Pull request by tdonohue**
## References
* Fixes a large number of recent security alerts from `dependabot` (at least 10+ by my count) by updating our existing dependencies

## Description
_NOTE:_ While this PR looks large, it's almost entirely the `yarn.lock` file which has changed. Other changes are very minor & easy to code review.

This PR cleans up our dependencies as follows:
* Updates us to the latest Angular 13 release (to patch Angular for bugs/security issues). We've already been running Angular 13 so this is a minor upgrade
* Updates other dependencies to most recent patched versions which are compatible with Angular 13.  Some key updates are:
    * Updates to Sass 1.33.0 -- required to upgrade `ngx-ui-switch` to v13.  This required minor fixes to a few of our Sass stylesheets.
    * Updates to latest Bootstrap 4 release (to support Sass 1.33.0)
* Removal of a large number of **unused dependencies**.   Unused dependencies were determined by running `npx depcheck` (https://www.npmjs.com/package/depcheck) and then double checking each result by searching if they are called by our codebase.  Any which seem 100% unused were removed. 

## Instructions for Reviewers
* Verify all tests pass
* Pull down this PR & verify no changes to build/install process.  Spin up the UI and verify that nothing seems broken.
* NOTE: the new version of `ngx-scroll-to` has strict requirements for which versions of yarn & node it supports.  Therefore, if you are using an older version of either, you may get an error that says `The engine "node" is incompatible with this module.`  If you see that, simply use `yarn install --ignore-engines` to ignore the error (or upgrade your Node or Yarn, alternatively).

### CODE REVIEW

**Comment by tdonohue** [comment]
@artlowel : Would you or someone on your team be willing to take a look at this one?  It's easy to code review & mostly just needs more testers.  It's *important* though as it fixes a lot of `dependabot` notified security vulnerabilities (by just updating our dependencies in minor ways).

**Comment by tdonohue** [comment]
NOTE: This appears to currently have a few e2e test failures which are unrelated to these changes (they are accessibility failures). I'll get those fixed on Monday as they seem to be minor accessibility checks failing.

**Review by artlowel — APPROVED** [review]
Thanks @tdonohue!

The builds work, and I can't find any issues with the UI anywhere. Though I see font-awesome was upgraded from v4 to v6, and that results in some subtle icon changes (mostly for the better imo). It seems to be backwards compatible

**Comment by tdonohue** [comment]
Thanks @artlowel !  Merging this immediately so that we can see the full impact on the `dependabot` security notices.  If we notice any oddities we can clean them up as needed in follow-up PRs

**Pull request merged**
