### PR TITLE
Clarify that submission page may be closed while REST processes uploads

### PR DESCRIPTION
**Pull request by jensvannerum**
## References
https://github.com/DSpace/DSpace/issues/8060#issuecomment-1240592298
> After the file has been uploaded to REST (once progress bar reaches 100% AFAIK?) the upload remains shown w/ “Processing…” – this can take quite a long time for large files
At this point it is unclear whether it is safe to close the page or if the upload will continue if the user gets logged out after idling for too long
@ybnd  confirmed that both are fine.
A simple message like “it is safe to close this page now” would help a lot

_Originally posted by @Raf-atmire in https://github.com/DSpace/DSpace/issues/8060#issuecomment-1240592298_

## Description
This PR makes the `UploaderComponent` more clear, letting the end-user know the page can be left / closed

## Instructions for Reviewers
List of changes in this PR:
* Removed the hard coded "..." in the component so it does not look like it's processing something
* Updated the "Processing" string to clearly state the page can be closed
* Added a TODO comment in the translation files that this translation needs to be revised, since the original string was updated

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
@jensvannerum : This has merge conflicts. Could you rebase this on `main` when you get the chance?

**Comment by tdonohue** [comment]
@jensvannerum : This one still has a merge conflict. Any chance you could rebase this when you have a chance? Thanks!

**Review by artlowel — APPROVED** [review]
Thanks @jensvannerum!

**Review by tdonohue — APPROVED** [review]
👍 Thanks @jensvannerum .  This is a very small change that looks good to me.  Ran a quick test by uploading a larger sized file & I see the new message in the upload box.

**Pull request merged**
