### PR TITLE
Remove material-ui dependency

### PR DESCRIPTION
**Pull request by pastr**
## References
None

## Description
Remove the material-ui dependency, it's not used and it's a React library.

## Instructions for Reviewers
The application works the same without these dependencies. These dependencies are not used in the codebase.

List of changes in this PR:
* Removed @material-ui/core and @material-ui/icons dependencies

## Checklist
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `yarn lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `yarn check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [x] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
Thanks @pastr. I verified there are no imports of `material-ui` anywhere in our Angular code and building the application still works with them removed.

P.S. I think you also need to commit the changes to `yarn.lock`.

**Comment by pastr** [comment]
@alanorth Oh you are right, I forgot about it. 
It's done 👍

**Comment by tdonohue** [comment]
@pastr : The conflicts in this PR are because we recently switched from `yarn` to just `npm` (so the `yarn.lock` is replaced with `package-lock.json`).  See #3173 

If you could find time to update this, I still think this is a necessary change.  If not, I might be able to find time to rework this in the future.  Apologies it's taken so long to review, but I'd like to finally get this merged.

**Comment by pastr** [comment]
hello @tdonohue 
Happy to learn about the switch to npm!
I found 2 others react dependencies (Prop-types and react-copy-to-clipboard) that were not used and also removed them.
I noticed that my editor automatically fixed some indentation in package.json but it seems more consistent that way (2 spaces indentation everywhere).

**Review by tdonohue — APPROVED** [review]
👍 Thanks @pastr !  I was able to give this another look/test today. Looks good. I also built the system with this PR installed and can verify that there doesn't seem to be any change in behavior.

**Comment by tdonohue** [comment]
After merging this, I've realized that these `material-ui` dependencies **might be required for sites using Mirador IIF viewer** (https://wiki.lyrasis.org/display/DSDOC7x/IIIF+Configuration).

When I looked at backporting this to 8.x / 7.x, `yarn install` returned these new warnings:
```
warning " > mirador-dl-plugin@0.13.0" has unmet peer dependency "@material-ui/core@^4.11.0".
warning " > mirador-dl-plugin@0.13.0" has unmet peer dependency "@material-ui/icons@^4.9.1".
warning " > mirador-dl-plugin@0.13.0" has unmet peer dependency "prop-types@^15.7.2".
warning " > mirador-share-plugin@0.11.0" has unmet peer dependency "@material-ui/core@^4.7.2".
warning " > mirador-share-plugin@0.11.0" has unmet peer dependency "@material-ui/icons@^4.5.1".
warning " > mirador-share-plugin@0.11.0" has unmet peer dependency "prop-types@^15.7.2".
warning " > mirador-share-plugin@0.11.0" has unmet peer dependency "react-copy-to-clipboard@^5.0.1".
```

Digging into those mirador-*-plugins shows they are enabled by default in the Mirador Viewer Settings here:
https://github.com/DSpace/dspace-angular/blob/main/src/mirador-viewer/config.default.js#L173-L176

That implies to me that we might need to undo this PR, unfortunately.

@mspalti: Do you happen to know if we need to include these for Mirador to function properly?  Maybe we need to move these dependencies over to "optional" (as not all sites will be using Mirador)?

**Comment by mspalti** [comment]
There will be a few react dependencies because Mirador, obviously, uses react.

In the case the download and share plugins, these are not required. If we remove them from the default Mirador configuration the viewer will work. We'd need to test that, obviously. The share plugin is sort of a core feature because it's a handy tool for embedding DSpace Manifests on other sites (i.e. the interoperability part of the IIIF framework). But I wouldn't call it essential for an installation that's only concerned with embedding an image viewer in a DSpace Item. For anyone wanting more than this I think they'd want are these two plugins.

btw, It looks like there's a newer version of mirador-share-plugin. We might test that. And perhaps work a bit on fixing the material dependency warnings. In my experience, the missing deps haven't caused problems with functionality.

**Comment by tdonohue** [comment]
@mspalti : Thanks for the verification that removing these dependencies shouldn't be a big deal.  I agree it'd be nice to upgrade any Mirador plugins that we can.

For now, I'm going to refrain from backporting this change as it seems like it may need more testing that nothing "breaks" with IIIF when removing these `material-ui` dependencies.  Once that is verified, we could consider backporting this to 8.x and 7.x (but either would require a manual backport).

**Comment by tdonohue** [comment]
NOTE: I finally got around to fully testing [Mirador / IIIF Integration](https://wiki.lyrasis.org/display/DSDOC8x/IIIF+Configuration) after the removal of these dependencies.   I'm glad to report that Mirador works fine without material-ui or the other dependencies removed in this PR.  I was also able to remove `react` and `react-dom` (both of which are only included for Mirador) in #3553 , and Mirador **still works well**.

That said, I wanted to also note that this will **not be backported to 8.x or 7.x** (which use Yarn instead of NPM).  The reason is that `yarn install` will throw a large number of "unmet peer dependency" warnings when all these Mirador-related dependencies are fully removed.  The better solution for 8.x and 7.x seems to be to move the Mirador-related dependencies all to "dev" dependencies (as they are not needed in production or at runtime).  I've already done that in #3573 (for 8.x), and verified that works best for `yarn install` and Mirador continues to work well.  This same concept will be ported to 7.x as well.

**Pull request merged**
