### PR TITLE
Simple search UI

### PR DESCRIPTION
**Pull request by LotteHofstede**
This PR connects to #136 
The simple search UI was implemented in this PR.
The search UI is split up in two components: search results and the search form

The search results are a list of items found by the search service. The results use the object list component (with pagination) to show all found objects. Special object list elements were created for search results, so hithightlighted values (with markup) are displayed in the search results instead of the default metadata field value.

The search form is the input form on top of the search page. This page can be reused on other pages (for example, I also added it to the home page). The form exists out of a dropdown, where a scope can be selected when available and an input form, where the user can type a search query.

Bootstrap was upgraded to Bootstrap4 beta - there are still be some minor issues with @ng-bootstrap 4 beta - that will hopefully be resolved in the future.

There still seems to be something wrong with the tests, I will try and fix this as soon as possible.

### CODE REVIEW

**Comment by artlowel** [comment]
This PR connects to #140 

That issue has a comment saying we shouldn't upgrade bootstrap now, but rather wait until the css only version is released. In today's meeting discussed it, and decided to upgrade now and [switch to bootstrap-css when it becomes available](https://github.com/DSpace/dspace-angular/issues/154)

**Comment by wwelling** [comment]
@tdonohue I suggest coveralls for coverage report and integration with travis ci build.

https://coveralls.io/

**Comment by artlowel** [comment]
I've looked at the conflicts between the three PRs, and it seems to be it would be easiest to merge this one first, then #152 and then #149

So I propose we merge this without tests, but leave the issue open, and ask @LotteHofstede to add those tests in a separate PR as soon as possible

I have no experience with coveralls, but looking at their site it seems to do the job, so +1 for that

**Comment by wwelling** [comment]
Sounds good to me. I will resolve merge conflicts on #152 as soon as this is merged.

**Comment by tdonohue** [comment]
@artlowel : That plan sounds fine to me. I'll also create a ticket to configure coveralls.  As I do think it's time to start ensuring we are building out specs alongside new code (and adding specs for old code that doesn't yet have it).

**Pull request merged**
