### PR TITLE
Issue#819

### PR DESCRIPTION
**Pull request by atarix83**
## References
* Fixes [https://github.com/DSpace/dspace-angular/issues/819](https://github.com/DSpace/dspace-angular/issues/819)

## Description
This PR fix issue described in [this issue](https://github.com/DSpace/dspace-angular/issues/819) by avoiding that a successful RemoteData is emitted two time, with undefined payload int the first one

## Instructions for Reviewers
To test this PR :
- go to the mydspace page
- open the new submission 
On current main branch scrolling down the list should show an hanging loading icon. With this Pr it should work properly

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
@atarix83 : I agree with @artlowel here. It's unclear to me why the scope of this fix was expanded.

My impression from discussions in meetings was that we all agreed that #819 should be properly fixed by the work going on to resolve #739 (which is scheduled for beta5).  So, we had discussed a simple, temporary fix for beta4 of leaving out the EPerson language for now (and we can add a note in #739 to "undo" that temporary fix).  Is there a reason why you didn't go with that approach? Am I misunderstanding something?

**Comment by atarix83** [comment]
@tdonohue @artlowel 
you're right we have decided to simply leaving out the EPerson language, but I found out a way to finnaly resolve the issue of RemoteData emitted twice and saw this resolved the problem on LocaleService. In addition now when the cache obejct is expired RemoteData is emited as failed when currently is never emitted.
I think that it should be a general improvement, I tested it and it doesn't seem to have impact, but if you prefer to go on with the workaround I'll revert it

**Comment by tdonohue** [comment]
@atarix83 : Overall, I'm not against this change...but it seems like we'd need to carefully test it.   I'm also not entirely certain whether this change will be made "obsolete" once @artlowel 's work on #739 is complete. 

So, I'd appreciate @artlowel 's feedback on how this PR as-is would affect #739....there's a few possible approaches I see here:

1. If we are fairly comfortable that this PR is the correct direction for the long term (and will not need reverting after #739), then let's test it very thoroughly and make sure it has no side effects & then work to merge it.
2. If we feel this PR's implementation has some promise, but needs to be tested more with the work going on for #739, then maybe we should have @artlowel pull this code into his ongoing work & we'll address it as part of the solution to #739.  In that case, we should create a separate PR to solve #819  with just the simple workaround for now.
3. If this seems like it's all just temporary & it'd likely need reverting as part of the solution to #739, then we should simply update this PR to be the simple workaround for now.

@artlowel, do you have any feedback on the approaches above based on the ongoing work to fix #739?

**Comment by artlowel** [comment]
It is just temporary. As detailed in #739, the logic to determine the RemoteData state will move to a reducer and RemoteDataBuildService will drastically change, perhaps not even be necessary anymore. The state of an expired RemoteData object will be "stale".

**Comment by tdonohue** [comment]
Ok, given it'd be temporary, I think we should revert this back to the original idea @atarix83 & just disable the EPerson language temporarily.  You can choose to either update this PR directly, or close it an create a new one.

**Comment by atarix83** [comment]
@artlowel @tdonohue 
I've reverted changes and disabled the EPerson language temporarily

**Review by artlowel — APPROVED** [review]
Thanks @atarix83

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me too. Thanks @atarix83

**Pull request merged**
