### PR TITLE
[#646] Move submission input label, value, required, hint, value-pairs to angular i18n

### PR DESCRIPTION
**Pull request by kshepherd**
## References
* Addresses #646
* Requires DSpace/DSpace#8322

## Description
All form components used by submission in dspace-angular are piped through 'translate'. This PR aims to shift localisation of submission input definitions over to dspace-angular `en.json5` to take advantage of this localisation.

This means administrators will not need to maintain separate `submission_form_xx.xml` forms which are cumbersome to maintain, and keeps i18n labels, hints, required messages in the frontend application with other form localisation. 

This PR is a work in progress. There are some comments in the JSON5 file as this is allowed by the spec, but after an initial review we can change the formatting if that is necessary.

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.

### CODE REVIEW

**Comment by kshepherd** [comment]
I've pushed an update to `dynamic-scrollable-dropdown` template so that the formatted listEnty is piped to translate, which means the Types, Languages and other value pairs can also be i18n'd.
I didn't do this for the value (ie. stored value for value-pairs) though that might be worth it?

I'm pretty sure this won't cause any unexpected translation as the keys used are really long and specific like `submission.section.describe.value-pairs.common_iso_languages.english`

If anyone thinks this could be a problem and if there are other dynamic controls that might need this for working with Controlled Vocabs and Value Pairs please let me know!

**Comment by abollini** [comment]
hi @kshepherd thanks for proposing that, I agree that keep (manually) in sync several `submission_forms_xx.xml` file is cumbersome but the main advantage of these xml files over the i18n is that when the admin make change/add new form these are almost immediately available to the user without the need to rebuild the application. Moreover, it would force other REST client to implement their own i18n for configuration managed by the REST part.
If we want to move these translation to angular IMHO we will need to first define a way to reload the i18n file at runtime on the angular side without the need to rebuild/package the application until then we should at least offer the values provided by the REST side as fallback if no specific i18n key is defined.
An alternative approach could be to modify the structure of the xml file to accommodate all the translation in a single file, this would require a lot of work on the REST side

**Comment by kshepherd** [comment]
This is a good point, I hadn't considering how inaccessible the json5 i18n files are, comparatively. A full rebuild to change a label seems excessive. (This problem applies to all other i18n text, of course, and I think will be a pain for admins)

My reasoning behind moving the translation to Angular is that all the other labels served by the Web UI are handled there. That said, perhaps it's a more simple, maintainable fix here to do some translation at REST before sending the submission data to Angular.

**Comment by tdonohue** [comment]
@abollini and @kshepherd :  another option would be to move these keys to the Messages.properties file on the backend. That file still exists...it's much smaller though as *most* translations occur in the UI.  But, we still do have the need for some backend messages, and that's where they are generally stored: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/resources/Messages.properties

(That said, I'm not sure that solves the issue of making these labels *easily editable*, as that file is embedded in dspace-api.jar by default)

**Comment by kshepherd** [comment]
@tdonohue yep, that's what I was meaning about "translation in REST", use I18nUtil to translate those backend messages before sending submission definition / form data to angular... that seems pretty simple, right? I think that'd still be an improvement over having a different form for each language.

**Comment by mwoodiupui** [comment]
I think that having part of the description of a submission field in the back-end and another part in the front-end is cumbersome.  But abstracting the descriptions to message catalog keys *within the back-end* makes a lot of sense.

Each part of the system should be able to talk about what it knows, and trust the other parts to do the same.  I dislike the idea that multiple front-ends will have to have their own, probably duplicate, explanations of what the back-end wants the user to put into a submission field.  That is:  the back-end should hold the logical design of a form (with labels) and a front-end should render that and provide the behavior.

Putting the labels for form fields into the front-end requires the front-end to know too much about the details of the back-end, since the back-end is in charge of which fields are in the form.  It's too tightly coupled.

**Comment by kshepherd** [comment]
Just a reminder that this PR is not 100% complete from memory, there may still be some keys missing.

Also, given the feedback, I'm not sure that there is much point to a review of the changes.
The related PR in the DSpace backend might still be useful for future work that translates in the backend, instead: https://github.com/DSpace/DSpace/pull/8322

**Comment by tdonohue** [comment]
@kshepherd : I had only left this PR open as I wasn't sure if a final decision had been made.  That said, since it sounds like most of us (who've looked at this PR) lean towards a solution which is *all in the REST API*, I'll close this PR.  So, let's move this discussion over to the backend PR https://github.com/DSpace/DSpace/pull/8322 (and @kshepherd , let us know when you feel that's ready for reviewers to provide more feedback on)

**Pull request closed without merging**
