### PR TITLE
Header Accessibility Fix: Allow enter key or spacebar to expand or contract menu based on current active status

### PR DESCRIPTION
**Pull request by tdonohue**
## References
Small improvement to the fixes to #1167 in PR #1252

## Description
Deque retested those header fixes, and found one issue was only partially fixed. 

* If you use a Keyboard to select the "All of DSpace" menu in the Header, you can open it by pressing "Enter"
* However, once it is open, there is no way to close it using only the keyboard.  

This PR fixes that issue by ensuring pressing "Enter" will open/close that menu based on the current status. 

## Instructions for Reviewers
* Review code changes
* Test keyboard interaction of header menu
    * Tab to the "All of DSpace" menu, press "Enter" (or spacebar).  It should open
    * Click Tab again, reselecting "All of DSpace".  press "Enter" (or spacebar) again. Now it should close.
    * Verify you can still tab to a submenu (e.g. "By Subject") and press "Enter" to go to that browse by page.

### CODE REVIEW

**Review by artlowel — APPROVED** [review]
Thanks @tdonohue! 

This does what it says, and can be merged as is.

But in the admin sidebar menu (and most other places where we added these keyboard commands, e.g. opening and closing the search facets) we made _both_ space and enter do the action, so for consistency it would be good if you could add space as well

**Comment by tdonohue** [comment]
@artlowel : Thanks for the initial review.  Since it wasn't much work, I added support for spacebar as well.  Just as a note though, at least in Chrome spacebar doesn't work as well as Enter key...as click "spacebar" on any menu item scrolls you down to the bottom of the page (while also now opening/closing the menu).  This seems to be the same behavior as on demo7.dspace.org though & I didn't have time to try and debug it (as it seems unrelated to this larger accessibility issue)

**Comment by artlowel** [comment]
@tdonohue @ybnd had that same scrolling issue in a recent PR. IIRC the `$event.stopPropagation()` [here](https://github.com/DSpace/dspace-angular/pull/1295/commits/129ea726e8a3e71adfc589633744faf675070a71#diff-b608a6b35a10eb5c51c7f401ce3d7ac4d0fa97a9a12fde12df5de746df8eb47bR40) fixes that

**Comment by tdonohue** [comment]
@artlowel : Unfortunately, that suggestion doesn't appear to work in this scenario.  I tried it locally, and changed [this line](https://github.com/DSpace/dspace-angular/pull/1315/files#diff-48279e2a621179ca4c764f77abd6a2d66e6885f73fb2b3cf294bbf741a842b85R4) to:
```
(keyup.space)="$event.stopPropagation(); isActive ? deactivateSection($event) : activateSection($event)"
```

That seems to have no effect for me.  I can still open/close the menu using the spacebar, but anytime I do so, it auto-scrolls me to the bottom of the page.

I think there may be a larger issue at play here, as anytime you hit the spacebar while highlighting any part of the header (even just with the header logo highlighted) you are scrolled to the bottom of the page.

So, I think we may want to treat this as a separate issue.  It sounds like some sort of default behavior needs to be changed for the entire header, and it's not specific to this single menu option.  Maybe we simply leave this PR as-is and open a separate ticket about this?

**Comment by ybnd** [comment]
@tdonohue AFAIK "spacebar to scroll down" is the default behaviour for most browsers though, so I think that's to be expected if the components in play here don't override defaults for `keyup.space`?

[On any long page](https://demo7.dspace.org/search?spc.page=1&query=&spc.sf=score&spc.sd=DESC&spc.rpp=40) `space / shift+space` should just work the same as `pagedown / pageup`
I think the only way I know to disable this would be to explicitly handle `space` events for _all_ controls we want to work ~ "space to navigate"...

**Comment by ybnd** [comment]
Quick thought right now: could be that the callbacks in #1295 included `$event.preventDefault` also, [the current ones don't](https://github.com/DSpace/dspace-angular/blob/e5e6e9c07aca19fc4edfb44b18a79e0f8f5742e3/src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts#L39-L67)

**Comment by tdonohue** [comment]
@ybnd and @artlowel : I appreciate the help, but still no luck. I've gone ahead and pushed a commit with what I've tried -- adding both `event.preventDefault();` to the methods and `$event.stopPropagation();` to the `(keyup.space)`.  Still no luck.  Menu still responds fine to spacebar, but I'm also always scrolled to the bottom of the page.

I'm willing to try a few more ideas if you think this should be solveable.  But, at the same time, this wasn't reported as an accessibility bug by Deque (they only reported issues with using the Enter key to open/close menus) -- so, it's really a question of how much time we spend on trying to get spacebar to also work.

**Comment by tdonohue** [comment]
@ybnd and @artlowel :  Found a bit of time to dig into this today.  It turns out it was something simple... `keyup` vs `keydown`.  I stumbled on some hints that most browsers implement the scrolling on spacebar *keydown*.  So, I tried just switching all my code to use `keydown` instead, and it worked.  Both Enter & Spacebar can control the menu & the scrolling no longer occurs.  I *did* have to ensure the component methods call `event.preventDefault();`, but the call to `event.stopPropagation();` was unnecessary (so I removed it).

If one of you could give this a test on your end, I'd appreciate it.  I think it's probably ready to merge now.

**Review by artlowel — APPROVED** [review]
That works!

Thanks @tdonohue!

**Pull request merged**
