### PR TITLE
Community and collection logos

### PR DESCRIPTION
**Pull request by Atmire-Kristof**
This PR adds the possibility to upload a logo to communities and collections.

At the top of the “Edit Metadata” tab on Collection/Community Edit, you’ll find a section for the logo.

If the community/collection doesn’t contain a logo yet, there will be a drop-zone visible where the user can drop a logo into (or use the browse function).
The logo will only be uploaded after the user has finished editing the community/collections and clicks “Submit”. This allows for the user to change their mind and delete the logo before it’s uploaded.

If the community/collection already contains a logo when visiting the edit page, the logo will be visible instead of the drop-zone, with a delete button to the right. Clicking the delete button marks the logo to be deleted (with a danger alert surrounding the logo and button). This hides the delete button and shows an undo button instead.
When submitting the form with a logo marked to be deleted, the logo will be deleted before navigating back to the object's page.

### CODE REVIEW

**Comment by tdonohue** [comment]
@Atmire-Kristof : I gave this some testing today.  The basic upload functionality works, but I noticed a few oddities:

1. When uploading a logo, I was surprised to not see it appear on the "Edit Community" page.  I get an upload succeeded message. But, I don't see the logo appear until I leave the "Edit Community" page and return to the Community view page.  If I then return to the "Edit Community" page, I see the logo there as well.
2. Once a logo is uploaded, I cannot seem to delete it.  I pressed the trash can, and it turns the background red (and I see the undo button). But at that point, the "Submit" button doesn't seem to work. If I leave the page, the logo still exists. 

These behaviors were using AoT compilation (`yarn start`)

**Comment by Atmire-Kristof** [comment]
@tdonohue , I've tried to reproduce your issues, but they work fine on my end. Unsure what could cause these.

1. When uploading a logo, it should automatically redirect the user to the community or collection page. Something is causing you to stay on the edit page for some reason, where the old community or collection is still cached, and thus not updating for you.
2. When marking a logo for deletion, I am able to click the submit button, which redirects me back to the communtiy or collection's page, as it's supposed to. Again, not sure why the submit button isn't doing that for you.

Maybe try running a `yarn clean install` first, if you haven't already? It could be that you're missing a dependancy that's indirectly causing these issues.

**Comment by tdonohue** [comment]
@Atmire-Kristof : I've retested today, and both the issues that I previously noted seem to be resolved now.  However, the behavior that @artlowel initially noted seems to have been reverted.  I expected that after dragging & dropping an image, it would immediately upload & appear.  However, it just gets queued...and the upload doesn't occur until I press the "Submit" button.   I think that behavior is a little odd. But, honestly, this works...it just seems like a usability issue (as I expected the drag and drop to immediately trigger an upload)

**Comment by Atmire-github** [comment]
As Kristof is out sick, I tried to solve the merge conflicts for him, but the first time I started from an outdated branch. That’s why I force pushed.

**Comment by PhilipVis** [comment]
As Kristof is out sick, I tried to solve the merge conflicts for him, but the first time I started from an outdated branch. That’s why I force pushed

**Pull request merged**
