### PR TITLE
Italian language

### LINKED ISSUE #1917: Italian translation - i18n language files
Add the support to the Italian language and create the `it.json5` language file

### PR DESCRIPTION
**Pull request by davide-negretti**
## References
* Fixes #1917

## Description
* Italian language support
* First bunch of translations

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by davide-negretti** [comment]
@tdonohue most of the labels have been translated. If that's ok, I will keep updating this branch until DSpace 7.5 has been released.

**Comment by davide-negretti** [comment]
@tdonohue I would move this PR to the next release so that we can improve the translations in the meanwhile

**Comment by tdonohue** [comment]
@davide-negretti : Just an FYI, it looks like this PR is failing `yarn lint` as there are extra spaces after some of your i18n keys in `it.json5`.  

Once you feel this is ready for review, please ping me.  I'd be glad to add this into 7.6 if we can get it ready in time.  Keep in mind, it doesn't need to be perfect, even a partial translation into Italian is a good start & we can improve upon it in future PRs.

**Comment by davide-negretti** [comment]
@tdonohue i fixed the lint issues. I noticed that the tests depend on the environment: they pass on GitHub, whose locale is 'en', but they do not pass on my machine, whose locale is 'it'. I won't be able to fix them today.

**Comment by davide-negretti** [comment]
@tdonohue i fixed the lint issues. I noticed that the tests depend on the environment: they pass on GitHub, whose locale is 'en', but they do not pass on my machine, whose locale is 'it'. I won't be able to fix them today.

**Comment by tdonohue** [comment]
@davide-negretti : I suspect the bug you are seeing with running tests in Italian is that some tests are verifying *English text* is being displayed. So, I don't think this is a bug in your PR.  I think this might regular a separate ticket to analyze if there's a way to fix our tests so that they are no longer dependent on English.  Or, alternatively, we may need to find a way to force tests to always run with English even if the locale is set to something else.

So, I think this PR is good as-is. I'll try and give it a quick test today or Monday & then get it merged if it's working for me.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @davide-negretti !  I tried this out today, and it's working well.  I'm going to merge this as-is because I think it's already a big step forward.  You are welcome to submit a follow-up PR later on if there's any more additions you'd like to make.

As noted, I think the test issue you mentioned should be logged as a separate bug.  I don't believe it's specific to Italian....and it likely won't work right for any non-English language.

**Comment by davide-negretti** [comment]
Thank you @tdonohue. I found that tests failed because they were designed assuming that Italian language did not exist in DSpace and English would have been used as a fallback language:

```
src/app/core/locale/locale.service.spec.ts

✖ should return the default language if the cookie language does not exist
Error: Expected 'it' to be 'en'.

✖ should return the default language if the cookie language is disabled
Error: Expected 'it' to be 'en'.
```

I managed to fix the issue and I created a new PR on the same branch

https://github.com/DSpace/dspace-angular/pull/2249

**Pull request merged**
