### PR TITLE
Improved UX when using navbar on 800px screen resolution

### LINKED ISSUE #1393: Navbar menu issue on screen with 800px width
**Describe the bug**
The search feature in the navbar is problematic in screen with a width around 800px, At such size, attempt to use the search will result in overlapping between the query input and the other navbar links. The issue becomes more evident if more links are put in the navbar or a wider logo is used

**To Reproduce**
1. set the screen size at 800px
2. open the home page
3. try to search using the navbar

**Expected behavior**
the query input should happen in a modal box, overlay at the middle of the page or in a new line under the current navbar so that it will not interfere with any other navbar entry.
This could help in addressing the need expressed in https://github.com/DSpace/dspace-angular/issues/695 as we can think about a radio button that would allow the user to choice between a global search and a search in the current community/collection

**Related work**
https://github.com/DSpace/dspace-angular/issues/695

### PR DESCRIPTION
**Pull request by corrad82-4s**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #1393 

## Description
Added an overlay over the header menu to make sure that the search input is always visible with good contrast.
When the search input is expanded, the background(options and logo) is blurred and when it is collapsed it will un-blur the background.

## Instructions for Reviewers

Reduce screen resolution to 800px and check that Search bar overlaps is not as in the screen reported in issue description, with bar overlapping Logo.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@corrad82-4s : Tested this today, and overall it works for small screens.  But, I'm not sure if we should have the same behavior on larger screens

Here's what I see on a small screen (800px width):
blur-small

That looks reasonable, as it needs to blur the header because the search box overlaps some of the header's navbar options.

However, it looks like that same blur happens on very large screens:
blur-large

In this scenario, I feel the blur looks odd, because the search box doesn't get anywhere near the other navbar options.  It seems unnecessary.

While I'm not against this design, I wanted to ask whether we should consider only enabling this blur for smaller screens (or if there's some other way to tell that there likely would be an overlap occurring)?   I'd also be interested in @artlowel 's opinion on this PR.

**Review by artlowel — CHANGES_REQUESTED** [review]
Thanks @corrad82-4s

I agree with @tdonohue, the blur looks strange. It think really the only change needed is [the line that makes the search box no longer transparent](https://github.com/DSpace/dspace-angular/pull/2015/files#diff-c1c0344b04a41f0ef57562ec7427941d765420381a9aa992b5f780ab07a40930R3). All the rest is superfluous in my opinion

**Comment by davide-negretti** [comment]
Hi @tdonohue @artlowel 

I changed the code so that the blur is enabled for medium screens only. This is right above and right below the breakpoint:

image

image


This is without blur:

image

Which version do you prefer?

**Comment by artlowel** [comment]
I prefer the version without the blur

**Comment by davide-negretti** [comment]
Hi @artlowel, I created a new pull request #2074

**Comment by tdonohue** [comment]
Closing, fixed/replaced by #2074

**Pull request closed without merging**
