### PR TITLE
Fix "Edit Group" page always requests all member Subgroups & EPersons

### LINKED ISSUE #2512: "Edit Group" page always requests all member subgroups and EPersons. This has bad performance for large groups.
**Describe the bug**
Related to https://github.com/DSpace/DSpace/issues/9052

"Edit Group" page always requests all member subgroups and EPersons. This has bad performance for large groups.

The Angular UI includes code which requests *every EPerson in a Group* or *every Subgroup in a Group* in order to determine whether a given EPerson or Group is already included in a given parent Group.

For example:
* `isMemberOfGroup` in `members-list.component.ts`: https://github.com/DSpace/dspace-angular/blob/main/src/app/access-control/group-registry/group-form/members-list/members-list.component.ts#L216C1-L233C3
* `isSubgroupOfGroup` in `subgroups-list.component.ts`: https://github.com/DSpace/dspace-angular/blob/main/src/app/access-control/group-registry/group-form/subgroup-list/subgroups-list.component.ts#L138-L159

This behavior is used to determine whether to display a Remove or Add button in the "Add EPeople" and "Add Subgroups" section of the "Edit Group" page.  See circled content below.

image

**To Reproduce**
1. Login as an Admin.  Open your browser's DevTools
2. Go to Access Control and click on Groups.
3. Edit a Group that has members (either EPerson or SubGroup)
4. Verify your DevTools shows a request similar to one of these:
    * `/server/api/eperson/groups/[uuid]/epersons?page=0&size=9999`  (if the group you are editing has Eperson members)
    * `/server/api/eperson/groups/[uuid]/subgroups?page=0&size=9999`  (if the group you are editing has subgroup members)

The `size=9999` tells the REST API to return up to 9,999 results on the first page.  This essentially disables pagination, unless there are 10,000 or more results.

**Expected behavior**
The User Interface should never send a request to load all objects at once.  This should be redesigned to no longer need to load every object at once.

**Related work**
Directly related to https://github.com/DSpace/DSpace/issues/9052  (However, this ticket describes improper behavior in dspace-angular, while 9052 describes improper behavior in the backend)

### PR DESCRIPTION
**Pull request by tdonohue**
## References
* Fixes #2512
* Requires DSpace/DSpace#9125 (which provides the new `isNotMemberOf` REST endpoints required by this PR)

## Description
Refactors the "Edit Group" (`/access-control/groups/[:uuid]`) code to no longer have major performance issues for very large Groups (i.e. groups with many members).

This requires the following:
* Replaces all general search() methods across EPerson and Group objects with calls to `isNotMemberOf` REST Endpoints. These endpoints will only return objects which are *not already a member of* the current Group.
* Removes all methods in Angular UI which attempted to determine group membership (e.g. isSubgroupOfGroup() in subgroups-list.component.ts, and isMemberOfGroup() in members-list.component.ts).  No longer needed as `isNotMemberOf` endpoint solves this problem.
* Removes unnecessary code complication required to determine group membership.  For example, `EpersonDtoModel` is no longer needed in `members-list.component.ts` as it was only necessary to store `memberOfGroup` information.  That info can also now be removed from `eperson-dto.model.ts` as well.
* Updated all specs to align with the new code.
* Fixes several bugs found along the way on the "Edit Group" form:
    * When editing a Group associated with a Community/Collection, the information about the Community/Collection could end up duplicated many times on the "Edit Group" form. Fixed in 8ee2eb9aa96578b4eca07c2f40f015b14a662af1
    * Fixed several scenarios where "Edit Group" form page would reload entirely after running a new search.  This would cause the page to scroll to the top after you clicked search.  (Not all scenarios could be fixed...this scroll to the top still occurs if you click to the next page of results.)  Fixed in 4edddb8f09775b63084ebb6e86af685ef55f4db5 and bf6d77fefd1394c1dbbeff7476f81b8989386e6c

## Instructions for Reviewers

* Requires installing DSpace/DSpace#9125 
* Fully test the "Edit Group" form (Login as Admin -> Access Control -> Groups -> Click Edit button next to a group)
    * Overall form behavior should be unchanged.  Should be able to add/remove members to the Group (both subgroups and EPersons).  Should be able to search/browse those members and use pagination.
    * A few form "features" were removed from the "Edit Group" form
        * Both the "Add EPeople" and "Add Subgroup" sections will now ONLY show results that are **not currently members**.  That means, when you perform a search in either section, you should never see current members of the group, or the group itself.  This also means this search results section will never have "Remove" buttons, just "Add" buttons.
        * "Add EPeople" searchbox no longer has a dropdown to select searching across "Metadata" or "Email".  The searchbox now automatically searches across **both**, but there is no longer a way to select only searching one.  (This change was necessary to align with `isMemberOf` endpoint behavior).
    * A few bugs were fixed:
        * If you edit a group associated with a Collection or Community (i.e. named `COLLECTION_*` or `COMMUNITY_*`), the community or collection name will only appear on the Edit Group form **once**.  Previously, there was a bug where it would be duplicated sometimes after you added or removed members to the group or preformed a search (especially for subgroups).
        * If you click on Search or Browse in either the "Add EPeople" or "Add Subgroup" sections, the page will no longer reload on every search.  (NOTE: It will still reload if you click on a new page of search results though)

### CODE REVIEW

**Review by atarix83 — APPROVED** [review]
thanks @tdonohue 

I gave it a try, the code looks good and it generally works good. I tried to add/remove members to/from group and the browse eperson list is updated according to the operation done

**Review by artlowel — APPROVED** [review]
Thanks @tdonohue!

It all works better than it did before

There's one strange thing though: if you edit a group, you'll see the search box to search for new members, and directly below it the current members of the group

If you then delete a member of the group, all of a sudden the results pop up underneath that new members search box. While by default they'll only show if you actually search. That's a bit disorienting

I think the easiest way to fix that is to already show those results when you first load the edit page. That's the way we do it for the other search interfaces in dspace too.

However if you don't have time to address this now, this PR is already an improvement and can be merged as is

**Comment by tdonohue** [comment]
@artlowel : I was able to reproduce the "strange" behavior you mentioned, and I agree that it'd be better to initialize the page with the search entries already there.   So, I've rebased this PR and pushed up a single new commit (9117ac0) which does two things:
* Adds the initial search to ngInit() for both EPeople and Groups sections
* Reorders the "Edit Group" page to list the "Current Members" section **before** the "Add Members" section (for both EPeople and Groups).  This order makes more sense to me if we are already showing search results on page load, as it makes it easier to see the "Current Members" instead of first showing a list of people/groups to add (which you'd have to scroll past to see "Current Members").  Here's as screenshot of the slightly updated layout:
edit_group_reordered

If you have a chance to give this a quick look tomorrow (Friday), I'd appreciate it.  I think the slightly updated layout makes the most sense for this new behavior, but would appreciate a second opinion.

**Review by artlowel — APPROVED** [review]
Much better

Thanks @tdonohue!

**Pull request merged**
