### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by atarix83**
This PR connects to [47](https://github.com/DSpace/dspace-angular/issues/47)

### CODE REVIEW

**Comment by artlowel** [comment]
Since the wrappers and the main components are part of app.component, I'd move the css you added to `main.scss` to `app.component.scss`

**Comment by artlowel** [comment]
Also, instead of prefixing the footer css with `/* just for demo */` I'd try to take it a step further in the right direction, by using variables as much as possible.
e.g. https://gist.github.com/artlowel/76bc90d2722fbe4ee2e2576bf718ee54
That way it'll be easier to theme later.

**Comment by artlowel** [comment]
LGTM

**Comment by sourcedump** [comment]
Good also for me!

**Comment by wwelling** [comment]
```
+.inner-wrapper {
 +  flex: 1 1 auto;
 +  flex-flow: column nowrap;
 +  display: flex;
 +  min-height: 100vh;
 +  flex-direction: column;
 +}
```
I don't think there should be a fixed min-height.

**Pull request merged**
