### PR TITLE
Fix DSO 404 pages

### LINKED ISSUE #865: When a DSO doesn't exist, we should show the 404 component.
**Describe the bug**
If the id for a DSO can't be found you don't see the 404 component, instead the page will be broken.

**To Reproduce**
1. enter the url of a community, collection or item page with a UUID that doesn't exist

**Expected behavior**
You should see the 404 component. The URL should still be the one you entered.

I expect this will take **4h** to fix.

### PR DESCRIPTION
**Pull request by Atmire-Kristof**
## References
This PR closes #865 

## Description
This PR refactors the resolve method of `DSOBreadcrumbResolver` to let RemoteData objects through containing an error response. This avoids the resolver blocking 404 pages from loading.

## Instructions for Reviewers
Changes made:
- Replaced `getSucceededRemoteData()` with `filter((rd) => hasValue(rd.error) || hasValue(rd.payload))` and `take(1)`
- Modified the map in this pipe to return undefined if our payload is empty

How to test:
- Visit a page for a DSpaceObject with a UUID that doesn't exist (e.g. community/collection/item pages). The page should display a 404 instead of an infinite loading indicator.
- Visit a page for an existing DSpaceObject and make sure the changes haven't broken any of the existing functionalities (mostly the breadcrumbs)

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
NOTE: For some reason `codecov` status on this PR never was synced back into GitHub.  However, it's available at https://codecov.io/gh/DSpace/dspace-angular/pull/891 -- and it shows that this PR passes, with an extremely slight decrease in coverage of 0.01%.

**Review by tdonohue — APPROVED** [review]
@Atmire-Kristof and @artlowel : The behavior of this PR is *better* than current `main`...but, I'm still able to produce some non-404 behaviors. 

Here's what works:
* If I access any Community/Collection/Item that exists & change *one digit* of the UUID, then I see a resulting 404 page & a 404 response.
* If I create a dummy URL with invalid subpaths, like http://localhost:4000/items/not/a/valid/path that also works.

Here's what does NOT work:
* If I enter in a completely random string (i.e. something that is not a valid UUID, like http://localhost:4000/items/aasdfasdfasdfsdaf or http://localhost:4000/items/notvalid), then I get a page that says "Error fetching item" and the REST API backend responds with a 401 Unauthorized message.

So, overall, the behavior of this PR shows improvements, as I no longer see a "Loading..." message for invalid paths.  But, I expected all invalid URL paths to send me to the 404 page.

Overall, I've given this a 👍 as it's better behavior than currently.  However, if the issue I've found is easy to add to this PR, it seems like a good opportunity to do so.

**Comment by artlowel** [comment]
@tdonohue we added a fix for that issue, but since we already have a 401 error page we redirect to it rather than 404 when rest returns a 401. If that's not desired then I think it makes more sense to change the status code on the rest side

**Review by tdonohue — APPROVED** [review]
👍 Thanks @Atmire-Kristof and @artlowel .  This looks good to me now. I've retested, and now see both a 404 and 401 page (depending on which is thrown by the backend).

**Pull request merged**
