### PR TITLE
Fix issues with meta tags

### LINKED ISSUE #1197: Several minor SEO issues in HTML `<meta>` tags
**Describe the bug**
There are 5 minor issues in our HTML `<meta>` tags at this time.  I decided to copy them all into a single ticket as they are most easily tackled by one person.  All of these issues appear to be in our [MetadataService](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/metadata/metadata.service.ts) which generates these tags.

1. The `citation_pdf_url` has incorrect logic as it requires the bitstream be PDF format.  Google Scholar previously told us to change that logic in [DS-1483](https://jira.lyrasis.org/browse/DS-1483) and then update it in [DS-3127](https://jira.lyrasis.org/browse/DS-3127) -- better logic for 7.x is listed below.
2. The `citation_abstract_html_url` often points at localhost URLs (as it uses the `ui` settings in your `environment.*.ts`)  This is reproducible on the demo site, e.g. https://demo7.dspace.org/entities/publication/3149d355-7c13-4abb-8537-1852c181d9b2 (use "inspect" on the page).
3. The `og:title` and `og:description` tags should be removed. These are hardcoded to reference DSpace (in general) and are unnecessary at this time since we don't support other "open graph" meta tags.  Plus we already have a "generator" tag to specify that the site is DSpace.
4. The `citation_date` tag should be renamed to `citation_publication_date` as that's the new tag that Google Scholar uses. See also https://scholar.google.com/intl/en/scholar/inclusion.html#indexing
5. Add `citation_publisher` tag to list the value of `dc.publisher` (if field exists)

**Expected behavior**

1. The `citation_pdf_url` should use the following logic (based on the two old JIRA tickets above):
    * Create a whitelist of preferred formats.  Per old JIRA ticket  [DS-3127](https://jira.lyrasis.org/browse/DS-3127), those formats should be:
        * application/pdf (PDF)
        * application/postscript (PS)
        * application/msword (DOC)
        * application/vnd.openxmlformats-officedocument.wordprocessingml.document  (DOCX)
        * text/richtext (RTF)
        * application/epub+zip (EPUB)
    * If the Item has one bitstream (in ORIGINAL bundle), add it to `citation_pdf_url` (regardless of format -- this overrides the whitelist)
    * If the Item has more than one bitstream, but the ORIGINAL bundle has one flagged as *primary*, add it to `citation_pdf_url` (regardless of format -- this overrides the whitelist)
    * If the Item has more than one bitstream, and none are flagged as *primary*, look for the **first bitstream** matching any of the preferred formats above.
2. The `citation_abstract_html_url` should not use the `environment.ui` settings. It likely can just use the value of `dc.identifier.uri` (which is the handle or public URL stored in metadata).  If that value isn't found, it could be built similar to the `citation_pdf_url`.
3-5 are self explanatory

### PR DESCRIPTION
**Pull request by ybnd**
## References

* Fixes #1197

## Description

Implement Google Scholar review suggestions for meta tags

## Instructions for Reviewers

The following meta tags were changed:

* `citation_pdf_url`: select Bitstreams ~ MIME type allowlist (if more than one option and no primary in ORIGINAL Bundle)
* `citation_abstract_html_url`: use `dc.identifier.uri` if available, fall back to current URL
* `citation_publisher`: use `dc.publisher` (except dissertations & tech reports, those use other tags)
* `citation_date` → `citation_publication_date`
* Remove `og:title` and `og:description` meta tags

#### Testing

1. Open some Item pages and inspect the `head > meta` in their HTML 
   * [ ] `citation_abstract_html_url` should not contain links to localhost, but should contain links ~ the Item's handle `dc.identifier.uri` is filled out. Otherwise, it should match the Item page URL
   * [ ] `citation_publisher` should be present if `dc.publisher` is filled out
   * [ ] `citation_publication_date` should be present
   * [ ] The following meta tags should _not_ be present: `citation_date`, `og:title`, `og:description`

2. For Items with one ORIGINAL Bitstream
   * [ ] `citation_pdf_url` should contain a link to that Bitstream
3. For Items with more than one ORIGINAL Bitstream
   * [ ] If a primary Bitstream is specified, `citation_pdf_url` should link to it
   * [ ] Otherwise, `citation_pdf_url` should contain a link to the first ORIGINAL Bitstream with one of these MIME types

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by ybnd** [comment]
@art @tdonohue LGTM & unit test fix incoming

**Review by tdonohue — CHANGES_REQUESTED** [review]
@ybnd : Overall, this fixes the issues you've described, but I've noticed an odd caching issue when testing with this PR.  It seems the `<meta>` tags don't always refresh when you browse to a new page.  Here's what I'm doing:
1. Start on a Community page, click on a Collection, then on an Item. Select "Inspect" in your browser and look at the `<head>` section.
    * You'll see a `<meta property='title'>` with the Collection Name and a second with the Item name.
    * You'll see a `<meta property='citation_title`>` with the Collection Name and a second with the Item name.
    * All other `<meta>` tags for the Item will be there though, which is correct.
2. Click back to the Collection. Select "Inspect" in your browser and look at the `<head>` section.
    * The Item `<meta>` tags (from step 1) are still visible. They seem to be cached, as they obviously shouldn't appear on a Collection.
3. Click on a different Item in the same Collection. Select "Inspect" in your browser and look at the `<head>` section.
     * Now, `<meta>` tags are still odd...Some still appear from the first Item (from step 1) while others are correct for the Item you are on.


Overall, the behavior I'm seeing almost seems like a caching issue...like these `<meta>` tags are not being entirely "reset" (to empty) when you browse to a new page, and this results in very odd behavior.  (**NOTE** This caching issue doesn't appear to be specific to this PR...as I can also sometimes get it to occur on demo7.dspace.org.  So, if you'd rather treat this as a separate bug, we can do so.  Besides this bug, the rest of the behavior of this PR seems correct.)

**Comment by ybnd** [comment]
> @ybnd and @artlowel : Overall, this fixes the issues you've described, but I've noticed an odd caching issue when testing with this PR. It seems the `<meta>` tags don't always refresh when you browse to a new page

@tdonohue @artlowel  After a bit of poking around on the current demo7.dspace.org I only ever saw the `<title>` meta tag change, and not even consistently. 

Looks like [this `distinctUntilKeyChanged`](https://github.com/dspace/dspace-angular/blob/425f530f087eba079e12223109b23d9d1a55187d/src/app/core/metadata/metadata.service.ts#L106) filters out way more changes than it should, e.g. when going back/forward between a Collection & an Item I see the DSO change in that pipe but it doesn't pass that filter... not sure what that's about.

**Comment by artlowel** [comment]
@tdonohue and @ybnd I fixed the issue. The reason was not only the distinctUntilKeyChanged issue @ybnd mentioned, but the fact that the responded both to the route changing, and calls for DSO page components initializing. With the second call often starting before the first had finished processing, resulting in unexpected results.

I fixed it removing the calls on DSO pages, and only listening to route changes, that's possible now (but wasn't when the metadataservice was originally written) because we're using resolvers on those pages, and they all put the resolved object in the dso property in the route data. 

I spent an additional **4 hours** on this though, most of that not on the solution itself, but on the tests. They were basically integration tests in a unit test file. Didn't mock anything which caused them to break with the slightest change. I practically had to rewrite them from scratch, getting rid of anything that isn't strictly necessary for the test.

**Comment by tdonohue** [comment]
Thanks @artlowel . I'll add 4 hours to the original ticket and re-test this as soon as possible.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@artlowel & @ybnd : I retested today.  With @artlowel 's updates, the behavior seems *improved*, however, I'm still seeing the `citation_author` field (and seemingly *only that field*) be cached between pages.  Here's what I'm doing:

1. Running `yarn start`
2. Bring up UI.  Immediately do `inspect` and open up the `<head>` section in a separate window
3. Now, in the UI, browse to an Item. I see the `<meta>` tags auto-refresh in my "inspect" window.
4. From that Item page, click on the Collection in breadcrumbs.  Most `<meta>` tags auto-refresh, but the `citation_author` tags from Item still exist from the previous page.
5. Click on Community in Breadcrumbs. Again, most `<meta>` tags auto-refresh, but the `citation_author` tags *still exist* from Item.

Last time I tested, I saw this behavior across the `<meta property="title">` and `<meta property="citation_title">` tags...that bug seems fixed. But somehow the behavior still exists for `citation_author`.  Is there something in the UI that could be **caching** the author names themselves?  It's odd that this specific field is now the issue.

Overall, again, I'm in favor of this PR.  I'd just really like to find a way to improve SEO by ensuring we always have accurate `<meta>` tags.  If you both feel this final bug needs to be a separate ticket, we can split it out...but I'd still rate it as high priority for 7.0.

**Comment by ybnd** [comment]
@tdonohue Should be fixed now 👍

**Review by tdonohue — APPROVED** [review]
👍 Perfect! Thanks @ybnd and @artlowel !  This is now working perfectly for me & is ready to be merged. Thanks for tracking down what was going on with the `meta` tags!

**Comment by tdonohue** [comment]
Merging this immediately, as it was previously discussed as `1 approval` in meetings (it includes a large number of refactored/updated specs), and I'd like to get it in place for final quick tests from Google Scholar.

**Pull request merged**
