### PR TITLE
Duplicate Detection ported from DSpace CRIS 7 Angular

### PR DESCRIPTION
**Pull request by kshepherd**
This pull request ports the Duplicate Detection framework from DSpace CRIS 7 into DSpace.

*Attribution: Ported from DSpace-CRIS and extended by The Library Code with support of Technische Universität Berlin*

DSpace Backend PR: https://github.com/DSpace/DSpace/pull/8415
REST Contract PR: TBD

**One outstanding issue**
_For a new submission, the default behaviour when no matches are found should be to keep the section hidden, but instead, the default message indicates that decisions are all registered._
Fixed, see comment https://github.com/DSpace/dspace-angular/pull/1732#issuecomment-1211459672

**To test**
- Make sure both the dspace-angular and DSpace PRs are applied
- Enable the ‘dedup’ event consumer in dspace.cfg and add the ‘detect-duplicate’ step to a submission process in item-submission.xml
- For best results, configure autosave on the dc.title field and any others you’re planning to test (eg. dc.identifier.doi, dc.identifier.isbn or so on). This means that whenever a change is saved to dc.title, the duplicate detection section will update with a new list of potential matches
- Submit an item to a collection with the detect-duplicate step enabled. Enter some text in the title so that 

**Notes for PR reviewers**
- There is a new ‘dedup’ table in the database, this should be added by flyway
- There is a new ‘dedup’ Solr core
- The ‘dedup’ consumer is not in the default event consumers by default, so it’ll need to be added for practical testing
- The fuzzy search signature is commented out of the deduplication.xml spring config by default, so uncomment that to test fuzzy matches (the default MD5 signatures for exact metadata matches still work)

**Notes for 4Science devs (regarding changes from CRIS)**
- SearchDeduplication was renamed to DeduplicationPluginService as that seemed more fitting to what it actually does
- tmpMapFilter, tmpFilter, other similar names of maps and lists were renamed to suit their purpose (eg. signatureSearchFilters)
- A lot of unused methods, variables, classes were stripped out during the port to keep code lean and easier to review. If some were partial implementations of future work, we can bring them in with a subsequent PR

As I’ve added an authorization check (configurable, enabled by default) so that the user needs read access to each item in the potential matches list, I manually disabled it for some integration tests and leave it for others, and explicitly test it in a new integration test

I’ve added javadoc and most is pretty straightforward but please correct me if I misunderstood terms such as ‘fake', ‘reader’

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [ ] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by kshepherd** [comment]
I solved the display issue that I had noted in my first PR description. Describing my fix below for reviewers' attention:

There is an action + effect combo “CleanDetectDuplicateSection”. It’s only dispatched when the `parseSaveResponse()` submission effect is called.

I modified the `DetectDuplicateService` so that if the workspace item is undefined when getDuplicateMatches()1 is first called (ie. the angular component is initialised and asking for matches but the sectionData is not fully populated yet), the Clean action is dispatched.

**Comment by artlowel** [comment]
Thanks @kshepherd!

Like [@benbosman on the backend](https://github.com/DSpace/DSpace/pull/8415#issuecomment-1380477718), I'm not assigned as a reviewer on this PR, but I gave it a quick test. A few comments and questions:

- It would be good to have a link (in a new window) to the full metadata page for a potential duplicate. In the list view you only have a handful of fixed metadata fields
- The action buttons on duplicate results are stuck together. I'd add a [bootstrap spacing class](https://getbootstrap.com/docs/4.1/utilities/spacing/) such as `mr-1`, or put them in a [button group](https://getbootstrap.com/docs/4.1/components/button-group/)
- There is a "Submitter decision" field when you look at the workflowitem as an editor, but it seems that if I mark something as a duplicate as the submitter, that duplicate doesn't show up for the editor, and if I mark it as not a duplicate, it shows up but still says "no decision yet". 
- What happens after I've "marked an item to merge" as an editor? Is there a way to merge those items from the UI?

**Comment by pnbecker** [comment]
We are willing to follow this up if it is clear who and when it is being reviewed. We rebased and fixed this PR several times. We would do this one more time if there is a concrete plan how this is being reviewed. We will not rebase again and again until it is clear who and when this will be reviewed. Please ping us or contact us otherwise if you are interested in reviewing it.

**Comment by pnbecker** [comment]
We took a a new simpler and clean approach. Closing this in favor for #2749

**Pull request closed without merging**
