### PR TITLE
PageNotFound Component

### PR DESCRIPTION
**Pull request by LotteHofstede**
This PR connects to #25 

I created a PageNotFound component with a 404 message and a button that redirects to the home page.

The app-routing module was updated to render this component as page content whenever a user is trying to reach a page for which no mapping exist.

This PR is dependent on PR #39

### CODE REVIEW

**Comment by sourcedump** [comment]
Hello! when I try to run a build of your branch I have many of this kind of error:
```
ERROR in [default] /home/nodejs/pera/dspace-angular-nf/node_modules/@types/lodash/index.d.ts:244:12
Duplicate identifier '_'.
ERROR in [default] /home/nodejs/pera/dspace-angular-nf/node_modules/@types/lodash/index.d.ts:244:15
Cannot find namespace '_'.
ERROR in [default] /home/nodejs/pera/dspace-angular-nf/node_modules/@types/lodash/index.d.ts:246:24
Cannot find name 'Partial'.
```
and the build fails. Do you know how to fix this?
Thank you very much

**Comment by artlowel** [comment]
The errors you're getting seem to be caused by using the latest version of lodash, a transitive dependency of this project. 
Since this PR doesn't use npm-shrinkwrap yet, when you run npm install on this branch, you'll get the latest version, instead of the latest compatible version.
I think this problem will go away by merging the latest master in to this PR branch.

**Comment by sourcedump** [comment]
Thanks for the tip

**Comment by sourcedump** [comment]
LGTM

**Comment by LotteHofstede** [comment]
Merged the latest master into this branch, hopefully you can now directly run the branch without any issues.

**Comment by sourcedump** [comment]
Thanks for the merge, I've already done that on my own to give a look to your implementation and all work fine. Thanks.

**Comment by artlowel** [comment]
LGTM, merging

**Pull request merged**
