### PR TITLE
Removed observable function calls from template (part 1)

### LINKED ISSUE #3257: Browser hangs due to infinite loop when editing groups
## Describe the bug
In DSpace v8, there is a bug when editing (access control) groups under certain circumstances (see steps to reproduce). As a result, the browser hangs due to an infinite loop and the target page is never reached.

## To Reproduce
1. Login as admin
2. Go to "EDIT > COLLECTION".
3. Select any collection - e.g. "Statistics > Books"
4. Click on "Assign Roles"
5. Click on any link to edit a group -- if none exists, create one using the UI buttons, in my case on "sandbox.dspace.org" the group is called "COLLECTION_7f052d6e-f7f7-4661-8347-701016969365_WORKFLOW_ROLE_editor".
6. Scroll down to the last section called "Groups" and click any link in the paginated table, for example, the "Administrator" item.
7. **Now an endless loop starts, the browser hangs after a while and the UI gets stuck, the target link is never reached**

While debugging or logging on the console, you can see (at least) in this line - https://github.com/DSpace/dspace-angular/blob/ee7e8358e7e0fd0b69f7c2e308d539670a103026/src/app/access-control/group-registry/group-form/group-form.component.ts#L537 - that this function is called in an infitine loop.

Other click sequences do not necessarily lead to the problem.

## Expected behavior
The click on the link should not lead to an infinite loop.

### LINKED ISSUE #3393: Opening the simple item page of a withdrawn item when logged in as administrator stalls the frontend instance
## Describe the bug
In DSpace 8.x, opening the simple item page of a withdrawn item when logged in as administrator stalls the frontend instance for about 10 to 15 minutes, making it unresponsive, then continues to display the simple item page.

## To Reproduce
1. Login as an administrator
2. Withdraw an item
3. Go the withdrawn item's simple item page, eg. by clicking the item in the breadcrumbs, searching for a withdrawn item in administrative search or because you copied the url beforehand.
4. The whole frontend instance stalls for about 10 to 15 minutes. After that time, the simple item page is displayed.

You can easily reproduce this on the DSpace Demo Website

## Expected behavior
The simple item page should come up immediately

### LINKED ISSUE #3571: Lack of community/collection information when editing a person's access control
## Describe the bug
When editing a person, in the people access control session, in the “Member of these groups:” table, the communities/collections column shows no information.

## To Reproduce
1. Log in as administrator.
2. In the sidebar, go to the access control area and then click on eperson.
3. Edit someone.
4. Notice that the table showing the groups the person belongs to doesn't show any information about the community/collection.

eperson-form-component-table

## Expected behavior
The community/collection column should return some information about the community or collection to which this person has access.

## Related work
I analyzed the code, because in version 7.5 of dspace angular the table returns all the information correctly, but as of version 7.6 the community/collection column returns empty. And there really was a change in the code that made this happen.

eperson-form-component-7-5

eperson-form-component-7-6

### LINKED ISSUE #3612: "Researcher Profile" panel being displayed by default in DSpace 7.6.2 and DSpace 8.0
On the "Update Profile" page, the "Researcher Profile" panel is now showing by default.

This affects both DSpace 7.6.2 and DSpace 8.0.

The documentation for DSpace 7.6.2 (https://wiki.lyrasis.org/display/DSDOC7x) and DSpace 8.0 (https://wiki.lyrasis.org/display/DSDOC8x/Researcher+Profiles) both state:

> The DSpace Researcher Profile feature has been introduced in DSpace 7.3 to support the ORCID Integration work but can be used alone. It is turned off by default and must be enabled manually

## To Reproduce

1) Checkout the "dspace-angular" Git repository, and switch into the directory:

```
$ git clone https://github.com/DSpace/dspace-angular.git
$ cd dspace-angular
```

2) Switch to the appropriate tagged release. The following will use "dspace-8.0", but the issue also affects "dspace-7.6.2":

```
$ git checkout dspace-8.0
```

3) Start the DSpace backend and frontend:

```
$ docker compose -p d8 -f docker/docker-compose.yml -f docker/docker-compose-rest.yml up -d
```

4) Once the DSpace backend has started, create a sample "admin@example.com" user:

```
$ docker exec -it dspace /bin/bash
dspace$ /dspace/bin/dspace create-administrator
Creating an initial administrator account
E-mail address: admin@example.com
First name: Admin
Last name: Admin
Is the above data correct? (y or n): y
Password will not display on screen.
Password: <Type "admin">
Again to confirm: <Type "admin">
Administrator account created
```
1) In a web browser, go to

    http://localhost:4000/

    The DSpace home page will be displayed.

2) Log in as the "admin@example.com" user, with a password of "admin". Accept the "End User Agreement". The home page will again be displayed, with the user now logged in as the "Admin Admin" user.

3) Once logged in, go to

    http://localhost:4000/profile

    The "Update Profile" page will be displayed. Note that the "Researcher Profile" panel is shown in the page.

## Expected behavior

That in a stock DSpace 7.6.2 or DSpace 8.0 build, the "Researcher Profile" panel will *not* be displayed on the "Update Profile" page, because according to the documentation, this functionality is disabled by default.

## Related work

This issue is likely caused by changed made in #2786, in which the following line was removed from the "src/app/profile-page/profile-page.component.html" file in commit 63fa8f39

```
    <ng-container *ngIf="isResearcherProfileEnabled() | async">
```

See <https://github.com/DSpace/dspace-angular/commit/63fa8f39f593193e35446d1335ce37b377847921#diff-c70e502c8e48e56416745c5b689f802158d00a55b41d490f9a88836d4c2b9761L4>

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #3393
* Fixes #3257
* Fixes #3571
* Fixes #3612

## Description
Currently, there are multiple instances where observable function calls are subscribed to directly in the template. This is considered a bad practice, as it cause a new Observable to be recreated each time Angular’s change detection is triggered. Some instances of this issue remain, but I will work on creating PRs to address them over the coming months.

## Instructions for Reviewers
**Guidance for how to test & review this PR:**
- Verify that the 4 linked issues have been resolved
- Verify that all these functionalities still work correctly:
  - EPerson pages
  - Group pages
  - Bitstream Format Registry
  - Metadata Registry
  - A component that uses the pagination component

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [x] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
I'm beginning to wonder if #3584 might be caused by a similar issue.  I'm not confident this PR would fix #3584, but the issue described in that ticket seems similar to the issues fixed by this PR.

Regardless, this is a high priority PR for me to get back to testing.  Hoping to get to it sometime this week.

**Comment by pilasou** [comment]
Hi @alexandrevryghem, @tdonohue,
I have tested the 4 issues that the PR fixes following reviewer's instructions on each issue. All tests passed! I have used DSpace Docker, I was on main branch for Backend and on PR code branch for Angular. 

Results for each issue: 

1. #3393 : the item page displayed nearly immediatly.
2. #3257 : the page is not frozen anymore and the corresponding group page is displayed.
3. #3571 : collection name appears in the table.
4. #3612  : the researcher profile section is not displayed annymore. Note that have not tested what happened if the Research Profile configuration is enabled (i.e Researcher profil section displays on the Profile page).

All those are very welcome fixes with no doubt! Thanks @alexandrevryghem

**Comment by pilasou** [comment]
@tdonohue Following your comment  (https://github.com/DSpace/dspace-angular/pull/3585#issuecomment-2455006448) on the potential impact of this PR against the https://github.com/DSpace/dspace-angular/issues/3584 issue, I have tried to reproduced the bug (on my DSpace Docker install, backend on Main branch) but was not able too. I followed the same step as on the video provided on the issue, I also clic on many different sections (list of collection, collection, item, etc.) but did not encounter the infinite loop bug. This said...more test required!

**Comment by saschaszott** [comment]
@alexandrevryghem , I've merged the changes of this PR into main. The problem that is described in #3584 is _not_ solved. I can safely reproduce the "infinite load" problem in my local dev instance.

**Comment by alexandrevryghem** [comment]
@saschaszott: That's indeed a separate issue, this PR only fixes #3393, #3257, #3571 & #3612

**Comment by saschaszott** [comment]
@alexandrevryghem , thanks! I can confirm that #3393 is fixed by this PR.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  Reviewed and tested this today.  The code looks good to me.  I tested that all 4 bugs are fixed.  I also did some basic testing of the functionality of the EPerson/Group/Metadata Registry/Bitstream Registry, as those are the pages that were modified most significantly.  No issues found, so this looks great to me.

Merging immediately as this has had several testers.  This should be ported to 7.6.x and 8.x (to fix the same bugs there).

**Comment by tdonohue** [comment]
@alexandrevryghem : Could you manually port this to both 8.x and 7.6.x?  It looks like it's too large to port automatically

**Comment by tdonohue** [comment]
Friendly reminder @alexandrevryghem that it'd be good to port this to `dspace-8_x` and `dspace-7_x` as several of the bugs fixed here also occur in those releases.

**Pull request merged**
