### PR TITLE
Migration to standalone components

### PR DESCRIPTION
**Pull request by atarix83**
## References

- See: https://wiki.lyrasis.org/display/DSPACE/DSpace+8+Angular+%3A+library-based+architecture+proposal
- Fixes: #2370

## Description
The goal of this document is to migrate the DSpace Angular application to a standalone components approach.

## Instructions for Reviewers
From a code review perspective the best approach to review this PR is to refer to the dedicated wiki page mentioned below.

From a functional perspective the best approach it to review this PR by running the application (against sandbox rest server) to verify everything works properly as the current sandbox environment.

List of changes in this PR:
See wiki page https://wiki.lyrasis.org/display/DSPACE/Migration+to+Standalone+Components

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@atarix83 : I've just merged the new ESLint rules PR (#2343).  So, if you (or someone at 4Science) can get this PR updated / cleaned up quickly, I'd love to test this early next week (either Monday or Tuesday).  The goal is to get this PR merged quickly to free up the work on upgrading to Angular 16 in #2752

**Comment by tdonohue** [comment]
@AndreaBarbasso : Please make sure to also resolve the merge conflicts in this PR (as I see you've been making updates).  It appears GitHub cannot run any of the automated tests/checks until the merge conflicts are resolved.  Thanks!

**Comment by AndreaBarbasso** [comment]
> @AndreaBarbasso : Please make sure to also resolve the merge conflicts in this PR (as I see you've been making updates). It appears GitHub cannot run any of the automated tests/checks until the merge conflicts are resolved. Thanks!

@tdonohue, sure thing, we should be able to merge the main branch and resolve conflicts by Tuesday.
We would recommend, however, to start checking and testing the PR now, as the migration to the standalone components pattern is already in place and extensive testing is needed!

**Comment by tdonohue** [comment]
@atarix83 and @AndreaBarbasso :  Unfortunately, this missed our "soft deadline" of today (Tuesday). As mentioned in the DevMtg, I'll be out of the office for the remainder of the week.  I'll have to rely on your team and/or @artlowel to **fully test this** as much as possible this week.  When I return on Monday, I hope it can be merged quickly.

In the meantime, please also see if you can start #2752 , as I'm worried that may become more difficult to achieve in time for 8.0 as this PR is running behind.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@atarix83 and @AndreaBarbasso : Overall this looks good and mostly works. However, I've found a number of pages which are slightly broken while testing this. All my tests are done in production mode (yarn build:prod; yarn serve:ssr)

1. Request a withdrawal feature no longer works.
    * Enable it via `qaevents.enabled = true` and `qaevents.withdraw-reinstate.group = Anonymous`
	* Login, and attempt to request a withdrawal on any Item
	* The popup modal will not appear and you will not be able to complete the request.
2. Select Collection popup broken in batch import
    * Login as Admin
	* Go to Import > Batch Import (Zip)
	* Click "Select Collection".  Popup is empty
3. Publication Claim feature no longer loads from Admin Menu
    * Ensure this feature is enabled, and at least one publication claim exists
	* Login as an Admin and go to "Notifications" > "Publication Claim"
	* Page will not load and you'll see errors in your Browser DevTools
4. Admin Workflow page no longer loads
    * Login as an Admin and go to "Administer Workflow"
	* Results will show but titles/authors are missing.  You can only see the buttons
	* You'll also see errors in your Browser DevTools
5. LDN Services page no longer loads
    * Login as an Admin and go to "COAR Notify -> LDN Services"
	* No services will load.  Errors will apepar in your Browser DevTools
6. Item Preview after import no longer loads properly
    * Login as someone with submit privileges
	* Go to MyDSpace, click the Import from external sources button
	* Select an external source and perform a search.
	* Click on import next to a result.  The "Item Preview" popup will appear but all information will be missing from this popup.
	* (NOTE: it's still possible to complete the import. The only bug is that the Item Preview page doesn't show its preview)

Overall, this is looking great and most features appear to be working (at least everything else I've tried).  These are the only ones where I've noticed larger bugs/failures.

**Comment by atarix83** [comment]
thanks @tdonohue for your feedback we'll take a look

**Comment by atarix83** [comment]
@tdonohue  

point 1, 2, 4 and 6 should be fixed, still working on point 3 and 5

**Review by artlowel — CHANGES_REQUESTED** [review]
Thanks @atarix83!

Everything mostly works, but I noticed a few issues, on top of the ones @tdonohue already mentioned:
- On community and collection homepages the active tab is no longer highlighted
- In search results and list items, the "metadata only" and "open access" badges are no longer shown (e.g. see the publications section on https://sandbox.dspace.org/entities/project/3329a278-2719-4bae-a5d5-d2039afc2fe2, or the results at: https://sandbox.dspace.org/search?query=test)
- The edit relationships tab crashes on items that have relationships (e.g. https://sandbox.dspace.org/entities/publication/8dfe7be1-77d3-440f-8b67-003dd6e7d90e/edit/relationships)
  - The console shows the error: Cannot read properties of null (reading 'getRenderTypes')

**Review by tdonohue — APPROVED** [review]
👍 Thank you @atarix83 !  I've verified that all the prior issues are fixed.  I've not noticed  any new issues. This looks good to me now.  Merging immediately to free up work on #2752

**Pull request merged**
