### PR TITLE
Fix router-outlet destroy issue

### LINKED ISSUE #1544: Search for a ePerson or Search for a group in the resource policies page doesn't work
**Describe the bug**
When adding a new resource policy to dspace object, it's not possible to Search for a ePerson or Search for a group.
Also, the Browse All button doesn't work and it's not possible to browse through the lists of ePersons and Groups by using the next page buttons.

**To Reproduce**
1. got to Edit item page
2. by the status tab click on Authorizations 
3. click on Add
4. Then try to use tha pagination to navigate the eperson/group list, or try to use the search and browse all buttons

**Expected behavior**
The pagination, search and browse functionality should work properly

### PR DESCRIPTION
**Pull request by atarix83**
## References
* Fixes #1544

## Description
This PR fixes problems reported in the issues by avoiding the router-outlet in the root.component is destroyed every time the full page loader is displayed (more detail here https://github.com/DSpace/dspace-angular/issues/1544#issuecomment-1056843963) 

## Instructions for Reviewers
Follow steps described in the issue #1544 and check the problems no longer occur

List of changes in this PR:
* use display none instead ngif to hide outer-wrapper
* full screen loader is used only for theme changing and authentication loading  

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@atarix83 : I tested this today and it's not working for me at all in production mode (`yarn build:prod; yarn serve:ssr`).  With this PR, when I login as a Site Admin, most of the Admin sidebar is missing. Here's a screenshot of what I see:
admin-menu

As you can see most of the admin tools are now gone.  I'm not sure what is going on here, as no errors appear in the Console and all responses from the REST API are 200 OK.  So, it must have to do with the changes to root or app components in this PR.

**Comment by atarix83** [comment]
@tdonohue 

problem with sidebar menu should be fixed now, could you review it again?

**Comment by tdonohue** [comment]
@atarix83 : This PR now appears to have merge conflicts. Could you get them resolved please?  It appears they came about when you pushed your last commit... so maybe your branch just isn't updated to the latest `main`?

**Review by tdonohue — APPROVED** [review]
👍 Thanks @atarix83 !  This is now working for me.  I've verified that it fixes the bug in #1544.  I've also tested configuring multiple themes (e.g. one global theme & a different one for a single community) just to verify theming is still working -- and it is.

So, I think this is ready to merge!

**Pull request merged**
