### PR TITLE
Kazakh Translation

### PR DESCRIPTION
**Pull request by myrza1**
Create Kazakh Translation

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #[issue-number]
* Requires DSpace/DSpace#[pr-number] (if a REST API PR is required to test this)

## Description
Our libraryan staff has translates at Science Library of [KATU](https://library.kazatu.kz/)

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

List of changes in this PR:
* First, ...
* Second, ...

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [ ] My PR doesn't introduce circular dependencies
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@myrza1 : Apologies for the delayed review! 

I was just testing this today.  While it looks like there are *some* Kazakh translated keys, I'm still seeing that nearly half the text is just English.  So, when I install this translation, most of the headers/pages (including Login, Search, etc) all still appear as English text. 

Would you have time to finish this translation in the near future?  Once it's finished, I'd gladly help re-test this so that we can add the Kazakh translation to the next version of DSpace 7.x.  Thanks!

**Comment by myrza1** [comment]
Is admin section should be Kazakh if admin guy undersand English or not? we would like to miss admin section

**Review by tdonohue — COMMENTED** [review]
@myrza1 : Thanks for your Kazakh translation!  I tested this out today, and it looks good to me (I used Google Translate to verify the translations seem accurate).

However, I did find a few minor issues:

1. It looks like you created the translation as a file named `kz.json5`... but, `kz` doesn't appear to be the Kazakh language code.  It looks like Kazakh either uses the language code `kk` (for the general Kazakh language) or `kk-KZ` (for the Kazakhstan version of Kazakh).  So, I think this file should be renamed either `kk.json5` or `kk-KZ.json5`, based on which version of Kazakh you've provided.
2. Finally, in order to enable this language by default in DSpace 7, I need to know what text to put in the language selector dropdown.  Should it be listed as "қазақ" in the language dropdown?  Or is there a better label for the Kazakh language?

Overall, I think this is nearly ready to be merged.  I just need your advice on those two minor issues, and then we can make sure this is added to the next release of DSpace 7.  Thanks again!

**Comment by tdonohue** [comment]
@myrza1 : I just wanted to ping you one last time to let you know we are finishing up the 7.4 release in the next 2 weeks.  If you have a chance to update this PR based on my last review (https://github.com/DSpace/dspace-angular/pull/1297#pullrequestreview-1059057947), then we may be able to include it in 7.4.  Otherwise, we'll have to reschedule it for 7.5 (due in Feb)

**Comment by myrza1** [comment]
> @myrza1 : I just wanted to ping you one last time to let you know we are finishing up the 7.4 release in the next 2 weeks. If you have a chance to update this PR based on my last review ([#1297 (review)](https://github.com/DSpace/dspace-angular/pull/1297#pullrequestreview-1059057947)), then we may be able to include it in 7.4. Otherwise, we'll have to reschedule it for 7.5 (due in Feb)

Hello, 

#1297 
1. We will rename to kk.json
2. Better label "Қазақ"

for next 2 week it maybe possible
Thanks!

**Comment by tdonohue** [comment]
@myrza1 : Thank you for making the updates!  I'll add this to my list of PRs to re-review and try to get this merged into the upcoming 7.4 release

**Review by tdonohue — APPROVED** [review]
👍 Thank you @myrza1 !  I've tested this today and verified that the translations load properly when selected & (using Google Translate) that the translations look reasonable.  I'm going to go ahead and merge this so that it's available in 7.4.  If you have any other updates to make, please feel free to create a new PR to enhance this `kk.json5` file!

**Pull request merged**
