### PR TITLE
Delete eperson

### LINKED ISSUE #730: Delete EPerson
Estimate from release plan: none
Expressing interest: none

From release plan: This is a subtask of "Manage EPeople" task (for Angular UI)

### PR DESCRIPTION
**Pull request by artlowel**
## References
* Fixes #730 
* Requires https://github.com/DSpace/DSpace/pull/2928

## Description
This PR adds the ability to delete EPersons

## Instructions for Reviewers
This PR adds functionality to the pre-existing delete buttons on the EPerson detail page and the EPerson overview. 

After clicking a delete button you'll get a confirmation dialog.

This PR will test whether the current user should have the right to delete a certain EPerson before enabling the button using the features and authorizations system. However, there are certain rules in the backend which prevent an EPerson from being deleted, that are only checked after you send the delete request for performance reasons (e.g. you try to delete the only EPerson in a workflow group that has items). In those cases, we can't disable the button ahead of time, instead you'll get an error notification with the message from the backend if you try the delete and it fails.

**Reviewers can test this PR by**:  
- Authenticating as an admin
- Going to Access Control → People from the admin sidebar
- Trying to delete an EPerson from the list
- Trying to delete an EPerson from the edit page
- Verifying that you are asked to confirm the deletion each time
- Verifying that if the delete succeeds you get a success notification
- Verifying that if the delete fails you get an error explaining why

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
@artlowel : quick FYI, this looks to have a minor code conflict after I merged #873

**Review by tdonohue — CHANGES_REQUESTED** [review]
@artlowel : The code looks good overall. No comments there.  

However in testing, I found a minor bug when I forced an error to occur.  Here's how to reproduce it:
1. Create a new eperson (or use an existing one)
2. Find a Collection that has no workflow yet.  Add that EPerson as the only member of a workflow group (it doesn't matter which one)
3. Try to delete that EPerson.  An error occurs (as that's expected), but the message says: `Error occured when trying to delete EPerson with id: [uuid] with code: 422 and message: OK`.  The problem is the "OK" in that message.

When looking at the actual response from the REST API (in Chrome DevTools), it has a different message.  It shows: 
```
{"timestamp":"2020-10-01T21:23:54.979+0000",
"status":422,
"error":"Unprocessable Entity",
"message":"Unprocessable or invalid entity",
"trace":"[a really long exception]",
"path":"/server/api/eperson/epersons/d32471a1-c625-4598-a75c-64e24fafed29"}
```

The message here likely should be improved/enhanced (possibly on the backend).  But, it's obviously not saying "OK" :) 

Beyond that minor bug, everything else seems to be working. I get a confirmation when I try to delete, and I can delete other epersons successfully.

**Review by tdonohue — APPROVED** [review]
👍 I re-tested this today with the backend PR (https://github.com/DSpace/DSpace/pull/2928).  The previous bug I reported is now solved.  I did find a small bug in the backend PR, but that issue is unrelated to this PR.  So, once the backend is ready-to-go, this PR can also be merged.

(NOTE to other reviewers.  The red ❌ on this PR can be _disregarded_, as it's a failure in an optional check.  It appears simply because the code coverage of new code in this PR is slightly lower than the percentage on `main`. However, the overall code coverage still *improves*,  so this PR is good enough as-is.)

Thanks @artlowel and @Raf-atmire !

**Review by atarix83 — APPROVED** [review]
@artlowel thanks for the PR

code looks good to me and I've tested the functionality successfully

**Comment by tdonohue** [comment]
Merging, as the backend PR (https://github.com/DSpace/DSpace/pull/2928) was also just merged. Thanks @artlowel !

**Pull request merged**
