### PR TITLE
[8.x] Accessibility cookie settings

### LINKED ISSUE #2668: Color Contrast in cookie settings box is not sufficient
**Describe the bug**
In the "We collect and process your personal information..." box, there is green text on the black background. The contrast between these two is not sufficient: accessibility requirements say it should be 4.5:1, but it is only 3.27:1.

**To Reproduce**
Use WAVE on the page, or fill https://webaim.org/resources/contrastchecker/

### PR DESCRIPTION
**Pull request by Andrea-Guevara**
## References
* Fixes #2668

## Description
Adding and changing some classes in the global scss to make the cookie settings more accessible.

## Instructions for Reviewers

List of changes in this PR:
* Added the variable "--very-dark-cyan" in _custom_variables.scss.
* Removed the variable ".cm-btn.cm-btn-success.cm-btn-accept-all" and its styling as it was no longer needed.
* Styled the "Accept all" button by overwriting the style of the ".klaro .cookie-modal .cm-btn.cm-btn-success.cm-btn-accept-all" variables.
* Added "text-decoration: underline;" to the anchors.
* Changed the color of some informational texts, which were previously gray and are now lighter to improve contrast.
* Changed the color of the "Save" button by overwriting the styling of the variables: .klaro .cookie-modal .cm-btn.cm-btn-info.

## Checklist
- [ ] Visit https://sandbox.dspace.org in an Incognito browser
- [ ] Klaro cookie popup should appear. Click on "Customize" to bring up the screen above
- [ ] Expand all sections on that screen.
- [ ] Run an accessibility scanner (WAVE or "axe DevTools) and check that the accessibility test is positive.

### CODE REVIEW

**Comment by tdonohue** [comment]
NOTE: it's possible this PR may have overlap/conflicts with #3199.  We've realized in today's Developers Meeting that migrating our cookie consent form to Orejime *might* fix (or partially fix) the same accessibility issues as this ticket.  This is because Orejime is a fork of Klaro which was created to _fix accessibility issues in Klaro_.

So, anyone reviewing/testing this PR may want to also compare it to #3199.  We need to determine if both PRs are necessary, or if migrating to Orejime will fix the issues we've had with accessibility in Klaro.

**Comment by tdonohue** [comment]
Per my prior comment, I've realized we *may* still want to apply this small PR to 8.x and 7.x to fix accessibility in Klaro for those releases of DSpace.  However, it should **not** be applied to 9.0, as #3199 will migrate us to using Orejime for 9.0

Could you update this PR @Andrea-Guevara to apply to `dspace-8_x` instead of to `main`?  I think that's the best way forward for this PR, as we cannot apply it to `main` (since #3199 will be applied on `main` once it is completed).

**Comment by Andrea-Guevara** [comment]
Good afternoon @tdonohue! I didn't quite understand what you asked me, or even if you asked me anything haha.

Is it to make the PR from a branch in dspace version 8?

**Comment by tdonohue** [comment]
@Andrea-Guevara : I was asking if you could change this PR to be against the `dspace-8_x` branch, so that we can apply it *only* to the 8.x releases.  If you look at the top of the PR, it's currently submitted for the `main` branch.  That `main` branch is *normally the best place to submit a PR*.  

But, in the case of this PR, we cannot merge this one into `main` as it will become obsolete once we merge #3199 into `main`.  Essentially, this PR cannot go into 9.0 as we are removing Klaro (which is what this PR updates).

However, if we could change this PR to be sent to the `dspace-8_x` branch, then we could still accept it for future 8.x releases (as those will still include Klaro). (The `dspace-8_x` branch is where we maintain the 8.x codebase.)

If this still doesn't make sense, we can probably apply this directly to `dspace-8_x` once someone has a chance to test this.

**Comment by tdonohue** [comment]
Closing as this is replaced by #3328, as we've decided this should only be merged to 8.x and 7.x.

**Pull request closed without merging**
