### PR TITLE
Fixed read-only visibility for submission form fields

### PR DESCRIPTION
**Pull request by alisaismailati**
## References
* Fixes https://github.com/DSpace/DSpace/pull/8848#issuecomment-1549440143

## Description
The visibility of submission form fields, based on the scope, is checked on `src/app/shared/form/builder/parsers/field-parser.ts` and `src/app/shared/form/builder/parsers/row-parser.ts`.

## Instructions for Reviewers
List of changes in this PR:
* First, it is checked if the field is hidden or not, based on the visibility (visibility should be different from read-only) and the submission scope. It is checked by `isHidden()` method at ` src/app/shared/form/builder/parsers/row-parser.ts`
* Second, it is checked that the field is read-only when the model has the visibility object and `visibility.main === VisibilityType.READONLY`.
* Finally, there are added all the needed configurations for each field to be configured as read-only (disabled) correctly.

**Include guidance for how to test or review your PR.** 
In the `submission-forms.xml` should be added the configuration for a field as in the example:
```
                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>title</dc-element>
                    <dc-qualifier>alternative</dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Other Titles</label>
                    <input-type>onebox</input-type>
                    <hint>If the item has any alternative titles, please enter them here.</hint>
                    <required></required>
                    <readonly>readonly</readonly>
                    <visibility>workflow</visibility>
                </field>

```
## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@alexandrevryghem : If you have any time this week, I'd appreciate some help in testing this PR...especially since [you helped discover the issue](https://github.com/DSpace/DSpace/pull/8848#issuecomment-1549440143).

**Comment by tdonohue** [comment]
@alisaismailati and @atarix83 :  I'm confused by this PR because it doesn't seem to fix the issue initially reported in https://github.com/DSpace/DSpace/pull/8848#issuecomment-1549440143  Instead it fixes a *different* read-only issue.

The issue originally reported in https://github.com/DSpace/DSpace/pull/8848#issuecomment-1549440143 was that this sort of configuration in `item-submission.xml` is no longer valid:
```
       <step-definition id="traditionalpageone" mandatory="true">
            <heading>submit.progressbar.describe.stepone</heading>
            <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
            <type>submission-form</type>
            <scope visibilityOutside="read-only">submission</scope>
        </step-definition>
```
In our Submission documentation, we state that it's possible to set a "visibility='read-only'" or "visibilityOutside='read-only'" attribute on the `<scope>` tag in order to make that entire step read-only.  See the docs here for the "scope" tag: https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-Structureofthe%3Cstep-definition%3Etag

This PR doesn't seem to fix that issue... I had assumed that it would, but that bug is still reproducible for me with this PR installed.

However, this PR _seems to instead fix_ an issue with making **individual fields read-only**.   It appears we have an (undocumented?)  `<readonly>` tag which can be added to any field in `submission-forms.xml`??  I was unaware of this option, but it does seem like it exists in our `submission-forms.dtd`: https://github.com/DSpace/DSpace/blob/main/dspace/config/submission-forms.dtd#L58
I wasn't aware of these settings as I don't see any documentation on this `<readonly>` tag, or the `<visibility>` tag in our docs at https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-CompositionofaField

So, before I can test this, I think I need to make sure I understand what this PR is fixing.

**Comment by alisaismailati** [comment]
Hi @tdonohue ,
Our PR fixes the second issue(individual fields read-only). The documentation is not updated, but we can update it.
And also we can have a look in the first problem.

**Review by tdonohue — COMMENTED** [review]
@alisaismailati and @atarix83 :  Re-tested this today, and it's looking good overall.  The read-only settings all appear to work.  
* I verified that the `<readonly>readonly</readonly>` works for an individual field in the `submission-forms.xml`
* I verified that the `<scope visibilityOutside="read-only">submission</scope>` works to disable an entire section.

However, I'm seeing a slightly odd behavior when I use the `<visibility>workflow</visibility>` tag for a single field.  So, I wanted to ask about the expected behavior.  Here's what I'm doing:
1. I'm using the example configuration for dc.title.alternative:
    ```
                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>title</dc-element>
                    <dc-qualifier>alternative</dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Other Titles</label>
                    <input-type>onebox</input-type>
                    <hint>If the item has any alternative titles, please enter them here.</hint>
                    <required></required>
                    <readonly>readonly</readonly>
                    <visibility>workflow</visibility>
                </field>
    ```
2. My expectation is that `<visibility>workflow</visibility>` should make this field **only visible in the workflow**?
3. However, if I test this setting... I find that the "Other Titles" field is **visible in both workflow & submission** (and it's readonly in both).
4. If I then *remove* the `<readonly>readonly</readonly>` configuration (and just have the `<visibility>workflow</visibility>`), then the field **disappears from both workflow & submission**.

Is that expected behavior?  Or is the `<visibility>` tag not working properly? 

Overall, I'm +1 this PR.  It fixes the main bugs with the read-only settings.  Therefore, I'm OK with merging this as-is and logging a separate bug for the `<visibility>` tag.  But, I wanted to ask this question in case there's a quick fix.

**Comment by alisaismailati** [comment]
Hello @tdonohue ,
We fixed also the behavior when we use the `<visibility>workflow</visibility>` tag for a single field.
Now should be everything fixed and working fine.

**Review by tdonohue — APPROVED** [review]
@alisaismailati  and @atarix83 : I believe this is working correctly now.. so I'll go ahead and approve it.  We do need to document the missing field configs though here: https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-CompositionofaField

Here's the behavior I'm seeing
* `<scope visibilityOutside="read-only">submission</scope>` works properly. It disables an entire section when in workflow.  Only editable in submission
* On individual fields, if you specify *both* `<readonly>readonly</readonly>` and `<visibility>submission</visibility>` this appears to have the same behavior as above. That individual field is editable in submission, but it's read-only (disabled) in workflow.  (So `<readonly>` appears to act like `visibilityOutside="read-only"`)
* On individual fields, if you specify *just* `<visibility>submission</visibility>`, then that field is ONLY visible in submission (and not visible in workflow).

This seems like reasonable behavior... though I admit, I'm not 100% sure if it's correct, since these `<readonly>` and `<visibility>` tags are undocumented (so I'm not sure what should happen when both are used together).  But, I'm going to assume it's correct and merge this.  If we find that behavior is NOT correct, then we can patch it in a follow-up PR.

**Pull request merged**
