### PR TITLE
Updated Mirador dependencies.

### LINKED ISSUE #1447: Mirador IIIF viewer build failing
**Describe the bug**
Carl Jones and I noticed that Mirador viewer builds have recently started to fail. Error message:

```
ERROR in ./node_modules/mirador-share-plugin/es/MiradorShareEmbed.js
Module not found: Error: Can’t resolve ‘@material-ui/core/styles/createMuiTheme’ 
```

**To Reproduce**
1. yarn run build:mirador

### PR DESCRIPTION
**Pull request by mspalti**
## References
* Fixes #1447

## Description
Not sure when this started, but Mirador builds are currently failing. The issue appears to be in one of the plugins. Updating the plugin version fixes the problem.

## Instructions for Reviewers
Includes package.json updates for mirador and the mirador-share-plugin. Updates the plugin from 0.11.0 to 0.13.0. Updates mirador from 3.0.0 to 3.3.0. Our Mirador dependencies are now:

```
    "mirador": "^3.3.0",
    "mirador-dl-plugin": "^0.13.0",
    "mirador-share-plugin": "^0.11.0",
```
I noticed that `react `and `react-dom` are actually devDependencies and made that update as well. (This doesn't affect the size of the compiled bundle.)

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by mspalti** [comment]
There's an npm (yarn) subtly here that I don't fully understand.  Wouldn't ^0.10.0 require that `yarn clean install` pickup the minor version 0.11.0? In testing, the mirador build only succeeded when I explicitly updated the minor version in package.json. (I didn't actually check the lockfile after the fresh install.) 

I guess related to this, is there a general recommendation for when we should avoid minor versions (between DSpace releases) and instead accept only patch updates (~) or require an exact version match?

**Comment by tdonohue** [comment]
Ran into this bug when trying to test #1436... so, I'll test this fix first.

**Review by tdonohue — APPROVED** [review]
👍 This fixes the current build issues I was also seeing with Mirador on `main`.  Merging immediately.

@mspalti : To answer your questions, our `yarn.lock` file is what defines the dependency versions that will be used.  So, regardless of the versions specified in `package.json` (and available through NPM), Yarn will go with exactly what is in the `yarn.lock` file until you tell it to update (via `yarn add` or `yarn update`, etc).  So, I think that's why our `main` branch continued to use older versions of these dependencies, even if the `package.json` had a lenient version number.

**Comment by mspalti** [comment]
@tdonohue thanks, that's what I needed. Good to get the brief on "update." Makes sense now!

**Pull request merged**
