### PR TITLE
'pree2e' and 'ci' scripts added

### PR DESCRIPTION
**Pull request by sourcedump**
This PR connects to [#49](https://github.com/DSpace/dspace-angular/issues/49).

'pree2e' and 'ci' scripts added. 
'pree2e', runned each time 'e2e' is called, keeps protractor drivers up to date while 'ci' runs tslint and all the tests (both Unit tests and E2E tests).

### CODE REVIEW

**Comment by artlowel** [comment]
LGTM

**Comment by sourcedump** [comment]
Actually you need to run a 'start:dev' manually before executing 'ci' (for e2e testing).
Do you think it's possible to run 'start:dev' and, when the server is up, auto-run 'ci' and, again, at the end, shutdown the server started with 'start:dev'?

**Comment by sourcedump** [comment]
Ok, the 'ci' script now run the 'server' before the 'e2e'.

**Comment by artlowel** [comment]
It works, but are you using [npm-run-all](https://github.com/mysticatea/npm-run-all) in order to run two npm scripts in parallel? If so, note that we already have a dependency on [concurrently](https://github.com/kimmobrunfeldt/concurrently) that does the same thing.

**Comment by sourcedump** [comment]
Hello Art, I've tryed to use 'concurrently' but I need to use the '-k' option to kill the server at the end of the tests and with 'npm-run-all' all is fine, instead with 'concurrently' I have a false error at the end of the run. All the scripts run correctly but at the end an error is reported. I'll try to figure out why.

**Comment by artlowel** [comment]
If you can't get it to work, I'm also fine with swapping out concurrently for npm-run-all everywhere (it's only used for two scripts), as long as npm-run-all also works on all platforms. It's just that I'd rather not add two dependencies to do the same job.

**Comment by sourcedump** [comment]
I've relplaced 'concurrently' with 'npm-run-all'. Now all is fine.

**Comment by artlowel** [comment]
LGTM. Merging

**Pull request merged**
