### PR TITLE
Fixes for submission forms bugs

### LINKED ISSUE #1110: Deleting a single file in a multi-file submission makes all files disappear.
**Describe the bug**
If you start a submission, and upload many files, then delete one...all of the files disappear from the submission.  However, only the one is deleted.  The others will reappear if you exit the submission & reopen it.

**To Reproduce**
1. Start a new Item submission
2. Upload 3 files.  This succeeds. All three files will be listed.
3. Now, delete one file.  **This succeeds, but now all files disappear from the submission form.**
4. Click "Save for Later"
5. Now, go back in and edit the same submission. You'll see that 2 files now remain.

**Expected behavior**
Deleting one file should only cause that file to disappear from the submission form.

### LINKED ISSUE #1119: Embargo of Bitstream during submission not working
**Describe the bug**
(Copied from [Test Plan, Item T023](https://docs.google.com/spreadsheets/d/1BdK8SzytA7HoxOZgldCIHabMxeR4mYTXt_ynVT_-KR8/edit#gid=1865680815)): 

> https://demo7.dspace.org/entities/publication/39d319ea-6e9d-4c54-91cd-32e495351e67/full  I added an embargo date, but was able to download the files on a different browser at which I was not logged in. Perhaps the embargo didn't work because I didn't fill in the second box - about how long the items should be accessible. That box was marked with an asterisk,  but was grayed out so I couldn't see possible values

**To Reproduce**
In verifying this bug, I found that the Embargo date doesn't seem to be saving

1. Start a new submission
2. Upload a File
3. Edit the File, changing the "Access condition type" to "embargo", and adding a "Grand access from" date.
4. Click the green Save icon above the file.  If you have Chrome DevTools open, you'll see the REST API responds to the PATCH request with a `500 Internal Server Error`.
5. Now, click "Save for later"... or try to complete the Submission. Either way you'll get another `500 Internal Server Error`

**Expected behavior**
Obviously, the embargo date should be saved.

### LINKED ISSUE #1121: Files disappear in submission process
When I upload a file and complete metadata, then accept the license, the uploaded file disappears. If I try to upload again, I see BOTH files. If I try to delete one before completing the submission, they BOTH disappear.

### LINKED ISSUE #1144: Bitstream/Attachment appearance issue during submission process
**Describe the bug**
Bitstream/Attachment uploaded at the beginning of the submission process disappears as soon as the "terms acceptance" check box is checked and the "Deposit" button gets deactivated. 

Upon re-uploading the attachment in the same submission process, both fresh and previous attachments uploaded appear. Upon selecting the "terms acceptance" check box on the second attempt, the "Deposit" button remains activated.

**To Reproduce**
1. Go to the item submission form, upload bitstream at the beginning of the process, or drag and drop at any time.
2. Click on the checkbox appearing next to "I confirm the license above". After refresh, you will notice the Deposit button will get de-activated and bitstream uploaded will not appear in the Upload files section.
3. Upload the same bitstream again using any of the available methods
4. Click on the checkbox appearing next to "I confirm the license above". After refresh, you will notice that bitstream will appear twice and the Deposit button will stay active for completing the submission.

**Expected behavior**
Upon clicking the checkbox appearing next to "I confirm the license above", the bitstream added in the form should not disappear and the Deposit button should get activated for finishing submission.

**Related work**
Link to any related tickets or PRs here.

### LINKED ISSUE #1195: Bugs on submission form
**Describe the bug**
I've fount out a couple of bugs in the submission form.

**To Reproduce**
Bug #1
1. start a new submission
2. edit the title
3. save the submission form
3. edit again the title by cancelling all the text and then point the form focus to another form's field
4. edit again the title by entering a new text 
5. save the submission form, you should get an error notification

Bug #2
1. start a new submission
2. add an empty new item in a repeatable field by clicking on the `Add more` button
3. delete the new item added by clicking on the trash icon
4. save the submission form, you should get an error notification

**Expected behavior**
In case of bug#1 the form should properly save the change. In case of bug #2 no changes to save should be detected

### LINKED ISSUE #1220: Bug on repeatable qualdrop value
**Describe the bug**
trying to delete a qualdrop fields with different metadata generates an error

**To Reproduce**
1. start a new submission with a qualdrop value field (e.g a publication has `Identifiers` field)
2. enter a new identifier
3. save submission
4. click add more to add a new identifier
5. select a different identifier than the one saved before
6. enter the new identifier
7. save the submission
8. click on the Trash icon to delete the last identifier added
9. save the submission an error message should be displayed

**Expected behavior**
The delete operation should be saved successfully

### LINKED ISSUE #1229: Deposit license in submission is reset because of page-changes
**Describe the bug**

During the submission, even for a codebase that is [completely default DSpace](https://demo7.dspace.org/), when you tick the licence and fill a metadata and/or a upload a file afterwards, the licence gets unticked.

**To Reproduce**
1. Start a submission
2. Fill in some metadata
3. Tick the 'I confirm the license above' box at the bottom of the page
4. Fill in some other metadata (or simply click a text box, you don't even need to change anything)
5. The checkbox is unticked again

**Expected behavior**
The actual page-changes to the submission should not 'revert' the ticking of the checkbox mentioned above.

### PR DESCRIPTION
**Pull request by atarix83**
## References
* Fixes #1110 
* Fixes #1121 
* Fixes #1119 
* Fixes #1195 
* Fixes #1144
* Fixes #1220 
* Fixes #1229 

## Description
Fixes the problems reported on each issues. For what concerning the bitstream embargo issue (#1119) I've also fixed the form visualization because the form fields appeared disaligned

## Instructions for Reviewers
Check the bugs reported are no longer exist

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 I've retested all the bugs listed in the description, and I can no longer reproduce any of them. Thanks @atarix83 , this looks good to me!

**Comment by atarix83** [comment]
@artlowel  @tdonohue I've added also fix for https://github.com/DSpace/dspace-angular/issues/1220

**Comment by tdonohue** [comment]
@artlowel : It looks like this PR from @atarix83 is now having the same/similar e2e failure as you are running into in #1221.  That makes me wonder if something changed in the GitHub CI environment to cause this new failure? Maybe the GitHub CI environment is using a new version version of ChromeDriver (or some other dependency) that is causing issues? Or maybe a recent REST API change is causing this odd failure (nothing seems obviously related to me, but it's possible)?

(As a sidenote, if possible it'd be wonderful to get both this PR and #1221 merged prior to OR2021, as both fix some immediately evident issues to anyone wanting to try out DSpace 7.  But, I realize our time to debug these e2e issues is running short.)

**Comment by tdonohue** [comment]
@atarix83 : If you could rebase this on the latest `main`, the CI/build process has just been fixed.  Once you pull in the fix, your tests should hopefully succeed.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @atarix83 !  I've rereviewed this, and retested and cannot reproduce the bugs anymore.  I also found this PR fixes a newly submitted bug (#1229), so I added that one to the list in the description.

In any case, I'm in favor of merging this as soon as @artlowel has a chance to give it a quick look.

**Comment by tdonohue** [comment]
@atarix83 : After running this PR locally for several days, I've just encountered a small bug which was undiscovered.  If you edit a Bitstream with an existing "Access Condition", the form will break and no longer be able to be saved.  Here's how to reproduce:
1. Start a new Submission
2. Upload a File
3. Edit the Bitstream, add an Embargo date to it.  Click the green Save icon -> Will Succeed
4. Edit that same Bitstream again. Make no changes. Click the green Save icon. -> Will Fail with a 500 backend error.
5. At this point, the Form is corrupted, and clicking the Form's "Save" or "Save for later" will continue to return 500 errors.

If you'd rather this be fixed in a separate ticket, we can move this one forward as-is & I'll create a separate ticket.

**Comment by atarix83** [comment]
@tdonohue I've fixed the latest issue you have reported, could you please review it?

**Comment by tdonohue** [comment]
@atarix83 : I gave this another test today... the problem with the 500 exception is now **fixed**. 

However, strangely, when saving an embargo date, the date is always saved **incorrectly**.  For example, If I attempt to save an embargo date of `2021-07-31` (July 31), it will save as one day earlier (2021-07-30). If I edit the embargo, it'll show up a day earlier than that (2021-07-29), and it keeps moving one day earlier each time you edit the embargo date.

All in all, this is still a PR worth merging soon, as it fixes a large number of issues.  So, I'm OK with merging this as-is, and reporting the embargo date issue separately, if that's easiest.

**Review by artlowel — APPROVED** [review]
Thanks @atarix83! The code looks good, and all the issues mentioned have been fixed.

I can also reproduce @tdonohue's embargo date issue, but as I understood from the meeting that has already been fixed in a different PR

**Comment by atarix83** [comment]
@tdonohue @artlowel 
is the issue occurring when entering the date manually or by selecting from calendar ?

**Comment by tdonohue** [comment]
@atarix83 : It was occuring for me in both scenarios -- entering manually or selecting a date from a calendar.  And, it even occurs if you simply edit the bitstream again & save it with no changes -- the date is saved as one day earlier each time.  So, if you add an embargo date of 2021-07-31 and save it, it becomes 2021-07-30.  If you edit that bitstream again & make no changes but click the save, it changes then to 2021-07-29.  If you edit again, it becomes 2021-07-28, and so on.

Since this PR is at +2, if you'd rather deal with this embargo date issue as a separate ticket, we can do so (though I do want the embargo date issue fixed in 7.0, as we want this to work properly).  I'll wait to merge this until I've heard back from you.

**Comment by atarix83** [comment]
@tdonohue @artlowel 

I can't reproduce the issue following the steps you've reported. Are you using the `api7.dspace.org` as server rest? 
Could you please provide me which is the json patch operation sent to the server and the response from it? we should verify if the problem is on angular side and the date is sent wrongly or if is an issue on rest side that responding to the request with an incorrect date.

**Comment by artlowel** [comment]
I was testing against api7.dspace.org. But looking into it again now it turns out my issue wasn't the exact same @tdonohue described, it just looked similar because of the dates I happened to pick:

If you set an embargo or lease date using the calendar, click the green save icon for the bitstream, and then edit it again, this time straight from the input without using the calendar, and then save again, your changes won't be saved. It will jump back to the date you originally set using the calendar.

I also noticed that if you edit and save a bitstream multiple times in a row, after a few times the page will crash with this error
```
core.js:4442 ERROR TypeError: Cannot read property 'rows' of null
    at e.buildFileEditForm (section-upload-file-edit.component.ts:154)
    at e.ngOnChanges (section-upload-file-edit.component.ts:145)
```

**Comment by atarix83** [comment]
@artlowel @tdonohue 
I've fixed the issue occurred while entering the date manually. Now it'd work.

> I also noticed that if you edit and save a bitstream multiple times in a row, after a few times the page will crash with this error
I've tried several times but I can't reproduce

moreover I can't still reproduce the errors describe by Tim

if you agree I'd move this issue in a new ticket while trying to reproduce it systematically

**Comment by artlowel** [comment]
Here's a video of how to reproduce it

https://user-images.githubusercontent.com/1567693/123424445-23258d00-d5c1-11eb-896c-c781d2e61a6f.mov

I'm fine with moving this to a separate ticket

**Review by tdonohue — APPROVED** [review]
@atarix83 : Gave this a test again today.  I'm still seeing issues with saving the embargo date, whether I select it from the calendar popup or enter it manually.  However, as so many other PRs have become dependent on this one (there's at least two), I think we should merge this as-is and log the other issues separately.  So, I'll move the embargo bug into a separate ticket & add a video showing what I see.

Strangely, I tried to reproduce @artlowel 's issue, but cannot seem to reproduce it locally.

**Comment by tdonohue** [comment]
Merging this as-is to get the submission fixes applied.  Any additional bugs should be logged as separate tickets.

**Comment by tdonohue** [comment]
Moved embargo bug to #1256

**Pull request merged**
