### PR TITLE
Possible fix for browse-by-date links

### LINKED ISSUE #2214: Links to items fail initially when browsing by year
**Describe the bug**
I recently noticed that when choose to browse `By Issue Date` in a collection and limit results by year I see strange behavior. Instead of following the route to the item, the browse page instead reloads. After that the route to the Item works fine. However, if I return to the list after viewing the item and select the next item in the browse list I see the same result. The item route is not followed, the browse page reloads, and after that I can follow the link to the item. The pattern repeats.

**To Reproduce**
1. Choose the `by issue date` browse option
2. Limit your search to a year that has items
3. Select the first item. The browse page will reload (if you haven't visited this item before)
4. Now select the item again and you should get the item view
5. Go back to browse and select the next item in the list (repeat)

**Expected behavior**
When you select an item from the browse list the item route should always be followed.

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by mspalti**
## References
* Fixes #2214

## Description
Currently the browse-by-date component appears to be initialized multiple times via router updates. One of these updates seems unnecessary and removing it solves the problem with item links.

The removed line might actually needed in cases that I haven't found. But if it's truly redundant then removing might be a quick fix for #2214

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by artlowel — APPROVED** [review]
Thanks @mspalti!

The fix works, and I honestly can't think of a reason for that call to be there in the first place.

That setStartsWith method is only called from onInit with the params from the URL, so updating the URL with the exact same param at the end of it seems wholly unnecessary

**Comment by artlowel** [comment]
Yeah sorry about that 😅

**Comment by mspalti** [comment]
I'll get to your feedback tomorrow, @artlowel. Sorry I'm slow getting to it, busy week. 😌

**Review by tdonohue — APPROVED** [review]
👍 Thanks @mspalti !  Tested and verified the original bug is fixed along with the additional bug reported by @artlowel above.  This looks good.

**Pull request merged**
