### PR TITLE
Enhance e2e test infrastructure. Add initial tests for authenticated actions like submission, mydspace, etc.

### PR DESCRIPTION
**Pull request by tdonohue**
## Description
This PR concentrates entirely on adding e2e tests and enhancing the e2e testing infrastructure to support tests for pages that require authentication.

Changes include:
* Upgraded Cypress to 9.5.1.  Required to support drag & drop upload testing for submission UI (which is new in Cypress 9.x)
* Making UUIDs (and similar) used by e2e tests more easily configurable in `cypress.json`. That way, it's easier to run e2e tests on local data, instead of requiring our demo entities data set
* Add custom `cy.login([email], [password])` function which can be used to pre-authenticate before accessing any page requiring authentication (e.g. /mydspace).
* Stabilize existing e2e tests by ensuring they `wait()` when necessary for search results to load, etc.  Also ensured xhr requests from prior tests don't accidentally overlap with next test by loading `about:blank` page between each test.
* Add initial e2e tests for these pages:
    * Login modal in header
    * MyDSpace
    * Submission UI
* Minor updates to some UI components to better support e2e tests. This includes..
    * Adding `id` attributes where e2e tests could easily use them to select particular elements on page
    * For same purpose, adding ~~`data-e2e`~~ `data-test` attributes specific to e2e tests, when a specific component could not be easily given a unique `id`
    * Fixed some minor accessibility issues in grid search results & MyDSpace (discovered when running accessibility tests via e2e)
    * Added i18n keys to Grid search results components where hardcoded text was discovered.

## Instructions for Reviewers
* Review code and verify e2e tests succeed.

### CODE REVIEW

**Comment by tdonohue** [comment]
While all these tests succeed locally, it appears that our demo entities data set is lacking in test data for the MyDSpace and Submission pages, which results in e2e test failures in GitHub CI (e.g. no in-progress submissions exist by default).  I'll flag this as WIP for now, as I'll need to update that demo entities data set with some additional test data.

**Comment by tdonohue** [comment]
These tests now succeed locally & in CI.  It required some minor fixes to the tests in this PR and also an update to our test data set (to now include some "in progress submissions" which can be used for e2e tests) at https://github.com/DSpace-Labs/AIP-Files/releases/tag/demo-entities-data

@artlowel and @atarix83 : Assigning this to you for review.  It is almost entirely new e2e tests, so it should be a quick review. But, as detailed in the description above, it includes some minor fixes to the UI to support e2e tests or fix minor accessibility issues.

**Comment by tdonohue** [comment]
@artlowel : Per your feedback, regarding how running `ng e2e` runs by default against `api7.dspace.org` (and how that can sometimes result in random failures)

I dug into it a bit more today.  It looks like that behavior is simply an artifact of the fact that our default runtime configuration points at `api7.dspace.org`: https://github.com/DSpace/dspace-angular/blob/main/config/config.yml#L3

Unfortunately though, that means there's no easy way to keep the default runtime configuration pointing at `api7.dspace.org` _while also_ changing `ng e2e` to run against a different configuration.

Cypress has no way of passing environment variables to the running application or controlling how the application boots up. Instead Cypress [requires the application to test _is already running_](https://docs.cypress.io/guides/references/best-practices#Web-Servers).   Our `ng e2e` command is just setup in such a way that it first boots up the Angular UI (currently using the default `production` environment), and then starts up Cypress to run against it. 

That said, I have discovered that developers can switch the default mode of `ng e2e` by setting `NODE_ENV`, for example:
```
# This defaults to using config.prod.yml, or config.yml
ng e2e

# This will run e2e tests using config.dev.yml instead
NODE_ENV=development ng e2e
```

So, overall, I'm starting to lean towards simply documenting in our README that `ng e2e` **requires** first spinning up the [demo entities data set](https://github.com/DSpace-Labs/AIP-Files/releases/tag/demo-entities-data) in either a locally controlled server or a Docker instance.  It will NOT work against api7.dspace.org (as that's an uncontrolled server).  You can use `NODE_ENV` if you want to specify a different `config.dev.yml` to use...but, by default it'll use `config.prod.yml` or defaults in `config.yml`

That said, if you have any other ideas, I'd welcome them. I'm just not seeing an easy solution here.

**Review by artlowel — APPROVED** [review]
Thanks @tdonohue!

Looks good!

I like the idea of adding `data-e2e` attributes in order to target specific UI elements, that way a change of class or id won't break the test. However, that would be just as useful for unit tests, so perhaps we should call it `data-test` instead? It doesn't make a lot of sense to add separate data attributes for unit and e2e tests.

**Comment by tdonohue** [comment]
Thanks @artlowel and @atarix83 !  I've just updated all `data-e2e` to be `data-test`.  I'll wait for Github CI to succeed and then move forward with merging.

**Comment by tdonohue** [comment]
Merging, as this is at +2 and all feedback has been addressed.

**Pull request merged**
