### PR TITLE
Recent item home

### PR DESCRIPTION
**Pull request by DSquareTechnologies**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #[issue-number]
* Requires DSpace/DSpace#[pr-number] (if a REST API PR is required to test this)

## Description
Short summary of changes (1-2 sentences).

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

List of changes in this PR:
* First, ...
* Second, ...

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [ ] My PR doesn't introduce circular dependencies
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
@DSquareTechnologies : I was just reviewing all open PRs for possible inclusion in 7.3 and stumbled on this PR without any description.  Is this an accidental PR, or is this the "Recent Submissions" work you've been working on?  

If it's the "Recent Submissions" work, we'd need a description added to this PR, including details on how testers can test this feature. We'd also need the failing tests to be fixed in this PR.

As a sidenote, our deadlines for 7.3 are rapidly approaching.  PRs which should be considered for 7.3 must be created by April 28 (or very shortly after), that allows reviewers enough time to review them before May 19.  All PRs for 7.3 MUST be merged by May 27, or they will be rescheduled for 7.4 (due in Oct).  If you have any other outstanding work you'd like considered for 7.3, please create PRs as soon as reasonably possible. Thanks!

**Comment by DSquareTechnologies** [comment]
Gaurav has updated required details in the PR. Please confirm if that's 
fine?

**Comment by DSquareTechnologies** [comment]
Is it possible to assign this PR to gauravd2t?
________________________________

**Comment by DSquareTechnologies** [comment]
Okay he will create a new PR in morning. Hope his account has rights to do so. Thanks
________________________________

**Comment by tdonohue** [comment]
Thanks @DSquareTechnologies !  I'll close this PR then as it seems like a new PR is the easiest approach.  @GauravD2t definitely has the rights to create a new PR, as any GitHub account can send us PRs (there's no restrictions, we accept PRs from anyone who wants to send them).

**Comment by DSquareTechnologies** [comment]
Here is the URL passed by Gaurav

https://github.com/GauravD2t/dspace-angular/pull/3
________________________________

**Comment by tdonohue** [comment]
@DSquareTechnologies : Unfortunately, it seems that @GauravD2t has misunderstood how to send us a PR.  That link you shared is in Guarav's own GitHub repository. As you can see from the link it starts with "https://github.com/GauravD2t/dspace-angular/" which is not correct.  It needs to be a PR under https://github.com/DSpace/dspace-angular/ 

I've added a comment to Guarav with more information at https://github.com/GauravD2t/dspace/pull/3#issuecomment-1111240104

**Pull request closed without merging**
