### PR TITLE
Fix move item page

### LINKED ISSUE #1232: Move item features is not working
**Describe the bug**
The move item feature seems to be completely broken. The search collection is not working most of time, entering some query terms produce the expected REST call with results but nothing is shown to the user. Empty the input leads to a menu with some collections (1-step Workflow collection, 3-step..., abc) but selecting one of them and clicking move the loading indicator over the move button stay forever. Nevertheless, the item seems to be moved (I have moved https://demo7.dspace.org/items/e1a070d3-7f94-494c-9ff8-5fcaabdc4738 to the https://demo7.dspace.org/collections/536584ca-cd75-4016-b99c-3c83c399ca2f collection, it was in https://demo7.dspace.org/browse/title?scope=020c3471-ba82-4f37-a424-b66bbd3df7fa before

### PR DESCRIPTION
**Pull request by ybnd**
## References

* Fixes #1232

## Description

Fix collection search/selection box & response handling on the "Move item" page

## Instructions for Reviewers

List of changes in this PR:

* Replace `ds-dso-input-suggestions` with `ds-authorized-collection-selector`
  * The original `owningCollection` is highlighted on load
  * Replace "Move" & "Cancel" buttons with "Save" & "Back" to fit in with other edit pages. Disabled when the original Collection is selected
  * Add "Discard" button → resets the selected Collection back to the original one
* Work around malformed Collection-like objects in response to `owningCollection` PUT request: don't try to parse it, just look at the status code
* Move `TruncatablePartComponent`'s CSS to global styles, so it can respond to theme changes. Needed to make the highlighted collection render properly.
* Update the in and outputs for dynamic listable components every time they change, instead of only on init. Needed to allow us to change which collection is highlighted on select

**Reviewing**

1. Edit any Item. Open its "Move item" page ("Move..." button on the status page)
   * [ ] The page should include the same DSO selector as the one used in the "New"/"Edit" modals
   * [ ] The Items `owningCollection` should be selected in this component
   * [ ] The "Save" and "Discard" buttons should be disabled
2. Select any other Collection
   * [ ] The "Save" and "Discard" buttons should become enabled
3. Click "Discard"
   * [ ] The DSO selector should highlight the `owningCollection` again
   * [ ] The "Save" and "Discard" buttons should become disabled again
4. Select any other Collection and click "Save"
   * [ ] You should see a success notification
   * [ ] You should be redirected back to the "Edit item" status page
   * [ ] The Item's owning Collection should be updated in the breadcrumbs

## Checklist

_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — APPROVED** [review]
👍 @ybnd : Overall, this works great and is a big improvement.

However, that said, I will note **one tiny issue** I found in testing:
* After the move is complete, the breadcrumbs for the Item do *NOT* update for the moved Item until I reload the browser window.  So, the item appears as if it was not moved until I click reload in my browser...then the updated breadcrumbs appear, etc.

As the overall feature works, I'll go ahead and approve it.  However, if you find it's easy to fix the breadcrumb reloading issue, I'd gladly re-review to verify it's fixed.

**Comment by ybnd** [comment]
@tdonohue Huh, I thought I handled the breadcrumb reloading thing...
I'll take another look 👍

**Comment by ybnd** [comment]
Should work now!
* Added a `setStaleByHrefSubstring` call (was @art's other suggestion)
* Still keeping the `findById` call
  * Breadcrumbs load fine without it, but...
  * Loading is smoother if we make the request before navigating, otherwise we move right after the notification pops up and jump straight into a long loading animation

**Review by tdonohue — APPROVED** [review]
👍 @ybnd : Re-tested today and it's all working correctly for me now.  The breadcrumbs now get updated after the item is moved.  Thanks!

**Comment by tdonohue** [comment]
As discussed in today's meeting, flagging this as `1 Approval` and merging.

**Pull request merged**
