### PR TITLE
Show notifications when failing to create/delete role Groups

### LINKED ISSUE #1557: UX: delete a workflow group causes an error without enough information
**Describe the bug**
If you try to remove  workflow group that is associated with some workflow tasks the backend raise a 422 error but the UI will just report a generic error

**To Reproduce**
1. create a collection
2. assign an editor role to the collection setting an user as member of the created group
3. deposit an item in such collection
4. try to remove the editor group

**Expected behavior**
A message saying that there are related workflow tasks and so the group cannot be removed would be more appropriate

### PR DESCRIPTION
**Pull request by ybnd**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #1557
* Backend PR: https://github.com/DSpace/DSpace/pull/8286

## Description
Show error notifications when Community/Collection role Group creation/deletion fails.

## Instructions for Reviewers
1. Run a local DSpace instance at the backend PR's branch
2. Select (or create) a Collection with the admin account assigned to the first workflow role
3. Deposit a new submission, confirm that it appears in the admin account's pool on `/mydspace`
4. Edit the Collection: attempt to delete the first role' Group
   * A notification should pop up informing you that this can't be done

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@ybnd : It's possible I'm misunderstanding how to test this, but this doesn't seem to work for me right now.

Here's what I tried to do:
(I'm running this PR with the backend PR. The frontend is in production mode: `yarn build:prod; yarn serve:ssr`)
1. Create a new Collection
2. Edit it, Go to "Assign Roles" and add an "Editors" group (COLLECTION_[uuid]_WORKFLOW_ROLE_editor).  Add myself to that group.
3. Go to MyDSpace and create a new Submission to that Collection. Goes into Workflow
4. Back on MyDSpace, I see that Item in the Pool.  Leave it unclaimed for now.
5. Go back to the Collection. Edit it & Click delete on the "Editors" group.  I get a really odd error which returns `422 OK` (see screenshot).  Group is NOT deleted.
odd-error
6.  Now, go back to MyDSpace and claim the workflow item.
7. Attempt to delete the "Editors" group again.  This time it SUCCEEDS.

I'm never able to trigger the new code you've added here with the custom error message.  I feel like I'm missing something or doing something wrong, but I cannot get this to work.

**Comment by ybnd** [comment]
@tdonohue 
* Groups with pending claimed tasks can still be deleted as of the backend PR. I only brought up that problem there and opened another issue for it, I think we still have to discuss how to approach it exactly.
 https://github.com/DSpace/DSpace/issues/8272
* The "422 OK" notification does look weird, I'll look into what's going wrong there

**Comment by ybnd** [comment]
I can't seem to replicate this with the two PR branches, this is the notification I get


The one you got does look a lot like how it looks when running against current `main`


That message is just the [default Angular message](https://github.com/angular/angular/blob/970a3b5c70fee29aa40945836ebeb464d75438e4/packages/common/http/src/response.ts#L345-L346) that comes up when the error response doesn't come with it's own message (no idea why yours would have "422 OK" though...)

**Comment by tdonohue** [comment]
@ybnd : Thanks for retesting. In that case, maybe I made a mistake in my tests & somehow was running this against `main` instead of against https://github.com/DSpace/DSpace/pull/8286.   I'll retest this -- sounds like the mistake may have been on my end. 

I'll also ignore the issue described in https://github.com/DSpace/DSpace/issues/8272 since that will be fixed separately.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@ybnd : I retested today, being very careful to ensure I'm running your backend code in https://github.com/DSpace/DSpace/pull/8286 ... and *I'm still getting the same "422 OK" error* in the User Interface.

I also checked the `dspace.log` when the error occurs, and I see this message (which tells me I'm running the backend code as the new error message is in the logs):
```
2022-05-20 19:23:32,930 INFO  a14cfb2c-4e21-445c-bdb9-b1f53afe8843 71d75523-0992-48fc-ae4d-1d9f0975d555 org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [DELETE /server/api/core/collections/1928a851-019d-4bdb-989f-7639072fd495/workflowGroups/editor] originated from /collections/1928a851-019d-4bdb-989f-7639072fd495/edit/roles
2022-05-20 19:23:32,937 ERROR a14cfb2c-4e21-445c-bdb9-b1f53afe8843 71d75523-0992-48fc-ae4d-1d9f0975d555 org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ Cannot delete group, the associated workflow role still has pending tasks (status:422)
```

But, the UI still shows me this error box:
error

Here's what my browser's DevTools show (When testing, I have `server.error.include-stacktrace = always` set on the backend so I can see the `trace` property): 
exception

(I also tried commenting out my custom `server.error.include-stacktrace` setting, but I get the same results, just without the `trace`)

I'm not sure what I could be doing differently from you.  As noted, I'm running the UI in production mode. I definitely have the correct backend PR (as the error in `dspace.log` is correct) and I definitely have the correct frontend PR (as the error alert box has the `comcol-role.edit.delete.error.title` text you defined in this PR).  

I'm confused, as I don't see anything *obviously wrong* in either of your PRs...but I'm unable to get them to work together as expected.

**Comment by ybnd** [comment]
Thanks for the extra info!

The 422 response I get back does include that `message` we need while yours didn't, so this appears to be a backend issue.

**Review by tdonohue — APPROVED** [review]
👍 Retested today (after the changes to the backend) and this is now working exactly as described.  The code also looks good.  Thanks again @ybnd !

**Pull request merged**
