### PR TITLE
"Recently Added Items" to Community pages added

### LINKED ISSUE #1901: Add "Recently Added Items" to Community pages
**Is your feature request related to a problem? Please describe.**
continues #667 

Please add "Recently Added Items" to Community pages like that done for the Home page in #667.

DSpace7_4_recent_items_on_home

This will match the display in DSpace 6.4.

**Describe alternatives or workarounds you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by CrisGuzmanS**
Hello @tdonohue 🤚. This is my pull request. I hope it is worth for DSpace. I will be attentive to any comments 👍

## References
* Fixes #1901 

## Description
I implemeted the Recently Added Item according to each community like in the Home Page section.

## Instructions for Reviewers

List of changes in this PR:
* I moved `RecentItemListComponent` from `HomePage` Module to `Shared` module, because `RecentItemListComponent` is used now for `CommunityPageComponent`.
* I added the optional `scope` in `RecentItemListComponent` input to allow accept Community and search items according to the given `scope`.

1. Login
2. Create a new item
4. go to the item's community, the item should be visible in the Recent Submission section.

image

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@CrisGuzmanS : Thanks for this quick fix.  While I'm not against this look & feel, I do find it a bit odd that "Recent Submissions" appear differently in Collections than in Communities.  On the Collection Homepage they have their own tab under "Browse" like this:
recent-submissions


But, in your implementation, the "Recent Submissions" on the Community page appear under the "Subcommunities and Collections" tab on the Community.  I wonder if there'd be a way to create a new tab for them, so that maybe the tabs look like this on a Collection page?

```
| Recent Submissions | Subcommunities and Collections | By Issue Date | By Author | By Title | By Subject |
```

Then recent submissions would show by default, but you can easily switch over to the Community/Collection list.

If you think that'd be too difficult, we can consider this PR as-is... but I may want to run it by a few other developers for their feedback as well first.  Thanks!

**Comment by CrisGuzmanS** [comment]
@tdonohue I have been working on the recommendations you made, however, I am having a hard time with the part that I need to create a new special routeLink, either for the **communities and subcommunities** or for the **recentitems**, since currently the communities and subcommunities tab is shown in the root tab of the community and one of the two sections must be in a special route as each of the tabs on `browse`.

What I notice in DSpace 6 is that both sections are shown separately from the tabs, if there is a possibility to do something like that, I could do it, since it would not be necessary to create a new url.

**Review by artlowel — COMMENTED** [review]
Yes, each tab should get their own route. It makes sense because it means you can share the URL with someone and already be on the correct tab. It's the way we do it in other places with tabs as well.

The way to implement this would be to move [the sub-community and collection parts of the community home page](https://github.com/DSpace/dspace-angular/blob/9c780200b2136621517cff034234c5c29c6d7762/src/app/community-page/community-page.component.html#L34-L35) to a dedicated component, containing only them, and replace them with a `<router-outlet>` in the community page component, the way it happens on [the edit item page](https://github.com/DSpace/dspace-angular/blob/9c780200b2136621517cff034234c5c29c6d7762/src/app/item-page/edit-item-page/edit-item-page.component.html#L24) for example.

Then create a similar dedicated component for the recent item list

And then add child routes to [the community page route](https://github.com/DSpace/dspace-angular/blob/9c780200b2136621517cff034234c5c29c6d7762/src/app/community-page/community-page-routing.module.ts#L48-L52) for both those components, again, [the way it works for edit item](https://github.com/DSpace/dspace-angular/blob/9c780200b2136621517cff034234c5c29c6d7762/src/app/item-page/edit-item-page/edit-item-page.routing.module.ts#L62-L121)

Finally, you'll have to add links to those new routes to ComcolPageBrowseByComponent, to ensure they show up in the tab selector

**Comment by alanorth** [comment]
We are interested in seeing recent submissions on community pages. If @CrisGuzmanS is still interested in pushing this forward I can help with testing.

**Comment by tdonohue** [comment]
Closing, as we've realized this feature will be implemented as part of the PRs that will fix https://github.com/DSpace/DSpace/issues/8426   See also the discussions in #2732  

In summary, this PR is not necessary anymore as it will be solved by the PRs for that ticket.

**Pull request closed without merging**
