### PR TITLE
Themed component fixes

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## Description
Moved 2 themed components in the `custom` theme that were in the incorrect folder. Also added a missing themed component template to the `custom` theme and fixed a small issue with the wrapper.

## Instructions for Reviewers

List of changes in this PR:
* Moved the `ComcolPageHandleComponent` & `ComcolPageBrowseByComponent` to the `comcol` folder in `src/themes/custom` like in `src/app` and fixed incorrect path in `ThemedComcolPageBrowseByComponent`
* Added `SearchComponent` & `ItemListPreviewComponent` template in `custom` theme and added missing injection token to the `ThemedSearchComponent`
* ~~Replaced the remaing usages of `<ds-thumbnail>`with `<ds-themed-thumbnail>`~~ Dropped this commit https://github.com/DSpace/dspace-angular/pull/2753/commits/7bf098332899368b8152d31aafddd91cd1cd0c20 in favor of the #2845 (might still be worth cherry-picking on the backport branch)
* Created `ThemedComcolPageContentComponent`, `ThemedMetadataImportPageComponent`, `ThemedItemDetailPreviewFieldComponent` & `ThemedProfilePageMetadataFormComponent`

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
Thanks @alexandrevryghem. I recently noticed there was no example of the `ThemedItemListPreviewComponent` in the `custom` theme either. If you want to add that here...

**Review by tdonohue — CHANGES_REQUESTED** [review]
@alexandrevryghem : This PR isn't working well for me...it's causing several of the modified components to no longer work.

For example:
1. Editing your Profile no longer works.  Login, go to Profile. Edit your Phone  and try to Save.  Nothing will happen and you'll see this error in your browser's DevTools Console
```
main.a81ae43db92c47c1.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'updateProfile')
    at m.updateProfile (5361.8c7375ea4a27a350.js:1:21281)
    at 5361.8c7375ea4a27a350.js:1:19314
    at jm (main.a81ae43db92c47c1.js:1:2255807)
    at F (main.a81ae43db92c47c1.js:1:2255980)
    at HTMLButtonElement.<anonymous> (main.a81ae43db92c47c1.js:1:2352376)
    at Y.invokeTask (polyfills.98e7e738d15c5076.js:1:17578)
    at Object.onInvokeTask (main.a81ae43db92c47c1.js:1:2212739)
    at Y.invokeTask (polyfills.98e7e738d15c5076.js:1:17497)
    at Zt.runTask (polyfills.98e7e738d15c5076.js:1:12839)
    at X.invokeTask [as invoke] (polyfills.98e7e738d15c5076.js:1:18664)
```
2. The Community/Collection pages no longer load. The "Search" tab is empty.  Here's an example when using the "custom" theme:
empty-community-page

These issues only seem to appear with this PR installed.  In my situation, I'm testing in production mode (`yarn build:prod; yarn serve:ssr`)

**Comment by alexandrevryghem** [comment]
@tdonohue: Thnx for the feedback, both issues are now fixed

**Review by tdonohue — CHANGES_REQUESTED** [review]
@alexandrevryghem : This is now working better.  

However, I'm still seeing an empty page on the `/subcoms-cols` path for every Community when using the `custom` theme.  For example, this Community has subcollections, but they don't appear:
empty-sub-coll
(I don't see an obvious error occurring, but the page is empty for every Community)

Everything else that I reported previously seems to be fixed!

**Comment by alexandrevryghem** [comment]
@tdonohue: Sry that component looked like it was pointing to the correct template, but actually it was still pointing to the HTML of the custom theme. I also found one other small mistake in `ThemedComcolPageContentComponent` but now everything should work 🤞

**Pull request merged**
