### PR TITLE
Added production startup script: this connects to #11

### PR DESCRIPTION
**Pull request by wwelling**
Added production startup script.

Please test pull requests with ```npm run start:prod```

This will build and run in production using AoT compilation.

### CODE REVIEW

**Comment by wwelling** [comment]
```npm run clean:ngc``` will clean up AoT generated files.

**Comment by artlowel** [comment]
When I try `npm run start:prod` I get the following error:
```
> dspace-angular@0.0.0 build:prod:json /Users/art/IdeaProjects/dspace7-angular/code
> webpack --config webpack.prod.config.ts --json | webpack-bundle-size-analyzer

sh: webpack-bundle-size-analyzer: command not found
Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14)
```

Maybe `webpack-bundle-size-analyzer` wasn't installed with `--save` or `--save-dev`?

**Comment by wwelling** [comment]
webpack-bundle-size-analyzer requires to be installed globally

```npm install -g webpack-bundle-size-analyzer```

**Comment by wwelling** [comment]
We probably should have a global script to easily acquire global dependencies.

**Comment by artlowel** [comment]
With webpack-bundle-size-analyzer as a global dependency it works fine. Merging

**Comment by artlowel** [comment]
I agree, a script to install global dependencies would be a good idea. I created an issue: #14

**Pull request merged**
