### PR TITLE
[Issue 1410] Production build

### LINKED ISSUE #1410: Unable to run production distribution server without node_modules
**Describe the bug**
For production deployment it is desirable to run distribution without node_modules. This is critical for containerization where as an image with node_modules is over 2GB and a little over 200MB without. Webpack node externals usually only provides benefits for libraries and not so much for servers. Bundling dependencies should reduce overall image size through additional tree-shaking and potential performance gains by reducing runtime requires.

**To Reproduce**
1. yarn install
2. yarn build:prod
3. rimraf node_modules
4. node dist/server

**Expected behavior**
Running distribution server should run as normal without node_modules directory.

**Related work**
N/A

### PR DESCRIPTION
**Pull request by wwelling**
## References

* Resolves #1410 

## Description

Update for a production build and docker deployment. Docker image now under 200MB down from over 2GB.

## Instructions for Reviewers

List of changes in this PR:
1. fix imports
2. remove [universal bundle workaround](https://github.com/angular/angular-cli/issues/7200)
3. add missing production dependencies
4. move dependencies between dev and production where appropriate
5. update server to ensure is run only when not requiring the bundle
6. ~~update Dockerfile to run production build~~ (Docker updates were removed, as that work will be done in a later ticket/PR)
7. remove webpack-node-externals

```
docker build -f Dockerfile --no-cache -t dspace-angular .
docker run -p 4000:4000 dspace-angular
```

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [X] My PR did not introduce any new warnings from [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by wwelling** [comment]
Will be attempting to remove the use of webpack node externals next to further reduce the image size.

**Comment by wwelling** [comment]
image

**Review by tdonohue — COMMENTED** [review]
@wwelling : Overall, great work here!  I've reviewed the changes, and they all look reasonable (and most are minor, but important refactors).  

I've tested it using `yarn start` and everything builds fine.  The resulting UI seems to all work fine as well (I didn't test everything, but tested the basics & also verified SSR is working properly, and it is).

However, when I attempt to run the new Docker script, I'm hitting issues there.  I cannot seem to get [our usual build process](https://github.com/DSpace/dspace-angular/blob/main/docker/README.md#to-build-dspace-images-using-code-in-your-branch) to succeed.

When I run `docker-compose -f docker/docker-compose.yml build`... it seem to be working fine, but it eventually fails with this error:
```
...
#15 21.30 Compiling @kolkov/ngx-gallery : es2015 as esm2015
#15 21.42 Compiling angulartics2/routerlessmodule : es2015 as esm2015
#15 30.35 (node:61) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /dspace-angular/node_modules/tslib/package.json.
#15 30.35 Update this package.json to use a subpath pattern like "./*".
#15 30.35 (Use `node --trace-deprecation ...` to show where the warning was created)
#15 238.3 Generating ES5 bundles for differential loading...
#15 256.9 Killed
#15 257.2 error Command failed with exit code 137.
#15 257.2 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#15 257.5 error Command failed with exit code 137.
#15 257.5 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn build:prod]: exit code: 137
```

I haven't had a chance to dig into why this might be happening. But, obviously we'd want to get the docker-compose build process working properly again.

**UPDATE:** Part of the issue may just be that the `docker-compose.yml` script needs minor updates...for instance, it still uses an `environment.dev.ts` (not an `environment.prod.ts`)

**Comment by wwelling** [comment]
Thanks @tdonohue. Let me update the docker compose files.

**Comment by wwelling** [comment]
@tdonohue was able to build and run using docker compose.

**Comment by wwelling** [comment]
```
C:\Users\william_welling\Development\dspace-angular>docker-compose -f docker/docker-compose.yml build
Building dspace-angular
[+] Building 470.5s (16/16) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 1.40kB                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                      0.1s
 => => transferring context: 35B                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/node:lts-alpine                                                                                                     6.9s
 => [build 1/5] FROM docker.io/library/node:lts-alpine@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b                                         0.0s
 => [internal] load build context                                                                                                                                      0.5s
 => => transferring context: 320.00kB                                                                                                                                  0.5s
 => CACHED [build 2/5] WORKDIR /app                                                                                                                                    0.0s
 => CACHED [build 3/5] COPY . .                                                                                                                                        0.0s
 => CACHED [build 4/5] RUN yarn install --ignore-scripts                                                                                                               0.0s
 => [build 5/5] RUN yarn build:prod                                                                                                                                  460.5s
 => CACHED [production 2/7] RUN apk update                                                                                                                             0.0s
 => CACHED [production 3/7] RUN deluser --remove-home node                                                                                                             0.0s
 => CACHED [production 4/7] RUN addgroup -S dspace -g 1199                                                                                                             0.0s
 => CACHED [production 5/7] RUN adduser -h /home/dspace -s /bin/sh -u 1099 -S dspace -G dspace                                                                         0.0s
 => CACHED [production 6/7] WORKDIR /home/dspace                                                                                                                       0.0s
 => [production 7/7] COPY --from=build --chown=dspace:dspace /app/dist /home/dspace/dist                                                                               0.5s
 => exporting to image                                                                                                                                                 0.4s
 => => exporting layers                                                                                                                                                0.3s
 => => writing image sha256:ebbf65e4869616af6bec6fd7d665eb5750c5728c04b9b05c8786b16b94ef6ad1                                                                           0.0s
 => => naming to docker.io/dspace/dspace-angular:latest                                                                                                                0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
```

```
C:\Users\william_welling\Development\dspace-angular>docker-compose -f docker/docker-compose.yml up
Creating network "docker_dspacenet" with the default driver
Creating dspace-angular ... done
Attaching to dspace-angular
dspace-angular    | [HPM] Proxy created: /  -> http://localhost:8080/server/sitemaps
dspace-angular    | [00:57:28 GMT+0000 (Coordinated Universal Time)] Listening at http://dspace-angular:4000/
```

**Comment by wwelling** [comment]
Removed docker changes as not relevant to issue.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @wwelling !  I've retested this today & verified that it fixes the ticket by doing the following:

* `yarn run build:prod`
* Deleted my entire "node_modules" folder
* `yarn run serve:ssr`

Everything still appears to work...also verified that SSR still works.  So, this looks great to me!  @artlowel or @atarix83 : If one of you can take a quick look as well (perhaps on Monday), I think this is ready to merge.

**Comment by tdonohue** [comment]
Merging with two approvals. Thanks again @wwelling !

**Pull request merged**
