### PR TITLE
150 list and grid feedback

### PR DESCRIPTION
**Pull request by jonas-atmire**
This PR connects to #150 
It uses the ViewMode to switch between displaying "list" and "grid"
(Currently, only the pre-existing viewmode switcher on the search page is used)

Additionally, this also moves some packages to the "shared" module instead of directly under the app directory

### CODE REVIEW

**Comment by tdonohue** [comment]
@jonas-atmire : This is currently showing build errors in Travis: https://travis-ci.org/DSpace/dspace-angular/jobs/309526382#L4099

**Comment by artlowel** [comment]
@tdonohue looking at the travis build output, those errors don't seem to be caused by this PR, they're in files that aren't affected by this PR. 

I think that #207 and #208 made the travis rules stricter and more likely to fail, and this PR is the first one to use them so it fails on errors that were already there.

In any case, those errors prevent the actual tests on this PR from even running, so they should still be fixed before the PR can be reviewed.

**Comment by jonas-atmire** [comment]
The initial failure of the build(/test) was my doing.
During the merging my IDE seems to have made an incorrect path for an import
https://github.com/DSpace/dspace-angular/pull/202/commits/9b812100b12a558c1ea6d722309c18835b73e5e6#diff-1397f93dd840039a0989edfdbf4bfe4eL15

This broke the spec-bundle.js imports.
 
The tests are now running, but some additional non-pr related tests still show some errors (that do not break the actual test run).
I'll fix these as well

**Comment by tdonohue** [comment]
I finally got around to testing this today. Overall, it works well (thanks @jonas-atmire!).  However, I did notice two issues in my tests:

1. The grid view seems to loose pagination tools (at least on my screen).  Pagination only exists in the list view, and when I switch to grid view, I just see `Now showing items` at the top (with no numbers) and the pagination tools at the bottom are gone.
2. After switching to the grid view, if I go back to the list view, the pagination tools now oddly paginate after *12* items (when it usually defaults to 10). So, I now see `Now showing items 1 - 12 of 20` at the top of the list view.

Beyond those two minor issues, this seems to work well.

**Comment by artlowel** [comment]
2. That was part of the spec. 12 divides by more numbers than 10, so the chances of having a full bottom row, and therefor a page that looks balanced, are greater. I told jonas to switch to the nearest multiple of 12 from the original rpp.

**Comment by tdonohue** [comment]
@artlowel : It's quite off putting to see that change occur automatically when switching back and forth, but I understand better now.  I just wonder if we should auto-switch back to 10 when you move back to "list view" (since obviously it's auto-switching to 12 when you move to grid view).

**Comment by artlowel** [comment]
@tdonohue yes, it should definitely auto-switch back. If it doesn't that's a bug

**Comment by jonas-atmire** [comment]
Currently, the pagination on the grid view has been fixed.
Additionally to this, the results per page is now updated according to the viewmode being used.

Another thing that has to be fixed is the following.
When changing from list to grid view, the results per page options in the sidebar still needs to update

**Pull request merged**
