### PR TITLE
[Issue 145] Support base path

### LINKED ISSUE #145: Base Path support
As you build your app, using default settings, your project will work under:
http://localhost:3000/

But if you need to use a different base url like http://localhost:3000/angular/
You can use the simplest solution wich is to set the HTML5 `<base>` tag in the index.html file:
`<base href="/angular/">`

changes here can be a problem regarding the config settings in different environments. In a production environment you might not want to use the "/angular" base path.

Other solution is to use the APP_BASE_HREF, 
`<base ng_href="{{APP_BASE_HREF}}">`

and in the app module, include:
```
import { APP_BASE_HREF } from '@angular/common';

@NgModule({
providers: [
    { provide: GLOBAL_CONFIG, useFactory: (getConfig) },
    { provide: APP_BASE_HREF, useValue: '/angular/'}
  ],
```
I think this base path should be a supported enviornment setting (ServerConfig already includes the **baseUrl** property).

### PR DESCRIPTION
**Pull request by wwelling**
## References
* Fixes #145

## Description
Provides base path support.

## Instructions for Reviewers
Run dspace-angular with defining configuration `ui.nameSpace` such as `/dspace7`. Which runs from URL `http://localhost:4000/dspace7`.

List of changes in this PR:

* wrap server app with router configuring base path
* update base href in head before providing APP_BASE_HREF
* refactor absolute paths to relative including reload and redirects
* add base-href script to support in development

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by wwelling** [comment]
This will work for production using only the `DSPACE_UI_NAMESPACE` environment variable. However, using ng serve now requires updating angular.json as no longer supporting `--base-href`. Unfortunately, that means the current dev only Dockerfile may have to do some hacks to work.

**Comment by wwelling** [comment]
I have added support for development and which the Dockerfile as is will support a base path. The only caveat is it changes angular.json in which could get caught up in a commit.

**Comment by ybnd** [comment]
I can't seem to get this to work properly:  e.g. with `ui.nameSpace: test` in YAML config:
* http://localhost:4000/ → `cannot GET /` (as expected)
* http://localhost:4000/test → redirects to http://localhost:4000/test/test/test, which is a 404 page
* Click a routerLink to the homepage → redirects to http://localhost:4000/test/test/home, which works. Using links keeps working, but the prefix is doubled every time.
* Reloading or directly opening any of these `/test/test/*` pages doesn't work though

**Comment by wwelling** [comment]
@ybnd It appears not only does `ui.nameSpace` need to start with a `/` but also does not seem like `ui.nameSpace` can be on one line as yaml supports. It must be

```
ui:
  nameSpace: /test
```

**Comment by wwelling** [comment]
I am going to look at supporting `nameSpace` with a leading forward slash and standard yaml with `ui.nameSpace` being on one line.

**Comment by ybnd** [comment]
@wwelling hadn't noticed I was missing the leading `/`!

I didn't actually test with `ui.nameSpace` on one line in YAML, just wrote it that way to save space...
Don't know if you really need to look into that though, `js-yaml` doesn't support it anyway

**Comment by wwelling** [comment]
@ybnd thanks. Looks like we should just consider affording `nameSpace` without a leading `/`. Or should this be another issue?

**Comment by tdonohue** [comment]
@wwelling and @ybnd : As the `nameSpace` setting for both the `ui` and `rest` sections of `config.yml` are always shown as having a preceding slash, I'd recommend considering that as **required**.  We can change that behavior in a future ticket if we feel it should be changed, but currently all examples show preceding slashes, e.g. https://github.com/DSpace/dspace-angular/blob/main/config/config.example.yml#L11 and https://github.com/DSpace/dspace-angular/blob/main/config/config.example.yml#L24

**Review by tdonohue — COMMENTED** [review]
@wwelling : Thanks! Tested this and it works in Production mode, but it doesn't appear to fully work in Docker (it's possible I misunderstood your comments above on how to get it working in Docker).

1. (WORKS) First, tested in production mode (running locally, not in Docker):
    * Ran `yarn build:prod`
    * Updated my local `config.prod.yml` to have:
        ```
        ui:
          ssl: false
          host: localhost
          port: 4000
          nameSpace: /dspace
        ```
    * Started with: `yarn serve:ssr`
    * SUCCESS.  Everything is at http://localhost:4000/dspace    Tested basic actions (search/browse/login/logout) and everything seems to work fine.
2. (DOESN'T WORK) Second, tested dev mode in Docker:
    * NOTE: Already had backend/REST API running in Docker.
    * Updated `./docker/docker-compose.yml` to change value of `DSPACE_UI_NAMESPACE`.
        ```
        DSPACE_UI_NAMESPACE: /dspace
        ```
    * Spun up UI in Docker: `docker-compose -p d7 -f docker/docker-compose.yml up -d`
    * Waited for it to build & boot
    * INITIAL SUCCES:  UI is available at http://localhost:4000/dspace
    * FAILURE: Login doesn't work (redirects to `/dspace/dspace/home`).  Links in header don't work (Communities & Collections, All of DSpace, Statistics) -- same reason, uses `/dspace/dspace` as the path.  After login, all links in sidebar also use `/dspace/dspace`

Overall, I'm +1 this effort, but I wanted to note that it's not working in a Docker dev environment. It does work well for Production though.  So, if needed, we could document this only works in Production for now.

**Comment by wwelling** [comment]
@tdonohue thanks for testing. I am not sure what went wrong with testing Dockerfile (dev mode) as I had success. Possibly, `dspace__P__ui__P__url` not updated or some stale image?

If you want to test a clean full Docker deploy you can try, https://github.com/TAMULib/dspace-docker/tree/145-base-path-support. It is all ready to go for this branch.

```
docker --version

docker kill $(docker ps -q)

docker container prune -f
docker image prune -f
docker volume prune -f

docker container ls -a
docker image ls -a
docker volume ls

rm -rf temp
mkdir temp
cd temp

git clone --branch 145-base-path-support git@github.com:TAMULib/dspace-docker.git

cd dspace-docker

cp .env.angular.example .env.angular
cp .env.dspace.example .env.dspace

docker-compose build --no-cache
docker-compose up
```

***Caution: will clear docker images and containers***

**Comment by wwelling** [comment]
@tdonohue appears intermittent failing tests

**Review by tdonohue — APPROVED** [review]
👍 Thanks @wwelling !  Your guess was correct.  I retested this today & everything works. I *think* my mistake last time was that I neglected to _rebuild_ the `dspace-angular` Docker image (a very important step!) after applying this PR, so I had tried to test this with an outdated image.

After correctly rebuilding everything, I'm finding this works both for Docker (using `DSPACE_UI_NAMESPACE` env variable) and for normal production mode (using `config.prod.yml`).  So, this looks good to me. Thanks!

**Review by artlowel — COMMENTED** [review]
I just tried it today, and while it seems to work fine in dev mode, in prod mode it seems all the assets are still hosted under `/` 

image

image



Perhaps I'm doing something wrong?

My prod config looks like this
```yaml
ui:
  nameSpace: /dspace7
```

I also tried adding all the other UI properties but that doesn't make a difference

**Comment by wwelling** [comment]
Thanks @artlowel. This is odd as we have it working in production on infrastructure, but it does not work with `yarn start` I will investigate.

**Comment by wwelling** [comment]
@artlowel I know what is missing. The `yarn start` script is not running the `base-href` script to update the `angular.json` file before build. Will have commit momentarily.

**Comment by wwelling** [comment]
@artlowel was a merge mistake here https://github.com/DSpace/dspace-angular/pull/1642/commits/2db80022b500c4067b655ae593131e90a711a634.

Will commit fix soon.

**Comment by wwelling** [comment]
@artlowel could you please try again.

**Review by artlowel — APPROVED** [review]
Now it works

Thanks, @wwelling!

**Comment by tdonohue** [comment]
Merging as this is now at +2.  Thanks again @wwelling !

**Comment by bkeese** [comment]
Adding a late comment here hoping for some feedback on a related (I think) issue. 

I have just deployed a repo in a subdirectory here:
https://institutionalmemory.iu.edu/aim/communities/eabd44ee-7819-46d0-8355-f44769e0713d
Internal links seem to be fine. But, whenever handles come into play, redirects are to the base url instead of the subdirectory 'aim'.  I don't know enough about the mechanics of handles to effectively find a solution. Can anyone help?

**Pull request merged**
