### PR TITLE
Fixed home page issues

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Small fixes related to #2275
* Small fixes related to #2681

## Description
Some fixes for issues on the home page related to new features merged in the past few weeks:

#2275:
- The home page content (communities in dspace & recent submissions) is not aligned anymore with the home news content
- For screens smaller than 576 pixels the home page facets are being displayed on top of the communities section & recent submission section
- The home page used the non themed version of `ds-themed-configuration-search-page`
- Hide the `Reset filters` button on the home page facets

#2681:
- Fix minor memory leak on home page & footer (subscriptions not being cleaned up)
- Created the missing route for `/info/coar-notify-support` and created an option to hide that link in the footer like done for EULA & Privacy Policy

Other minor fixes:
- Fixed blank page being displayed instead of 404 when disabling EULA/Privacy Policy page and going to (`/info/end-user-agreement`/`/info/privacy`)
- Prevent `/server/api/eperson/profiles/{userId}` to be called when unauthenticated leading into a `/server/api/eperson/profiles/undefined` call
- Fixed a minor alignment issue on `/community-list` where the names would not be vertically centred in comparison with the chevron icon and item count badge

## Instructions for Reviewers
List of changes in this PR:
* Rewrote the way the search facets are being rendered next to the home page content. I used the `PageWithSidebarComponent` to render them, this has some benefits for example on screen with a small height the facets bar will move along with you and won't stay at the top on long pages. It will also automatically use the whole width to display the search filters when your screen is between 576px & 768px
* Display the expand collapse button of search facets on screens between 576px & 768px above the search bar
* Moved COAR logic out of `HomePageComponent` and into a separate component

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alexandrevryghem** [comment]
I thought about 2 additional minor improvements that I can add to this PR if there are no objections:
- We could maybe hide the `Reset filters` button when `inPlaceSearch` is `false`, because it simply redirect you to the search page, and you can't select any filter on the home page (you are automatically redirected to the search page).
- We could also maybe move the COAR code from the home page to a dedicated component. We can still call that component in the HTML of `HomePageComponent`, but this way we clearly seperate that functionality from the home page code

**Comment by tdonohue** [comment]
@alexandrevryghem : Would you have time to quickly rebase this on the latest `main`?  I want to make sure this is compatible with the recent updates to Angular 16 (I suspect it will be, but currently it's not running on the latest code in tests)

**Comment by alexandrevryghem** [comment]
@tdonohue: I retested it locally after merging the latest main and fixed a remaining spacing issue on the home page and also already implemented [these suggestions](https://github.com/DSpace/dspace-angular/pull/2844#issuecomment-1972187510)

**Comment by tdonohue** [comment]
@alexandrevryghem : it appears this PR accidentally includes a ton of unrelated commits now (it shows over 8,000 lines of code changed).  Could you try to clean it up quickly so that I can test it today/tomorrow?

**Comment by alexandrevryghem** [comment]
@tdonohue: Sry I don't know what happend 😬 I cherry-picked the changes back on the latest version of `main`

**Comment by tdonohue** [comment]
@alexandrevryghem : No worries!  I've been in the same situation... sometimes Git/GitHub does things that are unexplainable.  It looks good now & I'll try to review this one tomorrow.  Thanks!

**Review by tdonohue — APPROVED** [review]
👍 Thank you @alexandrevryghem !  This looks great!  I also like the new configuration flag to optionally disable the COAR Notify support page, even if you have COAR Notify enabled.

I tested all the fixes locally and everything seems to be working

**Pull request merged**
