### PR TITLE
Feature process polling

### LINKED ISSUE #2294: UI should have a ProcessPollingService for common polling activities
Per discussion in #2228, we agree that `dspace-angular` should have a `ProcessPollingService` which can be used to check if a specific activity has completed.

Currently, we are doing this via similar code in several components:
* In `src/app/process-page/detail/process.detail.component.ts` added in #2228 -- used to continually poll until a process completes.
* In [`src/app/collection-page/edit-collection-page/collection-source/collection-source-controls/collection-source-controls.component.ts`
](https://github.com/DSpace/dspace-angular/blob/f7bea3eaa990e09022d71cb636471dfbd305db4d/src/app/collection-page/edit-collection-page/collection-source/collection-source-controls/collection-source-controls.component.ts#L104-L109) to check if a test of Collection source settings is completed

Ideally, this sort of "polling until something completes/responds" logic should be split out from individual components into a common `ProcessPollingService`.  

Additional brainstorms regarding this service were provided by @artlowel in [this comment](https://github.com/DSpace/dspace-angular/pull/2228#pullrequestreview-1422639960) (and a few later comments in the same PR 2228).

### PR DESCRIPTION
**Pull request by KoenP**
## References
* Fixes #2294
* Requires https://github.com/DSpace/dspace/pull/9241

## Description
Adds an `autoRefreshUntilCompletion` method to `ProcessDataService` that is intended to be used anywhere where we request the current status of a process repeatedly until it is done. Also replaces ad-hoc implementations of this concept around the code base with this method. This method also allows you to pass `followLinks` to it for performance reasons.
During the making of this PR an additional bug was discovered, the cached object retrieved using a `followLink`s currently aren't automatically marked as stale when you invalidate the cached object with whom you requested them.
 
## Instructions for Reviewers
List of changes in this PR:
* `ProcessDataService` obtains a new method `autoRefreshUntilCompletion`, which transforms a process ID into an `Observable<RemoteData<Process>>` for that process ID. A second optional parameter allows for the polling interval to be configured.
* `CollectionSourceControlsComponent` was adjusted to use this method instead of its own implementation.
* `ProcessDetailComponent` was adjusted to use this method instead of its own implementation.

This feature is probably most easily tested by verifying that `CollectionSourceControlsComponent` and `ProcessDetailComponent` still work as before.

## Checklist
- <input type="checkbox" checked  disabled> My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- <input type="checkbox" checked  disabled> My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- <input type="checkbox" checked  disabled> My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- <input type="checkbox" checked  disabled> My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- <input type="checkbox" checked  disabled> My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- <input type="checkbox" checked  disabled> If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- <input type="checkbox" checked  disabled> If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- <input type="checkbox" checked  disabled> If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@KoenP :  Gave this a review & test (alongside the required backend PR).  Overall, the code looks good and the test was successful.  However, I've found the "Delete process" button now results in a 404 error.  This is not reproducible on https://sandbox.dspace.org/, so I believe it is caused by this PR (or maybe the backend PR?)

Here's how to reproduce the issue:
1. Login as an Admin, and run a Process (or find one you've run in the past)
2. Click on the Process to get to it's detail page (`[dspace.ui.url]/processes/[id]`).
3. On the detail page, click "Delete Processes"
4. The deletion will succeed, but you'll see a 404 error page.  It appears to be caused because you remain on the process detail page instead of being sent back to the Processes Overview (`[dspace.ui.url]/processes`)

Beyond that bug, everything else looks great.  I can also verify that the polling is much smoother.  The page doesn't have to continually reload/redraw until the process is completed.

**Comment by alexandrevryghem** [comment]
@tdonohue: Thnx for the review! I fixed the error, but I also found out that visiting a non-existing process pages (e.x. https://sandbox.dspace.org/processes/10000) throws a `504 Gateway Time-out` error. I also fixed that issue, and I committed it in a separate commit. This way it should be fairly easy to cherry-pick it on `dspace-7.x` if you want that fix there too.

**Comment by tdonohue** [comment]
@KoenP : Please rebase this on `main`.  It's possible that the e2e test failures impacting this PR were just fixed by the merger of #2722 into `main`.

**Comment by tdonohue** [comment]
@KoenP and @alexandrevryghem :  I saw that the e2e tests failed again, so I thought I'd try them locally.  I  **can reproduce the failure** locally in this scenario:
1. Install the backend PR this depends on: https://github.com/DSpace/DSpace/pull/9241
2. Install this PR
3. Run `yarn e2e`.  This will eventually spin up Cypress to run the tests.  Try out these two which are failing frequently in GitHub:
    * `browse-by-dateissued.cy.ts` - This fails locally as well. It appears to be an issue with the Browse by Date Issued page loading _very slowly_.  It does eventually load, but it takes so long that the e2e test times out. (Because it's a race condition, I'm sometimes able to get this to succeed. But usually, it fails for me locally)
    * `browse-by-title.cy.ts`  - Same scenario. This appears to be a test timeout issue. The Browse by Title page loads very slowly.  (Same here, sometimes I'll get lucky and this will succeed. But most of the time it fails for me.)
    * This same issue does NOT occur for `browse-by-author` or `browse-by-subject`.  Those pages load more quickly. It seems to be specific to browse pages which immediately display *Item objects*.

**I can verify this same behavior does NOT occur on `main`.**  On `main`, both of these pages load very rapidly in `yarn e2e` and I never see these timeouts.  So, it appears to be specific to these PRs.  I'm not sure myself what the cause may be, and whether it's this frontend PR or the backend PR.

**Comment by tdonohue** [comment]
@KoenP and @alexandrevryghem : As noted in today's Dev Meeting to @artlowel , the issue I [identified above](https://github.com/DSpace/dspace-angular/pull/2480#issuecomment-1942727904) **may be in this PR** (possibly in some of the changes to `base-data.service`)?   

If I run this frontend PR with the `main` backend, I can still reproduce the odd slowness in some e2e tests via `yarn e2e`.   I cannot reproduce those issues when I run both `main` branches.

So, I believe the issue might be in some of the changes to `src/app/core` in this PR which may be causing side effects on the Browse by Issue Date / Title pages.  I could be wrong, but I wanted to report these findings to ensure this PR gets more analysis.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @KoenP and @alexandrevryghem !  Verified this is working correctly now.  Tested the Process Detail is refreshing properly & that Collection Source import process is working well. Code looks good too.

(Also verified locally that `yarn e2e` is no longer timing out..so the e2e test issues appear fixed as well.)

This can be merged _as soon as_ the backend PR DSpace/DSpace#9241 is ready. (it needs some updates based on feedback & based on recent changes to `main`)

**Comment by tdonohue** [comment]
Backend PR is complete.  Re-tested this today, and it still works well.  Merging immediately.

**Pull request merged**
