### PR TITLE
 Improve logging Angular implementation

### LINKED ISSUE #1248: Improve logging Angular implementation
This issue relates to https://github.com/DSpace/DSpace/pull/3303
To get the best from this logging mechanism, the Angular UI should be improved by adding to all the requests these two new custom header

- X-CORRELATION-ID with a random generated uuid or any hard to conflict string generated at the application load and keep stable for all the browsing session

- X-REFERRER to note the page that has generated the REST request

### PR DESCRIPTION
**Pull request by atarix83**
## References
* Fixes #1248

## Description
To get the best from this logging mechanism, the Angular UI should be improved by adding to all the requests these two new custom header

  -  X-CORRELATION-ID with a random generated uuid or any hard to conflict string generated at the application load and keep stable for all the browsing session

   - X-REFERRER to note the page that has generated the REST request

## Instructions for Reviewers
Check in the browser network console if the new headers are attached for each request to rest server

List of changes in this PR:
* Add the creation of an uuid at app initialization and save to a session cookie
* Create a new interceptor in order to attach the new headers to each http request

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
Assigning this to @artlowel and I to review once it's ready (since it's small though, I flagged for 1 approval, so whoever tests it first is fine with me).  Currently though, it appears to be failing some tests @atarix83 .  Let us know when you feel it's ready for review.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@atarix83 : I gave this a try today, and (currently) it crashes the entire UI when running `yarn start`.  It builds successfully, but when I access the UI it never successfully loads, and on the commandline I see this error: 

```
[10:34:33 GMT-0500 (Central Daylight Time)] Listening at http://localhost:4000/
ERROR {
  statusCode: undefined,
  statusText: undefined,
  message: "Cannot read property 'length' of undefined"
}
```

I suspect this issue is the same reason that the e2e tests currently all fail...the UI isn't starting up properly for some reason.

**Comment by artlowel** [comment]
I can reproduce @tdonohue's issue. On the client I also get a CORS error on every request. Perhaps that is the cause for the problem, and if that's the case it may simply be an issue with the REST PR: https://github.com/DSpace/DSpace/pull/3303

**Review by tdonohue — APPROVED** [review]
👍 Re-tested today with the updated backend PR (https://github.com/DSpace/DSpace/pull/3303) and it's working now.  As mentioned in a recent meeting, the necessary change was on the backend -- the new Http Headers needed to be added to the list of "allowedHeaders" in Spring Boot.

All in all, this looks good to me.

**REMINDER TO ALL:** Because our e2e tests run on the latest REST API `main` code, they will **never succeed** for this PR until the corresponding REST API PR is merged (as the `main` code will block the new HTTP Headers sent by this PR).  So, e2e test failures can be ignored in this PR as they are expected behavior.

**Review by artlowel — APPROVED** [review]
Thanks @atarix83!

**Comment by tdonohue** [comment]
After merging the REST side PR (https://github.com/DSpace/DSpace/pull/3303), all PR checks now succeed!  Merging this one as well since it's at +2.

**Pull request merged**
