### PR TITLE
fix for filter suggestion issue and bitstream description issue

### LINKED ISSUE #1681: Filter value selected from lookup doesn't work in the same way as clicking on checkbox
**Describe the bug**
When in a search filter (e.g. Authors) an existing filter value entry is selected from a lookup result, the filter doesn't work the same as clicking directly on a filter value. The result is that the selected filter value is duplicated two times and also the filter values of the resulting search are different than when clicking on the same filter value directly. 

**To Reproduce**

https://user-images.githubusercontent.com/2486489/172673681-9acfe0bd-3788-4150-872e-9c6d8975b4ff.mp4

**Expected behavior**
I expect that if a filter value resulting from a lookup is selected the search reacts in the same way when the filter is selected by clicking on the checkbox

### LINKED ISSUE #1682: Bitstream description overflows in admin edit
**Describe the bug**
When the description of a bitstream is long (a paragraph, for example), once displayed in edit section (Bitstream tab) it overflows and make hard to understand other information provided for the bitstream and to perform bitstream related actions

**To Reproduce**
1. Create a new item
2. add an attachment
3. Insert a paragraph in file details 
image

5. deposit the item
6. Open the item in edit mode and go to "Bitstreams" panel 
image

**Expected behavior**
description on many lines or limited / truncated. Or just limited with full text shown as tooltip in case of mouse over event

As 4Science, we can take in charge this little fix / UX improvement, for which we roughly estimate 4 hours of work

### PR DESCRIPTION
**Pull request by atarix83**
## References
* Fixes #1681
* Fixes #1682

## Description
The issue regarding the filter has been resolved by changing the bahaviour of the suggestion list. Now when clicking on a filter suggestion the search is triggered directly with the proper filter operator.

The issue regarding the bitstream description has been resolved with a text truncate and a tooltip to show the entire description :
Screenshot 2022-06-14 at 1 31 26 PM

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by abollini — APPROVED** [review]
tested, both issues have been solved. Thanks @atarix83

**Comment by tdonohue** [comment]
@artlowel : Thanks for your feedback here.  I had forgotten about that feature of filters (that you can use NOT or wildcard syntax).  That said, I do agree with you last statement that the "tradeoff might be worth it".  

I'll retest today to be sure to understand the behavior on `main` vs this PR & what the tradeoff essentially is.  I do suspect though that few people are aware of those Lucene syntax filter queries... which is why the current behavior on `main` is seen as confusing.

**Comment by atarix83** [comment]
@artlowel @tdonohue 
I think most of the users are not aware of Lucene syntax filter queries, and see the current behaviour as weird/buggy. 
Furthermore with this PR Lucene syntax can be still used anyway but you have to write it throughout. 
Honestly I don't see as a big side effect

**Comment by tdonohue** [comment]
@artlowel and @atarix83 :  I've retested this, and verified that the wildcard (`*`) & negative (`-`) filter searches both still function the same as on `main`.  But, as noted, you cannot use autocomplete of names...so you'd need to type the query out.

I think this is tradeoff is worth the better usability.  I do think that #1681 is a usability bug in that it shows confusing behavior.  I  better understand why it worked that way, but I think this new behavior is more straightforward to most users.  Advanced users still can use these Solr syntax filters but they need to do more typing for now.  

So, I'm going to merge this for 7.3.  I do feel that we can revisit it later on if we see a major side effect...but this PR looks like an improvement to me.

**Pull request merged**
