### PR TITLE
bugfix of issue 897

### LINKED ISSUE #897: TypeError: Cannot read property 'uuid' of undefined
Try to access property `uuid` of undefined variable `metadata` in `FilterInputSuggestionsComponent` which leads to a type error (as shown in Chrome's web dev console). This error occurs only in context of facet filter generation. 

The error is issued by the statement at line 80 ([file](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/input-suggestions/filter-suggestions/filter-input-suggestions.component.ts#L80))

```js
    this.objectUpdatesService.setValidFieldUpdate(this.url, this.metadata.uuid, this.valid);
```

1. clone git repo dspace-angular (use branch `main`)
2. run `yarn install` 
3. run `yarn start`
4. open Chrome browser and dev console
5. go to http://localhost:4000/search
6. click into search form input field

Error message in dev console:
```
ERROR TypeError: Cannot read property 'uuid' of undefined
    at t.checkIfValidInput (filter-input-suggestions.component.ts:80)
    at Object.handleEvent (filter-input-suggestions.component.ngfactory.js.pre-build-optimizer.js:48)
    at Object.handleEvent (core.js.pre-build-optimizer.js:29239)
    at Object.handleEvent (core.js.pre-build-optimizer.js:29784)
    at qp (core.js.pre-build-optimizer.js:19859)
    at core.js.pre-build-optimizer.js:21044
    at t.i [as _next] (core.js.pre-build-optimizer.js:23747)
    at t.__tryOrUnsub (Subscriber.js.pre-build-optimizer.js:194)
    at t.next (Subscriber.js.pre-build-optimizer.js:132)
    at t._next (Subscriber.js.pre-build-optimizer.js:76)
```

PR that fixes the problem follows.

### PR DESCRIPTION
**Pull request by saschaszott**
## References

Fixes #897

## Description

perform missing check for undefined / null

## Instructions for Reviewers

apply change and perform steps to reproduce the error as stated in #897 

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
Thanks @saschaszott for this bug fix!   I *think* this may also fix #867 (which looks to be the same error found in a different way).  I'll see if I can find a reviewer (or test this myself) to verify the fix.

**Review by artlowel — COMMENTED** [review]
Thanks @saschaszott!

While this fixes the symptom, the reason for this issue is that validation was added to this component, but it doesn't need validation everywhere it's used. So perhaps a better workaround would be to add an @Input() to toggle validation, and to only enable it for the edit-in-place field

That doesn't mean you have to be the one to do that @saschaszott. But if you want to, it would be appreciated.

**Comment by saschaszott** [comment]
@artlowel I do not agree completely: the component `FilterInputSuggestionsComponent` is currently used in two different contexts: `EditInPlaceFieldComponent` and three subclasses of `SearchFacetFilterComponent`.

The problematic method call

```js
this.objectUpdatesService.setValidFieldUpdate(this.url, this.metadata.uuid, this.valid);
```

is only required in the context of `EditInPlaceFieldComponent` (in this context values for both `@Input` variables `url` and `metadata` of `FilterInputSuggestionsComponent` are supplied):

```html
            <ds-filter-input-suggestions [suggestions]="(metadataFieldSuggestions | async)"
                                         [(ngModel)]="metadata.key"
                                         [url]="this.url"
                                         [metadata]="this.metadata"…
            ></ds-filter-input-suggestions>
```

**Comment by artlowel** [comment]
I realize that that metadata property is currently only present when validation is required, but the logic: if the metadata property has a value, then validation must be required seems a little arbitrary. It also isn't very good at communicating to people looking at this code later on how they should configure the component if they use it somewhere else

**Comment by saschaszott** [comment]
@artlowel Would it be more concise to use the `form` only in context of `EditInPlaceFieldComponent`?

**Comment by artlowel** [comment]
Leaving form out would have the same issue: it isn't obvious how it's related to validation for someone using the component.

Perhaps the best thing to do would be to create e.g. a ValidationSuggestionsComponent, that extends FilterInputSuggestionsComponent and adds the FormGroup, the metadata input and the validation function, use that in EditInPlaceFieldComponent, and use [the original FilterInputSuggestionsComponent](https://github.com/DSpace/dspace-angular/blob/5c101d116a8db8ac40da236723744deb1e229508/src/app/shared/input-suggestions/filter-suggestions/filter-input-suggestions.component.ts) everywhere else

**Comment by tdonohue** [comment]
@saschaszott and @artlowel :  Having caught up on this discussion, I like @artlowel's last recommendation here...it sounds (to me) like we need two components which allow a developer to decide whether they want validation turned on or off, based on the component used.

I agree that the concept of assuming validation is always required if metadata property exists seems a little odd (even if that's currently the case in our codebase).  In the long run, I like the idea of having a validating component which extends a non-validating one, so you can decide which you'd like to use.

As @artlowel initially said, I don't think that means this work needs to come from @saschaszott .  So, @saschaszott , if you aren't interested in that code refactor, I can assign this to someone else -- this PR you've created already has been a good contribution (in terms of discussion of the best solution) even if we'd rather refactor the code more thoroughly.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@saschaszott and @artlowel :  Having caught up on this discussion, I like @artlowel's last recommendation here...it sounds (to me) like we need two components which allow a developer to decide whether they want validation turned on or off, based on the component used.

I agree that the concept of assuming validation is always required if metadata property exists seems a little odd (even if that's currently the case in our codebase).  In the long run, I like the idea of having a validating component which extends a non-validating one, so you can decide which you'd like to use.

As @artlowel initially said, I don't think that means this work needs to come from @saschaszott .  So, @saschaszott , if you aren't interested in that code refactor, I can assign this to someone else. This PR you've created already has been a welcome contribution (in terms of discussion of the best solution) even if we'd rather refactor the code more thoroughly.

**Comment by tdonohue** [comment]
@saschaszott : I haven't heard back from you, so I'm going to assume this needs to be reassigned.  That's no problem (as I said earlier), but if you are working on this let us know.  In the meantime, I'll start asking around to see if someone else can help move this forward.  Thanks!

**Comment by tdonohue** [comment]
Closing this PR as the #897 task has been reassigned for immediate fixing.  This bug has become high priority for us as we've hit it in several different scenarios.

**Pull request closed without merging**
