### PR TITLE
Updating Hungarian translations for DSpace 8.0

### PR DESCRIPTION
**Pull request by kanasznagyzoltan**
## Description
Updating Hungarian translations for DSpace 8.0. Translating a lot of non-translated values and fixing some weird automatic translations.

## Instructions for Reviewers
- Pull my changes on the hu.json5 file
- Start the dspace-angular frontend
- Change the language from English to Hungarian

### CODE REVIEW

**Comment by msutya** [comment]
Tested it. New translations appear correctly. Looking through them, I couldn't find grammatical errors either

**Review by tdonohue — APPROVED** [review]
👍 Thanks @kanasznagyzoltan !

**Comment by tdonohue** [comment]
@kanasznagyzoltan : Could you please create a version of this PR for our `main` branch as well?  This was unable to be ported automatically (see above error), so it will have to be done manually.  Otherwise, the changes you've made will *only* be in 8.1 and will be missing from 9.0.

**Comment by kanasznagyzoltan** [comment]
> @kanasznagyzoltan : Could you please create a version of this PR for our `main` branch as well? This was unable to be ported automatically (see above error), so it will have to be done manually. Otherwise, the changes you've made will _only_ be in 8.1 and will be missing from 9.0.

Dear @tdonohue 
I am sorry for my late reply. I will also do the changes for the 9.0 version. If i will be ready in mid january, it is ok?
Thank you!

**Comment by tdonohue** [comment]
@kanasznagyzoltan : mid January is fine with me.  I was simply noting that this PR was only applied to 8.x, so your new translations will appear on our Demo site (https://demo.dspace.org).  However, the `main` branch did not receive **any updates**, so the Sandbox site (https://sandbox.dspace.org) is still likely showing old translations.  At the very least, it'd be great to get the translations you added for 8.x *copied over* to the `main` branch (even if you don't get new 9.0 keys added yet).

**Comment by kanasznagyzoltan** [comment]
@tdonohue 
I'm sorry, Tim. I promised to do this, but I haven't had the chance to complete it yet. However, I will have time in April. If it can still be included in DSpace 9.0, I’d be happy to work on it.

Thank you!

**Comment by tdonohue** [comment]
@kanasznagyzoltan : Yes, if this can be completed in April, then we can still include it in 9.0.  Thanks!

**Comment by kanasznagyzoltan** [comment]
> @kanasznagyzoltan : Yes, if this can be completed in April, then we can still include it in 9.0. Thanks!

Thank you Tim!

**Pull request merged**
