### PR TITLE
Fix themed components duplicating themself when switching themes

### LINKED ISSUE #2346: When Extending Theme It gets duplicated multiple times
**Describe the bug**
When extending the theme to overwrite it duplicates all the elements multiple times. This is with DSpace 7.6. 

So what I did was copy the dspace theme, made it called "theme1" and made my normal changes there. I then created theme2 and want to apply it to specific collections to add additional metadata fields to some of the views. 

It looks like it's rendering the original version, and the extended theme? See the photo below

image

**To Reproduce**
1. Create custom theme by copying the dspace theme (theme1)
2. Enable your new theme1
3. Create a new theme (theme2) that you want to change only `src/themes/theme2/app/item-page/simple/item-types/untyped-item/untyped-item.component.html` in
4. Enable themes in config.yml
```yml
themes:
  - name: theme2
    extends: theme1
    uuid: '6d684812-6d29-4564-8b51-f5670957936b'

  # default theme, based on DSpace
  - name: theme1
```

**Expected behavior**
I would it to only change the elements defined in

### LINKED ISSUE #2348: Bug: theme matching by handle doesn't work, but uuid does
**Describe the bug**
Matching on a collection handle does not appear to work for a collection, but using a UUID does work (except for the duplicated elements #2346)

**To Reproduce**

```yml
themes:
  - name: etdr
    extends: krex
    handle: '2097/4'
    # uuid: '6d684812-6d29-4564-8b51-f5670957936b'

  # default theme, based on DSpace
  - name: krex
```

This works though
```yml
themes:
  - name: etdr
    extends: krex
    uuid: '6d684812-6d29-4564-8b51-f5670957936b'

  # default theme, based on DSpace
  - name: krex
```

**Expected behavior**
Theming should be applied to the collection items when using the handle, or the uuid.

**Related work**

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Closes #2346

## Description
This PR fixes 4 issues related to theming:
-  A bug where the old component is not destroyed when the theme is updated which leads to the every themeable component being duplicated every time the theme changes.
- A rare issue in production mode where the `@ViewChild` variables can sometimes still be uninitialised when trying to render the component, leading to the component not rendering.
- An error where the base theme wouldn't be restored after leaving a UUID/handle theme (this issue only happend when there was no default/fallback theme set).
- An infinite loop caused by the `createHeadTags` method when not overriding the `headTags` property in you themes (only the case when you have themes extending each other)

## Instructions for Reviewers
List of changes in this PR:
* Changed the `ngOnInit()` to `ngAfterViewInit()`, because `@ViewChild` is only initialised after the OnInit, but right before AfterViewInit (see [docs](https://angular.io/api/core/ViewChild)). This is often not an issue because Angular is slow enough because of relatively large/complex HTML templates, and by the time the `ThemedComponent` tries to create the component the AfterViewInit hook will often already have been called. But sometimes it does resolve fast enough (for example the `HomeNewsComponent` which only contains text and an image) and then the code breaks when it [tries to create the component](https://github.com/DSpace/dspace-angular/blob/404ccd9b0ecdcdfe63ad22779859b1a01eddc12e/src/app/shared/theme-support/themed.component.ts#L124) because `vcr` is still `undefined`.
* Ensured that `destroyComponentInstance()` is always triggered before the `ThemedComponent` creates it's new component.
* Ensured that the base theme is restored when leaving a UUID/handle theme, this was done by fixing the `ThemeService. getActionForMatch` method who doesn't update the current theme, when the new fallback/default theme is not set. This is for example the case when you only use this theme config:
  ```yml
  themes:
    - name: dspace
      handle: '123456789/1'
  ```

**Guidance for how to test/review this PR:**
Error 1:
- Add the following config to you `config.yml` file:
  ```yml
  themes:
    - name: dspace
      extends: custom
      handle: '123456789/1'
    - name: custom
  ```
- Go to the home page and check that the custom theme is being used
- Go to the top level community `123456789/1` and check that the dspace theme is being used (you can easily spot it by looking at the header)

Error 3:
- Replace the `themes` config with the following config in your `config.yml` file:
  ```yml
  themes:
    - name: dspace
      handle: '123456789/1'
  ```
- Go to the top level community `123456789/1` and check that the dspace theme is being used (you can easily spot it by looking at the header)
- Go back to the home page and check that the base theme is used again

Error 4:
- Use the following config:
   ```yml
   themes:
     - name: dspace
        extends: custom
     - name: custom
   ```
- Check that the `createHeadTags` method isn't throwing an infinite loop error anymore in the browser console
- Check that the default favicon is used
- Overwrite the `headTags` in the custom theme by adding a custom favicon for example & check that the new favicon is used
- Overwrite the `headTags` in the dspace theme by adding a custom favicon for example & check that that new favicon is used instead of the one from the custom theme

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by misilot** [comment]
@alexandrevryghem thank you for this! This fixed the duplicative elements I was seeing!

**Comment by alanorth** [comment]
Thanks @alexandrevryghem! I had problems rebasing this PR branch on top of `dspace-7_x`, but after cherry-picking the first three commits I also noticed that my themed components were no longer duplicated when switching themes:

- [103176: Fix vcr not being defined yet in OnInit hook](https://github.com/DSpace/dspace-angular/pull/2395/commits/928d7a45a372003547b86be1ff3725288da43ad4)
- [101577: Ensure the component is always destroyed before rendering the…](https://github.com/DSpace/dspace-angular/pull/2395/commits/873a8e16a362794eab85d09afa73c9f6c787c169)
- [Reset to base theme when no default theme is set and leaving UUID/han…](https://github.com/DSpace/dspace-angular/pull/2395/commits/ea677bda741bdccee8422945fb9cd7caa4f1e450)

So take that as a partial +1 from me. I would be very interested in a DSpace 7 port of this pull request.

**Comment by alanorth** [comment]
Thanks @alexandrevryghem. I managed to merge the branch, but ironically now my extended themes don't work at all. :thinking:

**Comment by misilot** [comment]
How are you doing your matching for the theme? By handle or UUID? If by handle try switching to UUID. On Aug 25, 2023, at 12:18 AM, Alan Orth ***@***.***> wrote:﻿
Thanks @alexandrevryghem. I managed to merge the branch, but ironically now my extended themes don't work at all. 🤔

**Comment by alanorth** [comment]
Hey @misilot, sorry yes, I updated my comment shortly after. I had reset my branch and forgot to add my custom theme back to `angular.json`. Everything is working now, and I'm wondering what else to test.

**Review by alanorth — APPROVED** [review]

**Pull request merged**
