### PR TITLE
Portuguese Translation [Work in progress]

### PR DESCRIPTION
**Pull request by vitorsilverio**
Initial translation to PT
- [x] 404 messages
- [x] bitstream messages

Please tell me if i need to translate everything before merge, i can keep updating this PR until there.

### CODE REVIEW

**Comment by bram-atmire** [comment]
Hi @vitorsilverio - many thanks for your translation! If you are willing to translate the entire catalog, yes, please, do it as multiple commits to this pull request & we'll finalize the review and the merge when you are done. 

You're also welcome to contribute it in smaller pieces, but definitely preferred if you can do it entirely in the scope of a single pull request.

**Comment by vitorsilverio** [comment]
OK @bram-atmire i ll translate everything and ping you when i finish

**Comment by vitorsilverio** [comment]
@bram-atmire i finished the translation

**Comment by vitorsilverio** [comment]
I think i done something wrong when merge, a lot of files were added to my PR

**Comment by vitorsilverio** [comment]
Closing this, the translation is PR #525

**Comment by bram-atmire** [comment]
@vitorsilverio I think it's because of some changes that were applied to master in the meanwhile. I *think* a the owner of the pull request, you should have a button somewhere that says REBASE.

Otherwise, it's also possible to close this pull request and start a new one.

**Pull request closed without merging**
