### PR TITLE
E2E test stabilization, and upgrade to latest Cypress v9 and axe-core

### PR DESCRIPTION
**Pull request by tdonohue**
## Description
Simple PR to attempt to stabilize some randomly failing e2e tests.  Based on what I've seen in recent CI runs, it looks like there are three main random failures:
* Random authentication errors (sometimes the auth fails... I've attempted to fix this in this PR)
* Random accessibility testing failures (Not sure our code is at fault. Appears to be a possible bug in Cypress or Axe. So, I upgraded to latest axe-core and cypress to see if that helps)
* Random page not loading failures.  Uncertain of the root cause at this time.  May be a Cypress issue?

This PR does the following:
* Upgrade us to the latest version of Cypress v9 and `axe-core`.
    * (NOTE: [Cypress v10](https://docs.cypress.io/guides/references/migration-guide) is also now available, but that's a major upgrade requiring refactoring of existing e2e tests.  So, that may require much more work to complete & may need to be scheduled for a future date.)
* Change our authentication strategy in e2e tests to use the login form in the UI.  Previously we were using requests directly to the backend REST API to authenticate -- while that approach is likely faster, it seems to sometimes hit random failures (possibly cause of an out-of-sync CSRF token?).  It's likely more stable to use our login form at all times.

## Instructions for Reviewers
* Verify e2e tests pass & seem more stable.
* Check code.

### CODE REVIEW

**Comment by tdonohue** [comment]
This is ready for review now.  While it hasn't fully stabilized *all tests* (After restarting tests 5 times, I did finally hit some random Axe accessibility check failures), it seems better than previously.

**Comment by tdonohue** [comment]
@artlowel : This might be one you could quickly review. From what I've seen, these small changes make the e2e tests *more stable*, but there still will be some random failures (they seem less frequent though)

**Review by atarix83 — APPROVED** [review]
thanks @tdonohue 

it seems to be better, but we can't be 100% sure it resolves the random errors definitely.
I think we need to keep monitored for upcoming builds after the merge and plan to migrate to new cypress v10

**Comment by tdonohue** [comment]
Agreed @atarix83. I don't think this is going to fix the random failures 100% of the time, but I find the random failures are less frequent with this PR in place.  I also agree that an upgrade to Cypress v10 is needed at some point...however, that's a major upgrade (I attempted it locally & found it to be quite complex & wasn't able to get it working properly -- I think v10 still is a bit buggy).

In any case, merging this immediately & we'll see if this has a decent impact or if we need to prioritize a Cypress v10 upgrade sooner.

**Pull request merged**
