### PR TITLE
Remove Bitstreams on edit-item-page doesn't work

### LINKED ISSUE #3116: Remove Bitstreams on edit-item-page doesn't work
**Describe the bug**
A new issue appeared, where you can't remove the bitstreams of an item using the edit-item-page. After selecting bitstreams for deletion, the **Save**-button stays deactivated. Only if you select bitstreams of all existing bundles, the button is clickable. 

**To Reproduce**
1. Login as an site-administrator
2. Open the edit-item-page of an item with attached bitstreams
3. Navigate to the *Bitstreams*-tab.
4. Click on the tiny garbage-can of one bitstream for deleting it.
5. Try to click *Save* in order to apply the changes (you can also try to *Discard* the changes, it won't work either) 

**Expected behavior**

The **Save** or **Discard** buttons should be clickable.

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #3116
* Related #3060
* Port #3127

## Description
Fixed the issue on the edit bitstream tab from the item page, and also fixed the same kind of performance issues on the Content Source tab from edit collection.

## Instructions for Reviewers
List of changes in this PR:
* Fixed the issue on the edit bitstream tab. This issue has been fixed by replacing the `observableZip` with an `observableCombineLatest` because when you have multiple bundles, the `this.objectUpdatesService.hasUpdates` won't emit for all the bundles causing the `observableZip` not to emit and update it's value. By changing it to an `observableCombineLatest` even when one bundle has been changed the whole observable will update.
* The same type of optimisation (like done on the edit relationship & edit bitstream tab) also still needed to be applied to the Content Source tab from edit collection so I also fixed this at the same time

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alexandrevryghem** [comment]
While testing this PR I discovered that the discard & save buttons were not automatically disabled again after deleting a bitstream. I tested this on the `dspace-7.6` tag and was also able to reproduce it there. This is caused by a bigger caching issue, so I'm putting this PR as "Ready for review" and will try to contribute a fix for that issue too but this will most likely be for 8.1

**Comment by Leano1998** [comment]
Thanks @alexandrevryghem  for the fix!
I tested it locally and it worked fine for me.

**Comment by tdonohue** [comment]
Closing & reopening to reboot GitHub actions.  (For some reason they didn't spin up properly with this PR.)

**Comment by tdonohue** [comment]
@alexandrevryghem : Is there also a `main` version of this PR?  I believe this bug is occurring on both 7.x and main.  (I tried pulling this PR into main but there's several conflicts)

**Comment by alexandrevryghem** [comment]
@tdonohue: I created the port PR #3127

**Review by tdonohue — APPROVED** [review]
👍 Thanks again @alexandrevryghem !  Tested this via #3127.. Verified this code is identical for 7.x.

**Pull request merged**
