### PR TITLE
Remove ng-high-memory & remove Node v10 support

### LINKED ISSUE #1037: Make memory to build UI more configurable
**Describe the bug**
Currently, we "hardcode" & require 8GB of available memory to build the Angular UI.  See this setting:
https://github.com/DSpace/dspace-angular/blob/main/package.json#L26

Ideally, we should support systems which have less than 8GB of available memory, as there's no reason (that I can tell) for this default setting except that it speeds up the build on systems which have more memory available.  There's no way to easily override this default setting, unless you manually edit the `package.json` before building the UI.

Should we consider **removing** the `--max_old_space_size=8192` flag in that setting?  That would allow users more control over how much memory they wanted to provide by using the `NODE_OPTIONS` environment variable, like:

`NODE_OPTIONS="--max_old_space_size=8192" yarn start`

~~(The downside to this approach appears to be that `--max_old_space_size` seems to default to 512MB, which is really low)~~
**UPDATE:** In Node v12, it appears that Node might automatically just use "available memory".  See "Properly configure default heap limits" section here: https://nodejs.medium.com/introducing-node-js-12-76c41a1b3f3f

Obviously, if we remove this default, we may want to update our CI build process to still use 8GB by setting this environment variable in our build.yml: https://github.com/DSpace/dspace-angular/blob/main/.github/workflows/build.yml#L12

### PR DESCRIPTION
**Pull request by artlowel**
## References
* Fixes #1037

## Description
This removes ng-high-memory, because starting from node 12, it is no longer needed or even advisable to set the amount of memory required.

## Instructions for Reviewers
To test this, verify that the scripts that used ng-high-memory still work: start, test, ci, and lint-fix

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@artlowel : This looks great, **however** if you look at our Node v10 build in GItHub Actions, you'll see it's hitting memory issues now. 

So, for the time being, I **think** we need to set `NODE_OPTIONS="--max_old_space_size=8192"` in our CI configuration.  Doing so should just be a matter of  adding this to the [`env` section](https://github.com/DSpace/dspace-angular/blob/main/.github/workflows/build.yml#L12)

```
env:
   # Tell node to use a max of 8GB memory
   # NOTE: this can be removed once we drop support for Node v10 as v12+ manage memory automatically
   NODE_OPTIONS: '--max_old_space_size=8192'
```

That should get the v10 builds/tests working again.

**Comment by tdonohue** [comment]
After a bit more thought, maybe we should just go with my **alternative** suggestion.  Moving us off Node v10 now would simplify our documentation (as we'd need to warn them to set NODE_OPTIONS), and it seems like this may be a good opportunity to add in v14 to our CI tests.  But, I'm open to suggestions

**Comment by artlowel** [comment]
I agree, I'll update the PR to switch to node 12 and 14 builds on Github Actions

**Review by tdonohue — APPROVED** [review]
👍 Thanks @artlowel .  This looks correct and is passing tests for Node v12 & v14.

**Pull request merged**
