### PR TITLE
Live REST API & Dso list component

### PR DESCRIPTION
**Pull request by artlowel**
This PR connects to #98 and connects to #111

It contains:
- The switch to the live REST API
- The DSO List component
- A start to the Browse Component (but still in strong need of refactoring)

My apologies for the fact that it isn't split up neater, but I'm out of time.

Known issues: 
- Going to the URL of any page in a paginated list will always send you to the first page 
- Downloaded files will always have the filename "retrieve"

### CODE REVIEW

**Comment by artlowel** [comment]
>Going to the URL of any page in a paginated list will always send you to the first page

The last commit fixes this issue

**Comment by tdonohue** [comment]
@artlowel : apologies, I didn't get to testing this. But, I'd say go ahead and merge once you are satisfied.  If you have any concerns, we can wait to merge post-OR2017, and simply use your demo site for any demos at OR.

**Comment by rivaldi8** [comment]
I've tested it a bit and all seems to work properly. I've just found a minor issue between the pagination and the browser's back button.

For example, if you navigate to the item of the second page of the collection's item list, then go back in history, it goes to the first page of the item list instead of to the second. The pagination shows the second page as active, though.

**Comment by artlowel** [comment]
@rivaldi8 I can reproduce the problem but I'm going to merge it, and open a separate issue for it

**Pull request merged**
