### PR TITLE
Layout improvement in feedback form page

### PR DESCRIPTION
**Pull request by saschaszott**
## Description

This PR applies some layout improvements to the feedback form page by increasing vertical spacing.

### Before

image

### After

image

### CODE REVIEW

**Comment by tdonohue** [comment]
@saschaszott : This has code conflicts. If you wish to have it still considered for 8.0, please get this PR cleaned up and updated to latest `main`. Otherwise, we'll have to reschedule for 9.0. Thanks!

**Comment by saschaszott** [comment]
@tdonohue , conflicts were resolved ;)

**Review by tdonohue — APPROVED** [review]
👍 Thanks @saschaszott !  Tested today and verified the layout has better spacing.  Also verified everything still works properly

**Comment by tdonohue** [comment]
Failing tests here are from an unrelated e2e test.

**Pull request merged**
