### PR TITLE
Cannot map new items with Collection Admin

### LINKED ISSUE #1203: Cannot map new items with Collection Admin
A Collection Admin should be able to add (map) existing items from other collections

**Describe the bug**
The Collection Admin can edit item metadata, assign roles but cannot map existing items from other collections.

**To Reproduce**
1. Log as a "Collection Administrator" (not as an Admin)
2. Edit the collection for which you have permissions
3. Go to "Item Mapper" -> "Map new items"
4. Click on "Search" and select any item
5. Click on "Map selected items"

**Expected behavior**
A new item should be mapped in the collection

### PR DESCRIPTION
**Pull request by alemarte**
## References
* Fixes #1203

## Description
The Object Selector component has been enhanced. Is now possible to pass a FeatureID to check against to decide whether an item is selectable or not according to this authorization check.

## Instructions for Reviewers
The CollectionItemMapperComponent now inject the feature `canManageMappings` to the inner object selector component. This way only those items on which the user has that authorization will be selectable to be part of the mapping request.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@alemarte : I tested this today, and it doesn't seem to fully solve #1203 ... but I cannot quite tell if the bug is on the frontend or if it's in the original backend PR DSpace/DSpace#3240 (created by @Micheleboychuk). 

Here's how this should work for various roles:

1. **Site Admins** can obviously map items between any Collections in the site. **(WORKS)**
2. **Community Admins** can only map items across Collections within Community(ies) they administer (but cannot map items from other Communities) **(PARTIALLY WORKS)**
3. **Collection Admins** can only map items if they administer multiple collections...in which case they can map from one Collection they administer to another they administer **(DOESN'T WORK)**

Here's how to reproduce the issues that I see

**Community Admin issue:**
* Login as a Site Admin & make a user the Admin of a Community which has multiple Collections
* Login as that Community Admin
* Edit one of the Collections under your Community
* Select Item Mapper
* Search for an Item contained by another Collection under your Community. **This works!**
* Search for an Item contained by a *Collection in a different Community*.  You'll be able select it (checkbox is not disabled).  **This results in a 403 error.** _(EXPECTED BEHAVIOR: Checkbox should be disabled, as Community Admin doesn't have permissions to do this mapping)_

**Collection Admin issue:**
* Login as a Site Admin
* Make a single user a Collection Admin on *two collections*
* Login as that Collection Admin
* Edit one of the Collections you Administer
* Select Item Mapper
* Search for an Item contained by the *other* Collection you Administer
* You'll find the item, but **you won't be able to map it, as its checkbox is disabled**.  _(EXPECTED BEHAVIOR: Checkbox should be enabled, as Collection Admin has Admin privileges in both Collections and should be allowed to do this mapping)_

Again, I'm not fully certain whether the issues are on the UI side or the REST side...or maybe a combination of both.  But, maybe between you and @Micheleboychuk , you can figure out where the issues are?

**Comment by alemarte** [comment]
@tdonohue Thanks for your review and a detailed explanation on how to reproduce the relevant cases.

It seems that the problem is on the REST side. In particular the end point 

`http://localhost:8080/server/api/authz/authorizations/search/object?uri=http://localhost:8080/server/api/core/items/<ItemUUID>&feature=canManageMappings&embed=feature`

does not act as we expect and as you described the select checkbox can be wrongly disabled or wrongly enabled leading to 403 error.

**Comment by alemarte** [comment]
This PR can now be tested together with the REST counterpart https://github.com/DSpace/DSpace/pull/3318

**Review by tdonohue — CHANGES_REQUESTED** [review]
@alemarte : I've re-tested this with https://github.com/DSpace/DSpace/pull/3318 applied to the backend, and the behavior is improved, but still doesn't work for Collection Admins.
1. **Site Admin** behavior is still working as expected
2. **Community Admin** is now *fixed* & working as expected
3. **Collection Admin** behavior is the same as [previously reported](https://github.com/DSpace/dspace-angular/pull/1250#pullrequestreview-694358433).  It doesn't appear that a Collection Admin ever can map items, even if they administer multiple collections. Currently, it seems the checkboxes on the item mapper page are always disabled for Collection Admins.

All that said, as I've noted in the REST PR review, if we feel that it's not easily possible to support this feature for Collection Admins, another solution could be to limit access to the "Item Mapper" tab to only Site or Community Admins for now.  

So, either the REST API PR from @Micheleboychuk should be fixed to support Collection Admins, *or* this Angular PR should be updated to disable the "Item Mapper" tab when you are logged in as a Collection Admin.

**Review by tdonohue — APPROVED** [review]
👍 I retested this today (with the backend PR) based [on the feedback from @abollini](https://github.com/DSpace/DSpace/pull/3318#issuecomment-880860105) .  It is working completely after I made sure to do a full reindex prior to testing.

Thanks @alemarte for your hard work here!  No changes are necessary, as it seems the issue was entirely on my end.

**Pull request merged**
