### PR TITLE
Use thumbnail links for items and bitstreams

### LINKED ISSUE #1213: Thumbnail resolution should happen on the rest side
**Is your feature request related to a problem? Please describe.**
Finding the correct thumbnail for an item or a bitstream is every slow at the moment, because it is done client side. The UI has to download the entire thumbnail bundle, ignoring pagination, to compare filenames with bitstreams in the ORIGINAL bundle and find a match.

We've never had much issues with this because we've never used DSpace 7 in a situation where we had a lot of items with a lot of bitstreams and thumbnails. If you do the performance becomes very poor in situations where you need to resolve multiple thumbnails quickly, e.g. the search result grid view.

**Describe the solution you'd like**
I created https://github.com/DSpace/DSpace/issues/3286 to get this issue addressed by adding optional `thumbnail` links to bitstreams and items. 

Afterwards we'll need to update the UI to make use of these links and to get rid of the old matching code

This can be done in an estimated **4 hours**

### PR DESCRIPTION
**Pull request by ybnd**
## References

* Fixes #1213
* Requires DSpace/DSpace#3309

## Description

Update `Item` / `Bitstream` models to match the new `thumbnail` endpoint introduced in DSpace/DSpace#3309.

Remove the old workaround method to retrieve thumbnails.

## Changes

* Refactored `followLink` (see below)
* Include `thumbnail` endpoint in `Item` and `Bitstream` models
* Added some `followLink` calls where thumbnails are to be retrieved along with the Item
* Updated Item components (pages, list elements, ...) to use `Item.thumbnail`
* Removed `BitstreamDataService#getThumbnailFor` and `BitstreamDataService#getMatchingThumbnail`

#### `followLink` refactor (@artlowel)

In order to embed these thumbnail links with search results, we've had to add support for optional links to the `followLink()` function. Search results can contain both items that can have the thumbnail link as well as communities and collections that can't.

Because the amount of situational parameters for that function was getting to be quite large, we've refactored it to move all these situational parameters to a single object: https://github.com/DSpace/dspace-angular/commit/0d5fc8a1c0035e59b9ed44cbfccc4c6fc66c823f. That way, the signature of that function won't need to change again after this, and if you only want to change one these parameters you no longer have to supply the default values of all the others. 

It does mean we've had to update _every_ followLink call that used one of these parameters which makes this PR seem a lot bigger than it is.

## Instructions for Reviewers

1. Select (or create) some Items with Bitstreams and corresponding thumbnail Bitstreams
2. Go to `/search` and set the view to grid. Search for an Item with thumbnails.
   * The search result grid elements should load the Items' thumbnails
3. Open one of the Items' "simple" page
   * The page should load the Item's thumbnail
4. Open one of the Items' "full" page
   * The page should load the thumbnails of the Item's Bitstreams

## Checklist

_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
@ybnd : Just a quick note...it looks like LGTM has noted (in comment above) that you have several unused imports to clean up in this PR. Looks to me like in some places you removed code without also removing the corresponding import statements, which resulted in this LGTM alert.

**Comment by ybnd** [comment]
@tdonohue That should be all of them, I'll check tomorrow to make sure 👍

**Review by tdonohue — APPROVED** [review]
👍 Thanks @ybnd and @artlowel ! Tested this today with the corresponding backend PR, and I found no obvious problems. Thumbnails are still loading properly both for regular items and entities. Also verified that thumbnail permissions still work properly (e.g. thumbnail will not be displayed publicly if it is access restricted), and that works too.  Thanks again!

**Comment by tdonohue** [comment]
Merging with one approval, as the actual code changes are small here (lots of repetition of the minor followLink refactor, and specs updates)

**Pull request merged**
