### PR TITLE
Fix: Item edit pages not hidden/redirect for anon or non-authorised users

### LINKED ISSUE #2728: Edit authorizations page (& other item edit pages) not hidden/redirect for anon or non-authorised users
**Describe the bug**
The item page edit authorizations ({item-page}/edit/authorizations) loads for anon users and users that don't have edit permission on an item.
Example: https://demo.dspace.org/entities/publication/27ed7c48-f460-4deb-a8b5-f6e442fbe2d4/edit/authorizations

Anon / Unauthorised user can't read current RP or add new ones (because no results for users/groups search) though, so page not functional / provides no hidden info for them.

Idem for make private page ({item-page}/edit/private), eg: https://demo.dspace.org/entities/publication/27ed7c48-f460-4deb-a8b5-f6e442fbe2d4/edit/private

Idem for item move page ({item-page}/edit/move), eg: https://demo.dspace.org/entities/publication/27ed7c48-f460-4deb-a8b5-f6e442fbe2d4/edit/move

Idem for item delete page ({item-page}/edit/delete), eg: https://demo.dspace.org/entities/publication/27ed7c48-f460-4deb-a8b5-f6e442fbe2d4/edit/delete

**To Reproduce**
1. As anonymous / non logged in user, go to a {item-page}/edit/authorizations page
2. Verify this shows empty list of RP for the item (& its bundles)
Idem for logged in user that does not have edit rights on that item.

Idem for make private page ({item-page}/edit/private)
Idem for item move page ({item-page}/edit/move)
Idem for item delete page ({item-page}/edit/delete)

**Expected behavior**
- For anon should redirect to login page
- For user without item edit rights => should show forbidden page

### PR DESCRIPTION
**Pull request by ZahraaChreim-Atmire**
## References
* Fixes #2728

## Description
Refactored all guards based on SomeFeatureAuthorizationGuard as well as their dependents into functional guards for compatibility with Angular 17. Additionally, ensured proper fixes across module files, resolvers, and tests to accommodate these changes, while addressing issue #2728 with additional guard implementation and corresponding test coverage.

## Instructions for Reviewers
List of changes in this PR:
* First, refactored SomeFeatureAuthorizationGuard and SingleFeatureAuthorizationGuard as functional guards as well as all other guards that extended them.
* Second, updated all the routes that use them and verified that they still function in exactly the same way as they do on demo.dspace.org
* Third, refactored the unit tests to work with the new functional guards as well.
* Fourth, created new guards for the routes described in issue #2728 and verified that after adding them the issue no longer occurs.
* Fifth, wrote unit tests for the new guards.

How to test and review this PR:
* Steps to reproduce the bug can be found in #2728
* With the new feature, anon users are redirected to login page, and users without item edit rights are shown forbidden page
* These changes aim to prevent unauthorized access to certain Item pages requiring specific authorizations.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@ZahraaChreim-Atmire : Overall this looks good & I've verified it fixes the issues described in #2728 .  However, it seems to have accidentally **broken** the ability of Community/Collection Administrators to manage roles/groups.

Here's how to reproduce the bug I'm seeing:
1. Start by running this PR in prod mode (`yarn build:prod; yarn serve:ssr`).  It might also occur in Dev mode
2. Login as a user with Community Admin permissions
3. Visit the Community you are an Admin of, and edit it. 
4. Now visit the "Assign Roles" tab.   Attempt to edit the Administrator group.  **You'll wrongly get a 403 error.**  (This action works on sandbox.dspace.org and demo.dspace.org)
5. Visit a Collection under the Community you are an Admin of.  Edit that Collection. This should work.
6. Visit the "Assign Roles" tab for that Collection.  Create a group -> THIS WORKS.  Now, click on the Group to edit it.  **You'll wrongly get a 403 error.** (This action also works on sandbox.dspace.org and demo.dspace.org)

If you try the same with a Collection Admin, that user will also not be able to edit Groups associated with their Collection.

Beyond those Group editing bugs, everything else appears to work properly.

**Comment by ZahraaChreim-Atmire** [comment]
@tdonohue Thank you for your feedback! The 403 errors for Community/Collection Administrators when managing roles/groups have now been fixed.

**Review by tdonohue — APPROVED** [review]
👍 Thank you @ZahraaChreim-Atmire and @LotteHofstede !  I've verified this now completely works for me, including the ability for Community/Collection Admins to manage roles/groups *and* the End User Agreement changes.  

I'll leave this open for a few more days for @atarix83 to have a look.  But, then I'll get this merged into 8.0

**Comment by tdonohue** [comment]
Merging immediately as this works well and fixes the noted high priority bugs.  @atarix83 : if you have feedback on this PR after OR2024, we can ask that it be addressed in a follow-up PR.

Thanks again @ZahraaChreim-Atmire and @LotteHofstede !

**Pull request merged**
