### PR TITLE
Fix cache issue when depositing a submission

### LINKED ISSUE #1924: Submission enters an endless loop, when depositing with errors and no unsaved changes
**Describe the bug**

When depositing a submission a second time (e.g. after the first one failed validation) without any changes.
the submission form enters an endless loop, requesting, re-requesting, and re-requesting the workspace item.

Version: DSpace 7.4

**To Reproduce**
1. Start a submission
2. Do *not* fill out all required forms
3. Click the *Deposit* button
4. Wait for the validation errors to appear
5. Click the *Deposit* button again, without making any changes

**Expected behavior**
The submission should fail validation again

### LINKED ISSUE #2577: Severe cache bug during submission on deposit
**Describe the bug**
When a new submission that contains a relationship issue is created a severe cache bug occurs which doesn't allow to deposit the item.
Essentialy if all the changes in the submission have been saved, before to deposit the application try to retrieve the submission object again to check if the item can be deposited ([it happens here](https://github.com/DSpace/dspace-angular/blob/main/src/app/submission/objects/submission-objects.effects.ts#L213)). In the case the changes of the submission are not yet saved before to add a new relationship field they are saved when the relationship is added. This probably cause a cache problem and when the user try to deposit the item the application can't retrieve the updated submission object ([it happens here](https://github.com/DSpace/dspace-angular/blob/main/src/app/submission/objects/submission-objects.effects.ts#L213)) because it gets a remote data with status error stale and this leads to an endless loop of request to REST server.

**To Reproduce**
It can be reproduced in the sandbox environment also
1. as submitter try to create a new publication in the collection `Publication 2` which have a relationship field
2. start to fill out the form following this order and without clicking on save:
  - accept the license
  - add the titlke and the date that are mandatory
  - add an author
  - upload a file
3. click on deposit
4. the submission is hanging forever and in the network endless requests are sent

https://github.com/DSpace/dspace-angular/assets/2486489/a1f132d9-798f-4677-b038-cb2fe933056f

[Untitled_ Oct 26, 2023 9_46 AM.webm](https://github.com/DSpace/dspace-angular/assets/2486489/86f4a394-6589-488d-b70e-e2b6cd77581b)

**Expected behavior**
The submission should be deposited

**Related work**
It's important to retrieve every time a fresh submission object because of the bug already resolved https://github.com/DSpace/dspace-angular/issues/1502

### PR DESCRIPTION
**Pull request by atarix83**
## References
* Fixes #2577 
* Fixes #1924

## Description
This is a quick fix for the problems mentioned before. It's not resolving the general problem with `reRequestOnStale` [mentioned here](https://github.com/DSpace/dspace-angular/issues/2577#issuecomment-1781429053)

## Instructions for Reviewers
Check the mentioned bugs are fixed

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@atarix83 : I tested this PR today, and I can still reproduce both bugs with this fix in place.   So, I'm not sure what this is doing?

In my setup, I'm running this PR in the UI in production mode (`yarn build:prod`, `yarn serve:ssr`).  I then tried to reproduce the bugs as described.  For example, for #1924, I followed the exact steps in its description:
1. Started a new "Publication" submission (collection selected doesn't matter)
2. Do not fill out anything on the form.  Immediately click "Deposit"
3. Wait for validation error to go away.  Immediately click "Deposit" again. 
4. Entire page hangs.  If I watch the backend logs (dspace.log) I can see the UI page is requesting `GET /server/api/submission/workspaceitems/[:id]` over and over again (in an infinite loop)

I've rebuilt this PR twice in case something was cached.  I'm just not able to figure out how to test this.  Is it working properly for you when running in Production mode?

**Comment by atarix83** [comment]
@tdonohue 

i've tested it with SSR because i didn't previously and it works fine. Both bugs are fixed for what i can reproduce.
@artlowel  could you help us to verify if this PR is working for you ?

**Comment by tdonohue** [comment]
@atarix83 ; I re-tested quickly today and I can no longer reproduce the odd behavior I was seeing before.  This appears to work, but I want to do some further testing tomorrow before giving it a +1. 

Apologies, I have no idea what I must have done wrong before.  Either I failed to pull down the PR code properly, or some sort of caching was getting in the way.  But basic tests on Chrome today show this appears to be working. I'll triple check things tomorrow just to be sure :)

**Review by artlowel — APPROVED** [review]
Thanks @atarix83!

That works

**Review by tdonohue — APPROVED** [review]
👍 Thanks @atarix83 !  Retested today and verified that both #2577 and #1924 are fixed by this PR.  (My prior tests were somehow flawed... I suspect I didn't build the PR's branch and was accidentally running `main`.)

**Pull request merged**
