### PR TITLE
More accessible file download link for users who use a screen reader

### LINKED ISSUE #3083: [Accessibility] Avoid repetition of identical link text on same page
**Describe the bug**
This relates to items that have a number of different download options. For each option, the Download Link currently says "Download". According to Success Criterion 2.4.4 Link Purpose (In Context), the user should be able to determine the purpose of each link from the link text alone. [In this example](https://sandbox.dspace.org/items/cd374806-70ac-4541-a711-559c9bb60a76/full), users with screen readers would hear the word "Download" read numerous times but not know the context, purpose and destination of each download link.

**To Reproduce**
1. Visit https://sandbox.dspace.org/items/cd374806-70ac-4541-a711-559c9bb60a76/full
2. See list of Download Links at the right side of each file description

**Expected behavior**
A clear and concise description of what each link does, e.g. "Download the PDF...". 

**Related work**

### PR DESCRIPTION
**Pull request by Andrea-Guevara**
## References
* Fixes #3083

## Description
Adding a more detailed description to the file download link using the “attr.aria-label” attribute.

## Instructions for Reviewers
In the anchor of the component “file-download-link.component” the attribute “attr.aria-label” has been added to leave a more detailed description of the functionality of the link for users who make use of a screen reader.

List of changes in this PR:
* The attribute “attr.aria-label” has been added
* The translation key “file-download-link.download” has been created
* The “dsoNameService” service has been used to fetch the bitstream name.
* Finally, the translation key was concatenated with the “dsoNameService” service in the “attr.aria-label” attribute.

To reproduce:

1. Visit an item using a screen reader.
2. See list of Download Links at the right side of each file description.
3. See that the screen reader announces the functionality of the link which is “download” plus the name of the file.

### CODE REVIEW

**Comment by tdonohue** [comment]
@Andrea-Guevara : This PR appears to be failing `lint` checks in the `file-download-link.component.ts`. See inline comments at https://github.com/DSpace/dspace-angular/pull/3264/files  Please fix those lint errors so that the automated tests are able to run on this PR.

**Comment by Andrea-Guevara** [comment]
Good morning @tdonohue
thank you very much for your comment :)
done!

**Comment by nwoodward** [comment]
Hi @Andrea-Guevara. These changes look good on inspection, but I would like to test them to make sure. Could you fix the merge conflicts? They are in the translation files, so they will be quick. Then I will test the PR right away.

**Comment by Andrea-Guevara** [comment]
@nwoodward  Hello, good afternoon.
Sorry for the delay in replying, I've been away for a few days and couldn't reply before! 

I've resolved the conflicts. I had some problems with blank spaces in the same translation key files, but these have also been resolved.

If you have any questions, I'd be happy to help.

**Review by nwoodward — APPROVED** [review]
Thanks @Andrea-Guevara! I tested these changes, and they add the `aria-label` attribute to the Download file links.

**Comment by tdonohue** [comment]
Manually ported to 8.x in #3762 and 7.x in #3763

**Pull request merged**
