### PR TITLE
Fix security issues reported by LGTM

### PR DESCRIPTION
**Pull request by YanaDePauw**
## Description
This PR resolves 2 security issues flagged by LGTM:
1. Addition of a rate limiter to prevent a DOS attack
2. Add a warning in the log when using a self-signed ssl certificate and disabling the validation. The corresponding LGTM error is suppressed due to the presence of this warning

## Instructions for Reviewers
To verify the rate limiter, you can do the following:
* Build the app in production mode using the default settings
* Browse through the app as a normal user and verify that the rate limiter does not interfere with this behaviour
* Hard refresh the app multiple times and verify that refreshing gets blocked and shows a message saying "Too many requests, please try again later" on a white page.

To disable the rate limiter, do the following:
* Overwrite or change the environment constant `rateLimiter` to `undefined`.
* Hard refresh the app multiple times and verify that this keeps working.

To verify the self-signed certificate warning, the following steps can be performed:
* Build the app in production mode when setting ssl to true, but without providing a certificate.
* Verify that a warning is logged that recommends to configure a valid certificate instead.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — CHANGES_REQUESTED** [review]
@YanaDePauw : The code here looks good overall.  I've tested this though, and it seems our rateLimiter settings are *too restrictive*.  When I run this with `yarn start`, after logging in (and triggering a hard refresh), I encountered a large number of  `429 Too Many Requests` responses from the frontend.

I noticed when looking at our rate limiter settings here we seem to be limiting to 100 requests a minute.  That seems reasonable, but it looks (to me) like a simple hard refresh ends up using a large number of requests (approx 30-40).  So, if you browse around a bit, and login (all within a minute), then you end up triggering 429 errors & seeing a page that says "Too many requests, please try again later"

I suspect we need to either decrease the `windowMs` or increase the `max`.  One other comment inline below.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@YanaDePauw : First off, the code looks great here.  But, I'm still hitting very frequent `429 (Too Many Requests)` errors without much effort at all.  Once I reproduce the error, the UI is unusable (goes to a blank page that says "Too many requests, please try again later") until I wait for a minute.  Here's how to easily reproduce it:

In the span of one minute, do the following:
1. Open Chrome Dev Tools
2. Visit (or reload) the homepage: http://localhost:4000/home
3. Login
4. Usually, the error has already occurred (in Chrome Dev Tools).  But, if not, click Reload in the browser.

You can also reproduce it by simply clicking Reload (in the browser) on the Homepage twice in one minute.

So, this PR is working well, but I think we need to rethink the default settings.  Maybe we should consider increasing this to something like 1,000 requests in a minute?  (I know that's a large number, but it seems like something in the 100 range is much too small.)  Any thoughts on this @artlowel ?

Overall, this PR is great & I'm essentially +1....we just need better default settings before we can merge it.

**Comment by artlowel** [comment]
It's strange @tdonohue I can't reproduce your issue, not even with the original 100 requests per second. The only time I get it is if I'm refreshing 5-6 times in a row, not by following the instructions in your comment. But I agree we should set the defaults for that limit on the high side. Though perhaps 1.000 is pushing it. Can you try setting it to 500 in your environment.prod.ts and see if you still have issues?

**Comment by tdonohue** [comment]
@artlowel & @YanaDePauw :  That is odd that you are not seeing the same behavior.  I'm also running this PR with `yarn start`, not sure if that makes a significant difference.

In any case, if I update my `environment.commons.ts` to be this:
```
// The rateLimiter settings limit each IP to a "max" of 500 requests per "windowMs" (1 minute).
    rateLimiter: {
      windowMs: 1 * 60 * 1000,   // 1 minute
      max: 500 // limit each IP to 500 requests per windowMs
    }
```
Then I no longer see the 429 errors (unless I consistently hit the reload button in my browser approximately 7-8 times in a row).

So, setting the `max` to 500 seems like a "good enough" solution for now.

**Comment by artlowel** [comment]
I also used `yarn start` so that's not the reason.

We'll change it to 500

**Review by tdonohue — APPROVED** [review]
👍 This looks good now.  Thanks @YanaDePauw and @artlowel !

**Pull request merged**
