### PR TITLE
Creative Commons selector is not loading

### PR DESCRIPTION
**Pull request by toniprieto**
## Description
Testing an issue on the current main branch, I have seen that the Creative Commons selector of the submit form is not loading. The problem seems to be an unimplemented function findAll in SubmissionCcLicenseDataService after applying PR #1791  

I have tried to fix the problem by implementing the function in a similar way to other data services and it seems to work fine.

## Instructions for Reviewers

* Activate the cclicense step in item-submission.xml
* Check that the cc selector is not loaded in a new submission and the javascript console shows an error
* Apply the patch and test again

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
@ybnd : Would you be willing to give this a quick review/test, since it seems to be a bug fix to your large #1791 PR ?

**Comment by ybnd** [comment]
@tdonohue @toniprieto yup, this was an oversight on my part & is addressed correctly here!

The only thing I would add is a "composition test" like e.g. [here](https://github.com/DSpace/dspace-angular/blob/a13f4ee3b9431a74d3d94fde9bd09119f379534b/src/app/core/submission/vocabularies/vocabulary.data.service.spec.ts#L16-L19) to assert that everything has been wired up correctly.

I'm pretty confident this is all we need, but I'll do a full test tomorrow just to be sure.

**Comment by toniprieto** [comment]
Thanks @ybnd , I've added the composition test

**Review by ybnd — APPROVED** [review]
Confirmed the original bug and that your PR fixes it; good to go!

**Comment by tdonohue** [comment]
Merging with one approval.  Thanks @toniprieto !

**Pull request merged**
