### PR TITLE
Search in sidebar/facet don't escape special characters

### LINKED ISSUE #1900: Search in sidebar/facet don't escape special characters
**Describe the bug**

The facet search, that uses the endpoint `/server/api/discover/facets/{facetName}`, in the search sidebar (expand filter in sidebar, start typing in search bar of that facet) doesn't escape special characters.

Additionally, the facets endpoint, `/server/api/discover/facets/{facetName}?prefix` search doesn't take into account capital letters. The search in de facets/filters sidebars has a workaround for capital letters since the value gets lowercased, but should probably addressed REST side. 

**To Reproduce**

- Go to [search](https://demo7.dspace.org/search)
- Expand the sidebar filter and start typing search bar
- (see network tab) The search query gets sent to `/server/api/discover/facets/{facetName}?prefix={query}` lowercased but not url escaped
- See below for examples

Example Special characters
- [subject?prefix=10](https://api7.dspace.org/server/#/server/api/discover/facets/subject?prefix=10)=> Has result "10% kobalt dengan pengacuanan suntikan serbuk mikro"
- [subject?prefix=10%](https://api7.dspace.org/server/#/server/api/discover/facets/subject?prefix=10%25) => No results, so shows all subjects
- Escaped: [subject?prefix=10%25](https://api7.dspace.org/server/#/server/api/discover/facets/subject?prefix=10%25) => Has result "10% kobalt dengan pengacuanan suntikan serbuk mikro"
- In UI this is an issue, because requests done do not have escaped value in prefix

Example capital letters:
- [author?prefix=a](https://api7.dspace.org/server/#/server/api/discover/facets/author?prefix=a) => results, all starting with A or a
- [author?prefix=A](https://api7.dspace.org/server/#/server/api/discover/facets/author?prefix=A) => no results, despite there being authors starting with A
- In UI this is not an issue, because the requests done have lowercased value in prefix

Example comma (not an issue): [author?prefix=asnani,%20m](https://api7.dspace.org/server/#/server/api/discover/facets/author?prefix=asnani,%20m) => result  "Asnani, Minakshi"

**Expected behavior**
The search in the sidebar for additional facet values should be url escaped so that special characters can be used.

**Related work**
Capital letter REST issue here: https://github.com/DSpace/DSpace/issues/8516

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #1900
* https://github.com/DSpace/DSpace/pull/8529

## Description
The facet search, that uses the endpoint `/server/api/discover/facets/{facetName}`, in the search sidebar (expand filter in sidebar, start typing in search bar of that facet) didn't escape special characters.

## Instructions for Reviewers
* Go to [search](https://demo7.dspace.org/search)
* Expand the sidebar filter and start typing search bar
* (see network tab) The search query gets sent to `/server/api/discover/facets/{facetName}?prefix={query}` lowercased and url escaped
* *For example if you search by subject and you enter as value `&fakeparam=test` on demo7 this call will be made [`/server/api/discover/facets/subject?prefix=&fakeparam=test&page=0&size=5&configuration=default`](https://api7.dspace.org/server/api/discover/facets/subject?prefix=&fakeparam=test&page=0&size=5&configuration=default) but now with this fix this request will be made instead: [`/server/api/discover/facets/subject?prefix=%26fakeparam%3Dtest&page=0&size=5&configuration=default`](https://api7.dspace.org/server/api/discover/facets/subject?prefix=%26fakeparam%3Dtest&page=0&size=5&configuration=default)*

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by jtimal** [comment]
hello @alexandrevryghem 

What we do is to normalize the string, we remove the accents, more or less like this

`indexOfCoincidence(completeTerm: string, subTerm: string){
		completeTerm = completeTerm.normalize('NFD').replace(/[\u0300-\u036f]/g, "").toUpperCase();
		subTerm = subTerm.normalize('NFD').replace(/[\u0300-\u036f]/g, "").toUpperCase();
		return completeTerm.indexOf(subTerm)
	}`
If you like my idea, I can check it in more detail, it works like this:

image

**Comment by alexandrevryghem** [comment]
Hey @jtimal

I looked into this but and your solution does indeed work for nomralizing the accents but it would also require extra backend changes to ignore accents when searching for the results too. So you should probably create a new issue for this.

**Comment by alexandrevryghem** [comment]
>  I just don't know how to create this request
In [the issues tab](https://github.com/DSpace/dspace-angular/issues) you just need to click on the Create Issue button and describe the bug/feature.

> do we wait for Tim to review it or do we let him know?
He will read the new issue you create 🤷‍♂️

**Comment by jtimal** [comment]
Very thanks @alexandrevryghem ,

I'd better wait until @tdonohue can read this part and tell me how I can help.

**Pull request merged**
