### PR TITLE
Fixed Edit Item's Version History crashing

### LINKED ISSUE #3252: Edit Page Hangs on Version History
In direct reference to [Version History causes Item page to hang](https://github.com/DSpace/dspace-angular/issues/2924).

Hello.

I am right now developing two different DSpace instances and I struggled with this issue for hours thinking it had something to do with my malformed Entities configuration in one of my instances (let's call it Instance A, see: <https://github.com/DSpace/DSpace/issues/9729>), but I found that I could reproduce this error in my other DSpace instance that doesn't even have Entities enabled (Instance B), leading me to suspect that this may have something to do with the DSpace code itself, and my suspicions were validated once I found this closed issue (I also found that it didn't matter if `dspace.entity.type` was set to Item). Of course, I am using DSpace 8.0.

- **Instance A**
	- On research hospital's private intranet with strict security regime.
	- Only permitted exposed ports are 443 and 80.
	- Uses RHEL 9.4.
	- Has a mangled custom Entities configuration that [I have yet to resolve](https://github.com/DSpace/DSpace/issues/9729).
- **Instance B**
	- AWS EC2 VM .
	- Uses Ubuntu 22.
	- Has no Entities enabled.

**Describe the Bug**:

image

When an Item has multiple versions, going to the Version History on the Edit page for that Item causes CPU usage to skyrocket to 100% and the memory usage to slowly spiral out of control. This was originally discovered in Instance A.

As you can see in the [Slack post](https://dspace-org.slack.com/archives/C3V628QNN/p1722459198020639), I originally believed it had something to do with my Postgres tables. Modifying them did nothing, and `./bin/dspace database info`/`test` returned no issues or errors. I had also initially believed that this had something to do with the fact that `./bin/dspace healthcheck` would crash and give me Java/SQL error (I have attached that error log
[here](https://github.com/user-attachments/files/16614387/dspace-healthcheck.1.log)). That, along with the aforementioned Entities hunch, were both dispelled when I tried to reproduce the issue on Instance B and found that the exact same thing would occur.

The SSL log for Instance A does contain a lot of errors whose relevance I can't really determine to this particular issue, so for the sake of brevity, I will set them aside. Suffice it to say that the REST API backend is accessible at `url.com/server`.

The `dspace.log` does not have anything that would obviously stand out to me as being an obvious source of the issue, but I can include that later if needed.

**To Reproduce**

1. Create an Item.
2. Create a new version of said Item.
3. Attempt to view the "Version History" tab of the Edit Item screen.

**Expected Behavior**

Like before, not hanging.

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #3252

## Description
This PR removes the method calls from the template that return Observables causing an infinite rerendering of the page.

## Instructions for Reviewers
List of changes in this PR:
* Created a `VersionsDTO` containg all the data that is required to render the template in order to prevent the infinite recreation of the `canEditVersion` `Observable`.

**Guidance for how to test or review this PR:**
Test that everything still work correctly on the item page & the edit item version history tab both for items with and without any versions.

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `yarn lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `yarn check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [x] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Review by aseyedia — APPROVED** [review]
I implemented these changes in both of my DSpace instances and the Version History page no longer hangs 👍.

**Comment by tdonohue** [comment]
@alexandrevryghem : Based on reviewing the code, this *looks like* it may need backporting to `dspace-7_x`?  I see very similar code on that branch.  If that's so, I think this will require a manual backport to 7.x

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  Tested today and verified it works. The code looks good to!

**Comment by tdonohue** [comment]
@alexandrevryghem : I've just realized that this PR is refusing to run automated tests.  I'm going to close & reopen to see if that triggers them to run.  As I want to simply verify they all succeed before merging.

**Comment by tdonohue** [comment]
@alexandrevryghem : It looks like this hit merge conflicts for both backports to the `dspace-8_x` and `dspace-7_x` branches.  Could you find time to create backport PRs to apply this fix to 8.x and 7.x (if necessary for both)?

**Comment by tdonohue** [comment]
Ported to 7.x in #3368.

**Comment by tdonohue** [comment]
Ported to 8.x in #3412 and to 7.x in #3368

**Pull request merged**
