### PR TITLE
Primary bitstream toggle implementation

### LINKED ISSUE #1578: "Primary Bitstream" toggle on Edit Bitstream page doesn't work
**Describe the bug**
The "Primary Bitstream" toggle on the Edit Bitstream page doesn't work, even though a success message is returned to the user.

primary

**To Reproduce**
1. Edit an Item with multiple bitstreams
2. On the "Bitstreams" tab, edit one bitstream
3. Mark it as the Primary Bitstream by moving the toggle.  Click Save
4. You will see a "Bitstream Saved" success message.  But, if you go back to the Bitstream, you'll see that it is NOT marked as the primary bitstream

In Chrome DevTools, the following notices will appear in the console:
```
Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:8080/server/api/core/bitstreams/dcefbc84-dca2-434f-b049-23578c43e0b0/content with MIME type application/pdf. See https://www.chromestatus.com/feature/5629709824032768 for more details.

Form submission canceled because the form is not connected
```

NOTE: Other fields on that same page work properly, though they also seem to show the "Cross-Origin Read Blocking" notice...so it's possible that's not the root cause.

**Expected behavior**
Obviously, this toggle should work since it appears on the page.

**Related work**
Depends on https://github.com/DSpace/DSpace/issues/3349 (as it appears we do not have endpoints to support this feature yet)

### PR DESCRIPTION
**Pull request by LotteHofstede**
## References
* Fixes #1578
* Dependent on DSpace/DSpace#8876 and DSpace/RestContract#222

## Description
This PR adds implementation to display and save the primaryBitstream when editing a bitstream.

## Instructions for Reviewers
Visit an edit bitstream page and edit the bitstream and toggle the "Primary Bitstream" switch and save the changes.
The user should be redirected to the `edit/bitstreams` overview page.
Make sure to change the primary bitstream toggle on multiple bitstreams in the same bundle and make sure there's always only one primary bitstream per bundle and the form reflects your changes after reloading the page.

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by hardyoyo** [comment]
I'd like to request that few screenshots be added to this PR, to make reviewing easier. I'm attempting to confirm this is working, and I do not see any toggle on the edit bitstream page.

Also, while this is a welcome addition--when it's visible on the edit bitstream page--I believe we also need to put the toggle on the main submission page, so contributors can indicate which of their bitstreams is the primary one, at the time of submission. They're the most-qualified person to make this judgement.

**Comment by hardyoyo** [comment]
After a bit more digging, I found the toggle, on the edit bitstream page. Pasting a screenshot below.

image

**Comment by hardyoyo** [comment]
This seems to work and satisfy the narrow use case of restoring the functionality requested in this bug report: https://github.com/DSpace/dspace-angular/issues/1578

I would have liked to see support for setting this toggle on submission, but, that is clearly not in scope for this work. We will explore options for getting support for our additional use case covered.

**Comment by tdonohue** [comment]
@LotteHofstede and @artlowel : This is still waiting on updates to align it with the newly refactored backend PR.  Any chance of those occurring soon, or do we need to consider rescheduling this?

**Review by tdonohue — COMMENTED** [review]
Thanks @LotteHofstede !  This is working well overall.  However, I did find a minor issue (not caused by this PR though, so we could treat it as a separate bug).

I've found that, while the `<ds-thumbnail>` component respects the primary bitstream (by always returning the thumbnail associated with that bitstream), the `<ds-media-viewer-image>` component **does not**.

Here's how to reproduce the issue:
1. Enable the media-viewer for images in your `config.*.yml`:
    ```
    mediaViewer:
      image: true
    ```
2. Create/find an Item which has *at least* two files with thumbnails.  This could be an Item with two image files or two PDFs, but you must see multiple files in the THUMBNAIL bundle.
3. Check which thumbnail is being displayed on the Item page `/item/[uuid]` when the mediaViewer is turned on.
4. Now, edit the Item, and select the *other* file as the primaryBitstream.  This will **change** the thumbnail anywhere the `<ds-thumbnail>` component is used (e.g. in search results or on the Collection page or similar)
5. Go back to the Item page and notice that the thumbnail displayed by the `mediaViewer` does not change.  
    * It appears the mediaViewer does NOT obtain the thumbnail from the `/items/[uuid]/thumbnail` REST endpoint.  If you call that endpoint manually, you'll see it will always return the `thumbnail` associated with the primary Bitstream.

As I said, this isn't a bug caused by your PR.  But, I wanted to point it out in case you feel there may be a quick fix.  If there's no quick fix, I'm OK with this PR as-is... and we can log this bug in a separate ticket to be addressed later.

So, I'm +1 this current implementation, but I wanted to see if we can improve it further by fixing the behavior of the mediaViewer to use the correct thumbnail.

**Comment by artlowel** [comment]
@tdonohue I took a quick look at that mediaviewer issue, and I don't see a quick way of fixing it in the scope of this PR. 

While we might be able to force the mediaviewer thumbnail to always be the primary bitstream, that would lead to confusing behavior because the image you'd see in the viewer when clicking the thumbnail would still be the first image bitstream returned, not necessarily the primary bitstream.

So you'd have to rewrite it to reorder it so the primary bitstream is first in the list. But [the code that populates the list](https://github.com/DSpace/dspace-angular/blob/9919abebcef564889039ed2b6562d03529dc6442/src/app/item-page/media-viewer/media-viewer.component.ts#L56-L91) retrieves thumbnails and original bitstreams separately, takes pagination into account, the code contains nested subscribes, etc; not something that's easily tweaked. 

It may also turn out that the best place to fix this would be to add rest support to get a list of image bitstreams and their thumbnails

**Pull request merged**
