### PR TITLE
fix: linkName from decorator assign value to the correct property

### LINKED ISSUE #2819: The linkName in the `@link` decorator doesn't assign the value on the correct property
**Describe the bug**
When you have an `@link` with a `linkName` that differs from the property to which you added the decorator, the embedded data will not be linked to that property, but instead, it will be linked to a new property with the name defined in `linkName`.

**To Reproduce**
1. In the `item.model.ts` class, rename the `accessStatus` property to, for example `accessStatusValue`, and update the `@link` to `@link(ACCESS_STATUS, false, 'accessStatus')`.
2. Fix the usages of `accessStatus` in `AccessStatusBadgeComponent`, add `accessStatus` to the list of `BROWSE_LINKS_TO_FOLLOW`, and add a pipe with a `take` and a `console.log` to log the page of items in `BrowseService#getBrowseItemsFor`.
3. Now go to the `/browse/dateissued` page and check your console. You will see that the value is not set on the `accessStatusValue` property, but on `accessStatus`.

**Expected behavior**
The embedded data should be saved on the property to which you added the `@link` decorator.

**Related work**
I discovered this bug during #2480. After implementing this fix, it will be important to check that [these changes](https://github.com/DSpace/dspace-angular/pull/2480/commits/8ddc62168ef82f32d00a89ce387003c49ad21af1) still work as expected. The current implementation now only checks if the property with the `linkName` has a value, but when this is fixed, this should be updated. Otherwise, some `followLinks` will never be automatically invalidated when their parent is invalidated.

### PR DESCRIPTION
**Pull request by pcg-kk**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #2819

## Description
In this PR I provide a fix to the `HALLink` mechanism. Before, the link was assigned to the variable from the `linkName`, not the real model property.

## Instructions for Reviewers
List of changes in this PR:
* First, I changed the `link.service` to retrieve the correct name of the property
* Second, I add a unit test for a new case
* Third, I fixed the test mock to use the Map instead of the array because in other cases some tests were false positive

To test this issue please follow reproduction steps by @alexandrevryghem from this commit https://github.com/DSpace/dspace-angular/commit/bb13004dfd719eb7d99af74e186b28987af2c095

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by tdonohue** [comment]
@alexandrevryghem : Would you have time to review the changes in this PR?  It appears it was created to solve a minor issue that you logged in #2819, so I'd appreciate your feedback on this solution.

**Review by alexandrevryghem — CHANGES_REQUESTED** [review]
@pcg-kk: Thx for this PR it does fix the problem in the model class where the data isn't assigned to the correct property, but you still need to modify [this code](https://github.com/DSpace/dspace-angular/pull/2480/commits/8ddc62168ef82f32d00a89ce387003c49ad21af1) to be compatible with the possibility of having a `@link` on a property with a different name than the `linkName`. [That code](https://github.com/DSpace/dspace-angular/pull/2480/commits/8ddc62168ef82f32d00a89ce387003c49ad21af1) is responsible for automatically invalidating the `RemoteData` when one of its `followLink`s is invalidated. So if you use the example from https://github.com/DSpace/dspace-angular/commit/bb13004dfd719eb7d99af74e186b28987af2c095, currently `hasValue(remoteDataObject.payload['thumbnail'])` is used [here](https://github.com/DSpace/dspace-angular/pull/2480/commits/8ddc62168ef82f32d00a89ce387003c49ad21af1#diff-919ea7fa8185d9189a1b347d9ed75f4a4e1ea653b4c05957d2d05b024d9c4daaR287) instead of `hasValue(remoteDataObject.payload['thumbnailBitstream'])`

**Comment by pcg-kk** [comment]
@alexandrevryghem am I correct that what we need now is to provide a correct followName for payload, something like:

```
const linkDefinition = getLinkDefinition((remoteDataObject.payload as any).constructor, followLinkName);
if (linkDefinition?.propertyName && hasValue(remoteDataObject.payload[linkDefinition.propertyName]) && followLinkName !== 'self') {
  // followLink can be either an individual HALLink or a HALLink[]
  const followLinksList: HALLink[] = [].concat(remoteDataObject.payload._links[followLinkName]);
  for (const individualFollowLink of followLinksList) {
    if (hasValue(individualFollowLink?.href)) {
      this.addDependency(response$, individualFollowLink.href);
    }
  }
}
```

**Comment by alexandrevryghem** [comment]
@pcg-kk: Sorry for the delay. I tested your solution, and it seems to work nicely. I can see that the addDependency function is called again even when you change the name of the property to which the link decorator is attached. Once you add the fix to your branch, I’m a +1.

**Comment by pcg-kk** [comment]
@alexandrevryghem version is updated

**Comment by alexandrevryghem** [comment]
@pcg-kk: Could you also update the `‎BaseDataService.findByHref‎` with the same logic

**Comment by pcg-kk** [comment]
@alexandrevryghem fixed

**Review by alexandrevryghem — APPROVED** [review]
@pcg-kk: Thnx! I tested it again today, and the `BaseDataService#findByHref` works correctly, but I saw that `BaseDataService#findListByHref`'s `addDependency` was never called, even for paginated list that contained embedded data, so I added that fix. I also updated the test case's mock payload with a class containing real `@link`s, this way we can simulate how it would work in a real environment and restored that test assertion. I'm a +1 now

**Comment by tdonohue** [comment]
@pcg-kk and @alexandrevryghem : I'm not sure if this is important to backport, but I tried anyways (since it was an older ticket).  The backports all failed.  We can keep this as a fix in 9.0 only for now.  But, if either of you want to see this in 8.x or 7.6.x, please create backport PRs.

**Pull request merged**
