### PR TITLE
Pass `ng-content` to themed child components

### LINKED ISSUE #2009: Angular content projection doesn't work with themed components
**Describe the bug**
The angular content projection https://angular.io/guide/content-projection doesn't work when using the themed component instead of the original one. An example is occurring with the [dynamic-lookup-relation-search-tab.component](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html) where if the `ds-themed-search` is used instead of the `ds-search` the content projection doesn't work

**To Reproduce**
1. change the code of [dynamic-lookup-relation-search-tab.component](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html) in order to use `ds-search` instead of `ds-themed-search`
2. create a new publication in a collection where the creation of relationship with person is enabled 
3. search for a new author in order to open [dynamic-lookup-relation-search-tab.component](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html)
4. using the `ds-search` the dropdown to select many entries is visible, as opposed to when using the `ds-themed-search`
Schermata da 2022-12-22 16-18-32

**Expected behavior**
Angular content projection is a common pattern and should not be inhibited by our theming functionality.

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## References
* Fixes #2009

## Description
Made it possible to pass `ng-content` to themed components & added an example component (`FileDownloadLinkComponent`).
Also mad it possible to defined default values in the themed component children.

## Instructions for Reviewers

List of changes in this PR:
* Created a `div` in `ThemedComponent` which temporarily contains the `ng-content` from the parent `themed-*` component to be able to pass it on to the child component. This way `ng-content` can also be used for themed components.
* Made `FileDownloadLinkComponent` themeable
* Added a filter to the `ThemedComponent.connectInputsAndOutputs()` to not override the default values set in the themed components

**Include guidance for how to test or review your PR.** 
- Set the theme to custom theme in `config.yml`
- Uncomment the `CustomEagerThemeModule` in `src/themes/eager-themes.module.ts`
- Test if the new components in the custom theme folder can be themed

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by atarix83** [comment]
@alexandrevryghem  

is this PR resolving this issue https://github.com/DSpace/dspace-angular/issues/2009 ?

**Comment by alexandrevryghem** [comment]
@atarix83

Yes this PR should fix those issues. (I added that issue to the references in the PR description)

**Review by atarix83 — APPROVED** [review]
thanks @alexandrevryghem 

I've verified that this PR resolve #2009 and it seems to work fine

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem !  This looks good to me too. Verified that this change also doesn't impact behavior of these file download components.

**Pull request merged**
