### PR TITLE
[Port dspace-7_x] Fixed caching & same entity type relationship with different left/rightwardtype bugs on edit item relationships

### PR DESCRIPTION
**Pull request by alexandrevryghem**
Manual port of #3106 to `dspace-7_x`

### CODE REVIEW

**Comment by tdonohue** [comment]
Closing, as this manual port was already completed in #3107.  This is a duplicate

**Comment by alexandrevryghem** [comment]
@tdonohue: I'm reopening this again, I made a mistake in my PR description this was actually the backport for PR #3106

**Comment by tdonohue** [comment]
@alexandrevryghem : This appears to have a lot of unrelated changes?  It looks like you've accidentally backported all new lint rules in this PR.

**Review by tdonohue — APPROVED** [review]
👍 Thanks again @alexandrevryghem ! Verified code is the same as in #3016.

**Pull request merged**
