### PR TITLE
Fix ResourcePolicy cache issues

### LINKED ISSUE #644: Issue with request of embed objects, where object cache entry is missing
During implementation of https://github.com/DSpace/dspace-angular/issues/601 I encountered several issues with request of embed objects. In many case when the request is already fetched by rest, the payload returned is undefined due to a missing object cache entry in the cache. Objects cache should exist for this requests because are not expired, as a result the request is not dispatched again.
Probably this issue is related to https://github.com/DSpace/dspace-angular/issues/626

### LINKED ISSUE #1753: Edit Item > Authorizations > Policy Group change does not appear
**Describe the bug**
In DSpace 7, Edit Item > Authorizations..., e.g. https://demo7.dspace.org/items/03731881-2185-4baf-a6a8-1438a4d29dc8/edit/authorizations, after one changes a Policy Group, no Group appears for that Policy.

**To Reproduce**
1. Before any changes, Policies for Bundle ORIGINAL is Group="Anonymous."
DSpace7_edit_policies_1
2. I have changed Policies for Bundle ORIGINAL to Group="rebit ecm." This change does not appear (no Group appears).
DSpace7_edit_policies_2
3. I refreshed the page. The new Group="rebit ecm" now appears.
Dspace7_edit_policies_3

**Expected behavior**
After a policy is changed and saved the new group should immediately appear.

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by ybnd**
## References
* Fixes #644
* Fixes #1753
* Builds on #1808

## Description
This PR addresses a caching issue on the `items/.../edit/authorizations` page

* The `EPerson` or `Group` of an entry used to disappear right after it was changed
  → solved by invalidating existing RPs when their target is updated

* Extracted RP table entries into a separate component: `ds-resource-policy-entry`

* Other invalidation issues have already been solved with the "wait for invalidation" pattern introduced in #1608. Because this is starting to lead to quite a lot of code duplication we refactored it into a new method: `RemoteDataBuildService.buildFromRequestUUIDAndAwait`

## Instructions for Reviewers
Confirm that the issue can no longer be reproduced as described in https://github.com/DSpace/dspace-angular/issues/644#issuecomment-1137766491

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
@ybnd : This has minor merge conflicts now. Could you rebase it when you get the chance?  Thanks!

**Comment by ybnd** [comment]
@tdonohue I've merged https://github.com/DSpace/dspace-angular/pull/1808 back in as @Atmire-Kristof fixed the merge  conflicts there

**Comment by tdonohue** [comment]
@ybnd : Apologies, but after merging your PR #1791, this now has some small merge conflicts (again).  I'd appreciate it if you could rebase this again when you get the chance.

**Comment by ybnd** [comment]
Fixed the merge conflicts & reapplied changes to `deleteByHref` made in this PR to their new home in `DeleteData`

**Review by tdonohue — APPROVED** [review]
👍 Thanks @ybnd !  This fixes the original bug.  As this PR refactors some of the work in #1808, I also re-tested the bugs described in #1808...they are still fixed as well.  Overall, this all looks good to me.

**Review by atarix83 — APPROVED** [review]
thanks @ybnd for this PR

The code LGTM and the bux is fixed.

While testing i found out an annoyng issue, that is not related with this task, with button alignment in the item's resource policy page
Schermata da 2022-09-22 10-41-19

To fix it it just needs to add a `flex-shrink-0` class here https://github.com/atmire/dspace-angular/blob/w2p-94207_Fix-resource-policy-cache-issues/src/app/shared/resource-policies/resource-policies.component.html#L14

@ybnd  @tdonohue is it possible to apply the fix before merging the PR?

**Comment by ybnd** [comment]
@atarix83 Thanks!
I agree about the buttons, fixed.

**Comment by tdonohue** [comment]
Merging as this is at +2, and the final small style fixes have been applied. Thanks again @ybnd !

**Pull request merged**
