### PR TITLE
Fix Spec has no expectations errors

### PR DESCRIPTION
**Pull request by alexandrevryghem**
## Description
Currently there are some tests (in total 60) who don't have any expecations, this is often because of Observables who only emit after the test has already finished. In this PR I enabled a rule to always throw `Spec has no expectations` for tests without expectations, this PR also fixes those tests. Some tests also don't expect anything because they only exist to check if an error is thrown, for those tests I added `expect.nothing()` at the end to make sure they also succeed with this rule (I also always added some inline explanation on the places where I used this). Enabling this rule would mean that small errors like [this one](https://github.com/alexandrevryghem/dspace-angular/commit/abc8640b5e35b1abdaad181b7f26feed9b624d77#diff-e8b237ccac3c65fd546c65d75eb6b32bbbfb37f5b8576fe2ebe9ce1101f9ec1dR28) would be catched earlier, instead of making you think that everything is working.

## Instructions for Reviewers
I committed every test I fixed seperatly with a short explanation with the reason of the change in the commit description, I think this will make it easier to review 🤷.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alexandrevryghem** [comment]
There are still 2 tests failing, in my opinion they can be removed, but I would prefer having someone else's feedback before deleting them:
- For [the failing test in `Notifications reducer`](https://github.com/DSpace/dspace-angular/blob/404ccd9b0ecdcdfe63ad22779859b1a01eddc12e/src/app/shared/notifications/notifications.reducers.spec.ts#L109-L139), the test `ChangeDetectorRef` part needs to be removed and then you can see that the test fails. The problem is that `tick()` & `flush()` don't work well with ngrx, this means that you can't use those to increment the time, I tried using `delay()`, but while fixing the tests from `ObjectUpdatesEffects`, the only way I found to correctly wait that the actions where handled there was to add `expect(updatesEffects.mapLastActions$).toBeObservable(cold())`. I tried reusing this approach here but it didn't work, the failing test also doesn't actually test code from the `NotificationsReducer`, but rather code from  `ObjectUpdatesEffects.removeAfterDiscardOrReinstateOnUndo$`, because this timeout code has already been tested I thought that maybe it could be removed
- For [the failing test in `ExternalSourceService`](https://github.com/DSpace/dspace-angular/blob/404ccd9b0ecdcdfe63ad22779859b1a01eddc12e/src/app/core/data/external-source-data.service.spec.ts#L100-L103), it's normal that this test fails, it's because of [this code](https://github.com/DSpace/dspace-angular/blob/404ccd9b0ecdcdfe63ad22779859b1a01eddc12e/src/app/core/data/base/base-data.service.ts#L272-L276). The code prevents that stale objects from the cache are returned, this way a backend request can be made, and it will update the store. That value can't be returned from the backend in the tests because there is no backend, so this test can't be fixed. The only thing you could do is put the correct value in the store and check that the correct value is in the store but this is pointless. There is already a test who checks that the backend request is made [here](https://github.com/DSpace/dspace-angular/blob/404ccd9b0ecdcdfe63ad22779859b1a01eddc12e/src/app/core/data/external-source-data.service.spec.ts#L95-L98), so in my opinion [this test](https://github.com/DSpace/dspace-angular/blob/404ccd9b0ecdcdfe63ad22779859b1a01eddc12e/src/app/core/data/external-source-data.service.spec.ts#L100-L103) can be removed.

**Comment by tdonohue** [comment]
@alexandrevryghem : I finally got around to reading this PR and [your comments above about the failing tests](https://github.com/DSpace/dspace-angular/pull/2371#issuecomment-1637089839).  I agree with your logic that it seems reasonable to remove both of the failing tests.

So, if you find time to update this to delete the failing tests & get this passing tests...then I'll do my best to move this forward soon as it seems like a very useful change before we start doing major code updates (to Angular 16, etc)

**Comment by alexandrevryghem** [comment]
@tdonohue: All tests are fixed now

**Review by tdonohue — APPROVED** [review]
👍 Thanks @alexandrevryghem for this necessary improvement/fix!  I looked over the code and it looks good.  Also verified locally that all tests on existing `main` pass this check.

**Pull request merged**
