### PR TITLE
Various small changes to improve customizability

### LINKED ISSUE #1528: Errors using the "custom" theme in DSpace 7.2
**Describe the bug**
When using the custom theme in DSpace 7.2, I see errors in the browser's console:

```
ERROR TypeError: Cannot read properties of undefined (reading 'injector')
    at NavbarComponent_ng_container_15_Template (navbar.component.html:9:109)
    at executeTemplate (core.js:9614:1)
    at refreshView (core.js:9480:1)
    at refreshEmbeddedViews (core.js:10605:1)
    at refreshView (core.js:9504:1)
    at refreshComponent (core.js:10651:1)
    at refreshChildComponents (core.js:9277:1)
    at refreshView (core.js:9530:1)
    at refreshEmbeddedViews (core.js:10605:1)
    at refreshView (core.js:9504:1)
```

This error is repeated multiple times.

The site looks like I would expect it should, but when I make any search, I do not see any results, filters, ...

image

**To Reproduce**
1. Checkout dspace-7.2
2. Copy config/config.example.yml to config/config.dev.yml
3. Edit config/config.dey.yml and change `themes.name` to `'custom'`
4. Edit docker/docker-compose.yml to set api7.demo.org as backend
5. Change directory into docker and run docker-compose build --no-cache && docker-compose up -d && docker-compose logs -f
6. When everything is running, open a browser, go to localhost:4000 and Open your browser's console.

**Expected behavior**
No error should show up in the browser's console when using an the custom theme without any changes. Opening the search should work normally.

### PR DESCRIPTION
**Pull request by ybnd**
## Description
This PR bundles multiple small fixes & adjustments we've made to better support custom themes

Also, Fixes #1528 (see https://github.com/DSpace/dspace-angular/pull/1512/commits/fba1dfb689b18263b5c7ef9e92f301f6d2e2b528 and https://github.com/DSpace/dspace-angular/pull/1512/commits/2830da955739b61c91c15f587051b0d75f4e5464)

## List of changes in this PR
* Made a few more components themeable
  * `ComcolPageBrowseComponent`
  * `AdminSidebarComponent`
  * `SearchComponent`
  * `ItemListPreviewComponent`
  * `CommunityListComponent`
* Propagate the `SearchFormComponent.showScopeSelector` input down from `SearchComponent` so we can get at it from a theme
   Note that this change was made before https://github.com/DSpace/dspace-angular/commit/c28221623ca1405469db14459e1cffe92a65d575, so the commit in question has mostly been overwritten. Make sure to look at the file _after_ the `main` merge.
* `DSOSelectorComponent`: use `DSONameService` for more flexibility
* `ds-truncatable`
   * support Bootstrap `$light` background
   * fix RGBA/RGB gradient issue on Safari, e.g. before fix:

* Fix some minor issues with thumbnails / grid view
* `ThemedComponent`: propagate `ngOnChanges` calls down to the wrapped component in order to support theming for components that use it.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@ybnd : Thanks! I gave this a review today, and the code changes all look reasonable. It's mostly making sure we are using themed components everywhere & adding a few new ones to support that.

However, when I tried to test this out, I'm hitting the errors reported in #1528.  Since I can reproduce those same errors on `main`, they aren't the fault of this PR.  But, they make it harder to test this PR because (for example) I cannot get search results to display when using the `custom` theme.

If you are interested in helping out on #1528, we might be able to just bundle that fix into this PR.  Otherwise, I'm likely going to need to set this PR aside briefly until we find help on #1528 (I also pinged @artlowel on it) -- as I want to be able to test this PR before merging it.

Overall though, I *think* this PR should work.  I'm just having trouble testing it fully.

**Comment by ybnd** [comment]
@tdonohue This should cover the search issue from #1528 
AFAIK the other issue (navbar) is not directly theme-related

**Comment by pnbecker** [comment]
We tested the two commits against #1528 and they solves the issues their. I think this PR should be merged asap.

**Comment by artlowel** [comment]
**Update** I also added a themeable version of CommunityListComponent to this PR: https://github.com/DSpace/dspace-angular/pull/1512/commits/dc00fd4c759898431686c65fa30cd56fc5012749

**Review by tdonohue — APPROVED** [review]
👍 Thanks @ybnd !  Tested this today by enabling the "custom" theme and verifying that everything still works properly.  It does.  Code looks good to.

Merging this, as it also has approval from other testers via comments above.

**Pull request merged**
