### PR TITLE
Fix Request-a-Copy grant form optional message not optional in form validation

### LINKED ISSUE #2440: Rac grant form: message field is still used in validation even though is optional
**Describe the bug**
The message field is optional but a requirement for a not empty message is still used to disable the submit button

**To Reproduce**
1. Submit a request
2. Attempt to grant request
3. Form won't allow you to submit until there is a message even though it says it's optional

**Expected behavior**
A user can grant a request without entering a message

**Related work**
#2439

### PR DESCRIPTION
**Pull request by amgciadev**
Message is optional: remove req in [disabled]

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #2440 
## Description
It removes the check for an empty message for the submit button [disabled] attribute
## Instructions for Reviewers
Attempt to grant a request and confirm that now the message is optional

List of changes in this PR:
* Very simple fix removing the message emptiness check

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [X] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [X] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [X] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [X] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by pilasou** [comment]
@amgciadev @tdonohue Hi! I tried to test, but the fix did not seem to correct the problem, if I do not put a text in the Message text box, the answer cannot be sent, no matter if the choice is to send or deny the request.
image

Just to let you now what i did to test: 

- I am testing using Docker as described in [Testing DSpace 7 Pull Requests](https://wiki.lyrasis.org/display/DSPACE/Testing+DSpace+7+Pull+Requests)
- Backend is on Main branch (I change config for SMTP and rebuild)
- Frontend on PR branch (fix-rac-grant-b)
- Rebuild the frontend then start the frontend.
- Connect as admin, and change Demo Submitter email by mine 
- Connect as Demo Submitter and add a new item with bitsteam with embargo
- As anonymous go to the new item and ask for a copy
- Clic on the URL in the email received
- Try to accept or deny, not possible if no text is entered in the Message field.

**Review by artlowel — APPROVED** [review]
Thanks @amgciadev. It works for me

@pilasou check your network tab when you approve the request. Is it possible you're getting a 403 - Invalid CSRF token error response? I got that too at first. If so, that's a variant of https://github.com/DSpace/dspace-angular/issues/1486, and not related to this PR

**Comment by pilasou** [comment]
@artlowel @tdonohue : long story short: my 2nd test failed, but without the 403 error (see below). After reinstalling completly DSpace with Docker, I face the same problem I reported initialy. 
image

The test I made this morning before Dev meeting works but I am not able to know why.

**Comment by pilasou** [comment]
Hi @amgciadev @tdonohue, retest this morning after a clean complete reinstall of Docker and it worked. I was able to respond to the copy request without entering any additionnal message. However, if no information in entered the email contains NULL text : 
image

**Comment by tdonohue** [comment]
I can verify this works. However, as @pilasou noted, the result is that the literal text "null" is now returned in the response email like this:
```
Date: Fri, 20 Oct 2023 19:25:56 +0000 (UTC)
From: dspace-noreply@myu.edu
To: testuser@test.com
Subject: Request for Copy of Restricted Document is Granted

Dear Tim Donohue:

Your request for a copy of the file(s) from the below document has been approved by Demo Site Administrator.  You may find the requested file(s) attached.

Automatic Generation of Headlines for Online Math Questions
http://localhost:4000/handle/123456789/1151

An additional message from Demo Site Administrator follows:

null

Best regards,
The DSpace Started with Docker Compose Team
```

So, this PR works fine.  But, a minor fix to the backend is needed to handle the case where this message is not specified.

I'm going to merge this, and create a tiny PR to fix the backend issue.  It's literally just a check to handle a possible "null" value for this optional message field.

**Comment by tdonohue** [comment]
The `"null"` message bug is fixed in https://github.com/DSpace/DSpace/pull/9136

Merging this as it is at +3 (I vote +1 as well).

**Comment by amgciadev** [comment]
Thanks all!

**Pull request merged**
