### PR TITLE
Opaque config: this connects to #64 and this connects to #79

### PR DESCRIPTION
**Pull request by wwelling**
Organized src directory. Moved platform specific source files into platform directory.

Provided global configuration as OpaqueToken that can be injected.

Build sets production config value.

Server uses configuration for address, port, and universal configurations preboot and async.

@artlowel Could you please check if setting preboot to false gives the entire action history of the redux state for debugging?

### CODE REVIEW

**Comment by wwelling** [comment]
OpaqueToken is now deprecated.

https://angular.io/docs/ts/latest/api/core/index/OpaqueToken-class.html

It will work fine for the current version of Angular we are using.

After upgrade it becomes InjectionToken.

https://blog.thoughtram.io/angular/2016/05/23/opaque-tokens-in-angular-2.html#injectiontoken-since-angular-4x

**Comment by artlowel** [comment]
According to that blogpost, it shouldn't be too difficult to upgrade though: a find and replace, and removing `@Inject(GLOBAL_CONFIG)` everywhere. 
And there are some good changes here, so it seems like a good idea to merge this anyway.

However I wasn't able to get the local `environment.dev.js` or `environment.prod.js` files to work. It keeps saying `Environment file not specified. Using default.`

**Comment by artlowel** [comment]
>@artlowel Could you please check if setting preboot to false gives the entire action history of the redux state for debugging?

It does

**Comment by wwelling** [comment]
@artlowel I am looking into why it is not selecting the dev or prod environment config files.

**Comment by wwelling** [comment]
@artlowel I have addressed the environment config files:

```yarn start```, ```yarn run server```, and ```yarn watch:prod``` will use ```environment.prod.js```
```yarn run start:dev``` and ```yarn watch:dev``` will use ```environment.dev.js```

testing will use ```environment.test.js```

if no environment config files are available, ```environment.default.js``` will be used

**Comment by artlowel** [comment]
LGTM

**Comment by artlowel** [comment]
Oh yeah, apart from one thing: 
I'd cut off the file structure in README.md at the depth of the app directory (as it is currently). The goal of that section was to explain the config files in the root, not to give an overview of _every_ file in the entire project. That would also require us to have to update it way too often.

**Comment by wwelling** [comment]
I will update the depth of the tree in the readme.

**Comment by artlowel** [comment]
+1

**Comment by atarix83** [comment]
I've tested it, environment config files are used properly.
For me it's ok.

**Pull request merged**
