### PR TITLE
Add support for locally hosted fonts

### PR DESCRIPTION
**Pull request by artlowel**
This PR adds the ability to serve custom fonts, either from the `/resources/fonts` directory, or from`/themes/${theme-name}/resources/fonts`. 

If a file with the same name exists in both places and the theme is active, the themed version will get priority.

### CODE REVIEW

**Comment by tdonohue** [comment]
@artlowel : Could I recommend a tiny improvement here before we merge?  I'd like to see this PR create a `/resources/fonts` folder and add in a brief README there regarding the types of font files supported...looks like the current supported list is EOT (Embedded Open Type), TTF (TrueType), SVG, WOFF (Web Open Font Format) and WOFF2.  I think there's a few other formats out there (like OTF or OpenType Font), so it'd be good to make sure we document the formats we support in a README

**Comment by artlowel** [comment]
@tdonohue Done, also added support for OTF.

**Comment by tdonohue** [comment]
@artlowel : It looks like some sort of build error was accidentally introduced in the latest changes.  Travis is currently throwing errors.

**Comment by artlowel** [comment]
@tdonohue It should be fixed now. I had to apply the same changes to the test webpack config

**Comment by tdonohue** [comment]
Looks good to me. This is a very minor change (no new code, just a change to the build/packaging processes), so merging with just one approval.

**Pull request merged**
