### PR TITLE
A set of new Finnish translation keys

### PR DESCRIPTION
**Pull request by reetagithub**
## Description
Some new Finnish translation keys. About 500 keys are still to be translated.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [ ] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
@reetagithub the history on this branch seems to have picked up changes to many (all?) of the other JSON5 files as well. If you don't mind, once you're done translating `fi.json5`, I can help you extract _just_ the changes to the Finnish strings and clean up this PR?

**Comment by reetagithub** [comment]
Alan, that would be great. Unfortunately I will nor have the time to finish Finnish before my vacation. We could do that today. I’ll be working 8 hours from now, so if we could do it todaty, that would be nice. This way I could continue with the Finnish file after my vacation (still about 300 translation keys to go).

Alan Orth ***@***.***> kirjoitti 29.6.2023 kello 14.51:



@reetagithub<https://github.com/reetagithub> the history on this branch seems to have picked up changes to many (all?) of the other JSON5 files as well. If you don't mind, once you're done translating fi.json5, I can help you extract just the changes to the Finnish strings and clean up this PR?

**Comment by alanorth** [comment]
@reetagithub it's OK if you don't do them all at once because they won't be "live" in DSpace until the next point release (7.6.1) anyway. I can extract and merge the ones that you complete by the end of today and that will already be a great success.

**Comment by reetagithub** [comment]
Perfect! Actually I only have a few left now, I’ve been busy yesterday :) .  I did yarn lint —fix with success, and my newest modifications (from June 30) seem to be present in the PR now. If you can clean up my mess, it will be geatly appreciated, Alan!


Alan Orth ***@***.***> kirjoitti 30.6.2023 kello 9.09:



@reetagithub<https://github.com/reetagithub> it's OK if you don't do them all at once because they won't be "live" in DSpace until the next point release (7.6.1) anyway. I can extract and merge the ones that you complete by the end of today and that will already be a great success.

**Comment by alanorth** [comment]
Closing in favor of a consolidated and cleaned up pull request in #2347 with approval from @reetagithub above.

**Pull request closed without merging**
