### PR TITLE
Request by UUID issue

### LINKED ISSUE #644: Issue with request of embed objects, where object cache entry is missing
During implementation of https://github.com/DSpace/dspace-angular/issues/601 I encountered several issues with request of embed objects. In many case when the request is already fetched by rest, the payload returned is undefined due to a missing object cache entry in the cache. Objects cache should exist for this requests because are not expired, as a result the request is not dispatched again.
Probably this issue is related to https://github.com/DSpace/dspace-angular/issues/626

### PR DESCRIPTION
**Pull request by artlowel**
## Description
requestService.getUUID() didn't work for UUIDs of requests that aren't sent because they were already cached. 

## Instructions for Reviewers
The reason was that there was an observableRace to find which observable that returns first: the one in the cache or the one in the index that maps unsent UUIDs to the cached ones.

Because ngrx selectors return undefined immediately if they have no result, in practice the call that checked the requestcache always won the race because its undefined came before the result from the index.

The way to fix it was to add an hasValueOperator() to each of the race observables. That way they can only win if they return something.

I also optimized getByHref by ensuring it doesn't pass calls on to getByUUID if the UUID is empty

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs for any bug fixes, improvements or new features. A few reminders about what constitutes good tests:
    * Include tests for different user types (if behavior differs), including: (1) Anonymous user, (2) Logged in user (non-admin), and (3) Administrator.
    * Include tests for error scenarios, e.g. when errors/warnings should appear (or buttons should be disabled).
    * For bug fixes, include a test that reproduces the bug and proves it is fixed. For clarity, it may be useful to provide the test in a separate commit from the bug fix.
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/master/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by artlowel** [comment]
In this PR getByUUID no longer emits undefined when neither the request cache nor the index has a match. That isn't a problem in theory but I found that some other services depend on that behavior. I'll rewrite it to ensure it behaves exactly as the old version did when there is no match.

**Comment by artlowel** [comment]
Done. 

So now instead of an observableRace, we have an observableCombine latest followed by a an Array.find. This means that we'll always wait for both selects to emit something (undefined or otherwise). The find will return the one that has a value if there is one. If there isn't find will return undefined.

**Comment by atarix83** [comment]
@artlowel 
I gave one more test, but unfortunately this don't resolve the first issue that I have on https://github.com/DSpace/dspace-angular/pull/645.
what I cans see on the redux stack is that a remove cache action is triggered 
```
{
  type: 'dspace/core/cache/object/REMOVE',
  payload: 'http://localhost:3000/server/api/eperson/groups/f2c7eb75-aec0-4604-ab7f-6676723818ad'
}
```

than the following request for the group don't return results.
It's the same if I used [embed group in ResourcePolicy](https://github.com/4Science/dspace-angular/blob/%23601-resource-policies/src/app/core/resource-policy/models/resource-policy.model.ts#L104) object or if make [request with the link](https://github.com/4Science/dspace-angular/blob/%23601-resource-policies/src/app/core/resource-policy/models/resource-policy.model.ts#L88)

**Comment by artlowel** [comment]
@atarix83 As discussed in the meeting today: let's keep #644 open to fix your issue, and keep this PR small and to the point.

**Pull request merged**
