### PR TITLE
[#2622] Makes forgot-password link removable

### LINKED ISSUE #2622: Make forgot-password link removable
**Is your feature request related to a problem? Please describe.**
Make the *forgot-password* anchor removable as it is now working with the *new-user* one.

**Describe the solution you'd like**
Create a new `AuthorizationFeature` that will handle this behavior by checking a configuration property, and if the user is specified also that the user can update the password, i.e. `org.dspace.app.util.AuthorizeUtil#authorizeUpdatePassword`.

**Additional Context**
linked *DSpace* issue: https://github.com/DSpace/DSpace/issues/9192

### PR DESCRIPTION
**Pull request by vins01-4science**
## References
* Fixes #2622
* Requires DSpace/DSpace#9194

## Description
Introduces a new check to show the `forgot-password` link that uses the related `AuthorizationFeature`

## Instructions for Reviewers
Try to enable the additional configuration:
```cfg
user.forgot-password = false
```
inside the authentication-password.cfg and check that it is not shown inside the login-component, in both:

- dropdown login menu
- login page

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by vins01-4science** [comment]
The e2e tests are failing due to the changes introduced in the `login-component`.
Once the [#9194](https://github.com/DSpace/DSpace/pull/9194) backend PR will be merged, this test will pass without any problem.

**Comment by tdonohue** [comment]
@vins01-4science : Could you resolve the merge conflicts in this PR to make it easier to review?

**Comment by vins01-4science** [comment]
> @vins01-4science : Could you resolve the merge conflicts in this PR to make it easier to review?

Yes, sorry I forgot to address your comment.
I will update it shortly.

Thank you.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@vins01-4science :  Gave this a test & review today.  Overall it looks good.

I've also verified that the e2e test failure in this PR _only occurs because the backend PR isn't  merged yet_.  Once the backend PR & this one are merged, this e2e test should succeed (I've verified it succeeds for me locally with both the frontend & backend PRs installed).

All that said, I noticed a few small issues that would be nice to fix if possible:

*  Even when `user.forgot-password = false` is set on the backend, I can still access the Forgot Password page by typing in the "/forgot" path in my browser address bar (e.g. `http://localhost:4000/forgot`)  The good news is that when I submit it, I do receive an expected error.  But, ideally, I should not be allow to access this page.  Can we place some sort of "guard' in front of it that makes it inaccessible when disabled?
* Although it appears to not be related to this PR... I'm noticing that `user.registration = false` no longer works properly (at least via `yarn build:prod; yarn serve:ssr`).  The "Click here to register" link _always_ appears in the login dropdown even if that config is set to false.  (NOTE: This appears to also be a bug on `main`. But, if you find time to fix it in this PR, feel free.  Otherwise, I can log it as a separate bug ticket and look for a volunteer.)

**Comment by vins01-4science** [comment]
> @vins01-4science : Gave this a test & review today. Overall it looks good.
> 
> I've also verified that the e2e test failure in this PR _only occurs because the backend PR isn't merged yet_. Once the backend PR & this one are merged, this e2e test should succeed (I've verified it succeeds for me locally with both the frontend & backend PRs installed).
> 
> All that said, I noticed a few small issues that would be nice to fix if possible:
> 
>     * Even when `user.forgot-password = false` is set on the backend, I can still access the Forgot Password page by typing in the "/forgot" path in my browser address bar (e.g. `http://localhost:4000/forgot`)  The good news is that when I submit it, I do receive an expected error.  But, ideally, I should not be allow to access this page.  Can we place some sort of "guard' in front of it that makes it inaccessible when disabled?
> 
>     * Although it appears to not be related to this PR... I'm noticing that `user.registration = false` no longer works properly (at least via `yarn build:prod; yarn serve:ssr`).  The "Click here to register" link _always_ appears in the login dropdown even if that config is set to false.  (NOTE: This appears to also be a bug on `main`. But, if you find time to fix it in this PR, feel free.  Otherwise, I can log it as a separate bug ticket and look for a volunteer.)

@tdonohue Thank you, everything have been addressed.

For the `user.registration` issue I was not able to reproduce it, so probably it needs more investigation.

The guard issue has been addressed, so let me know if you find something else!

**Review by tdonohue — APPROVED** [review]
👍 Thanks @vins01-4science !  Re-reviewed and retested today.  All prior issues are fixed/addressed.  I'll merge this **after** the backend PR is merged so that the e2e tests will succeed once merged.

I also verified that the `user.registration` configuration **is working properly**.  I must have made a mistake in my earlier testing, as I can no longer reproduce that issue either.

**Pull request merged**
